### ISSUE TITLE
Issue installing via NPM

### ISSUE THREAD

**Issue by ACHildebrand** [directus/directus#10202]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Currently trying to get started with Directus and I've run across a problem installing it, here's the stack trace:

My best guess is that when it goes looking for Argon it's coming up with a 404, and when I directly copy the URL it's trying to access, it does in fact 404, the actual URL currently is: 
https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-x64-unknown.tar.gz
instead of
https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-ia32-unknown.tar.gz

I don't know if they stopped developing the ia32 branch for Argon but that seems to be the sticking point.

### To Reproduce

Install via NPM on a windows machine

### Errors Shown

```
Error: npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-ia32-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.3 and node@12.21.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-ia32-unknown.tar.gz 
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\npm\6.14.11\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\12.21.0\\node.exe" "C:\\Program Files (x86)\\npm\\6.14.11\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\home\\Teams-Directus\\node_modules\\argon2\\lib\\binding\\napi-v3\\argon2.node" "--module_name=argon2" "--module_path=C:\\home\\Teams-Directus\\node_modules\\argon2\\lib\\binding\\napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd C:\home\Teams-Directus\node_modules\argon2
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\12.21.0\node.exe C:\Program Files (x86)\npm\6.14.11\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\home\Teams-Directus\node_modules\argon2\lib\binding\napi-v3\argon2.node --module_name=argon2 --module_path=C:\home\Teams-Directus\node_modules\argon2\lib\binding\napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\home\Teams-Directus\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\12.21.0\\node.exe" "C:\\home\\Teams-Directus\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\home\Teams-Directus\node_modules\argon2
node-pre-gyp ERR! node -v v12.21.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN rollup-plugin-typescript2@0.31.1 requires a peer of typescript@>=2.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-type@2.0.3 requires a peer of @types/bluebird@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-type@2.0.3 requires a peer of ts-toolbelt@^9.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN Teams-Directus@1.0.0 No description
npm WARN Teams-Directus@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.28.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.28.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\local\AppData\npm-cache\_logs\2021-12-01T16_39_42_616Z-debug.log
```

### What version of Directus are you using?

Current

### What version of Node.js are you using?

12.18.0

### What database are you using?

MS-SQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

NPM on PaaS (Azure)

**Comment by rijkvanzanten** [comment]
Heya! Mind (re-)opening this issue on the [`node-argon2`](https://github.com/ranisalt/node-argon2/issues) repo? This is unfortunately out of our control..
