### ISSUE TITLE
Missing column "directus_users.collection_list" after upgrade from 9.0.0.rc95 to 9.0.2 & directus migration:latest - No page content after upgrade blank page. Downgraded back to rc95 and now all pages give a "page not found" error from the missing collection_list

### ISSUE THREAD

**Issue by TBDD2020** [directus/directus#10393]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Upgraded from 9.0.0.rc95 to 9.0.2 and have missing directus_user.collection_list fields causing errors alongside blank pages on the 9.0.2 version using nginx from a digital ocean one click marketplace image. Every page was blank, even sign in page, but i saw the vendor js files being loaded in the network call of the browser, NGINX T output added for review.

After failing to solve the issue i decided to downgrade back to rc95, but the "directus database migrate:down" is not working and the missing colum "directus_users.collection_list" is still missing. 

The downgrade made the signin page show up and work again, and i can successfully login but every page is now showing page not found error inside the directus application pages, because its looking for the collection_list that is not there.

### To Reproduce

Create A OneClick DigitalOcean Droplet with Directus v9.0.0.rc95

Spent 2 months adding data and setting it up.

Create 3 new Roles, and a new json field in the directus_users system collection for users collection.

Decided today to upgrade to V9.0.2, did "npm updated" and then "npx directus database migrate:latest"

Update was fine 6 errors that require audit nothing major, migrate:latest worked the first time, i didnt backup my DB until after i had used migrate:latest as i assumed it was a pretty simple thing.

**### ISSUE 01:** 
Blank Page on updated Directus page. Directus HTTPS is activated using a subdomain of the main website. Server is running 
nginx:

NGINX T output: https://pastebin.com/wKSzeu75

I read on some of the other bug reports that nginx may be responsible for the blank page, but looking through the nginx T output I am unsure if thats the case.

**### ISSUE 02:** 
After unsuccessfully finding a solution to issue 01, i decided to follow the downgrading advice and downgraded back to rc95 successfully but when trying to migrate:down i get another error:

```
npx directus database migrate:down
11:34:20 ✨ Running migrations...
11:34:20 🚨 Couldn't find migration
Error: Couldn't find migration
    at down (/var/directus/node_modules/directus/dist/database/migrations/run.js:65:19)
    at run (/var/directus/node_modules/directus/dist/database/migrations/run.js:36:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async migrate (/var/directus/node_modules/directus/dist/cli/commands/database/migrate.js:13:9)
    at async Command.parseAsync (/var/directus/node_modules/commander/lib/command.js:923:5)
```

BUT at least i am now able to see the signin page again and when i log in successfully, i get sent to the admin pages but every page is getting a server error because every page is looking for "directus_users.collecton_list"

```
extensions: {code: "INTERNAL_SERVER_ERROR"}
code: "INTERNAL_SERVER_ERROR"
message: "select \"directus_roles\".\"id\", \"directus_roles\".\"name\", \"directus_roles\".\"icon\", \"directus_roles\".\"description\", \"directus_roles\".\"ip_access\", \"directus_roles\".\"enforce_tfa\", \"directus_roles\".\"admin_access\", \"directus_roles\".\"app_access\", \"directus_roles\".\"collection_list\" from \"directus_roles\" where \"directus_roles\".\"id\" 
in ($1) - column directus_roles.collection_list does not exist"
```

any help would be greatly appreciated. I have made a dump of the directus database in case i have to manually edit some options?

### Errors Shown

```
npx directus database migrate:down
11:34:20 ✨ Running migrations...
11:34:20 🚨 Couldn't find migration
Error: Couldn't find migration
    at down (/var/directus/node_modules/directus/dist/database/migrations/run.js:65:19)
    at run (/var/directus/node_modules/directus/dist/database/migrations/run.js:36:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async migrate (/var/directus/node_modules/directus/dist/cli/commands/database/migrate.js:13:9)
    at async Command.parseAsync (/var/directus/node_modules/commander/lib/command.js:923:5)
```

```
extensions: {code: "INTERNAL_SERVER_ERROR"}
code: "INTERNAL_SERVER_ERROR"
message: "select \"directus_roles\".\"id\", \"directus_roles\".\"name\", \"directus_roles\".\"icon\", \"directus_roles\".\"description\", \"directus_roles\".\"ip_access\", \"directus_roles\".\"enforce_tfa\", \"directus_roles\".\"admin_access\", \"directus_roles\".\"app_access\", \"directus_roles\".\"collection_list\" from \"directus_roles\" where \"directus_roles\".\"id\" 
in ($1) - column directus_roles.collection_list does not exist"
```

### What version of Directus are you using?

9.0.2 & 9.0.0.rc95

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postgres

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying Directus?

OneClick Digital Ocean Droplet

**Comment by Oreilles** [comment]
What release are you on right now, and what is the content of your `directus_migrations` table ?

**Comment by TBDD2020** [comment]
I am on 9.0.0.rc95 right now because the 9.0.2 version wont even show me the login page, atleast on the rc95 i can login and get connected. even if the database error is happening. Please see below the database table for directus_migrations.


```
directus-# \dS directus_migrations
                       Table "public.directus_migrations"
  Column   |           Type           | Collation | Nullable |      Default
-----------+--------------------------+-----------+----------+-------------------
 version   | character varying(255)   |           | not null |
 name      | character varying(255)   |           | not null |
 timestamp | timestamp with time zone |           |          | CURRENT_TIMESTAMP
Indexes:
    "directus_migrations_pkey" PRIMARY KEY, btree (version)

```

```
timestamp | 2021-10-07 20:40:07.178925+00
-[ RECORD 29 ]-----------------------------
version   | 20210831A
name      | Remove Limit Column
timestamp | 2021-10-07 20:40:07.183269+00
-[ RECORD 30 ]-----------------------------
version   | 20210903A
name      | Add Auth Provider
timestamp | 2021-10-07 20:40:07.195596+00
-[ RECORD 31 ]-----------------------------
version   | 20210907A
name      | Webhooks Collections Not Null
timestamp | 2021-10-07 20:40:07.205429+00
-[ RECORD 32 ]-----------------------------
version   | 20210910A
name      | Move Module Setup
timestamp | 2021-10-07 20:40:07.213989+00
-[ RECORD 33 ]-----------------------------
version   | 20210920A
name      | Webhooks URL Not Null
timestamp | 2021-10-07 20:40:07.222879+00
-[ RECORD 34 ]-----------------------------
version   | 20210927A
name      | Replace Fields Group
timestamp | 2021-10-07 20:40:07.228844+00
-[ RECORD 35 ]-----------------------------
version   | 20210927B
name      | Replace M2M Interface
timestamp | 2021-10-07 20:40:07.235273+00
-[ RECORD 36 ]-----------------------------
version   | 20210924A
name      | Add Collection Organization
timestamp | 2021-12-08 06:51:16.448489+00
-[ RECORD 37 ]-----------------------------
version   | 20210929A
name      | Rename Login Action
timestamp | 2021-12-08 06:51:16.464151+00
-[ RECORD 38 ]-----------------------------
version   | 20211007A
name      | Update Presets
timestamp | 2021-12-08 06:51:16.495232+00
-[ RECORD 39 ]-----------------------------
version   | 20211009A
name      | Add Auth Data
timestamp | 2021-12-08 06:51:16.498055+00
-[ RECORD 40 ]-----------------------------
version   | 20211016A
name      | Add Webhook Headers
timestamp | 2021-12-08 06:51:16.500638+00
-[ RECORD 41 ]-----------------------------
version   | 20211103A
name      | Set Unique to User Token
timestamp | 2021-12-08 06:51:16.511962+00
-[ RECORD 42 ]-----------------------------
version   | 20211103B
name      | Update Special Geometry
timestamp | 2021-12-08 06:51:16.515932+00
-[ RECORD 43 ]-----------------------------
version   | 20211104A
name      | Remove Collections Listing
timestamp | 2021-12-08 06:51:16.518593+00
-[ RECORD 44 ]-----------------------------
version   | 20211118A
name      | Add Notifications
timestamp | 2021-12-08 10:29:55.839121+00

```

**Comment by Oreilles** [comment]
Your database is showing that all migrations have been run all the way up to the latest `9.1.2` release.
Could you try updating your Directus instance to `9.1.2` and tell us what issues you face from there ?

**Comment by Oreilles** [comment]
Sorry, the latest version actually is `9.2.1`.

**Comment by TBDD2020** [comment]
@Oreilles updated to 9.2.1 & get a blank screen, no login no sign up in the /admin just blank pages with 

Heres the install

```
/:/var/directus# npm install directus@v9.2.1
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN rollup-plugin-typescript2@0.31.1 requires a peer of typescript@>=2.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-type@2.1.2 requires a peer of @types/bluebird@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-type@2.1.2 requires a peer of ts-toolbelt@^9.6.0 but none is installed. You must install peer dependencies yourself.

+ directus@9.2.1
updated 12 packages and audited 1113 packages in 86.259s

1 package is looking for funding
  run `npm fund` for details

found 6 vulnerabilities (1 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

:/var/directus# npx directus database migrate:latest
13:22:03 ✨ Running migrations...
13:22:03 ✨ Database up to date

```


Heres the Errors in the browser console for /admin page but i see all files have 200 status in the browser console network tab. Although preview of the files is giving me a "We're sorry but Directus doesn't work without JavaScript enabled. Please enable it to continue."

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
vendor.162b55e9.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
use-sync.6d51d5e5.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Any idea? nginx T file is here: https://pastebin.com/wKSzeu75


And heres the database for directus_migrations after the update:

```
-[ RECORD 40 ]-----------------------------
version   | 20211016A
name      | Add Webhook Headers
timestamp | 2021-12-08 06:51:16.500638+00
-[ RECORD 41 ]-----------------------------
version   | 20211103A
name      | Set Unique to User Token
timestamp | 2021-12-08 06:51:16.511962+00
-[ RECORD 42 ]-----------------------------
version   | 20211103B
name      | Update Special Geometry
timestamp | 2021-12-08 06:51:16.515932+00
-[ RECORD 43 ]-----------------------------
version   | 20211104A
name      | Remove Collections Listing
timestamp | 2021-12-08 06:51:16.518593+00
-[ RECORD 44 ]-----------------------------
version   | 20211118A
name      | Add Notifications
timestamp | 2021-12-08 10:29:55.839121+00
```

**Comment by Oreilles** [comment]
Could you try setting up a local instance with `npm init directus-project directus-project`, connect it to your database and see if that works ? That could help us understand if the problem comes from your NGINX / Digitial Ocean configuration or from Directus itself.

**Comment by rijkvanzanten** [comment]
I'll transfer this to a Q&A discussion, as it sounds like there's a infrastructure/networking problem rather than a bug in Directus.
