### ISSUE TITLE
Cannot filter collection by tag values when using REST API and PostgreSQL

### ISSUE THREAD

**Issue by dpihac** [directus/directus#10528]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Consider a data model which has Tag field of type JSON. This field can have multiple or no values at all. I would like to filter all items in a collection with specific tags via the REST API.

Expected result is array of objects which contain specific tag, using the "_in" filter rules. Real world example would be, filter all the blog posts which have tag "featured".

Instead of result, error message is shown.

### To Reproduce

Use HTTP client like Postman or Insomnia to issue SEARCH request with the following body:

```
{
    "query":
    {
        "fields": ["*"],
        "filter":
        {
            "tags":
            {
                "_in": ["featured"]
            }
        }
    }
}
```

Here is a cURL example:

```
curl --request SEARCH \
  --url https://HOST/items/COLLECTION_NAME \
  --header 'Content-Type: application/json' \
  --data '{
    "query":
    {
        "fields": ["*"],
        "filter":
        {
                "tags":
                {
                    "_in": ["featured"]
                }
        }
    }
}
```

- HOST is URL of your Directus instance
- COLLECTION_NAME  is the collection which contains "tags" filed of type Tags (JSON)

### Errors Shown

Response of the request is:

```
{
	"errors": [
		{
			"message": "An unexpected error occurred.",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR"
			}
		}
	]
}
```

Upon further investigation, I was able to find error in the logs:

```
 [2021-12-15 20:35:32] 20:35:32 🚨 error select "clanci"."id", "clanci"."status", "clanci"."user_created", "clanci"."date_created", "clanci"."user_updated", "clanci"."date_updated", "clanci"."naslov", "clanci"."text", "clanci"."text_kratko", "clanci"."slug", "clanci"."image_thumbnail", "clanci"."kategorija", "clanci"."tags" from "clanci" where ("clanci"."tags" in ($1)) order by "clanci"."id" asc limit $2 - operator does not exist: json = unknown 
 [2021-12-15 20:35:32] error: select "clanci"."id", "clanci"."status", "clanci"."user_created", "clanci"."date_created", "clanci"."user_updated", "clanci"."date_updated", "clanci"."naslov", "clanci"."text", "clanci"."text_kratko", "clanci"."slug", "clanci"."image_thumbnail", "clanci"."kategorija", "clanci"."tags" from "clanci" where ("clanci"."tags" in ($1)) order by "clanci"."id" asc limit $2 - operator does not exist: json = unknown
 [2021-12-15 20:35:32]     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
 [2021-12-15 20:35:32]     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
 [2021-12-15 20:35:32]     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
 [2021-12-15 20:35:32]     at TLSSocket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
 [2021-12-15 20:35:32]     at TLSSocket.emit (node:events:390:28)
 [2021-12-15 20:35:32]     at TLSSocket.emit (node:domain:475:12)
 [2021-12-15 20:35:32]     at addChunk (node:internal/streams/readable:315:12)
 [2021-12-15 20:35:32]     at readableAddChunk (node:internal/streams/readable:289:9)
 [2021-12-15 20:35:32]     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
 [2021-12-15 20:35:32]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
 [2021-12-15 20:35:32] 20:35:32 ✨ request errored SEARCH 500 /items/clanci 16ms
```

Please note that this error message is specific to my instance and is based on the collection which contains fields as displayed in the SQL statement. Problem might be in the `pg-protocol` package and `parser.js`, but I didn't have time to debug that issue further.

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

PostgreSQL 12.9 on x86_64-pc-linux-gnu

### What browser are you using?

Postman, Insomnia

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker on Digital Ocean Apps

**Comment by rijkvanzanten** [comment]
This is a known limitation of JSON types in databases. See https://github.com/directus/directus/discussions/7277 for a discussion on how Directus could support that in the (near) future 🙂

**Comment by dpihac** [comment]
Thanks for the quick reply @rijkvanzanten. However, I was more getting at a specific use case, than a limitation of JSON and PostgreSQL per se. This is a limitation that should be documented and mentioned in documentation.

If I would like to filter all blog posts by specific tag, what would be alternative? Basically, how to filter on Tags field (could some other types also be affected)?

**Comment by benhaynes** [comment]
Perhaps you can set the tags to use the **CSV** type instead of JSON? This shouldn't have the same limitations, and therefore should be searchable.

**Comment by dpihac** [comment]
> Perhaps you can set the tags to use the **CSV** type instead of JSON? This shouldn't have the same limitations, and therefore should be searchable.

Thanks a lot @benhaynes! This is what I was testing yesterday and it worked as expected. I was thinking of updating documentation of Tags field to mention this.

**Comment by benhaynes** [comment]
Awesome. Documentation is always greatly appreciated! 👍
