### ISSUE TITLE
"value.toISOString is not a function" error on a timestamp non nullable field

### ISSUE THREAD

**Issue by vahidreza** [directus/directus#10678]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm using directus 9.4.0 on the docker.
directus is connected to an existing MSSQL database with tables that all of which have a timestamp non-nullable field.

the moment I want to fetch items from the server I get the error.

### To Reproduce

create any MSSQL 2008 R2 database and any table in it
add a timestamp field to the table and check out the "allow null"

then connect directus to the database using the docker command stating all required environment variables.

you will get the error the moment you load up directus and you go to the collection's page which has the timestamp field.

### Errors Shown

`✨ request errored GET 500 /items/Addresses?limit=25&fields[]=AddressTitle&fields[]=Detail&fields[]=Id&fields[]=RowVersion&sort[]=Id&page=1&meta[]=filter_count&meta[]=total_count 320ms
✨ request completed GET 304 /admin/assets/FiraMono-Medium.33e88fa9.woff2 1ms
✨ request completed GET 304 /notifications?filter=%7B%22_and%22:[%7B%22recipient%22:%7B%22_eq%22:%22BAF074B5-94EB-4195-840C-B275049801BF%22%7D%7D,%7B%22status%22:%7B%22_eq%22:%22inbox%22%7D%7D]%7D&aggregate=%7B%22count%22:%22id%22%7D 45ms`

`🚨 value.toISOString is not a function
TypeError: value.toISOString is not a function
    at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:232:48)
    at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:138:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/directus/node_modules/directus/dist/database/run-ast.js:41:21)
    at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:29:16)
    at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:208:25)
    at async /directus/node_modules/directus/dist/controllers/items.js:70:18`

### What version of Directus are you using?

9.4.0

### What version of Node.js are you using?

container's node version is v16.13.1

### What database are you using?

MSSQL 2008 R2

### What browser are you using?

Chrome

### What operating system are you using?

ubuntu

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Directus requires MS SQL Server version 13 and later (2016+). Please try it on a more up to date version of SQL Server. If the issue still persists, we can reopen and investigate 🙂

**Comment by vahidreza** [comment]
as ur recommendation i restored the db on MSSQL 2019 and i can confirm that the bug still exists. please reopen and reconsider.
thanks a lot.

**Comment by rijkvanzanten** [comment]
Can you share some SQL to setup a column with your specific column configuration?

**Comment by rijkvanzanten** [comment]
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Comment by tmdoit** [comment]
Problem exists in MSSQL 2016 13.0.6300.2.
Table schema:
![Zrzut ekranu 2022-03-22 o 09 32 49](https://user-images.githubusercontent.com/85706044/159439957-ee1b4eeb-7d31-46ec-a14d-bf7de15daf3e.png)
Log errror:
`directus    | 08:33:23 🚨 value.toISOString is not a function 
directus    | TypeError: value.toISOString is not a function
directus    |     at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:236:48)
directus    |     at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:142:14)
directus    |     at runMicrotasks (<anonymous>)
directus    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
directus    |     at async run (/directus/node_modules/directus/dist/database/run-ast.js:42:21)
directus    |     at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
directus    |     at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:210:25)
directus    |     at async /directus/node_modules/directus/dist/controllers/items.js:70:18
directus    | 08:33:23 ✨ request errored GET 500 /items/Dic_Dictionaries?limit=25&fields[]=Id&fields[]=Name&fields[]=TS&fields[]=TranslationID&sort[]=Id&page=1&meta[]=filter_count&meta[]=total_count 93ms
directus    | 08:33:24 ✨ request completed PATCH 204 /users/me/track/page 142ms`

Are you trying to convert "TIMESTAMP" type to datetime? In MSSQL "TIMESTAMP" is eq to "ROWVERSION" (a new unique number across the database is generated and assigned to the column).

If you need some more details or tests, I'm here for you.

**Comment by azrikahar** [comment]
@tmdoit would you mind opening a new issue for this? Attaching a [schema snapshot](https://docs.directus.io/reference/cli/#snapshot-the-data-model) in your new issue would also be very helpful. Thanks!
