### ISSUE TITLE
`directus schema apply` consider changes in display options as reason to create or remove field from database

### ISSUE THREAD

**Issue by cah4a** [directus/directus#10755]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Looks like `deep-diff` results could be unexpected for the [applySnapshot](https://github.com/directus/directus/blob/42476c45c83dcdb059ead0679ff3ec7caaa04a41/api/src/utils/apply-snapshot.ts#L13) function.

In my case, it returns something like:
```javascript
[
  DiffNew {
    kind: 'N',
    path: [ 'meta', 'display_options', 'prefix' ],
    rhs: null
  },
  DiffNew {
    kind: 'N',
    path: [ 'meta', 'display_options', 'suffix' ],
    rhs: null
  },
  DiffNew {
    kind: 'N',
    path: [ 'meta', 'display_options', 'conditionalFormatting' ],
    rhs: null
  },
  DiffNew {
    kind: 'N',
    path: [ 'meta', 'display_options', 'format' ],
    rhs: true
  }
]
```

[GetSnapshotDiff](https://github.com/directus/directus/blob/42476c45c83dcdb059ead0679ff3ec7caaa04a41/api/src/utils/get-snapshot-diff.ts#L16) function already knows that field exists and still should be present. But `applySnapshot` relies only on the output of the `deep-diff` and ignores its format.

### To Reproduce

1. Make fresh directus installation
2. Apply [snapshot1.yaml](https://gist.github.com/cah4a/06bb689f225713b8f06ca829d3fb0014)
3. Apply [snapshot2.yaml](https://gist.github.com/cah4a/06bb689f225713b8f06ca829d3fb0014#file-snapshot2-yaml)

Expected result: Snapshot applied successfully
Actual result: Error `Cannot read property 'field' of null at FieldsService.createField`

**What is more important** if you try to apply those snapshots in reverse order it will delete the `test` field completely.
It scares me.

### Errors Shown

```
➜ pnpx directus schema apply ./snapshot2.yaml
? The following changes will be applied:



Fields:
  - Create test.test

Would you like to continue? Yes
20:53:02 🚨 Failed to create field "test.test"
20:53:02 🚨 Cannot read property 'field' of null 
TypeError: Cannot read property 'field' of null
    at FieldsService.createField (/Users/cah4a/work/directus_schema_apply_error_bug/bug/node_modules/directus/dist/services/fields.js:202:30)
    at /Users/cah4a/work/directus_schema_apply_error_bug/bug/node_modules/directus/dist/utils/apply-snapshot.js:71:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### What version of Directus are you using?

9.4.1

### What version of Node.js are you using?

12.22.7

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by cah4a** [comment]
Any progress here?
Seems that is something that could destroy your data in production, isn't it?

**Comment by rijkvanzanten** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by rijkvanzanten** [comment]
> Seems that is something that could destroy your data in production, isn't it?

How so? It's not dropping columns during field updates to the metadata, so that shouldn't be an issue

**Comment by cah4a** [comment]
@rijkvanzanten Oh, actually, it does drop a column.

No error was raised. Thus no stack trace or error report here.

Try the snapshots I've provided. You should apply `snapshot2.yaml`, then `snapshot1.yaml` and column `test` will be gone.

**Comment by cah4a** [comment]
```
➜ pnpx directus schema apply ./snapshot2.yaml
? The following changes will be applied:

Collections:
  - Create test

Fields:
  - Create test.id
  - Create test.test

Would you like to continue? Yes
18:57:40 ✨ Snapshot applied successfully
```

Then go to pgcli, just to check db state.
```
test@localhost:bug> select * from test;
+------+--------+
| id   | test   |
|------+--------|
+------+--------+
SELECT 0
Time: 0.015s

```

So far, so good, everything expected.

Then apply snapshot1.yaml that should just remove `formatTitle` display option. Not so big change, heh?

```
➜ pnpx directus schema apply ./snapshot1.yaml
? The following changes will be applied:



Fields:
  - Delete test.test

Would you like to continue? Yes
18:57:49 ✨ Snapshot applied successfully
```

And it actually drops the column from the database completely! 

```
test@localhost:bug> select * from test;
+------+
| id   |
|------|
+------+
SELECT 0
Time: 0.016s
```

I REPEAT: DELETE THE COLUMN AND DESTROY THE DATA. Do you copy?

**Comment by jaycammarano** [comment]
Can confirm it deletes the column.

**Comment by cah4a** [comment]
The bug is still reproducing on version 9.5.0.

**Comment by cah4a** [comment]
Guys, I understand that _destroying data_ is not somewhat important, but do you have any plans to fix this?

**Comment by benhaynes** [comment]
> Guys, I understand that _destroying data_ is not somewhat important, but do you have any plans to fix this?

If it is an open issue (as opposed to being closed or a GH Discussion) then it is something we are indeed planning to resolve/fix. However unless the work is sponsored or an external PR is submitted, we work based on internal priority and can't give time estimates. Hope this helps!

**Comment by cah4a** [comment]
Thanks!
