### ISSUE TITLE
alter table `about_blocks` modify `image` char(36) null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'image': used in a foreign key constraint 'about_blocks_image_foreign'

### ISSUE THREAD

**Issue by terion-name** [directus/directus#10932]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

1. Got directus 9.4.0, developped locally, snapshotted schema, deployed to server, applied schema, added content
2. Made some changes, snapshotted schema, deployed to server, tried to apply schema — got error with incompatible foreign keys
3. Saw in issues that this issue seemed to be fixed in 9.4.2, Upgraded to 9.4.3, resnapshotted schema, deployed to server, tried to apply schema — getting `alter table `about_blocks` modify `image` char(36) null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'image': used in a foreign key constraint 'about_blocks_image_foreign'`

### To Reproduce

Initial schema:
[schema.yaml.zip](https://github.com/directus/directus/files/7834890/schema.yaml.zip)

Second schema, that failed to apply (on 9.4.0):
[schema.yaml.zip](https://github.com/directus/directus/files/7834888/schema.yaml.zip)

Current schema, that failed to apply (on 9.4.3):
[schema.yaml.zip](https://github.com/directus/directus/files/7834885/schema.yaml.zip)

### Errors Shown

```
10:44:27 🚨 Failed to update field "about_blocks.image"
23
10:44:27 🚨 alter table `about_blocks` modify `image` char(36) null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'image': used in a foreign key constraint 'about_blocks_image_foreign'
22
Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'image': used in a foreign key constraint 'about_blocks_image_foreign'
21
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
20
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
19
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
18
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
17
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
16
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
15
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
14
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
13
    at Socket.emit (node:events:390:28)
12
    at addChunk (node:internal/streams/readable:315:12)
11
    --------------------
10
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
9
    at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
8
    at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
7
    at new Promise (<anonymous>)
6
    at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
5
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
4
    at Client_MySQL.query (/app/node_modules/knex/lib/client.js:144:12)
3
    at /app/node_modules/knex/lib/execution/transaction.js:363:24
2
    at new Promise (<anonymous>)
1
    at Client_MySQL.trxClient.query (/app/node_modules/knex/lib/execution/transaction.js:358:12)

```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

node base docker image

### How are you deploying Directus?

Docker, kubernetes

**Comment by terion-name** [comment]
And by the way: it tries to run `alter table `about_blocks` modify `image` char(36) null` while the column is like this already. It should not try to alter it

**Comment by terion-name** [comment]
The diff of collection:

<img width="930" alt="Снимок экрана 2022-01-10 в 11 49 28" src="https://user-images.githubusercontent.com/1060205/148746217-9971aa6d-9265-4ce4-bf2b-76f2aadfbf61.png">

It seems that it changed with directus update, BUT from DB standpoint this is the same, and it must not run alters over this column

**Comment by terion-name** [comment]
Moreover, corresponding record in `directus_fields` table are the same in local and server dbs:
```
id	collection	field	special	interface	options	display	display_options	readonly	hidden	sort	width	translations	note	conditions	required	group
125	about_blocks	image	file	file-image	NULL	NULL	NULL	0	0	3	full	NULL	NULL	NULL	0	NULL
```

**Comment by terion-name** [comment]
And even more:

Applied latest schema to fresh db, imported data from previous (only data, without structure, just inserted rows).
On running schema apply again (the same schema!!):

```
alter table about_translations modify about_id int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'about_id' and referenced column 'id' in foreign key constraint 'about_translations_about_id_foreign' are incompatible.
22
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'about_id' and referenced column 'id' in foreign key constraint 'about_translations_about_id_foreign' are incompatible.
21
```

**Comment by terion-name** [comment]
@rijkvanzanten still an issue in 9.12.2. In context of #13914, to fight that problem imported data from local mysql. Getting now:

```
2022-06-15T20:50:23.567110291Z 20:50:23 🚨 Failed to update field "channels_translations.channels_id"
2022-06-15T20:50:23.567776659Z 20:50:23 🚨 alter table `channels_translations` modify `channels_id` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'channels_id' and referenced column 'id' in foreign key constraint 'channels_translations_channels_id_foreign' are incompatible.
2022-06-15T20:50:23.567804962Z Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'channels_id' and referenced column 'id' in foreign key constraint 'channels_translations_channels_id_foreign' are incompatible.
```
Data is exactly the same, structure also, both are mysql 8, keys are correct

**Comment by genu** [comment]
I'm also facing, I think, a similar issue. 

When I try to apply a schema on `PROD` deployment, it fails with `Failed to update field` error.

In my case, I'm using Postgres, so I don't think its strictly a `mysql` issue.

**Comment by azrikahar** [comment]
> When I try to apply a schema on `PROD` deployment, it fails with `Failed to update field` error.
> 
> In my case, I'm using Postgres, so I don't think its strictly a `mysql` issue.

I'm more leaning towards #7808 for OP's error, as in the `unsigned int` foreign key column is being attempted to be altered as `int` (which is what #14128 tries to address), so in that case it'd still be MySQL specific. 

As you are also getting `Failed to update field`, what are the specific errors shown after this line? `Failed to update field` is the generic error so it can be hard to deduce further, but error logs shown _after_ it should technically be more informative and looks different for PostgreSQL compared to MySQL if I'm not mistaken.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-280](https://linear.app/directus/issue/ENG-280/snapshot-apply-results-in-foreign-key-error)

**Comment by seanmangar** [comment]
I'm also facing this issue when attempting to apply a schema diff :

```
{
    "errors": [
        {
            "message": "alter table `event_event_category` modify `event_category_id` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'event_category_id' and referenced column 'id' in foreign key constraint 'event_event_category_event_category_id_foreign' are incompatible.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

It should not be attempting to change the integer format: `bigint unsigned ` which it  is currently is correct.

MySQL version: 8.0.35
Directus version: 10.7.2
