### ISSUE TITLE
Compatibility with MySQL InnoDB Cluster

### ISSUE THREAD

**Issue by RamyAllam** [directus/directus#11021]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm trying to run Directus on MySQL InnoDB Cluster v8.0.27 in Multi Primary mode and seeing the below error during `npx directus bootstrap` process
```
The table does not comply with the requirements by an external plugin.
```

The full stdout of the bootstrap process is as follows.  
```
11:10:51 ✨ Loaded extensions: categories-hooks, events-hooks, favorite-categories-hooks, favorite-tags-hooks, media-hooks, news-hooks, read-later-news-hooks, sitemap, apple-app-site-association, cities, currency, gcloud, likes, news, notifications, sitemaps, users
11:10:51 ✨ Initializing bootstrap...
11:10:52 ✨ Installing Directus system tables...
11:10:53 ✨ Running migrations...
11:10:53 ✨ Applying Remove Collection Foreign Keys...
11:10:53 ✨ Applying Remove System Relations...
11:10:53 ✨ Applying Remove System Collections...
11:10:53 ✨ Applying Remove System Fields...
11:10:53 ✨ Applying Add Cascade System Relations...
11:10:54 ✨ Applying Change Webhook URL Type...
11:10:54 ✨ Applying Add Relations Sort Field...
11:10:54 ✨ Applying Remove Locked Fields...
11:10:54 ✨ Applying Webhooks Collections Text...
11:10:54 ✨ Applying Add Refresh Interval...
11:10:54 ✨ Applying Make Filesize Nullable...
11:10:54 ✨ Applying Add Collections Accountability...
11:10:54 ✨ Applying Remove Files Interface...
11:10:54 ✨ Applying Rename Interfaces...
11:10:54 ✨ Applying Restructure Relations...
11:10:54 ✨ Applying Add Foreign Key Constraints...
11:10:54 ✨ Applying Add System Fk Triggers...
11:10:55 ✨ Applying Add Collections Icon Color...
11:10:55 ✨ Applying Add Insights...
11:10:55 ✨ Applying Add Deep Clone Config...
11:10:55 ✨ Applying Change Filesize Bigint...
11:10:55 ✨ Applying Add Conditions to Fields...
11:10:55 ✨ Applying Add Default Folder...
11:10:55 ✨ Applying Replace Groups...
11:10:55 ✨ Applying Add Required to Fields...
11:10:55 ✨ Applying Update Groups...
11:10:55 ✨ Applying Change Image Metadata Structure...
11:10:55 ✨ Applying Add Geometry Config...
11:10:55 ✨ Applying Remove Limit Column...
11:10:55 ✨ Applying Add Auth Provider...
11:10:55 ✨ Applying Webhooks Collections Not Null...
11:10:55 ✨ Applying Move Module Setup...
11:10:55 ✨ Applying Webhooks URL Not Null...
11:10:55 ✨ Applying Add Collection Organization...
11:10:55 ✨ Applying Replace Fields Group...
11:10:55 ✨ Applying Replace M2M Interface...
11:10:55 ✨ Applying Rename Login Action...
11:10:55 ✨ Applying Update Presets...
11:10:55 ✨ Applying Add Auth Data...
11:10:55 ✨ Applying Add Webhook Headers...
11:10:56 ✨ Applying Set Unique to User Token...
11:10:56 ✨ Applying Update Special Geometry...
11:10:56 ✨ Applying Remove Collections Listing...
11:10:56 ✨ Applying Add Notifications...
Error: ER_BEFORE_DML_VALIDATION_ERROR: The table does not comply with the requirements by an external plugin.
    at Query.Sequence._packetToError (/home/repo/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/repo/backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/repo/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/repo/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/repo/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/repo/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/repo/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/repo/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/repo/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/repo/backend/node_modules/mysql/lib/Connection.js:198:25)
    at /home/repo/backend/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/repo/backend/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/home/repo/backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/home/repo/backend/node_modules/knex/lib/client.js:144:12)
    at Runner.query (/home/repo/backend/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/home/repo/backend/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/home/repo/backend/node_modules/knex/lib/execution/runner.js:272:20) {
  code: 'ER_BEFORE_DML_VALIDATION_ERROR',
  errno: 3098,
  sqlMessage: 'The table does not comply with the requirements by an external plugin.',
  sqlState: 'HY000',
  index: 0,
  sql: 'update `directus_users` set `email_notifications` = true'
}
```

- Does Directus support MySQL InnoDB Cluster and/or MariaDB Galera Cluster?
- If not, are there any alternatives to run it on a DB cluster?

### To Reproduce

- Deploy a MySQL InnoDB Cluster
```
 MySQL  proj-mysql01:3306 ssl  JS > cluster.status()
{
    "clusterName": "my_innodb_cluster",
    "defaultReplicaSet": {
        "name": "default",
        "ssl": "REQUIRED",
        "status": "OK",
        "statusText": "Cluster is ONLINE and can tolerate up to ONE failure.",
        "topology": {
            "proj-mysql01:3306": {
                "address": "proj-mysql01:3306",
                "memberRole": "PRIMARY",
                "mode": "R/W",
                "readReplicas": {},
                "replicationLag": null,
                "role": "HA",
                "status": "ONLINE",
                "version": "8.0.27"
            },
            "proj-mysql02:3306": {
                "address": "proj-mysql02:3306",
                "memberRole": "PRIMARY",
                "mode": "R/W",
                "readReplicas": {},
                "replicationLag": null,
                "role": "HA",
                "status": "ONLINE",
                "version": "8.0.27"
            },
            "proj-mysql03:3306": {
                "address": "proj-mysql03:3306",
                "memberRole": "PRIMARY",
                "mode": "R/W",
                "readReplicas": {},
                "replicationLag": null,
                "role": "HA",
                "status": "ONLINE",
                "version": "8.0.27"
            }
        },
        "topologyMode": "Multi-Primary"
    },
    "groupInformationSourceMember": "proj-mysql01:3306"
}
```
- Configure the DB env variables to point to the cluster or MysqlRouter
- Run `npx directus bootstrap`

### Errors Shown

The table does not comply with the requirements by an external plugin

### What version of Directus are you using?

9.3.0 and 9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL InnoDB Cluster

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
As suggested by [this stackoverflow response](https://stackoverflow.com/a/54796958/9036382), this is a limitation of MySQL 5.7:

> My guess is that you are running your group in multi primary mode and as stated here:
> 
> https://dev.mysql.com/doc/refman/5.7/en/group-replication-deploying-in-multi-primary-or-single-primary-mode.html
> 
> > If a transaction executes against a table that has foreign keys with cascading constraints, then the transaction fails to commit when synchronizing itself with the group.
> 
> You are hitting this limitation. My suggestion is to try to run it in Single Primary mode.

**Comment by RamyAllam** [comment]
@Oreilles All the instances inside the cluster are running MySQL 8.0.27.  Does the same limit of 5.7 apply on 8.X?

**Comment by Oreilles** [comment]
Don't know for certain, as that section of the documentation have been removed from the version 8.
Have you tried running in Single Primary mode as suggested ?

**Comment by RamyAllam** [comment]
> Don't know for certain, as that section of the documentation have been removed from the version 8.
> Have you tried running in Single Primary mode as suggested ?

Yeah, I can confirm the bootstrap process is working properly under: Single-Primary 🎉 

However, I think it leads to another limitation because it will always read/write from only one Primary server since Directus does not support multiple DB servers in `DB_HOST` env.

I was thinking to use MySQLRouter to do balance the Read/Write Ops on all the Primary servers in the cluster but now I'm pointing Directus only to the MySQL Primary server IP OR The Primary Server Port in MySQLRouter.
```
[routing:my_innodb_cluster_rw]
bind_address=127.0.0.1
bind_port=6446
destinations=metadata-cache://my_innodb_cluster/?role=PRIMARY
routing_strategy=first-available
protocol=classic
```

I wonder if Regex-based routing for Queries using ProxySQL or MariaDB MaxScale is a way to go.  What do you think?

**Comment by Oreilles** [comment]
I'm sorry but I have no experience in any of those tech and couldn't help you further.
