### ISSUE TITLE
Timeout when deleting relation in many-to-many field with SQLite3 

### ISSUE THREAD

**Issue by robertrosman** [directus/directus#11064]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm running Directus locally with SQLite3, and I can't remove relations from an M2M field, since it always freezes for 30s, then throwing a timeout exception. It works with an admin account, but no other roles. I've enabled read/write access to all related collections for the given role. I've tried both through the admin app and through api, but neither works.

Here is the database structure for context:

```
wishes:
  id
  belongs_to (M2M)
  ...

accounts:
  id
  ...

wish2account
  id
  account
  wish
```

I've tried both of the following PATCH requests to `/items/wishes/1182` with the same result. belongs_to is [1270, 1259] before the request, trying to delete 1270.

```
{
  "id": 1182,
  "title": "A wish that won't update",
  "belongs_to": {
    "create": [],
    "update": [],
    "delete": [
      1270
    ]
  }
}
```

```
{
  "belongs_to": [
    1259
  ]
}
```

Any ideas how to get it working?

### To Reproduce

- Create two collections where the second table has a many-to-many field to the first
- Create some items in both and add some relations in the many-to-many field
- Delete one or more of the relations with a non-admin-role that still has permissions to do so
- Take a cup of tea
- Knex throwing timeout error

### Errors Shown

When running `DEBUG=knex:* npm run start`:

```
  knex:client acquired connection from pool: __knexUid1 +5s
  knex:query select `ip_access` from `directus_roles` where `id` = ? limit ? undefined +5s
  knex:bindings [ '9bb96de0-69aa-47b4-97fc-ca8c1de7befc', 1 ] undefined +5s
  knex:client releasing connection to pool: __knexUid1 +1ms
  knex:client acquired connection from pool: __knexUid1 +4ms
  knex:query select * from `directus_permissions` where `role` = ? undefined +5ms
  knex:bindings [ '9bb96de0-69aa-47b4-97fc-ca8c1de7befc' ] undefined +4ms
  knex:client releasing connection to pool: __knexUid1 +2ms
  knex:client acquired connection from pool: __knexUid1 +7ms
  knex:query select `wishes`.`id`, `wishes`.`status`, `wishes`.`user_created`, `wishes`.`date_created`, `wishes`.`date_updated`, `wishes`.`title`, `wishes`.`description`, `wishes`.`amount` from `wishes` where ((`wishes`.`id` in (?))) order by `wishes`.`id` asc limit ? undefined +10ms
  knex:bindings [ '1182', 1 ] undefined +10ms
  knex:client releasing connection to pool: __knexUid1 +1ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select * from (select `wish2account`.`wish`, `wish2account`.`id` from `wish2account` where `wish2account`.`wish` = ? order by `wish2account`.`id` asc limit ?) as `foo` undefined +2ms
  knex:bindings [ 1182, 100 ] undefined +2ms
  knex:client releasing connection to pool: __knexUid1 +1ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select * from (select `bookings`.`wish`, `bookings`.`id` from `bookings` where `bookings`.`wish` = ? order by `bookings`.`id` asc limit ?) as `foo` undefined +1ms
  knex:bindings [ 1182, 100 ] undefined +1ms
  knex:client releasing connection to pool: __knexUid1 +1ms
  knex:tx trx2: Starting top level transaction +0ms
  knex:client acquired connection from pool: __knexUid1 +3ms
  knex:query BEGIN; trx2 +4ms
  knex:bindings undefined trx2 +4ms
  knex:query update `wishes` set `title` = ?, `description` = ?, `date_updated` = ? where `id` in (?) trx2 +4ms
  knex:bindings [ 'Nytt test', '', 2022-01-15T04:41:42.928Z, '1182' ] trx2 +4ms
  knex:tx trx3: Starting nested transaction +8ms
  knex:query SAVEPOINT trx3; trx3 +4ms
  knex:bindings undefined trx3 +4ms
  knex:query RELEASE SAVEPOINT trx3; trx3 +0ms
  knex:bindings undefined trx3 +0ms
  knex:tx trx3: releasing connection +1ms
  knex:query select `wish2account`.`id` from `wish2account` where (`wish2account`.`wish` = ? and `wish2account`.`id` in (?)) order by `wish2account`.`id` asc limit ? trx3 +1ms
  knex:bindings [ '1182', 1270, 100 ] trx3 +1ms
  knex:query ROLLBACK trx3 +1m
  knex:bindings undefined trx3 +1m
  knex:tx trx2: releasing connection +1m
  knex:client releasing connection to pool: __knexUid1 +1m
05:42:42 🚨 KnexTimeoutError Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/Users/robert.rosman/repos/onskeappen-api/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/Users/robert.rosman/repos/onskeappen-api/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/Users/robert.rosman/repos/onskeappen-api/node_modules/knex/lib/execution/runner.js:30:19)
    at async run (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/database/run-ast.js:36:26)
    at async runAST (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/database/run-ast.js:29:16)
    at async ItemsService.readByQuery (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/services/items.js:208:25)
    at async ItemsService.readMany (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/services/items.js:256:25)
    at async AuthorizationService.checkAccess (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/services/authorization.js:228:28)
    at async ItemsService.deleteMany (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/services/items.js:461:13)
    at async ItemsService.deleteByQuery (/Users/robert.rosman/repos/onskeappen-api/node_modules/directus/dist/services/items.js:442:30)
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### What operating system are you using?

Mac OS

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment]
Hello @robertrosman 
I am not able to reproduce your issue. Here's a working example on 86b7f7f68 (latest commit on main):

https://user-images.githubusercontent.com/14039341/149621869-f5feeee2-63a4-482a-8e78-5d50a9bf6082.mov

Can you try running at this commit?
Here's how to run this repo locally 👍

**Comment by robertrosman** [comment]
Thanks for quick response @joselcvarela! Interesting, I'll try it out to see if I can reproduce or not with the latest commit on main.

**Comment by robertrosman** [comment]
Hmm, I tried both running the directus repo locally and also setting up a brand new project with the latest stable version. Both worked without being able to reproduce. I guess either my database is corrupt somehow, or my settings or plugins are messing with me 🙈
