### ISSUE TITLE
The /auth/refresh/ api endpoint throws 500 error

### ISSUE THREAD

**Issue by jawngee** [directus/directus#11177]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When the admin app refreshes the token, the server is reporting a 500 error and forces the user to login again.

### To Reproduce

Upgraded 9.4.0 to 9.4.3.

### Errors Shown

```bash
directus: 09:01:19 🚨 error select "s"."expires" as "session_expires", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ($1, $2) where "s"."token" = $3 and "s"."expires" >= $4 and ("d"."date_end" is null or "d"."date_end" >= $5) and ("d"."date_start" is null or "d"."date_start" <= $6) limit $7 - invalid input syntax for type uuid: "u.role" 
directus: error: select "s"."expires" as "session_expires", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ($1, $2) where "s"."token" = $3 and "s"."expires" >= $4 and ("d"."date_end" is null or "d"."date_end" >= $5) and ("d"."date_start" is null or "d"."date_start" <= $6) limit $7 - invalid input syntax for type uuid: "u.role"
directus:     at Parser.parseErrorMessage (/Volumes/Projects/Products/Ideas/Voyeur/cms/node_modules/pg-protocol/src/parser.ts:369:69)
directus:     at Parser.handlePacket (/Volumes/Projects/Products/Ideas/Voyeur/cms/node_modules/pg-protocol/src/parser.ts:188:21)
directus:     at Parser.parse (/Volumes/Projects/Products/Ideas/Voyeur/cms/node_modules/pg-protocol/src/parser.ts:103:30)
directus:     at Socket.<anonymous> (/Volumes/Projects/Products/Ideas/Voyeur/cms/node_modules/pg-protocol/src/index.ts:7:48)
directus:     at Socket.emit (node:events:390:28)
directus:     at Socket.emit (node:domain:475:12)
directus:     at addChunk (node:internal/streams/readable:315:12)
directus:     at readableAddChunk (node:internal/streams/readable:289:9)
directus:     at Socket.Readable.push (node:internal/streams/readable:228:10)
directus:     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
directus: 09:01:19 ✨ request errored POST 500 /auth/refresh 6ms
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres

### What browser are you using?

Safari and Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Running locally

**Comment by jawngee** [comment]
Fixed in this commit: https://github.com/directus/directus/commit/c40585c9c8e838bdafbca8bcbc3f997bba65d264
