### ISSUE TITLE
SMTP email

### ISSUE THREAD

**Issue by j-kia** [directus/directus#11210]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Email connection fails when I'm using email service

### To Reproduce

- Secure false

```
EMAIL_TRANSPORT: 'smtp'
EMAIL_FROM: 'kurs@axelina.com'
EMAIL_SMTP_HOST: 'smtp-relay.gmail.com'
EMAIL_SMTP_PORT: 25
EMAIL_SMTP_USER: 'kurs@axelina.com'
EMAIL_SMTP_PASSWORD: *********
EMAIL_SMTP_SECURE: 'false'
EMAIL_SMTP_IGNORE_TLS: 'true'
```

- Secure true (I also tried port 465)
```
EMAIL_TRANSPORT: 'smtp'
EMAIL_FROM: 'kurs@axelina.com'
EMAIL_SMTP_HOST: 'smtp-relay.gmail.com'
EMAIL_SMTP_PORT: 25
EMAIL_SMTP_USER: 'kurs@axelina.com'
EMAIL_SMTP_PASSWORD: *********
EMAIL_SMTP_SECURE: 'true'
```

### Errors Shown

- Error when EMAIL_SMTP_SECURE is false
```
Error: Mail command failed: 550-5.7.1 Invalid credentials for relay [94.16.105.112]. The IP address you've
550-5.7.1 registered in your G Suite SMTP Relay service doesn't match domain of
550-5.7.1 the account this email is being sent from. If you are trying to relay
550-5.7.1 mail from a domain that isn't registered under your G Suite account
550-5.7.1 or has empty envelope-from, you must configure your mail server
550-5.7.1 either to use SMTP AUTH to identify the sending domain or to present
550-5.7.1 one of your domain names in the HELO or EHLO command. For more
550-5.7.1 information, please visit
550 5.7.1  https://support.google.com/a/answer/6140680#invalidcred e13sm297726wrg.0 - gsmtp
    at SMTPConnection._formatError (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionMAIL (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:1566:34)
    at SMTPConnection.<anonymous> (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:1041:18)
    at SMTPConnection._processResponse (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at Socket.SMTPConnection._onSocketData (/directus/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```
- Error when EMAIL_SMTP_SECURE is true
```
[Error: 139748882389808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
10:00:51 🚨 139748882389808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
 
Error: 139748882389808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

10:00:51 ✨ request errored POST 500 /email/admin 166ms
10:00:51 ⚠️  Email connection failed:
10:00:51 ⚠️  139748882389808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySql

### What browser are you using?

Any browser

### What operating system are you using?

linux

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment]
I followed instructions also using a google email. Here is my config:
```
EMAIL_FROM="<MY_OTHER_EMAIL>@gmail.com"
EMAIL_TRANSPORT="smtp"

# ## Email (SMTP Transport)
# EMAIL_SMTP_POOL=true
EMAIL_SMTP_HOST="smtp.gmail.com"
EMAIL_SMTP_PORT=465
# EMAIL_SMTP_IGNORE_TLS=false
EMAIL_SMTP_USER="<MY_EMAIL>@gmail.com"
EMAIL_SMTP_PASSWORD="<APP_SPECIFIC_PASSWORD>"
EMAIL_SMTP_SECURE=true # Use TLS
```
I tested the mailing ability through an @mention in a comment on an item.

It was able to send and I was able to receive it. I did have to set an app-specific password through google but that didn't give me the same error. 
https://support.google.com/mail/?p=InvalidSecondFactor 

With port 25 I got:
> [INTERNAL_SERVER_ERROR] connect ETIMEDOUT 209.85.232.109:25
Which was also not your error.

**Comment by j-kia** [comment]
> Is there a specific place you were using the email system?

I get this error all the time wherever i want to use the email service. When sending invitation mail with directus app or using MailsService in custom endpoints to send email with template

**Comment by rijkvanzanten** [comment]
@j-kia Try setting `EMAIL_SMTP_SECURE` to false. When `false`, nodemailer will automatically decide whether or not to use SSL based on the host used

**Comment by j-kia** [comment]
> Try setting `EMAIL_SMTP_SECURE` to false. When `false`, nodemailer will automatically decide whether or not to use SSL based on the host used

I set it to false and get `Connection timeout` error

**Comment by j-kia** [comment]
I updated **openssl** and now it doesn't give me the `wrong version number` error, Now i just have `Connection timeout` error no matter setting `EMAIL_SMTP_SECURE` to `true` or `false` .

**Comment by jaycammarano** [comment]
Did you change your port back to 465? I got that error on port 25.

**Comment by j-kia** [comment]
@jaycammarano yes you're right, I was using port 25, I change it to 465 and now i get:

> Invalid login: 535-5.7.8 Username and Password not accepted.

I checked username and password and it was correct. it seems i should allow less secure app in my account settings. 
I will let you know if the problem is solved by doing this.

**Comment by jaycammarano** [comment]
> @jaycammarano yes you're right, I was using port 25, I change it to 465 and now i get:
> 
> > Invalid login: 535-5.7.8 Username and Password not accepted.
> 
> I checked username and password and it was correct. it seems i should allow less secure app in my account settings. I will let you know if the problem is solved by doing this.

Did you set an app-specific password with Google? I had to do that.

**Comment by rijkvanzanten** [comment]
It sounds to me like this is most likely a configuration issue, lets keep this discussion going in Discussions 👍🏻
