### ISSUE TITLE
Cannot save updates on M2A child items.

### ISSUE THREAD

**Issue by jorgefelico** [directus/directus#11310]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I create a collection that has child collections via M2A relationship, the child collections save initially without any issues , however when I go edit the child collection within the parent, The updates I make are not reflected on screen nor on the database. There's also a console error displaying.

### To Reproduce

Create two collections, make one collection have a Many to Any relationship with the other collection. Create a parent entry and add a child item of the other collection. Once the M2A item has been saved on the parent collection, go back and try to edit it.
![PeDeoXGxeW](https://user-images.githubusercontent.com/4616355/151497515-f4b3c045-1d91-487d-93fd-0a823ebb9c02.gif)

### Errors Shown

```
vendor.9c15ff54.js:5 TypeError: Cannot create property 'content' on string '17'
    at Proxy.A (index.3a276397.entry.js:43:69915)
    at onUpdate:modelValue (index.3a276397.entry.js:43:72473)
    at Nh (vendor.9c15ff54.js:5:656)
    at $1 (vendor.9c15ff54.js:5:735)
    at cB (vendor.9c15ff54.js:2:21133)
    at Proxy.v (index.3a276397.entry.js:43:62759)
    at HO.a.onUpdate:modelValue.t.<computed>.t.<computed> (index.3a276397.entry.js:43:65437)
    at Nh (vendor.9c15ff54.js:5:656)
    at $1 (vendor.9c15ff54.js:5:735)
    at cB (vendor.9c15ff54.js:2:21133)
```

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.18.3

### What database are you using?

MySQL 5.7.36

### What browser are you using?

Chrome

### What operating system are you using?

macOS & Windows 10

### How are you deploying Directus?

running locally

**Comment by jorgefelico** [comment]
Figured out it was an issue with the Sort field on the parent collection.
