### ISSUE TITLE
Insights - Can't create panel with Metric type

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11435]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can't create panel with `Metric` type.

### To Reproduce

https://user-images.githubusercontent.com/1007051/152574935-41ca8693-88d8-4036-8226-0c1e5879172f.mov

### Errors Shown

```
vendor.62e5a05d.js:5 TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.getField (index.7af4eb85.entry.js:32:420250)
    at Proxy.<anonymous> (vendor.62e5a05d.js:9:2538)
    at I3.fn (index.7af4eb85.entry.js:43:171225)
    at I3.run (vendor.62e5a05d.js:2:11990)
    at lB.get value [as value] (vendor.62e5a05d.js:2:20235)
    at I3.fn (index.7af4eb85.entry.js:43:171367)
    at I3.run (vendor.62e5a05d.js:2:11990)
    at lB.get value [as value] (vendor.62e5a05d.js:2:20235)
    at Object.options (index.7af4eb85.entry.js:43:172113)
    at I3.fn (index.7af4eb85.entry.js:32:170372)
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by NecoHorne** [comment]
Same issue after updating to 9.5.1

Running on Linux 5.11.0-1028-aws / Ubuntu 20.04

Node version: 16.13.2

DB: MySQL  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64

```
vendor.62e5a05d.js:5 TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.getField (index.7af4eb85.entry.js:32:420250)
    at Proxy.<anonymous> (vendor.62e5a05d.js:9:2538)
    at I3.fn (index.7af4eb85.entry.js:43:171225)
    at I3.run (vendor.62e5a05d.js:2:11990)
    at lB.get value [as value] (vendor.62e5a05d.js:2:20235)
    at I3.fn (index.7af4eb85.entry.js:43:171367)
    at I3.run (vendor.62e5a05d.js:2:11990)
    at lB.get value [as value] (vendor.62e5a05d.js:2:20235)
    at Object.options (index.7af4eb85.entry.js:43:172113)
    at I3.fn (index.7af4eb85.entry.js:32:170372)
```

**Comment by Shantarli** [comment]
Same here for 9.5.1 version
