### ISSUE TITLE
Can't create fields in a Repeater field

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11447]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can't create fields in a Repeater field.

### To Reproduce

https://user-images.githubusercontent.com/1007051/152649068-4793275d-8a0a-4d1d-8bb3-81f810026a73.mov

### Errors Shown

```
vendor.62e5a05d.js:5 TypeError: Cannot read properties of null (reading '0')
    at Proxy.A (index.7af4eb85.entry.js:257:5197)
    at i.onCancel.t.<computed>.t.<computed> (index.7af4eb85.entry.js:257:7435)
    at Nh (vendor.62e5a05d.js:5:656)
    at $1 (vendor.62e5a05d.js:5:735)
    at cB (vendor.62e5a05d.js:2:21133)
    at e.cancelable.C.onClick.t.<computed>.t.<computed> (index.7af4eb85.entry.js:43:39438)
    at Nh (vendor.62e5a05d.js:5:656)
    at $1 (vendor.62e5a05d.js:5:735)
    at cB (vendor.62e5a05d.js:2:21133)
    at _ (index.7af4eb85.entry.js:43:17676)
```

```
vendor.62e5a05d.js:5 TypeError: Cannot read properties of null (reading 'map')
    at D (index.7af4eb85.entry.js:257:5277)
    at Proxy.g (index.7af4eb85.entry.js:257:5042)
    at i.onClick.t.<computed>.t.<computed> (index.7af4eb85.entry.js:257:7656)
    at Nh (vendor.62e5a05d.js:5:656)
    at $1 (vendor.62e5a05d.js:5:735)
    at cB (vendor.62e5a05d.js:2:21133)
    at _ (index.7af4eb85.entry.js:43:17676)
    at Nh (vendor.62e5a05d.js:5:656)
    at $1 (vendor.62e5a05d.js:5:735)
    at HTMLButtonElement.r (vendor.62e5a05d.js:5:9056)
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by VaZark** [comment]
Can confirm the issue occurs on postgres as well for v9.5.1

**Comment by azrikahar** [comment]
@VaZark thanks for confirming it with a different database 👍 helps a lot to isolate the potential root cause. Submitted a PR to fix this.

**Comment by rashidpathiyil** [comment]
Stuck on this issue

**Comment by danieljwestman** [comment]
Same here, impossible to use the repeater interface as for now.

Running 9.5.1 with PG 13

**Comment by neosa** [comment]
There was a problem with the repeater after updating to the latest version
