### ISSUE TITLE
Cannot read properties of undefined (reading 'replace') after update to 9.5.1

### ISSUE THREAD

**Issue by annejan89** [directus/directus#11638]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After updating from 9.5.1 from v9.0.0-rc.98 and performing the latest migrations, Directus was showing an error message on all authorizes pages. While I was able to login.

### To Reproduce

Had to compare a newly created database (that was working correctly) with the existing database. After I spend some time on debugging I discovered that some rows in the directus_fields table had a missing translation key and value in the translations column while the language was set.

[{"language": "nl-NL", "translation": "Vragen"}]
[{"language": "en-US"}]

After clearing the columns with the missing translation key and value I was able to use Directus again.

### Errors Shown

{
  "stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at Proxy.parseField (http://localhost:8055/admin/assets/index.7af4eb85.entry.js:32:417152)\n    at http://localhost:8055/admin/assets/vendor.62e5a05d.js:9:2538\n    at Array.map (<anonymous>)\n    at Proxy.hydrate (http://localhost:8055/admin/assets/index.7af4eb85.entry.js:32:416868)\n    at async Promise.all (index 1)\n    at async il (http://localhost:8055/admin/assets/index.7af4eb85.entry.js:32:408358)\n    at async BC (http://localhost:8055/admin/assets/index.7af4eb85.entry.js:32:142192)",
  "message": "Cannot read properties of undefined (reading 'replace')"
}

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Mysql 8.0.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

locally

**Comment by annejan89** [comment]
Now I see this is a duplicate of #11490. Should be great to mention the exact error message (instead of screenshots) in that issue so its easier to find. This issue can be closed!
