### ISSUE TITLE
GraphQL Error with Translations of Model

### ISSUE THREAD

**Issue by wodka** [directus/directus#11693]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The moment I make the Translations of a Model public so I can query then via GraphQL an error appears.

![image](https://user-images.githubusercontent.com/385731/154551112-7f2def23-39fd-46ee-94e9-9f019f5bc197.png)
![image](https://user-images.githubusercontent.com/385731/154551219-35a511db-dc2f-4baf-9de4-adda865fea9a.png)
![image](https://user-images.githubusercontent.com/385731/154551171-6ff871db-04ea-4675-aea5-45d5b0712479.png)
![image](https://user-images.githubusercontent.com/385731/154551294-cac4da07-eab4-4c98-b753-02cee4254354.png)

TypeError[snippet_translations.languages_code]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })

### To Reproduce

Start a new Instance with 9.5.1 and add a translation to one Model.

-> Mark Model as public and it's translation and try to query it.

### Errors Shown

19:50:11 🚨 TypeError[snippet_translations.languages_code]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] }) 
Error: TypeError[snippet_translations.languages_code]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })
    at TypeMapper.convertOutputFieldConfig (/directus/node_modules/graphql-compose/lib/TypeMapper.js:230:27)
    at ObjectTypeComposer.setField (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)
    at /directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18
    at Array.forEach (<anonymous>)
    at ObjectTypeComposer.addFields (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)
    at getTypes (/directus/node_modules/directus/dist/services/graphql.js:339:105)
    at getReadableTypes (/directus/node_modules/directus/dist/services/graphql.js:398:62)
    at GraphQLService.getSchema (/directus/node_modules/directus/dist/services/graphql.js:134:41)
    at GraphQLService.execute (/directus/node_modules/directus/dist/services/graphql.js:91:29)
    at /directus/node_modules/directus/dist/controllers/graphql.js:27:40
19:50:11 ✨ request errored POST 500 /graphql 17ms

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

CockroachDB

### What browser are you using?

Chrome / Safari / Postman / Firefox

### What operating system are you using?

Docker / OSX / Linux

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello,
I am just testing that here and found no problem:

https://user-images.githubusercontent.com/14039341/154898128-d4de6e15-391c-4824-a3f3-c2342d33a1e8.mov

You might have some issue with those collections.
Can you try if this also happens on a fresh install?

**Comment by rijkvanzanten** [comment]
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._
