### ISSUE TITLE
Migration down() sorting by timestamp instead of version

### ISSUE THREAD

**Issue by boncossoftware** [directus/directus#12080]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When migrating down the order of the migrations is incorrect causing an incorrect down migrations. From what I can see, the problem is that when migrating down the migrations are sorted by timestamp but the timestamps are not accurate enough (seconds) to capture the correct reverse order. Probably the better solution would be to just reverse the order based on the version number keeping it consistent with the up migration. 

See code here:
[`const lastAppliedMigration = orderBy(completedMigrations, ['timestamp'], ['desc'])[0];`](https://github.com/directus/directus/blob/d9279c1de14290f3e28a88397bc445d4809f8cfe/api/src/database/migrations/run.ts)

### To Reproduce

Just try to migrate down on the latest version.

### Errors Shown

./node_modules/.bin/directus database migrate:down
15:38:56 ✨ Running migrations...
15:38:56 ✨ Undoing Add Default Folder...
15:38:56 🚨 alter table `directus_files` drop foreign key `directus_settings_storage_default_folder_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_settings_storage_default_folder_foreign'; check that column/key exists 
Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_settings_storage_default_folder_foreign'; check that column/key exists
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
    at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/app/node_modules/knex/lib/client.js:144:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/app/node_modules/knex/lib/execution/runner.js:224:21)
    at Runner.queryArray (/app/node_modules/knex/lib/execution/runner.js:241:31)

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL5.7

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

 running locally, Docker

**Comment by boncossoftware** [comment]
Or just use an incrementing number instead for the reverse order.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten Can the version numbers confirmed to be in ascending order? [#8254 (comment)](https://github.com/directus/directus/issues/8254#issuecomment-926054427)
> It might be an issue again if it's changed to version number and there's a long running PR which resulted in #8254. Will it could be ok if the filename of the migration is always changed to the date it's merged?

No they can't. There are user provided IDs in there as well through custom migrations, so that can't be relied on. The timestamps should be the reliable source of truth. If those aren't precise or wrongly generated, that's the bug to fix 👍🏻
