### ISSUE TITLE
Error "stack depth limit exceeded" when retrieving nested data (v9.5.2)

### ISSUE THREAD

**Issue by arladmin** [directus/directus#12140]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to retrieve all the records(around 30k) from a collection, along with the nested fields (```fields=*.*```), i run into this error:
```stack depth limit exceeded ```
If i don't retrieve nested data, then the API call runs successfully.

### To Reproduce

1. Retrieve all the records (```limit=-1```) from a collection (that contains a few relational fields)
2. Set ```fields=*.*```

### Errors Shown

```
stack depth limit exceeded

    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)

    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)

    at Socket.emit (node:events:520:28)

    at addChunk (node:internal/streams/readable:315:12)

    at readableAddChunk (node:internal/streams/readable:289:9)

    at Socket.Readable.push (node:internal/streams/readable:228:10)

    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14.x

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, understandably it was just released recently, but do you mind testing this on `9.7.0` to see does this issue still persist in the latest version? If it does, can you provide a minimal schema snapshot for us to replicate and investigate further? It'd be very helpful, thanks!

**Comment by rijkvanzanten** [comment]
I believe this was resolved in https://github.com/directus/directus/pull/11246
