### ISSUE TITLE
Validation causes error when creating items

### ISSUE THREAD

**Issue by alebianco-doxee** [directus/directus#12589]
### Describe the Bug

Under some circumstances, the new validation system may cause an error when creating an item

this is cause by the fact that the admin has a default validation value of `{}`; that is not overwritten if there're no required field (and a UUID, being a special field, is considered non-required); later, because of "wrong" if check, that empty object is added to the list of validations to check; finally the empty object does not play nicely with the joi schema creation and breaks everything.

as a workaround, I defined another not-nullable field in my collections.

### To Reproduce

- operating as admin
- create a collection
  - add a UUID field as primary key
  - add other fields but leave them as nullable
  - add some validation rules to the fields
- add a new item to the collection
- when saving the item, an error popup is displayed and the backend process reports the error below

### Errors Shown

```
14:56:20 🚨 [generateJoi] Filter doesn't contain field key. Passed filter: {}
Error: [generateJoi] Filter doesn't contain field key. Passed filter: {}
    at generateJoi (/directus/node_modules/@directus/shared/dist/cjs/utils/generate-joi.js:74:15)
    at validatePayload (/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:37:55)
    at /directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:23:20
    at Array.map (<anonymous>)
    at validatePayload (/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:22:66)
    at AuthorizationService.validatePayload (/directus/node_modules/directus/dist/services/authorization.js:361:84)
    at /directus/node_modules/directus/dist/services/items.js:84:46
```

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.4

### What database are you using?

sqlite & postgres (different environments)

### What browser are you using?

chrome

### How are you deploying Directus?

Docker

**Comment by alebianco-doxee** [comment]
this is where the empty object is added to the validation list because of the "wrong" if

https://github.com/directus/directus/blob/ca59a8e4d096b8f1d4948cea631f2f1713960bb6/api/src/services/authorization.ts#L472
