### ISSUE TITLE
Difficulties with user creation 

### ISSUE THREAD

**Issue by SumitBando** [directus/directus#12669]
### Describe the Bug

Trying to create a new user programmatically, as of registration flow, can not be done using a role name, detailed in "To Reproduce" section.

The documentation does not say it explicitly, but looks like the "role" needs to be the UUID primary key?
How will that work between dev/test/prod instances?

Trying to find it in the UI, which decides to fashionably elide it?!?
<img width="314" alt="Screen Shot 2022-04-11 at 10 56 24 AM" src="https://user-images.githubusercontent.com/248569/162670861-82e499bc-82ec-47d0-9935-0f1360021cef.png">

So the solution is to look at the tables, find the correct one (directus_roles), find the row with the role, and manually pick the uuid?

### To Reproduce

POST {{DIRECTUS_URL}}/users
{
	"email": "new@email.com",
	"password": "password",
	"role": "existingRole"
}

### Errors Shown

Status: 500 Internal Server Error
{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

error insert into "directus_users" ("email", "id", "password", "role") values ($1, $2, $3, $4) returning "id" - invalid input syntax for type uuid: "existingRole" 
error: insert into "directus_users" ("email", "id", "password", "role") values ($1, $2, $3, $4) returning "id" - invalid input syntax for type uuid: "existingRole"
    at Parser.parseErrorMessage (/Users/sumit/projects/neoleap-directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/sumit/projects/neoleap-directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/sumit/projects/neoleap-directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/sumit/projects/neoleap-directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

v14.17.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
> Trying to create a new user programmatically, as of registration flow, can not be done using a role name

> The documentation does not say it explicitly, but looks like the "role" needs to be the UUID primary key?

Yes it needs to and can only be the UUID primary key. Seems like it is indeed not reflected over here: https://docs.directus.io/reference/system/users/#the-user-object, so the docs should definitely be updated. Thanks for pointing that out. 👍

> A copy widget would be useful, instead of the ...

Agreed! It has been brought up a while ago, it's just not implemented yet. PRs are also welcome!

> So the solution is to look at the tables, guess the correct one (directus_roles), find the row with the role, and manually pick the uuid?

> How will that work between dev/test/prod instances?

If the need is to create a user using a role name instead of UUID, one solution would be to [create a custom endpoint](https://docs.directus.io/extensions/endpoints/) for it. A crude example of such endpoint extension would be:

(Insert this file to `/extensions/registration/index.js`)

```js
module.exports = (router, { services, exceptions }) => {
	const { RolesService, UsersService } = services;
	const { InvalidPayloadException } = exceptions;

	router.post('/', async (req, res, next) => {
		const rolesService = new RolesService({ schema: req.schema });

		if (!req.body.email || !req.body.password || !req.body.roleName) {
			return next(new InvalidPayloadException('email, password and/or role name missing'));
		}

		const foundRole = await rolesService.readByQuery({ filter: { name: req.body.roleName } });
		if (foundRole.length === 0) {
			return next(new InvalidPayloadException('role does not exist'));
		}

		const usersService = new UsersService({ schema: req.schema });

		try {
			const createdUser = await usersService.createOne({
				email: req.body.email,
				password: req.body.password,
				role: foundRole[0].id,
			});
			return res.json(createdUser);
		} catch (error) {
			return next(new InvalidPayloadException(error.message));
		}
	});
};
```

so that we make a POST request to `/registration` with this sample payload to create a user with `Manager` role:

```json
{
  "email": "test@example.com",
  "password": "password",
  "roleName": "Manager"
}
```

**Comment by SumitBando** [comment]
A solution will be to allow two different role attributes in the create call, roleID and roleName, and have the framework do the lookup for roleName.
