### ISSUE TITLE
Singleton breaks at v9.9.0

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#12910]
### Describe the Bug

When opening a Singleton Collection an error prompt gets shown and the content won't be loaded (correctly).

![image](https://user-images.githubusercontent.com/43739995/164389528-dceb7f5d-1c2f-4b48-8161-d3d0d715eb64.png)

There is one expection that I don't quite get: Sometimes when switching between Singletons it gets loaded correctly - but after a reload the same error come again.

Downgrading to v9.8 removed the errors completely.

### To Reproduce

Make sure you upgraded to v9.9.0

Create a Singleton 
Create a field and check collection view

I just tried 3 fields:
- input -> works normally
- translations -> breaks
- files -> breaks

### Errors Shown

![image](https://user-images.githubusercontent.com/43739995/164391035-0d01d999-1b66-4346-b3ae-13bd2c6fbb19.png)

Opened the "Training" Singleton here: 
Errors for translations and "references" which is another collection (O2M)
![image](https://user-images.githubusercontent.com/43739995/164391324-43035f66-6240-448d-90ac-60b1f3d5ce60.png)

Docker logs:
```
directus    | 06:50:37 🚨 Cannot convert undefined or null to object
directus    | TypeError: Cannot convert undefined or null to object
directus    |     at Function.keys (<anonymous>)
directus    |     at getFilterPath (/directus/node_modules/directus/dist/utils/apply-query.js:482:23)
directus    |     at addJoins (/directus/node_modules/directus/dist/utils/apply-query.js:115:32)
directus    |     at applyFilter (/directus/node_modules/directus/dist/utils/apply-query.js:100:5)
directus    |     at applyQuery (/directus/node_modules/directus/dist/utils/apply-query.js:53:9)
directus    |     at getDBQuery (/directus/node_modules/directus/dist/database/run-ast.js:162:38)
directus    |     at run (/directus/node_modules/directus/dist/database/run-ast.js:36:25)
directus    |     at runMicrotasks (<anonymous>)
directus    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
directus    |     at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
directus    | 06:50:37 ✨ request errored GET 500 /items/training_translations?aggregate=%7B%22count%22:%22id%22%7D&filter=%7B%22training_id%22:null%7D 28ms
directus    | 06:50:37 🚨 Cannot convert undefined or null to object
directus    | TypeError: Cannot convert undefined or null to object
directus    |     at Function.keys (<anonymous>)
directus    |     at getFilterPath (/directus/node_modules/directus/dist/utils/apply-query.js:482:23)
directus    |     at addJoins (/directus/node_modules/directus/dist/utils/apply-query.js:115:32)
directus    |     at applyFilter (/directus/node_modules/directus/dist/utils/apply-query.js:100:5)
directus    |     at applyQuery (/directus/node_modules/directus/dist/utils/apply-query.js:53:9)
directus    |     at getDBQuery (/directus/node_modules/directus/dist/database/run-ast.js:162:38)
directus    |     at run (/directus/node_modules/directus/dist/database/run-ast.js:36:25)
directus    |     at runMicrotasks (<anonymous>)
directus    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
directus    |     at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
directus    | 06:50:37 ✨ request errored GET 500 /items/references?aggregate=%7B%22count%22:%22id%22%7D&filter=%7B%22training_fk%22:null%7D 24ms
directus    | 06:50:37 ✨ request completed GET 304 /items/training 53ms

```

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### How are you deploying Directus?

Docker

**Comment by kuuroo3** [comment]
If you need a snapshot I gladly send mine via DM
