### ISSUE TITLE
POST API requests failing

### ISSUE THREAD

**Issue by RijkvanZanten** [directus/directus#1293]
When doing a [post request to create a new row](http://getdirectus.com/api/tables/create-row) in a table I get the following error: `array_key_exists() expects parameter 2 to be array, null given`. This happens for the Create Table endpoint as well. Create Column fails too, but returns `Undefined index: data_type` as error.

## Version Info
  - Directus version and branch: v6.3.4 (Lapis Lepus) master / build / development
  - PHP version: PHP 7.0.8-0ubuntu0.16.04.3
  - MySQL version: 5.7.15-0ubuntu0.16.04.1
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior
It should return the created object as follows
```javascript
{
  "id": 1,
  "active": 1,
  "title": "Test"
}
```

## Actual Behavior
Returns error (see below)

## Steps to Reproduce
 1. Do the post request as follows
```
curl --data 'active=1&title=Test' https://DIRECTUS_URL/api/1/tables/test/rows -u ACCESS_TOKEN:
```

## Logs or Screenshots
```javascript
{
  "code":2,
  "class":"ErrorException",
  "message":"array_key_exists() expects parameter 2 to be array, null given",
  "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php",
  "line":36,
  "trace":[
    {
      "function":"handleErrors",
      "class":"Slim\\Slim",
      "type":"::",
      "args":[
        2,
        "array_key_exists() expects parameter 2 to be array, null given",
        "\/var\/www\/cms.echteheldenvanoranje.nl\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php",
        36,
        {
          "tableName":"test",
          "recordData":null,
          "activityEntryMode":1,
          "childLogEntries":null,
          "parentCollectionRelationshipsChanged":false,
          "parentData":[
            
          ],
          "TableGateway":{
            "primaryKeyFieldName":"id",
            "memcache":{
              
            }
          },
          "this":{
            "primaryKeyFieldName":"id",
            "memcache":{
              
            }
          }
        }
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php",
      "line":36,
      "function":"array_key_exists",
      "args":[
        "id",
        null
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/api\/api.php",
      "line":710,
      "function":"manageRecordUpdate",
      "class":"Directus\\Db\\TableGateway\\RelationalTableGateway",
      "type":"->",
      "args":[
        "test",
        null,
        1
      ]
    },
    {
      "function":"{closure}",
      "args":[
        "test"
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Route.php",
      "line":436,
      "function":"call_user_func_array",
      "args":[
        {
          
        },
        [
          "test"
        ]
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1305,
      "function":"dispatch",
      "class":"Slim\\Route",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php",
      "line":85,
      "function":"call",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php",
      "line":92,
      "function":"call",
      "class":"Slim\\Middleware\\Flash",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1254,
      "function":"call",
      "class":"Slim\\Middleware\\MethodOverride",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/cms.echteheldenvanoranje.nl\/api\/api.php",
      "line":1696,
      "function":"run",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 [internal function]: Slim\\Slim::handleErrors(2, 'array_key_exist...', '\/var\/www\/cms.ec...', 36, Array)\n#1 \/var\/www\/cms.echteheldenvanoranje.nl\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php(36): array_key_exists('id', NULL)\n#2 \/var\/www\/cms.echteheldenvanoranje.nl\/api\/api.php(710): Directus\\Db\\TableGateway\\RelationalTableGateway->manageRecordUpdate('test', NULL, 1)\n#3 [internal function]: {closure}('test')\n#4 \/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Route.php(436): call_user_func_array(Object(Closure), Array)\n#5 \/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Slim.php(1305): Slim\\Route->dispatch()\n#6 \/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#7 \/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#8 \/var\/www\/cms.echteheldenvanoranje.nl\/vendor\/slim\/slim\/Slim\/Slim.php(1254): Slim\\Middleware\\MethodOverride->call()\n#9 \/var\/www\/cms.echteheldenvanoranje.nl\/api\/api.php(1696): Slim\\Slim->run()\n#10 {main}"
```

**Comment by WellingGuzman** [comment]
Hey @RijkvanZanten,

Thanks for report this, I'm working on a fix right now, it will be pushed soon enough.

**Comment by WellingGuzman** [comment]
Hey @RijkvanZanten let me know if this commit 6b58d1c fixed the issue.

**Comment by WellingGuzman** [comment]
False alarm, I need to work with JSON as well. as it was to be expected normally.

**Comment by RijkvanZanten** [comment]
The commit fixed the initial issue.

**Comment by WellingGuzman** [comment]
@RijkvanZanten Amazing. I pushed another fix for when the request body was a json.

**Comment by RijkvanZanten** [comment]
Ah great, I didn't even know that was supported. Is that in the API docs somewhere? @WellingGuzman

**Comment by WellingGuzman** [comment]
Yes, it's supported, but I'm afraid is not in the docs. Added a ticket for it https://github.com/directus/docs/issues/11
