### ISSUE TITLE
JS SDK tries to refresh static token

### ISSUE THREAD

**Issue by jarne** [directus/directus#13006]
### Describe the Bug

When using the JS SDK, v9.9.1, it throws an error when authenticating using a static token and sending any request. To me, it looks like it tries to refresh the static token, but a static token shouldn't be refreshed as I understand.

### To Reproduce

```js
const { Directus } = require("@directus/sdk");

(async () => {
    const directus = new Directus("...")

    await directus.auth.static("...")

    const playlist = await directus.items("playlist").readOne(5)

    console.log(playlist)
})()
```

### Errors Shown

```
/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:706
            throw new TransportError(err);
                  ^

TransportError: "refresh_token" is required in either the JSON payload or Cookie
    at Transport.request (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:706:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transport.get (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:710:16)
    at async ItemsHandler.readOne (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:37:26)
    at async /Users/jarne/Downloads/directus-js-sdk-bug-repro/app.js:8:22 {
  parent: TransportError: "refresh_token" is required in either the JSON payload or Cookie
      at Transport.request (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:696:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Transport.post (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:725:16)
      at async Auth.refresh (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:806:26)
      at async Auth.refreshIfExpired (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:800:9)
      at async Transport.beforeRequest (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:887:21)
      at async Transport.request (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:674:22)
      at async Transport.get (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:710:16)
      at async ItemsHandler.readOne (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/@directus/sdk/dist/sdk.cjs.js:37:26)
      at async /Users/jarne/Downloads/directus-js-sdk-bug-repro/app.js:8:22 {
    parent: Error: Request failed with status code 400
        at createError (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/Users/jarne/Downloads/directus-js-sdk-bug-repro/node_modules/axios/lib/adapters/http.js:293:11)
        at IncomingMessage.emit (node:events:538:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
```

```
config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        adapter: [Function: httpAdapter],
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        headers: {
          Accept: 'application/json, text/plain, */*',
          'Content-Type': 'application/json',
          Authorization: '',
          'User-Agent': 'axios/0.24.0',
          'Content-Length': 22
        },
        baseURL: 'https://myurl',
        withCredentials: true,
        method: 'post',
        url: '/auth/refresh',
        data: '{"refresh_token":null}'
      },
```

```
response: {
      raw: {
        errors: [
          {
            message: '"refresh_token" is required in either the JSON payload or Cookie',
            extensions: [Object]
          }
        ]
      },
      status: 400,
      statusText: 'Bad Request',
      headers: {
        date: 'Tue, 26 Apr 2022 10:58:08 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '133',
        connection: 'close',
        'content-security-policy': "script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
        'x-powered-by': 'Directus',
        etag: 'W/"85-eTA01tQQkdFQTnPlqwL4x3RG/8Y"',
        'cf-cache-status': 'DYNAMIC',
       [...]
        nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
        'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        server: 'cloudflare',
        'cf-ray': '701ecd300cff915f-FRA',
        'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
      },
      data: undefined,
      meta: undefined,
      errors: [
        {
          message: '"refresh_token" is required in either the JSON payload or Cookie',
          extensions: { code: 'INVALID_PAYLOAD' }
        }
      ]
    },
    errors: [
      {
        message: '"refresh_token" is required in either the JSON payload or Cookie',
        extensions: { code: 'INVALID_PAYLOAD' }
      }
    ]
  },
```

(not the full output due to security reasons, but I hope I've added all relevant parts)

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Node.js

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
It definitely shouldn't try refreshing, at least that's how it _should_ be. 🤔 Just to rule out some possibilities, would you mind trying the following code instead?

```js
const { Directus } = require("@directus/sdk");

(async () => {
    const directus = new Directus("...", { auth: { staticToken: "your_static_token" } } )

    const playlist = await directus.items("playlist").readOne(5)

    console.log(playlist)
})()
```

**Comment by jarne** [comment]
> It definitely shouldn't try refreshing, at least that's how it _should_ be. 🤔 Just to rule out some possibilities, would you mind trying the following code instead?
> 
> ```js
> const { Directus } = require("@directus/sdk");
> 
> (async () => {
>     const directus = new Directus("...", { auth: { staticToken: "your_static_token" } } )
> 
>     const playlist = await directus.items("playlist").readOne(5)
> 
>     console.log(playlist)
> })()
> ```

Just tested it, it works fine using this code.

**Comment by azrikahar** [comment]
Thanks for confirming! I can also reproduce this on my end. 

I believe this is actually the same as #12644, but oddly it was not reproducible during that time.
