### ISSUE TITLE
API 1.1 bookmarks/self endpoint returns 500 error

### ISSUE THREAD

**Issue by RijkvanZanten** [directus/directus#1319]
## Version Info
  - Directus 6.3.5, branch development, latest commit [fc66aca](https://github.com/directus/directus/commit/fc66acabaa63a1e3cb17a235d401a0f36e611556)
  - PHP version: 5.6.25
  - MySQL version: 5.6.28
  - Web server: Apache (using MAMP on Mac)
  - OS name and version: MacOS Sierra 10.12.2

## Expected Behavior
Return bookmarks of currently authorized user

## Actual Behavior
Returns `Invalid method (fetchByUserId) called...` error (see below for full error)

## Steps to Reproduce
1. download and install fresh installation of directus
2. checkout development branch
3. install composer dependencies
4. log in to directus
5. go to /api/1.1/bookmarks/self

## Logs or Screenshots
```
{
  "code":0,
  "class":"Zend\\Db\\TableGateway\\Exception\\InvalidArgumentException",
  "message":"Invalid method (fetchByUserId) called, caught by Zend\\Db\\TableGateway\\AbstractTableGateway::__call()",
  "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/zendframework\/zend-db\/src\/TableGateway\/AbstractTableGateway.php",
  "line":520,
  "trace":[
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/api\/routes\/A1\/Bookmarks.php",
      "line":86,
      "function":"__call",
      "class":"Zend\\Db\\TableGateway\\AbstractTableGateway",
      "type":"->",
      "args":[
        "fetchByUserId",
        [
          "1"
        ]
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/api\/routes\/A1\/Bookmarks.php",
      "line":86,
      "function":"fetchByUserId",
      "class":"Directus\\Database\\TableGateway\\DirectusBookmarksTableGateway",
      "type":"->",
      "args":[
        "1"
      ]
    },
    {
      "function":"selfBookmarks",
      "class":"Directus\\API\\Routes\\A1\\Bookmarks",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Route.php",
      "line":436,
      "function":"call_user_func_array",
      "args":[
        [
          {
            
          },
          "selfBookmarks"
        ],
        [
          
        ]
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1305,
      "function":"dispatch",
      "class":"Slim\\Route",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php",
      "line":85,
      "function":"call",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php",
      "line":92,
      "function":"call",
      "class":"Slim\\Middleware\\Flash",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php",
      "line":22,
      "function":"call",
      "class":"Slim\\Middleware\\MethodOverride",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1254,
      "function":"call",
      "class":"Directus\\Slim\\CorsMiddleware",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/api\/core\/Directus\/Application\/Application.php",
      "line":74,
      "function":"run",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/rijkvanzanten\/Development\/directus\/api\/api.php",
      "line":1888,
      "function":"run",
      "class":"Directus\\Application\\Application",
      "type":"->",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 \/Users\/rijkvanzanten\/Development\/directus\/api\/routes\/A1\/Bookmarks.php(86): Zend\\Db\\TableGateway\\AbstractTableGateway->__call('fetchByUserId', Array)\n#1 \/Users\/rijkvanzanten\/Development\/directus\/api\/routes\/A1\/Bookmarks.php(86): Directus\\Database\\TableGateway\\DirectusBookmarksTableGateway->fetchByUserId('1')\n#2 [internal function]: Directus\\API\\Routes\\A1\\Bookmarks->selfBookmarks()\n#3 \/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Route.php(436): call_user_func_array(Array, Array)\n#4 \/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1305): Slim\\Route->dispatch()\n#5 \/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#6 \/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 \/Users\/rijkvanzanten\/Development\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php(22): Slim\\Middleware\\MethodOverride->call()\n#8 \/Users\/rijkvanzanten\/Development\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1254): Directus\\Slim\\CorsMiddleware->call()\n#9 \/Users\/rijkvanzanten\/Development\/directus\/api\/core\/Directus\/Application\/Application.php(74): Slim\\Slim->run()\n#10 \/Users\/rijkvanzanten\/Development\/directus\/api\/api.php(1888): Directus\\Application\\Application->run()\n#11 {main}"
}
```

**Comment by WellingGuzman** [comment]
Hey @RijkvanZanten I pushed a fix https://github.com/directus/directus/commit/14a608071579b5cfa4b5e12a04fb18d2b0865855

Let me know if that works for you.
