### ISSUE TITLE
Unable to add conditions for WYSIWYG fields due to JS error

### ISSUE THREAD

**Issue by phihu** [directus/directus#13680]
### Describe the Bug

When trying to add a condition to WYSIWYG type field in a collection a JS error occurs making it impossible to add/save a condition or even close the window/cancel the process.
The error occurs wether or not the field is saved before trying to add the condition.

The error occurred since updating to v9.11.1 from v9.10.0.

Thanks for your great work!

### To Reproduce

Add a WYSIWYG type field to a collection, go to "Conditions" click "create new".
When trying to close the condition editing window or trying to save a condition an error occurs preventing the window from closing/the condition from being saved.

### Errors Shown

vendor.3b903562.js:5 TypeError: Cannot read properties of undefined (reading 'options')
    at Gv.fn (index.711ccefb.entry.js:31:295295)
    at Gv.run (vendor.3b903562.js:2:12019)
    at fH.get value [as value] (vendor.3b903562.js:2:20264)
    at Um (vendor.3b903562.js:2:19290)
    at index.711ccefb.entry.js:31:295634
    at Array.map (<anonymous>)
    at Proxy.s (index.711ccefb.entry.js:31:295585)
    at a.onInput.t.<computed>.t.<computed> (index.711ccefb.entry.js:31:295852)
    at id (vendor.3b903562.js:5:656)
    at mf (vendor.3b903562.js:5:735)
CU @ vendor.3b903562.js:5

vendor.3b903562.js:5 TypeError: Cannot read properties of null (reading '0')
    at Proxy.I (index.711ccefb.entry.js:256:5247)
    at IJ.a.onCancel.t.<computed>.t.<computed> (index.711ccefb.entry.js:256:7813)
    at id (vendor.3b903562.js:5:656)
    at mf (vendor.3b903562.js:5:735)
    at hH (vendor.3b903562.js:2:21162)
    at e.cancelable.F.onClick.t.<computed>.t.<computed> (index.711ccefb.entry.js:42:39825)
    at id (vendor.3b903562.js:5:656)
    at mf (vendor.3b903562.js:5:735)
    at hH (vendor.3b903562.js:2:21162)
    at _ (index.711ccefb.entry.js:42:17694)

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Firefox (both on Mac)

### How are you deploying Directus?

Digitalocean App Platform

**Comment by azrikahar** [comment]
This conditions options bug has been fixed in #13563 recently (not released yet) 👍
