### ISSUE TITLE
Missing scope for event hook trigger crashes app

### ISSUE THREAD

**Issue by licitdev** [directus/directus#13697]
### Describe the Bug

App crashes when creating an event hook trigger without specifying the scope in Flows.

### To Reproduce

Creating with scope works but crashes if without.

https://user-images.githubusercontent.com/26413686/171841742-3195d77c-7964-4826-b1f3-6955c5dbcb91.mov

### Errors Shown

```objc++
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')
    at Object.overview (triggers.ts:36:18)
    at operation.vue:89:17
    at renderFnWithContext (runtime-core.esm-bundler.js:421:21)
    at renderSlot (runtime-core.esm-bundler.js:5850:55)
    at Proxy._sfc_render (v-workspace-tile.vue:76:4)
    at renderComponentRoot (runtime-core.esm-bundler.js:464:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4231:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at setupRenderEffect (runtime-core.esm-bundler.js:4357:9)
    at mountComponent (runtime-core.esm-bundler.js:4140:9)
```

### What version of Directus are you using?

9.12.0

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
`scope` will need to have the same if condition as the `collections` so that join() doesn't happen on undefined values.

https://github.com/directus/directus/blob/1c502bfbfd13eab6c3acc7ea4f31af932cb9c57c/app/src/modules/settings/routes/flows/triggers.ts#L34-L44

(and there's a number of join() statements in the same file that may need the same treatment)

That said, I'm also wondering should we use the approach used here instead, so that it'll render the typical `--` like render display instead of flat out hiding the whole label 🤔
