### ISSUE TITLE
KnexTimeoutError with Directus 9.12.1 on SQLite 5.0.8

### ISSUE THREAD

**Issue by Sysdraw** [directus/directus#13736]
### Describe the Bug

When we call the function `ReadOn` on my hook I have this error `KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`.

I have this error after the update of Directus, my hook is broken. 

```js
	filter('orders.items.create', async (input, { collection }, { schema }) => {
		if (collection !== 'orders') return input;
		const productService = new ItemsService('products', {
			knex,
			schema,
			accountability: {
				admin: true,
				ip: '127.0.0.1'
			},
		});
		const product = await productService.readOne(input.product);
        return input;
        })
```js

I have that on my env environnement : 
```
DB_POOL_MIN=2
DB_POOL_MAX=500
```

### To Reproduce

Create a hook who call the function ReadOne.

### Errors Shown

 KnexTimeoutError Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\knex\lib\client.js:307:26)
    at async Runner.ensureConnection (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\knex\lib\execution\runner.js:294:28)
    at async Runner.run (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\knex\lib\execution\runner.js:30:19)
    at async run (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\database\run-ast.js:37:26)
    at async runAST (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\database\run-ast.js:30:16)
    at async ItemsService.readByQuery (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\services\items.js:216:25)
    at async ItemsService.readOne (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\services\items.js:251:25)
    at async C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\extensions\hooks\stripe-hook\index.js:282:61474
    at async Emitter.emitFilter (C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\emitter.js:27:28)
    at async C:\Users\XXX\Documents\Directus tutoriel\Stripe\directus-stripe\node_modules\directus\dist\services\items.js:74:19

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

18.3.0

### What database are you using?

SQLite 5.0.8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by eikaramba** [comment]
can you try to reuse the database object ?
`new ItemsService("xxxxx",{ schema, knex: database });`

Whenever i had this error, that helped.

**Comment by Creaprog** [comment]
With a `console.log(productService);`

```
ItemsService {
  collection: 'products',
  knex: [Function: knex] {
    with: [Function (anonymous)],
    withRecursive: [Function (anonymous)],
    withMaterialized: [Function (anonymous)],
    withNotMaterialized: [Function (anonymous)],
    select: [Function (anonymous)],
    as: [Function (anonymous)],
    columns: [Function (anonymous)],
    column: [Function (anonymous)],
    from: [Function (anonymous)],
    fromJS: [Function (anonymous)],
    fromRaw: [Function (anonymous)],
    into: [Function (anonymous)],
    withSchema: [Function (anonymous)],
    table: [Function (anonymous)],
    distinct: [Function (anonymous)],
    join: [Function (anonymous)],
    joinRaw: [Function (anonymous)],
    innerJoin: [Function (anonymous)],
    leftJoin: [Function (anonymous)],
    leftOuterJoin: [Function (anonymous)],
    rightJoin: [Function (anonymous)],
    rightOuterJoin: [Function (anonymous)],
    outerJoin: [Function (anonymous)],
    fullOuterJoin: [Function (anonymous)],
    crossJoin: [Function (anonymous)],
    where: [Function (anonymous)],
    andWhere: [Function (anonymous)],
    orWhere: [Function (anonymous)],
    whereNot: [Function (anonymous)],
    orWhereNot: [Function (anonymous)],
    whereLike: [Function (anonymous)],
    andWhereLike: [Function (anonymous)],
    orWhereLike: [Function (anonymous)],
    whereILike: [Function (anonymous)],
    andWhereILike: [Function (anonymous)],
    orWhereILike: [Function (anonymous)],
    whereRaw: [Function (anonymous)],
    whereWrapped: [Function (anonymous)],
    havingWrapped: [Function (anonymous)],
    orWhereRaw: [Function (anonymous)],
    whereExists: [Function (anonymous)],
    orWhereExists: [Function (anonymous)],
    whereNotExists: [Function (anonymous)],
    orWhereNotExists: [Function (anonymous)],
    whereIn: [Function (anonymous)],
    orWhereIn: [Function (anonymous)],
    whereNotIn: [Function (anonymous)],
    orWhereNotIn: [Function (anonymous)],
    whereNull: [Function (anonymous)],
    orWhereNull: [Function (anonymous)],
    whereNotNull: [Function (anonymous)],
    orWhereNotNull: [Function (anonymous)],
    whereBetween: [Function (anonymous)],
    whereNotBetween: [Function (anonymous)],
    andWhereBetween: [Function (anonymous)],
    andWhereNotBetween: [Function (anonymous)],
    orWhereBetween: [Function (anonymous)],
    orWhereNotBetween: [Function (anonymous)],
    groupBy: [Function (anonymous)],
    groupByRaw: [Function (anonymous)],
    orderBy: [Function (anonymous)],
    orderByRaw: [Function (anonymous)],
    union: [Function (anonymous)],
    unionAll: [Function (anonymous)],
    intersect: [Function (anonymous)],
    having: [Function (anonymous)],
    havingRaw: [Function (anonymous)],
    orHaving: [Function (anonymous)],
    orHavingRaw: [Function (anonymous)],
    offset: [Function (anonymous)],
    limit: [Function (anonymous)],
    count: [Function (anonymous)],
    countDistinct: [Function (anonymous)],
    min: [Function (anonymous)],
    max: [Function (anonymous)],
    sum: [Function (anonymous)],
    sumDistinct: [Function (anonymous)],
    avg: [Function (anonymous)],
    avgDistinct: [Function (anonymous)],
    increment: [Function (anonymous)],
    decrement: [Function (anonymous)],
    first: [Function (anonymous)],
    debug: [Function (anonymous)],
    pluck: [Function (anonymous)],
    clearSelect: [Function (anonymous)],
    clearWhere: [Function (anonymous)],
    clearGroup: [Function (anonymous)],
    clearOrder: [Function (anonymous)],
    clearHaving: [Function (anonymous)],
    insert: [Function (anonymous)],
    update: [Function (anonymous)],
    returning: [Function (anonymous)],
    del: [Function (anonymous)],
    delete: [Function (anonymous)],
    truncate: [Function (anonymous)],
    transacting: [Function (anonymous)],
    connection: [Function (anonymous)],
    jsonExtract: [Function (anonymous)],
    jsonSet: [Function (anonymous)],
    jsonInsert: [Function (anonymous)],
    jsonRemove: [Function (anonymous)],
    whereJsonObject: [Function (anonymous)],
    orWhereJsonObject: [Function (anonymous)],
    andWhereJsonObject: [Function (anonymous)],
    whereNotJsonObject: [Function (anonymous)],
    orWhereNotJsonObject: [Function (anonymous)],
    andWhereNotJsonObject: [Function (anonymous)],
    whereJsonPath: [Function (anonymous)],
    orWhereJsonPath: [Function (anonymous)],
    andWhereJsonPath: [Function (anonymous)],
    whereJsonSupersetOf: [Function (anonymous)],
    orWhereJsonSupersetOf: [Function (anonymous)],
    andWhereJsonSupersetOf: [Function (anonymous)],
    whereJsonNotSupersetOf: [Function (anonymous)],
    orWhereJsonNotSupersetOf: [Function (anonymous)],
    andWhereJsonNotSupersetOf: [Function (anonymous)],
    whereJsonSubsetOf: [Function (anonymous)],
    orWhereJsonSubsetOf: [Function (anonymous)],
    andWhereJsonSubsetOf: [Function (anonymous)],
    whereJsonNotSubsetOf: [Function (anonymous)],
    orWhereJsonNotSubsetOf: [Function (anonymous)],
    andWhereJsonNotSubsetOf: [Function (anonymous)],
    context: {
      queryBuilder: [Function: queryBuilder],
      raw: [Function: raw],
      batchInsert: [Function: batchInsert],
      transaction: [Function: transaction],
      _transaction: [Function: _transaction],
      transactionProvider: [Function: transactionProvider],
      initialize: [Function: initialize],
      destroy: [Function: destroy],
      ref: [Function: ref],
      disableProcessing: [Function: disableProcessing],
      enableProcessing: [Function: enableProcessing],
      withUserParams: [Function: withUserParams],
      client: [Client_SQLite3],
      userParams: {}
    },
    _events: [Object: null prototype] {
      query: [Function (anonymous)],
      'query-response': [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    setMaxListeners: [Function: setMaxListeners],
    getMaxListeners: [Function: getMaxListeners],
    emit: [Function: emit],
    addListener: [Function: addListener],
    on: [Function: addListener],
    prependListener: [Function: prependListener],
    once: [Function: once],
    prependOnceListener: [Function: prependOnceListener],
    removeListener: [Function: removeListener],
    off: [Function: removeListener],
    removeAllListeners: [Function: removeAllListeners],
    listeners: [Function: listeners],
    rawListeners: [Function: rawListeners],
    listenerCount: [Function: listenerCount],
    eventNames: [Function: eventNames],
    _internalListeners: [ [Object], [Object], [Object], [Object] ]
  },
  accountability: { admin: true, ip: '127.0.0.1' },
  eventScope: 'items',
  schema: {
    collections: {
      directus_migrations: [Object],
      directus_folders: [Object],
      directus_relations: [Object],
      directus_revisions: [Object],
      directus_dashboards: [Object],
      directus_files: [Object],
      directus_permissions: [Object],
      directus_webhooks: [Object],
      directus_collections: [Object],
      directus_fields: [Object],
      directus_presets: [Object],
      directus_roles: [Object],
      directus_shares: [Object],
      directus_sessions: [Object],
      directus_settings: [Object],
      directus_users: [Object],
      directus_panels: [Object],
      products: [Object],
      directus_flows: [Object],
      directus_operations: [Object],
      directus_activity: [Object],
      directus_notifications: [Object],
      paids: [Object],
      orders: [Object]
    },
    relations: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object]
    ]
  },
  cache: null
}
```

I don't know If this information can to help you.

If I do that : 
```js
		const productService = new ItemsService('products', {
			knex,
			schema,
			accountability: {
				admin: true,
				ip: '127.0.0.1'
			},
		});
		new ItemsService('products', {
			knex,
			schema,
			accountability: {
				admin: true,
				ip: '127.0.0.1'
			},
		});
````

Same issue.

**Comment by Sysdraw** [comment]
With a `console.log(productService);`

```
ItemsService {
  collection: 'products',
  knex: [Function: knex] {
    with: [Function (anonymous)],
    withRecursive: [Function (anonymous)],
    withMaterialized: [Function (anonymous)],
    withNotMaterialized: [Function (anonymous)],
    select: [Function (anonymous)],
    as: [Function (anonymous)],
    columns: [Function (anonymous)],
    column: [Function (anonymous)],
    from: [Function (anonymous)],
    fromJS: [Function (anonymous)],
    fromRaw: [Function (anonymous)],
    into: [Function (anonymous)],
    withSchema: [Function (anonymous)],
    table: [Function (anonymous)],
    distinct: [Function (anonymous)],
    join: [Function (anonymous)],
    joinRaw: [Function (anonymous)],
    innerJoin: [Function (anonymous)],
    leftJoin: [Function (anonymous)],
    leftOuterJoin: [Function (anonymous)],
    rightJoin: [Function (anonymous)],
    rightOuterJoin: [Function (anonymous)],
    outerJoin: [Function (anonymous)],
    fullOuterJoin: [Function (anonymous)],
    crossJoin: [Function (anonymous)],
    where: [Function (anonymous)],
    andWhere: [Function (anonymous)],
    orWhere: [Function (anonymous)],
    whereNot: [Function (anonymous)],
    orWhereNot: [Function (anonymous)],
    whereLike: [Function (anonymous)],
    andWhereLike: [Function (anonymous)],
    orWhereLike: [Function (anonymous)],
    whereILike: [Function (anonymous)],
    andWhereILike: [Function (anonymous)],
    orWhereILike: [Function (anonymous)],
    whereRaw: [Function (anonymous)],
    whereWrapped: [Function (anonymous)],
    havingWrapped: [Function (anonymous)],
    orWhereRaw: [Function (anonymous)],
    whereExists: [Function (anonymous)],
    orWhereExists: [Function (anonymous)],
    whereNotExists: [Function (anonymous)],
    orWhereNotExists: [Function (anonymous)],
    whereIn: [Function (anonymous)],
    orWhereIn: [Function (anonymous)],
    whereNotIn: [Function (anonymous)],
    orWhereNotIn: [Function (anonymous)],
    whereNull: [Function (anonymous)],
    orWhereNull: [Function (anonymous)],
    whereNotNull: [Function (anonymous)],
    orWhereNotNull: [Function (anonymous)],
    whereBetween: [Function (anonymous)],
    whereNotBetween: [Function (anonymous)],
    andWhereBetween: [Function (anonymous)],
    andWhereNotBetween: [Function (anonymous)],
    orWhereBetween: [Function (anonymous)],
    orWhereNotBetween: [Function (anonymous)],
    groupBy: [Function (anonymous)],
    groupByRaw: [Function (anonymous)],
    orderBy: [Function (anonymous)],
    orderByRaw: [Function (anonymous)],
    union: [Function (anonymous)],
    unionAll: [Function (anonymous)],
    intersect: [Function (anonymous)],
    having: [Function (anonymous)],
    havingRaw: [Function (anonymous)],
    orHaving: [Function (anonymous)],
    orHavingRaw: [Function (anonymous)],
    offset: [Function (anonymous)],
    limit: [Function (anonymous)],
    count: [Function (anonymous)],
    countDistinct: [Function (anonymous)],
    min: [Function (anonymous)],
    max: [Function (anonymous)],
    sum: [Function (anonymous)],
    sumDistinct: [Function (anonymous)],
    avg: [Function (anonymous)],
    avgDistinct: [Function (anonymous)],
    increment: [Function (anonymous)],
    decrement: [Function (anonymous)],
    first: [Function (anonymous)],
    debug: [Function (anonymous)],
    pluck: [Function (anonymous)],
    clearSelect: [Function (anonymous)],
    clearWhere: [Function (anonymous)],
    clearGroup: [Function (anonymous)],
    clearOrder: [Function (anonymous)],
    clearHaving: [Function (anonymous)],
    insert: [Function (anonymous)],
    update: [Function (anonymous)],
    returning: [Function (anonymous)],
    del: [Function (anonymous)],
    delete: [Function (anonymous)],
    truncate: [Function (anonymous)],
    transacting: [Function (anonymous)],
    connection: [Function (anonymous)],
    jsonExtract: [Function (anonymous)],
    jsonSet: [Function (anonymous)],
    jsonInsert: [Function (anonymous)],
    jsonRemove: [Function (anonymous)],
    whereJsonObject: [Function (anonymous)],
    orWhereJsonObject: [Function (anonymous)],
    andWhereJsonObject: [Function (anonymous)],
    whereNotJsonObject: [Function (anonymous)],
    orWhereNotJsonObject: [Function (anonymous)],
    andWhereNotJsonObject: [Function (anonymous)],
    whereJsonPath: [Function (anonymous)],
    orWhereJsonPath: [Function (anonymous)],
    andWhereJsonPath: [Function (anonymous)],
    whereJsonSupersetOf: [Function (anonymous)],
    orWhereJsonSupersetOf: [Function (anonymous)],
    andWhereJsonSupersetOf: [Function (anonymous)],
    whereJsonNotSupersetOf: [Function (anonymous)],
    orWhereJsonNotSupersetOf: [Function (anonymous)],
    andWhereJsonNotSupersetOf: [Function (anonymous)],
    whereJsonSubsetOf: [Function (anonymous)],
    orWhereJsonSubsetOf: [Function (anonymous)],
    andWhereJsonSubsetOf: [Function (anonymous)],
    whereJsonNotSubsetOf: [Function (anonymous)],
    orWhereJsonNotSubsetOf: [Function (anonymous)],
    andWhereJsonNotSubsetOf: [Function (anonymous)],
    context: {
      queryBuilder: [Function: queryBuilder],
      raw: [Function: raw],
      batchInsert: [Function: batchInsert],
      transaction: [Function: transaction],
      _transaction: [Function: _transaction],
      transactionProvider: [Function: transactionProvider],
      initialize: [Function: initialize],
      destroy: [Function: destroy],
      ref: [Function: ref],
      disableProcessing: [Function: disableProcessing],
      enableProcessing: [Function: enableProcessing],
      withUserParams: [Function: withUserParams],
      client: [Client_SQLite3],
      userParams: {}
    },
    _events: [Object: null prototype] {
      query: [Function (anonymous)],
      'query-response': [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    setMaxListeners: [Function: setMaxListeners],
    getMaxListeners: [Function: getMaxListeners],
    emit: [Function: emit],
    addListener: [Function: addListener],
    on: [Function: addListener],
    prependListener: [Function: prependListener],
    once: [Function: once],
    prependOnceListener: [Function: prependOnceListener],
    removeListener: [Function: removeListener],
    off: [Function: removeListener],
    removeAllListeners: [Function: removeAllListeners],
    listeners: [Function: listeners],
    rawListeners: [Function: rawListeners],
    listenerCount: [Function: listenerCount],
    eventNames: [Function: eventNames],
    _internalListeners: [ [Object], [Object], [Object], [Object] ]
  },
  accountability: { admin: true, ip: '127.0.0.1' },
  eventScope: 'items',
  schema: {
    collections: {
      directus_migrations: [Object],
      directus_folders: [Object],
      directus_relations: [Object],
      directus_revisions: [Object],
      directus_dashboards: [Object],
      directus_files: [Object],
      directus_permissions: [Object],
      directus_webhooks: [Object],
      directus_collections: [Object],
      directus_fields: [Object],
      directus_presets: [Object],
      directus_roles: [Object],
      directus_shares: [Object],
      directus_sessions: [Object],
      directus_settings: [Object],
      directus_users: [Object],
      directus_panels: [Object],
      products: [Object],
      directus_flows: [Object],
      directus_operations: [Object],
      directus_activity: [Object],
      directus_notifications: [Object],
      paids: [Object],
      orders: [Object]
    },
    relations: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object]
    ]
  },
  cache: null
}
```

I don't know If this information can to help you.

If I do that : 
```js
		const productService = new ItemsService('products', {
			knex,
			schema,
			accountability: {
				admin: true,
				ip: '127.0.0.1'
			},
		});
		new ItemsService('products', {
			knex,
			schema,
			accountability: {
				admin: true,
				ip: '127.0.0.1'
			},
		});
````

Same issue.

**Comment by eikaramba** [comment]
where is your knex variable defined. normally it has to be `knex: database` i think. see my code above.
