### ISSUE TITLE
DataFlows: Webhook/Request url always fail

### ISSUE THREAD

**Issue by mslonina** [directus/directus#13737]
### Describe the Bug

I'm trying to setup a simple flow passing data to the Directus instance itself via Webhook/Request URL operation. This however always results in a failure with empty result.

### To Reproduce

1. Create a model `test` with a `name`, `email` (string) fields
2. Create a flow, reacting on `test` item create
3. Add Webhook/Request URL with POST to i.e. http://localhost:8055/users - to create a sample user (using for example json from docs); I'm setting also Authorization Bearer [token generated on the admin user profile]. What I also tried here is to pass `{{$last}}` property (having seen what it contains, i.e. `{ "email": "{{$last.payload.email}}"}`, but it didn't worked either), also using modify json payload before passing it into the webhook operation
4. Add `Log to console` for both success and failure
5. Add new item in `test` model - the flow triggers, but the failure message from (4) appears, no user gets created

It looks like Webhook passes authorization (I've tried also without setting headers, and received 403 properly), but no user is created (and it does work via postman).

### Errors Shown

None

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

Docker

### What database are you using?

Docker

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Seems like the underlying issue is (somehow) the `Webhook/Request URL` operation is not actually working/firing once we add header(s) to it.

**Comment by mslonina** [comment]
I confirm, in 9.12.2 it works, thanks!

**Comment by cesarsalesgomes** [comment]
Not sure if it's related or if i should open another issue, but instead of invoking a localhost call to Directus (Port 8055) triggered by a flow, when invoking a localhost call to another port (e.g. another NodeJS server on Port 3000), axios seems to return connect ECONNREFUSED error.

![image](https://user-images.githubusercontent.com/6998275/177062022-6f294095-481c-474d-a043-c1fd8a0b010c.png)

**Comment by azrikahar** [comment]
@cesarsalesgomes assuming the "another NodeJS server on port 3000" is another docker container (as you mentioned you are using docker), I believe you will need to make sure they are on the same docker network and call `your-another-node-container-name:3000` instead of localhost. localhost in the Directus container or any other Docker containers is different from the localhost on the host machine 👍

**Comment by cesarsalesgomes** [comment]
@azrikahar well remembered! Working properly now, thanks!

**Comment by VISHNU-P-M** [comment]
Hi, 
I tried to implement a webhook for a collection creation
and I've added the URL as http://127.0.0.1:8000/api/my-request-handle-url
and set the authorization

but while trying to create the collection, I got an error 

`err: {
      "type": "Error",
      "message": "Requested URL \"http://127.0.0.1:8000/api/<...>\" resolves to a denied IP address",
      "stack":
          Error: Requested URL "http://127.0.0.1:8000/api/<...>" resolves to a denied IP address
              at validateIP (/home/vishnu/Projects/Directus/ProjectTracker/node_modules/directus/dist/request/validate-ip.js:21:27)
              at requestInterceptor (/home/vishnu/Projects/Directus/ProjectTracker/node_modules/directus/dist/request/request-interceptor.js:30:40)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async EventEmitter.<anonymous> (/home/vishnu/Projects/Directus/ProjectTracker/node_modules/directus/dist/webhooks.js:70:13)
              at async Promise.all (index 0)
    }`

**Comment by VISHNU-P-M** [comment]
Thanks, it worked

for reference 
I configured it like this

`IMPORT_IP_DENY_LIST=`

**Comment by agoyal118** [comment]
Hey, I'm having a similar issue as Vishnu. 

I am trying to create a blog with NextJS 13 and Directus. I want to blog to have on-demand ISR revalidation and hence I am using Directus Flow. I made the website using Nextjs 13 and am hosting it on Vercel. I am hosting Directus, PostgreSQL, and Redis Cache on a Digital Ocean Droplet using Docker (Docker Compose). The Directus Flow triggers but I get an error message saying that the Requested URL resolves to a denied IP Address (screenshot attached).

I've seen a lot of the previous posts regarding this saying to change the IMPORT_IP_DENY_LIST. I tried adding IMPORT_IP_DENY_LIST: "" to my Docker compose file but that didn't work. Although I don't think this makes a difference, I tried adding IMPORT_IP_DENY_LIST="" to my environment variables  in Vercel. However, I am still getting the error message. 

I am using Nginx as a reverse proxy so that my subdomain points to the Directus IP address and port instead of the Digital Ocean IP address (screenshot attached of Nginx file). 

Please see screenshots attached of the error message, my docker compose file, my Nginx reverse proxy file, and my environment variable. Any help would be greatly appreciated.

![resolves to denied ip address](https://github.com/directus/directus/assets/24549854/3db3ae3c-815d-402e-bf48-1ab8ada8b30a)
![docker compose file](https://github.com/directus/directus/assets/24549854/c42cb1e0-b1e6-4cd2-adea-d4f3d29e4ab7)
![vercel environment variable](https://github.com/directus/directus/assets/24549854/7ee6ddc3-1626-4b41-9b20-70e8515550c3)
![nginx reverse proxy](https://github.com/directus/directus/assets/24549854/ade14d92-108c-439f-bf17-81f395d4107e)

**Comment by clayboc** [comment]
Going to add this here because it might save someone some time. 
The above IMPORT_IP_DENY_LIST=   worked for me for the first part of my issue, a webhook that was returning a denied IP error.  After that was resolved, I was getting an axios 403 error. I have a corporate proxy in play but all the usual fixes were not helping. Adding no_proxy="*.localhost,localhost,127.0.0.1" to the directus .env solved it.
