### ISSUE TITLE
Error logged when filtering timestamp field as null in the App on SQLite

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#13884]
### Describe the Bug

When first filtering a timestamp field, there are no error on the App side and nothing will break, but just that an error will be logged in the console in API side (refer Errors Shown).

Seems to be due to #13410 added a length check at:

 
 
 https://github.com/directus/directus/blob/583a555b0b291d830a2d6349fc51aa5f5e831225/api/src/database/helpers/date/dialects/sqlite.ts#L6

   hence the error thrown.

   But note that it is _not_ the PR causing the error, but more so surfacing this `null` value not being handled even before the PR. 
   
   It used to be `const newDate = new Date(date);` which will do `new Date(null)` which is still valid and becomes `1 January 1970 UTC`.

### To Reproduce

Note: SQLite only

1. Create a collection with a timestamp field
2. Create a few records
3. Try to filter the timestamp field. Initially it'll be `contains` with null value, and technically expected as the user has yet to enter the filter value.
 

### Errors Shown

```
19:32:06 🚨 Cannot read properties of null (reading 'length')
TypeError: Cannot read properties of null (reading 'length')
    at DateHelperSQLite.parse (C:\Users\Azri\Documents\Projects\directus\api\src\database\helpers\date\dialects\sqlite.ts:6:12)
    at applyFilterToQuery (C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-query.ts:460:35)
    at addWhereClauses (C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-query.ts:368:6)
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-query.ts:336:7
    at Array.forEach (<anonymous>)
    at QueryBuilder_SQLite3.<anonymous> (C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-query.ts:335:12)
    at compileCallback (C:\Users\Azri\Documents\Projects\directus\node_modules\knex\lib\formatter\formatterUtils.js:7:12)
    at rawOrFn (C:\Users\Azri\Documents\Projects\directus\node_modules\knex\lib\formatter\wrappingFormatter.js:225:7)
    at QueryCompiler_SQLite3.whereWrapped (C:\Users\Azri\Documents\Projects\directus\node_modules\knex\lib\query\querycompiler.js:1084:17)
    at QueryCompiler_SQLite3.where (C:\Users\Azri\Documents\Projects\directus\node_modules\knex\lib\query\querycompiler.js:573:34)
```

### What version of Directus are you using?

9.12.2 (Main branch 583a555b0b)

### What version of Node.js are you using?

16.15.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
@licitdev Defaulting to jan 1 1970 for `null` dates doesn't feel like expected behavior to me, no 🤔

**Comment by licitdev** [comment]
Other vendors directly receive the "null" value and processes it... 🤔
If we pass in other invalid DateTime values for other vendors, they do throw Error 500s too. 

Should this issue be tagged as App instead? Updating it to behave similar to UUID fields where invalid values aren't be propagated.

**Comment by rijkvanzanten** [comment]
I'm confused. Is the problem here that we're trying to save `null` to sqlite and it crashes?

**Comment by licitdev** [comment]
When a user selects a field to filter, the `compareValue` is empty, which defaults as `null`.

![image](https://user-images.githubusercontent.com/26413686/173597656-85c21d26-4ca4-405a-844f-5fbb9d26cd0a.png)

Once the filter is selected, a request is immediately sent to server to fetch the filtered result with `{ timestamp: { _contains: null } }`, which results in an error 500.
 
I have pushed a PR which prevents the error 500.

As shown below, when passed with invalid values in Postgres, there will still be error 500s.

![image](https://user-images.githubusercontent.com/26413686/173601186-c137bd23-5c03-42a4-9c78-867f131cf8fe.png)

I wonder if we could add a validation UI where one could easily identify if a filter node is invalid. Currently if you were to key an invalid UUID, the field doesn't expand. It only expands when there is a valid UUID. The request is sent to server with the updated filter only when the UUID is valid. I wonder if there should be validation done on the app, alongside some indicator if the current filter node is invalid. 

https://user-images.githubusercontent.com/26413686/173602302-747122ab-b116-4e64-9a89-057d0315580f.mov

The improvement should be in a separate issue / PR. @rijkvanzanten Sorry for the confusion, I was thinking of validating the date filters within the app in the same PR. 😂
