### ISSUE TITLE
Error syncing schemas with nested collection

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#13894]
### Describe the Bug

There's a logic error in apply-snapshot.js :

`snapshotDiff.collections.filter(
				({ diff }) => diff[0].kind === 'N' && (diff[0] as DiffNew<Collection>).rhs.meta?.group === null
)`

This line filters collections to only get the top level, no group collections, and then recursively creates nested collections.

The error occurs when you have a remote schema that you're applying locally where a new remote collection is nested in a group.

Remote, the new collection is Patient Reported Outcome Measures in the Client group
<img width="1440" alt="Screen Shot 2022-06-14 at 6 47 37 PM" src="https://user-images.githubusercontent.com/695284/173707560-0598b787-4a60-4fc0-aba9-e38a41f4dec6.png">

Local, Client is a collection, not a group:
<img width="1440" alt="Screen Shot 2022-06-14 at 6 48 36 PM" src="https://user-images.githubusercontent.com/695284/173707684-0ae4461f-1b82-4630-9820-d48da13e2577.png">

Schema diff picks up the new collection, but when applying it, the collection is never created and an error is generated because of the missing collection while trying to create the fields:

<img width="1440" alt="Screen Shot 2022-06-14 at 6 50 12 PM" src="https://user-images.githubusercontent.com/695284/173707877-d70b7670-cd69-4ef9-a30e-0c3821d2c9b8.png">

### To Reproduce

Create a collection group with some nested collections.

Create another instance of directus with a collection with the same name as the collection group.

Attempt to sync the first schema to the second.

### Errors Shown

18:25:50 🚨 Failed to create field "hh_patient_reported_measures.date_created"
18:25:50 🚨 Cannot read properties of undefined (reading 'fields') 
TypeError: Cannot read properties of undefined (reading 'fields')
    at FieldsService.createField (/Users/claytongulick/source/telos/home-health/node_modules/directus/dist/services/fields.js:216:79)
    at /Users/claytongulick/source/telos/home-health/node_modules/directus/dist/utils/apply-snapshot.js:107:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What version of Directus are you using?

9.12

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chome

### How are you deploying Directus?

locally

**Comment by claytongulick** [comment]
It's kind of hard to describe the cause of the error, happy to help dig in. I'm stepping through the code in the debugger and can see the problem. In createCollections the filter that's applied is filtering out the new collection under the group, because the group isn't new, and the recursion never kicks off.
