### ISSUE TITLE
RangeError: Invalid time value on alias field

### ISSUE THREAD

**Issue by mslonina** [directus/directus#13994]
### Describe the Bug

I have a `iot_sensor` model and `iot_sensor_telemetry`:

- `iot_sensor` having i.e. id, name
- `iot_sensor_telemetry` having reference to sensor_id, and fields: status, timestamp (timestamp-type field), date_created

The `iot_sensor_telemetry` is shown properly as alias `telemetry` in the `iot_sensor` model.

When I query through the `iot_sensor_telemetry` all the fields are shown properly (filters work as well). But, if I query `iot_sensor` (wanted to show all my sensors in one place):

- when specifying `fields=*` - it works
- when specifying `fields=id,name,telemetry` - it works (showing empty telemetry table if there is no data)
- when specifying `fields=id,name,telemetry.status,telemetry.timestamp` or `fields=id,name,telemetry.*` I get:

```
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:238:86)
    at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:143:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/directus/node_modules/directus/dist/database/run-ast.js:42:21)
    at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
    at async run (/directus/node_modules/directus/dist/database/run-ast.js:56:36)
    at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
    at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:216:25)
    at async /directus/node_modules/directus/dist/controllers/items.js:70:18
```

- when specifying `fields=id,name,telemetry.status,telemetry.timestamp` and filtering by a sensor having telemetry data - it works
- when specifying `fields=id,name,telemetry.status,telemetry.date_created` - it works

### To Reproduce

As above

### Errors Shown

As above

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

Docker

### What database are you using?

Postgres 13

### What browser are you using?

Postman

### How are you deploying Directus?

Docker

**Comment by mslonina** [comment]
Both timestamp and date_created are provided as ISO8601, UTC, i.e. `2022-06-20T12:34:33.279Z`.

**Comment by mslonina** [comment]
Apparently it was caused by a bad value in the database.
