### ISSUE TITLE
"Users" custom field validation rules are not blocking

### ISSUE THREAD

**Issue by shipsides-sparknel** [directus/directus#14296]
### Describe the Bug

I have a role that is allowed to create users under the following field validation conditions in the roles section:
![image](https://user-images.githubusercontent.com/106218118/177483192-ad18c627-69b2-4fb6-bf5b-655958e4673f.png)

When that role creates a user, the validation appears to check as evidenced by the error, but the actual item proceeds to create itself (see 5 down the bottom right)
![image](https://user-images.githubusercontent.com/106218118/177483390-e160bc27-9206-4fac-8826-167ad48ad039.png)

And this is verified in the users section
![image](https://user-images.githubusercontent.com/106218118/177483516-16d7b4e4-d974-41ae-bf86-8ea7af996d0b.png)

### To Reproduce

1. Create a rule under Roles -> Directus Users -> Create -> Field Validation
2. Create a new user under that role
3. Observe the error and creation

### Errors Shown

The blocking error appears on the page
{
  "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at Hl (https://sparknel-dc.directus.app/admin/assets/index.133de9ba.entry.js:1:111578)\n    at Y (https://sparknel-dc.directus.app/admin/assets/index.133de9ba.entry.js:31:187396)\n    at k (https://sparknel-dc.directus.app/admin/assets/index.133de9ba.entry.js:31:184187)\n    at async jt (https://sparknel-dc.directus.app/admin/assets/index.133de9ba.entry.js:101:295667)",
  "message": "Cannot convert undefined or null to object"
}

But in reality, the error doesn't block

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard cloud

**Comment by shipsides-sparknel** [comment]
> @shipsides-sparknel Could you do me a favor, and copy the output of `Copy Raw Value` in that filter rules configuration UI? (You should be able to click the name "Rule" to see that menu). Thanks!

{
	"_and": [
		{
			"_or": [
				{
					"_and": [
						{
							"Linked_Partner": {
								"_nnull": true
							}
						},
						{
							"role": {
								"name": {
									"_eq": "Subcontractor"
								}
							}
						},
						{
							"Linked_Subcontractor": {
								"_nnull": true
							}
						}
					]
				},
				{
					"_and": [
						{
							"Linked_Partner": {
								"_nnull": true
							}
						},
						{
							"role": {
								"name": {
									"_eq": "Partner"
								}
							}
						}
					]
				}
			]
		},
		{
			"email": {
				"_nnull": true
			}
		},
		{
			"first_name": {
				"_nnull": true
			}
		},
		{
			"last_name": {
				"_nnull": true
			}
		}
	]
}

I did a little more testing on each combination and found:

- Any combination of first name, last name and/or email is filled out, Linked Partner and Role are not: the error appears, but the entry creates
- Only the Linked Partner is populated: the entry creates with no error
- Any time the role is populated: the entry is blocked and a validation error displays:
        _The following fields have invalid values:
        
        Role: validationError.undefined
        Role: validationError.undefined_

I tried switching Role Name to the Role ID, but the same thing happened.

I simplified the rule to something that doesn't use the custom fields:
{
	"_and": [
		{
			"email": {
				"_nnull": true
			}
		},
		{
			"first_name": {
				"_nnull": true
			}
		},
		{
			"last_name": {
				"_nnull": true
			}
		}
	]
}

And the same behaviour was observed as the first test - the error appears but the entry is not blocked. So it appears the problem isn't anything to do with the "Role" or my custom field (which is a M2O relationship)

I tried this as well to no effect:
{
	"_and": [
		{
			"email": {
				"_regex": ".*"
			}
		},
		{
			"first_name": {
				"_regex": ".*"
			}
		},
		{
			"last_name": {
				"_regex": ".*"
			}
		}
	]
}

**Comment by azrikahar** [comment]
Tested in latest version 9.15.1 and there doesn't seem to be the `Cannot convert undefined or null to object` error anymore, but user creation is still not being blocked by the validations.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-236](https://linear.app/directus/issue/ENG-236/users-custom-field-validation-rules-are-not-blocking)

**Comment by fatihsolhan** [comment]
Hi, any update on this?

**Comment by ComfortablyCoding** [comment]
I am not able to reproduce this issue on the latest version with the current information, so I'm going to close it for now. That said, I'm happy to continue the conversation here and will reopen the issue once a reproducible case is found

#### Issue Reproduction Attempt

https://github.com/user-attachments/assets/1c88a2b7-06a1-4ee2-9761-a517942ba14c
