### ISSUE TITLE
npx directusctl/ npx @directus/cli doesn't work

### ISSUE THREAD

**Issue by piotr-cz** [directus/directus#14450]
### Describe the Bug

CLI Client doesn't work

### To Reproduce

```command
npx directusctl
```
or
```command
npx @directus/cli
```

See docs > CLI > [Client](https://docs.directus.io/reference/cli/#client)

### Errors Shown

for `npx directusctl` console shows
```
Not Found - GET https://registry.npmjs.org/directusctl - Not found

  'directusctl@latest' is not in this registry.

Note that you can also install from a
404 tarball, folder, http url, or git url.
```
for `npx @directus/cli` console shows
```
declare const _default: import("../..").Command<import("../..").Toolbox<import("@directus/sdk").TypeMap>, unknown, void>;
        ^^^^^

SyntaxError: Unexpected token 'const'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (C:\Users\xxx\AppData\Local\npm-cache\_npx\34e488e770b21435\node_modules\gluegun\build\loaders\module-loader.js:15:12)
    at loadCommandFromFile (C:\Users\xxx\AppData\Local\npm-cache\_npx\34e488e770b21435\node_modules\gluegun\build\loaders\command-loader.js:41:56)
```

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.16

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
`npx directusctl` assumes `@directus/cli` is installed globally or in the project dependencies as the docs desribed, so the "Not Found" error is expected.

As for the `Unexpected token 'const'`, can confirm this does happen with the latest version.

---

Note: I believe this issue should be moved to https://github.com/directus/cli, but I believe I don't have the perms for that repo.
