### ISSUE TITLE
Google Cloud Storage - Unknown errors

### ISSUE THREAD

**Issue by espired** [directus/directus#14614]
### Describe the Bug

Cant figure how to connect to GCS through the Docs (Not informative enough)

### To Reproduce

config.js
`   STORAGE_LOCATIONS: "gcs",
    STORAGE_GCS_DRIVER: "gcs",
    STORAGE_GCS_KEY_FILENAME: "./key.json",
    STORAGE_GCS_BUCKET: "https://storage.googleapis.com/cdn.***.com/***/uploads",`

package.json:
`"@directus/drive-gcs": "^9.14.1",`

### Errors Shown

On upload:
`06:34:20 🚨 storage:gcs:responseTime in ERROR state 
FileNotFound: E_FILE_NOT_FOUND: The file health--NI4C doesn't exist
Not Found
    at handleError (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:18:20)
    at GoogleCloudStorage.put (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:195:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async testStorage (/usr/src/app/node_modules/directus/dist/services/server.js:261:21)
    at async Promise.all (index 3)
    at async ServerService.health (/usr/src/app/node_modules/directus/dist/services/server.js:107:45)
    at async /usr/src/app/node_modules/directus/dist/controllers/server.js:54:18
`

On GET:
`Error code: ERR_INVALID_ARG_TYPE
Original stack:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at GoogleCloudStorage._fullPath (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:42:61)
    at GoogleCloudStorage._file (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:45:39)
    at GoogleCloudStorage.exists (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:88:39)
    at AssetsService.getAsset (/usr/src/app/node_modules/directus/dist/services/assets.js:73:71)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/node_modules/directus/dist/controllers/assets.js:122:36
    at handleError (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:22:20)
    at GoogleCloudStorage.exists (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:92:19)
    at AssetsService.getAsset (/usr/src/app/node_modules/directus/dist/services/assets.js:73:71)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/node_modules/directus/dist/controllers/assets.js:122:36
06:34:44 ✨ request errored GET 500 /assets/0a0c5019-90fb-4d35-b678-fe3d287ba27b?download=true&key=system-medium-cover&modified=2022-07-20T15:19:08.756Z 25ms`

On Delete:
`06:35:17 🚨 E_FILE_NOT_FOUND: The file 3a0c7484-4a0d-4413-8081-b88a88d6502d doesn't exist
Not Found 
FileNotFound: E_FILE_NOT_FOUND: The file 3a0c7484-4a0d-4413-8081-b88a88d6502d doesn't exist
Not Found
    at handleError (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:18:20)
    at GoogleCloudStorage.flatList (/usr/src/app/node_modules/@directus/drive-gcs/dist/GoogleCloudStorage.js:220:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FilesService.deleteMany (/usr/src/app/node_modules/directus/dist/services/files.js:272:37)
    at async /usr/src/app/node_modules/directus/dist/controllers/files.js:252:9`

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

CRDB:21.2.9

### What browser are you using?

Chrome

### How are you deploying Directus?

Kubernetes

**Comment by azrikahar** [comment]
Hi, understandably you have closed this issue, but would you mind sharing what was the fix? Would be helpful if we can see how to improve the docs in this regard 👍

Perhaps a storage examples section like https://docs.directus.io/self-hosted/sso-examples/#sso-examples may help?

**Comment by espired** [comment]
Sure! sorry for that.
So, the docs are missing some concrete storage configuration examples, for example:
- `STORAGE_GCS_ROOT` was actually needed even though not mentioned on the GCS section.
- `STORAGE_GCS_BUCKET` doesnt need to include the whole bucket url, just the relative part

**Comment by azrikahar** [comment]
Thank you! @erondpowell let's track this to update it in the docs repo.
