### ISSUE TITLE
macOS 13 - Undefined

### ISSUE THREAD

**Issue by balabellam** [directus/directus#14830]
### Describe the Bug

macOS 13 is not part of the os nameMAP causing issues while signing in.

11:00:22 🚨 undefined is not iterable (cannot read property Symbol(Symbol.iterator)) 
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

    at macosRelease (/node_modules/macos-release/index.js:27:26)
    at ServerService.serverInfo (/node_modules/directus/dist/services/server.js:83:83)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /node_modules/directus/dist/controllers/server.js:45:18

11:00:22 ✨ request errored GET 500 /server/info?limit=-1 19ms

### To Reproduce

Install & Run Directus on macOS 13 beta.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 14

### What browser are you using?

Safari

### How are you deploying Directus?

locally

**Comment by balabellam** [comment]
Just added one entry for macOS 13 and everything works perfectly.

Location: /node_modules/macos-release/index.js
const nameMap = new Map([
	**_[22, ['Ventura', '13']],_**
	[21, ['Monterey', '12']],
	[20, ['Big Sur', '11']],
	[19, ['Catalina', '10.15']],
	[18, ['Mojave', '10.14']],
	[17, ['High Sierra', '10.13']],
	[16, ['Sierra', '10.12']],
	[15, ['El Capitan', '10.11']],
	[14, ['Yosemite', '10.10']],
	[13, ['Mavericks', '10.9']],
	[12, ['Mountain Lion', '10.8']],
	[11, ['Lion', '10.7']],
	[10, ['Snow Leopard', '10.6']],
	[9, ['Leopard', '10.5']],
	[8, ['Tiger', '10.4']],
	[7, ['Panther', '10.3']],
	[6, ['Jaguar', '10.2']],
	[5, ['Puma', '10.1']]
]);

**Comment by genu** [comment]
Look like macos-release version needs to be bumped to latest from upstream

**Comment by rijkvanzanten** [comment]
> Look like macos-release version needs to be bumped to latest from upstream

Easier said than done. `macos-release` (just like many of Sindre's other packages) is now ESM only, so we can't use it anymore :C

**Comment by genu** [comment]
That's true.

It looks like `macosRelease` is used in a single place. I knowing the exact OS version of macos add that much value? 🤔  Maybe just remove it altogether and remove that dependency?

Also, the whole `macos-release` dependency is like 33 lines in total. Why not just add an internal directus utility that does the same thing and still deperecate the `macos-release` dependency?
