### ISSUE TITLE
ERR_HTTP_HEADERS_SENT : Cannot remove headers after they are sent to the client

### ISSUE THREAD

**Issue by leosin** [directus/directus#14888]
### Describe the Bug

When editing articles or other operations in the background, the node service is automatically closed

```bash
node:_http_outgoing:654
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.removeHeader (node:_http_outgoing:654:11)
    at ServerResponse.send (/Users/michael/Projects/YARN/node_modules/express/lib/response.js:214:10)
    at ReadStream.<anonymous> (/Users/michael/Projects/YARN/node_modules/directus/dist/controllers/assets.js:153:25)
    at ReadStream.emit (node:events:520:28)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### To Reproduce

1. Freshly installed version 9.15.0
2. yarn start

### What version of Directus are you using?

9.15.0

### What version of Node.js are you using?

v16.14.0

### What database are you using?

MariaDB 10

### What browser are you using?

edge 103

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
What do you mean by _When editing articles or other operations in the background_ ?

**Comment by leosin** [comment]
That's what I'm configuring in the background,
eg: add data model or something else


but Just now I upgrade to 9.15.1, The problem is gone
Maybe it's my problem 😬

**Comment by rijkvanzanten** [comment]
Not sure! Lemme know if/when it happens again though 🙂

**Comment by piotr-cz** [comment]
This error started to pop up after I've upgraded from v9.14.5 to v9.15.1.
Occurs when using just API endpoints.

From the stack trace it looks like the response is send 2x

**Comment by rijkvanzanten** [comment]
@piotr-cz Any specific API endpoints?

**Comment by piotr-cz** [comment]
I'm not sure, I can just say it happens on `/items/<collection_name>` but not on `/fields/<collection_name>` on localhost (I didn't check on live server).

It showed up few times after I've updated directus, now more occasionally.

**Comment by rijkvanzanten** [comment]
@piotr-cz Did you use the `/assets` endpoint at all in that use?

**Comment by piotr-cz** [comment]
Yes, I do

**Comment by rijkvanzanten** [comment]
I _think_ it's this stream handling that might set headers after the response is already returned: 

https://github.com/directus/directus/blob/3e8d965642c0f9d360dc57f8a2a5390eef6cdb06/api/src/controllers/assets.ts#L190-L217

Could be the HEAD request 🤔

**Comment by piotr-cz** [comment]
Could be.
I'll try to see when exactly error happens when using the API.

**Comment by MarijnSt** [comment]
I'm encountering this issue as well. It's pretty random when it happens, not sure what the cause is...
If it happens it's always on /items/... requests and it does indeed always point to the node_modules/directus/dist/controllers/assets.js file

I also started having these issues once I upgraded from 9.12.2 to 9.15.1

**Comment by azrikahar** [comment]
Just want to chime in and say I did face this maybe 2-3 times to date, when viewing the files module page. However it'll resolve itself upon restarting the server and repeating the exact same steps, even after clearing browser cache etc.

Unfortunately I'm not able to find a reliable reproduction steps at the moment as well, but it's definitely something that's present.

**Comment by rijkvanzanten** [comment]
>  it has happened to me when I try to create a collection, or new fields in old collections, when I consume content from collections, even leaving the website still for a long time. Super random

I think the common thread here is still the /assets endpoint. Even in browsing the app, the /assets endpoint is used all over the place for thumbnails/image previews/avatar in the bottom left/project logo in the top left, etc. That combined with the fact that the error trace always points to `node_modules/directus/dist/controllers/assets.js` makes me pretty convinced the shared snippet above is the culprit. That doesn't however explain _why_ and _when_ it triggers those headers wrong.

**Comment by piotr-cz** [comment]
I can't see any pattern when error occurs.
Might be indeed somehow related to assets endpoint as is we use along other ones.

**Comment by TyrionFront** [comment]
Hi everybody.
Join the club: after "Directus" was updated to v9.15.1. I've got the same error 3 time in a row within 2 mins. At first glance from server logs it seems like those errors occured during recieving images data and every time after the error has been thrown the server was restarting itself (1st 5 screens - Sentry, last one - server logs).

<img width="263" alt="Screenshot 2022-08-10 at 11 21 46" src="https://user-images.githubusercontent.com/18406903/183854085-ae1f0ff3-37e6-413c-acdf-73a43b980012.png">
<img width="1088" alt="Screenshot 2022-08-10 at 11 22 01" src="https://user-images.githubusercontent.com/18406903/183854091-15dd4018-23ce-4c54-bb86-257436ec9c53.png">
<img width="851" alt="Screenshot 2022-08-10 at 11 22 29" src="https://user-images.githubusercontent.com/18406903/183854098-47aac43f-a9df-433d-978f-8df497c1b4d9.png">
<img width="858" alt="Screenshot 2022-08-10 at 11 22 46" src="https://user-images.githubusercontent.com/18406903/183854101-a20459a7-50f0-48da-a8b7-81f89264e161.png">
<img width="879" alt="Screenshot 2022-08-10 at 11 22 59" src="https://user-images.githubusercontent.com/18406903/183854104-c876d03d-2fcc-44f8-92bc-0a9fbb5a2b6a.png">
<img width="1438" alt="Screenshot 2022-08-09 at 17 12 47" src="https://user-images.githubusercontent.com/18406903/183854145-68852d03-afbd-4975-8fdd-61d2703129e3.png">

**Comment by melrefaie** [comment]
> Hello, I have the same error, the server stops when the same error occurs, in the console I can see the same error described by @leosin, I have been working these 3 days with the error occurring constantly, it has happened to me when I try to create a collection, or new fields in old collections, when I consume content from collections, even leaving the website still for a long time. Super random, I haven't been able to find a case where I can reproduce it. It started to happen when I updated v9.14.5 to v9.15.1.

It happens alot same issue

**Comment by leosin** [comment]
Today I deleted the logo, background and other pictures in the backend settings, and then used it for about 1 hour, no problem, haha

**Comment by melrefaie** [comment]
> 

@leosin  Same i deleted them. no issues for now

**Comment by melrefaie** [comment]
@rijkvanzanten 
Server crash while working with any asset. 
when new version update?

**Comment by vatologic** [comment]
Exactly the same error, fresh install, Node v16.16.0. As soon as I add either a background (JPEG 50Kb) and/or  logo (SVG  1Kb).

**Comment by xxmichas** [comment]
This seems to be a working temporary fix (you can test it with console.log).

Just paste the below code to \api\src\controllers\assets.ts:192

```
stream.on('end', () => {
  if (!res.headersSent) {
    res.status(200).send();
  }
});

**Comment by alsherif-khalaf** [comment]
It gives me the same error on Ubuntu Server , I Just removed the svg icon from sittings

**Comment by alsherif-khalaf** [comment]
It still crashes every time I add items
```

 - Table "directus_permissions": "utf8mb4_general_ci"                        │ 
│                                        ││ Directus >           - Column "permissions": "utf8mb4_bin"     
```

**Comment by melrefaie** [comment]
@rijkvanzanten  @benhaynes 

can you release new version?

**Comment by rijkvanzanten** [comment]
@melrefaie As I mentioned on the linked PR, new releases are scheduled on a bi-monthly cycle, which happens to be this Thursday 👍🏻

**Comment by melrefaie** [comment]
> @melrefaie As I mentioned on the linked PR, new releases are scheduled on a bi-monthly cycle, which happens to be this Thursday 👍🏻

ok thnx 👍🏻
