### ISSUE TITLE
Error applying snapshot with deleted collections containing translations

### ISSUE THREAD

**Issue by benosman** [directus/directus#15059]
### Describe the Bug

I get an error when trying to apply a snapshot that will delete collections containing translation fields.

It is because the schema apply command tries to delete the parent collection first, but the translation collection depends on it. Using postgres, I also get the same error through the web ui.

I did try altering the getSnapshotDiff function to change the sort order to see if that worked, and got a different error where it complained of a relationship not existing (I think that is a schema cache issue).

### To Reproduce

Start with a fresh directus instance and then apply snapshot_before.yaml to create example + example_translations collections:
[snapshot_before.yaml.txt](https://github.com/directus/directus/files/9332057/snapshot_before.yaml.txt)

Then try to apply snapshot_after.yaml which should delete both collections, but instead gives the error.
[snapshot_after.yaml.txt](https://github.com/directus/directus/files/9332056/snapshot_after.yaml.txt)

### Errors Shown

```
Failed to delete collection "example"
error drop table "example" - cannot drop table example because other objects depend on it
   at Parser.parseErrorMessage (/Users/me/projects/directus/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/me/projects/directus/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/me/projects/directus/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/me/projects/directus/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
 ELIFECYCLE  Command failed with exit code 1.
```

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome, Firefox

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment]
This should be the same as #11895 👍 Thanks for the snapshots! Will be very helpful later on when verifying said issue's solution on different database vendors.

**Comment by benosman** [comment]
> This should be the same as #11895 👍 Thanks for the snapshots! Will be very helpful later on when verifying said issue's solution on different database vendors.

Ah, I hadn't seen that one despite searching!

It does look to be the same issue, and the solutions suggested in there are very much along the lines of what I was thinking too. 👍
