### ISSUE TITLE
Directus won't run with Plesk / Passenger since 9.15.0

### ISSUE THREAD

**Issue by stylefieber** [directus/directus#15080]
### Describe the Bug

Since 9.15.0 Directus does not start properly. 9.14.5 just works as it should.

Plesk is the latest 18.0.45 on Ubuntu 20.0.44 LTS

### To Reproduce

Follow the instructions from the docs for installing Directus in Plesk environment.

After npm install, run app in development mode. Open the URL.

### Errors Shown

Passenger Debug gives me this message:

[ D 2022-08-16 00:25:28.9479 36692/T1 age/Spa/SpawnEnvSetupperMain.cpp:747 ]: shellName = 'false' detected as supporting '-l': false
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/vhosts/example.domain/subdomain/node_modules/rate-limiter-flexible/lib/RateLimiterCluster.js:22:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (node:internal/modules/cjs/helpers:102:18)

node:internal/modules/cjs/loader:956
  const err = new Error(message);
              ^

Error: Cannot find module '@directus/app/package.json'
Require stack:
- /var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js
- /var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js
- /var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/index.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/services/graphql/index.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/services/index.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/middleware/respond.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/controllers/activity.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/app.js
- /var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/server.js
- /var/www/vhosts/example.domain/subdomain/index.js
- /usr/share/passenger/helper-scripts/node-loader.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at resolvePackage (/var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js:9:43)
    at ExtensionManager.getSharedDepsMapping (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js:230:103)
    at ExtensionManager.generateExtensionBundles (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js:202:46)
    at ExtensionManager.load (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js:146:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExtensionManager.initialize (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js:87:13)
    at async createApp (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/app.js:108:5)
    at async createServer (/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/server.js:45:38) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/@directus/shared/dist/cjs/utils/node/index.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/extensions.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/services/graphql/index.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/services/index.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/middleware/respond.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/controllers/activity.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/app.js',
    '/var/www/vhosts/example.domain/subdomain/node_modules/directus/dist/server.js',
    '/var/www/vhosts/example.domain/subdomain/index.js',
    '/usr/share/passenger/helper-scripts/node-loader.js'
  ]
}

Node.js v18.7.0

### What version of Directus are you using?

9.15.0 / 9.15.1

### What version of Node.js are you using?

18.7.0

### What database are you using?

MariaDB 10.3.34

### What browser are you using?

Chrome

### How are you deploying Directus?

Plesk

**Comment by azrikahar** [comment]
> Error: Cannot find module '@directus/app/package.json'

This seems similar to #14706, and was technically fixed by #14728 in 9.15.0, but the fix might be (somehow) incompatible with Plesk 🤔

**Comment by stylefieber** [comment]
I am not sure. I tested different 9.14.x versions and it worked. I also thought it might be due to the pnpm change, but the 9.14.x versions after the change were okay. Maybe the fix broke it for Plesk envorinments.
