### ISSUE TITLE
Update item through API succeeds but throws UnauthorizedTableBigEditException due to user not having permissions to directus_activity table

### ISSUE THREAD

**Issue by Hainesy** [directus/directus#1531]
## Version Info
  - Directus version and branch: 6.4.0-rc.1 (I *think*)
  - PHP version: 7
  - MySQL version: 5.7.18
  - Web server: Apache
  - OS name and version: Linux mint 18

## Expected Behavior
JSON response with meta & data.

## Actual Behavior
Response contains UnauthorizedTableBigEditException, saying access is forbidden on directus_activity.

## Steps to Reproduce
 1. Set up a user without access to activity table
 2. Send a PATCH request to /api/1.1/tables/[table-name]/rows/[row-id]
 
## Logs or Screenshots
```
{
  "code":0,
  "class":"Directus\\Permissions\\Exception\\UnauthorizedTableBigEditException",
  "message":"[Group #3 User #5] Table bigedit access forbidden on `directus_activity` table record with null primary key and no magic owner column.",
  "file":"\/var\/www\/directus\/vendor\/directus\/database\/RowGateway\/BaseRowGateway.php",
  "line":246,
  "trace":[
    {
      "file":"\/var\/www\/directus\/vendor\/directus\/database\/TableGateway\/RelationalTableGateway.php",
      "line":255,
      "function":"save",
      "class":"Directus\\Database\\RowGateway\\BaseRowGateway",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/routes\/A1\/Entries.php",
      "line":149,
      "function":"manageRecordUpdate",
      "class":"Directus\\Database\\TableGateway\\RelationalTableGateway",
      "type":"->",
      "args":[
        "Accommodation",
        {
          "full_description_web":"<p>This is another version<\/p>",
          "id":"1"
        },
        1
      ]
    },
    {
      "function":"row",
      "class":"Directus\\API\\Routes\\A1\\Entries",
      "type":"->",
      "args":[
        "Accommodation",
        "1"
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php",
      "line":436,
      "function":"call_user_func_array",
      "args":[
        [
          {
            
          },
          "row"
        ],
        [
          "Accommodation",
          "1"
        ]
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1305,
      "function":"dispatch",
      "class":"Slim\\Route",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php",
      "line":85,
      "function":"call",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php",
      "line":92,
      "function":"call",
      "class":"Slim\\Middleware\\Flash",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php",
      "line":22,
      "function":"call",
      "class":"Slim\\Middleware\\MethodOverride",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1254,
      "function":"call",
      "class":"Directus\\Slim\\CorsMiddleware",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/core\/Directus\/Application\/Application.php",
      "line":80,
      "function":"run",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/api.php",
      "line":1933,
      "function":"run",
      "class":"Directus\\Application\\Application",
      "type":"->",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 \/var\/www\/directus\/vendor\/directus\/database\/TableGateway\/RelationalTableGateway.php(255): Directus\\Database\\RowGateway\\BaseRowGateway->save()\n#1 \/var\/www\/directus\/api\/routes\/A1\/Entries.php(149): Directus\\Database\\TableGateway\\RelationalTableGateway->manageRecordUpdate('Accommodation', Array, 1)\n#2 [internal function]: Directus\\API\\Routes\\A1\\Entries->row('Accommodation', '1')\n#3 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php(436): call_user_func_array(Array, Array)\n#4 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1305): Slim\\Route->dispatch()\n#5 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#6 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 \/var\/www\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php(22): Slim\\Middleware\\MethodOverride->call()\n#8 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1254): Directus\\Slim\\CorsMiddleware->call()\n#9 \/var\/www\/directus\/api\/core\/Directus\/Application\/Application.php(80): Slim\\Slim->run()\n#10 \/var\/www\/directus\/api\/api.php(1933): Directus\\Application\\Application->run()\n#11 {main}"
}
```

**Comment by WellingGuzman** [comment]
Hey @Hainesy each user group must have permission to update and add information to activity table.

This is something we will fix soon, as this is a system level process that shouldn't be requiring the user group permission to perform it.

If giving the user group permission to add/update entries in `directus_activity` doesn't fix the problem, let us know.

**Comment by WellingGuzman** [comment]
I will close this as this is an expected behavior, but we will improve this process to avoid this happening in a future.

This will be tracked here: #1532
