### ISSUE TITLE
Directus fails to start on IIS: Error: Cannot find module '@directus/app/package.json'

### ISSUE THREAD

**Issue by paulboudewijn** [directus/directus#15559]
### Describe the Bug

After updating Directus to the latest version it fails to start on IIS. 

### To Reproduce

Follow the steps on https://docs.directus.io/self-hosted/installation/iis.html

### Errors Shown

```
(node:46908) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module '@directus/app/package.json'
Require stack:
- [..]\node_modules\@directus\shared\dist\cjs\utils\node\resolve-package.js
- [..]\node_modules\@directus\shared\dist\cjs\utils\node\get-extensions.js
- [..]\node_modules\@directus\shared\dist\cjs\utils\node\index.js
- [..]\node_modules\directus\dist\extensions.js
- [..]\node_modules\directus\dist\services\graphql\index.js
- [..]\node_modules\directus\dist\services\index.js
- [..]\node_modules\directus\dist\middleware\respond.js
- [..]\node_modules\directus\dist\controllers\activity.js
- [..]\node_modules\directus\dist\app.js
- [..]\node_modules\directus\dist\server.js
- [..]\index.js
- C:\Program Files\iisnode\interceptor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at resolvePackage ([..]\node_modules\@directus\shared\dist\cjs\utils\node\resolve-package.js:9:43)
    at ExtensionManager.getSharedDepsMapping ([..]\node_modules\directus\dist\extensions.js:243:103)
    at ExtensionManager.generateExtensionBundles ([..]\node_modules\directus\dist\extensions.js:215:46)
    at ExtensionManager.load ([..]\node_modules\directus\dist\extensions.js:154:45)
    at async ExtensionManager.initialize ([..]\node_modules\directus\dist\extensions.js:93:13)
    at async createApp ([..]\node_modules\directus\dist\app.js:108:5)
    at async createServer ([..]\node_modules\directus\dist\server.js:45:38)
    at async startServer ([..]\node_modules\directus\dist\server.js:132:20)
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Seems like the same error as #15091. Would you mind helping with debugging and check what `require.main.filename` resolves to, as mentioned in this comment: https://github.com/directus/directus/discussions/15091#discussioncomment-3434967?

Feel free to answer this question over there to follow up in that same discussion. Perhaps this should/can be accounted in #15498 as a broader fix for such issue, if applicable.
