### ISSUE TITLE
graphQL can not working if has files column

### ISSUE THREAD

**Issue by imiskolee** [directus/directus#15783]
### Describe the Bug

graphQL response error:

TypeError[table_name.column_name]: Cannot construct TypeComposer from [undefined]

column_name is a files.

### To Reproduce

1. create collection A
2.  create field files
3. create collection B
4. create data to B with graphQL.

### Errors Shown

TypeError[table_name.column_name]: Cannot construct TypeComposer from [undefined]

```
    at TypeMapper.convertOutputTypeDefinition (/home/developer/develop/directus_staging/node_modules/.pnpm/graphql-compose@9.0.8_graphql@15.8.0/node_modules/graphql-compose/lib/TypeMapper.js:169:23)
    at TypeMapper.convertOutputFieldConfig (/home/developer/develop/directus_staging/node_modules/.pnpm/graphql-compose@9.0.8_graphql@15.8.0/node_modules/graphql-compose/lib/TypeMapper.js:233:33)
    at ObjectTypeComposer.setField (/home/developer/develop/directus_staging/node_modules/.pnpm/graphql-compose@9.0.8_graphql@15.8.0/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)
    at /home/developer/develop/directus_staging/node_modules/.pnpm/graphql-compose@9.0.8_graphql@15.8.0/node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18
    at Array.forEach (<anonymous>)
    at ObjectTypeComposer.addFields (/home/developer/develop/directus_staging/node_modules/.pnpm/graphql-compose@9.0.8_graphql@15.8.0/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)
    at getTypes (/home/developer/develop/directus_staging/api/dist/services/graphql/index.js:352:117)
    at getReadableTypes (/home/developer/develop/directus_staging/api/dist/services/graphql/index.js:401:62)
    at GraphQLService.getSchema (/home/developer/develop/directus_staging/api/dist/services/graphql/index.js:124:41)
    at GraphQLService.execute (/home/developer/develop/directus_staging/api/dist/services/graphql/index.js:81:29)
```

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

V16.15.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
I can't seem to reproduce this based on the reproduction steps, could there be other steps/configs involved? Here's what I've attempted by following the steps:

https://user-images.githubusercontent.com/42867097/192954117-20550b01-90a1-463e-8aed-6a41a685db1f.mp4

Do let me know if the steps in my attempt is not the same as what you have described 👍 I'll close this for now until further info arises.
