### ISSUE TITLE
TypeError: Cannot read properties of undefined - on new install

### ISSUE THREAD

**Issue by wasims1** [directus/directus#16221]
### Describe the Bug

We are freshly installing directus 9.19.2 (we removed all the tables for 9.3). However, we're getting this error that we cannot figure out why it's happening and preventing us from running directus:

TypeError: Cannot read properties of undefined (reading 'primary')
    at parseFields (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:194:71)
    at async getASTFromQuery (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:66:20)
    at async FlowsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:200:19)
    at async FlowManager.load (/directus/node_modules/directus/dist/flows.js:124:23)
    at async FlowManager.initialize (/directus/node_modules/directus/dist/flows.js:92:13)
    at async createApp (/directus/node_modules/directus/dist/app.js:109:5)
    at async createServer (/directus/node_modules/directus/dist/server.js:45:38)
    at async Command.startServer (/directus/node_modules/directus/dist/server.js:132:20)
    at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:923:5)

### To Reproduce

install directus 9.19.2 i guess

### Errors Shown

TypeError: Cannot read properties of undefined (reading 'primary')
    at parseFields (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:194:71)
    at async getASTFromQuery (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:66:20)
    at async FlowsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:200:19)
    at async FlowManager.load (/directus/node_modules/directus/dist/flows.js:124:23)
    at async FlowManager.initialize (/directus/node_modules/directus/dist/flows.js:92:13)
    at async createApp (/directus/node_modules/directus/dist/app.js:109:5)
    at async createServer (/directus/node_modules/directus/dist/server.js:45:38)
    at async Command.startServer (/directus/node_modules/directus/dist/server.js:132:20)
    at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:923:5)

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

whatever in the docker hub official directus 9.19.2

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

docker/k8s

**Comment by wasims1** [comment]
It turns out it's a permissions issue...
