### ISSUE TITLE
Error when updating/deleting an item based on a permission rule where foreign key can be null

### ISSUE THREAD

**Issue by sarthakgaur** [directus/directus#16498]
### Describe the Bug

Read this first: https://github.com/directus/directus/discussions/16350

There are three tables `table_1`, `table_2`, and `table_3`.

`table_1` table schema:
1. `name`
2. `status`

`table_2` table schema:
1. `name`
2. `table_1_field`

`table_3` table schema:
1. `name`
2. `table_2_field`

The `table_1_field` in `table_2` is a foreign key. It references a row in `table_1`. The `table_2_field` in `table_3` is a foreign key. It references a row in `table_2`.

There is a Tester Role. A user with a Tester role should be able to do the following:
1. Create `table_1`, `table_2`, and `table_3` rows.
2. Read all fields in `table_1`, `table_2`, and `table_3`.
3. Update a `table_1` row if the `status` is `draft`.
4. Delete a `table_1` row if the `status` is `draft`.
5. Update a `table_2` row if the `table_1_field` is `null`.
6. Update a `table_2` row if the `table_1_field.status` is `draft`.
7. Delete a `table_2` row if the `table_1_field` is `null`.
8. Delete a `table_2` row if the `table_1_field.status` is `draft`.
9. Update a `table_3` row if the `table_2_field` is `null`.
10. Update a `table_3` row if the `table_2_field.table_1_field` is `null`.
11. Update a `table_3` row if the `table_2_field.table_1_field.status` is `draft`.
12. Delete a `table_3` row if the `table_2_field` is `null`.
13. Delete a `table_3` row if the `table_2_field.table_1_field` is `null`.
14. Delete a `table_3` row if the `table_2_field.table_1_field.status` is `draft`.

As you can see for the Tester role, the update and delete rules for `table_2` are same. And, the update and delete rules for `table_3` are same.

Screenshots:

Tester role, Table 2, Update. Delete is also same.
![Alt text](https://i.imgur.com/W6BXc5a.png)

Tester role, Table 3, Update. Delete is also same.
![Alt text](https://i.imgur.com/vjCD9SV.png)

Errors are show when I try to do the following with a Tester role. Check the "Errors Shown" section for details:
1. Updating an item in `table_2` when `table_1_field` is `null`.
2. Updating an item in `table_3` when `table_2_field` is `null`.
3. Deleting an item in `table_3` when `table_2_field` is `null`.

### To Reproduce

Import this pg_dump file into a new database: https://pastebin.com/yqdqRnkw

Use the following credentials to log in:
Email: `tester@example.com`
Password: `test123`

Admin account credentials:
Email: `admin@example.com`
Password: `test123`

Try the following with `tester@example.com` user account:
1. Update an item in the `table_2` collection.
2. Update an item in the `table_3` collection.
3. Delete an item in the `table_3` collection.

### Errors Shown

Error message when updating an item in `table_2` when `table_1_field` is `null`:

```
[11:56:17] ERROR (53407 on fedora): select "table_3"."table_2_field", "table_3"."id" from "table_3" left join "table_2" as "inkhd" on "table_3"."table_2_field" = "inkhd"."id" left join "table_1" as "rqzsy" on "inkhd"."table_1_field" = "rqzsy"."id" left join "table_2" as "sbwvh" on "table_3"."table_2_field" = "sbwvh"."id" left join "table_1" as "jzboy" on "sbwvh"."table_1_field" = "jzboy"."id" where ((("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "jzboy"."status" = $1))) and "table_3"."table_2_field" in ($2) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
    err: {
      "type": "DatabaseError",
      "message": "select \"table_3\".\"table_2_field\", \"table_3\".\"id\" from \"table_3\" left join \"table_2\" as \"inkhd\" on \"table_3\".\"table_2_field\" = \"inkhd\".\"id\" left join \"table_1\" as \"rqzsy\" on \"inkhd\".\"table_1_field\" = \"rqzsy\".\"id\" left join \"table_2\" as \"sbwvh\" on \"table_3\".\"table_2_field\" = \"sbwvh\".\"id\" left join \"table_1\" as \"jzboy\" on \"sbwvh\".\"table_1_field\" = \"jzboy\".\"id\" where (((\"table_3\".\"table_2_field\" is null or \"[object Object]\".\"table_1_field\" is null or \"jzboy\".\"status\" = $1))) and \"table_3\".\"table_2_field\" in ($2) order by \"table_3\".\"id\" asc limit $3 - missing FROM-clause entry for table \"[object Object]\"",
      "stack":
          error: select "table_3"."table_2_field", "table_3"."id" from "table_3" left join "table_2" as "inkhd" on "table_3"."table_2_field" = "inkhd"."id" left join "table_1" as "rqzsy" on "inkhd"."table_1_field" = "rqzsy"."id" left join "table_2" as "sbwvh" on "table_3"."table_2_field" = "sbwvh"."id" left join "table_1" as "jzboy" on "sbwvh"."table_1_field" = "jzboy"."id" where ((("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "jzboy"."status" = $1))) and "table_3"."table_2_field" in ($2) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
              at Parser.parseErrorMessage (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/home/fedora/project/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:520:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 127,
      "name": "error",
      "severity": "ERROR",
      "code": "42P01",
      "position": "407",
      "file": "parse_relation.c",
      "line": "3541",
      "routine": "errorMissingRTE"
    }

```

Error message when updating an item in `table_3` when `table_2_field` is `null`:

```
[11:50:07] ERROR (53407 on fedora): select "table_3"."id", "table_3"."name", "table_3"."table_2_field" from "table_3" left join "table_2" as "uaqrr" on "table_3"."table_2_field" = "uaqrr"."id" left join "table_1" as "rxjav" on "uaqrr"."table_1_field" = "rxjav"."id" left join "table_2" as "lsjgx" on "table_3"."table_2_field" = "lsjgx"."id" left join "table_1" as "kvxfe" on "lsjgx"."table_1_field" = "kvxfe"."id" where (("table_3"."id" in ($1)) and (("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "kvxfe"."status" = $2))) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
    err: {
      "type": "DatabaseError",
      "message": "select \"table_3\".\"id\", \"table_3\".\"name\", \"table_3\".\"table_2_field\" from \"table_3\" left join \"table_2\" as \"uaqrr\" on \"table_3\".\"table_2_field\" = \"uaqrr\".\"id\" left join \"table_1\" as \"rxjav\" on \"uaqrr\".\"table_1_field\" = \"rxjav\".\"id\" left join \"table_2\" as \"lsjgx\" on \"table_3\".\"table_2_field\" = \"lsjgx\".\"id\" left join \"table_1\" as \"kvxfe\" on \"lsjgx\".\"table_1_field\" = \"kvxfe\".\"id\" where ((\"table_3\".\"id\" in ($1)) and ((\"table_3\".\"table_2_field\" is null or \"[object Object]\".\"table_1_field\" is null or \"kvxfe\".\"status\" = $2))) order by \"table_3\".\"id\" asc limit $3 - missing FROM-clause entry for table \"[object Object]\"",
      "stack":
          error: select "table_3"."id", "table_3"."name", "table_3"."table_2_field" from "table_3" left join "table_2" as "uaqrr" on "table_3"."table_2_field" = "uaqrr"."id" left join "table_1" as "rxjav" on "uaqrr"."table_1_field" = "rxjav"."id" left join "table_2" as "lsjgx" on "table_3"."table_2_field" = "lsjgx"."id" left join "table_1" as "kvxfe" on "lsjgx"."table_1_field" = "kvxfe"."id" where (("table_3"."id" in ($1)) and (("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "kvxfe"."status" = $2))) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
              at Parser.parseErrorMessage (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/home/fedora/project/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:520:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 127,
      "name": "error",
      "severity": "ERROR",
      "code": "42P01",
      "position": "454",
      "file": "parse_relation.c",
      "line": "3541",
      "routine": "errorMissingRTE"
    }

```

Error message when deleting an item in `table_3` when `table_2_field` is `null`:

```
[11:54:39] ERROR (53407 on fedora): select "table_3"."id" from "table_3" left join "table_2" as "xkvud" on "table_3"."table_2_field" = "xkvud"."id" left join "table_1" as "vlcjc" on "xkvud"."table_1_field" = "vlcjc"."id" left join "table_2" as "erkmn" on "table_3"."table_2_field" = "erkmn"."id" left join "table_1" as "mvwbm" on "erkmn"."table_1_field" = "mvwbm"."id" where (("table_3"."id" in ($1)) and (("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "mvwbm"."status" = $2))) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
    err: {
      "type": "DatabaseError",
      "message": "select \"table_3\".\"id\" from \"table_3\" left join \"table_2\" as \"xkvud\" on \"table_3\".\"table_2_field\" = \"xkvud\".\"id\" left join \"table_1\" as \"vlcjc\" on \"xkvud\".\"table_1_field\" = \"vlcjc\".\"id\" left join \"table_2\" as \"erkmn\" on \"table_3\".\"table_2_field\" = \"erkmn\".\"id\" left join \"table_1\" as \"mvwbm\" on \"erkmn\".\"table_1_field\" = \"mvwbm\".\"id\" where ((\"table_3\".\"id\" in ($1)) and ((\"table_3\".\"table_2_field\" is null or \"[object Object]\".\"table_1_field\" is null or \"mvwbm\".\"status\" = $2))) order by \"table_3\".\"id\" asc limit $3 - missing FROM-clause entry for table \"[object Object]\"",
      "stack":
          error: select "table_3"."id" from "table_3" left join "table_2" as "xkvud" on "table_3"."table_2_field" = "xkvud"."id" left join "table_1" as "vlcjc" on "xkvud"."table_1_field" = "vlcjc"."id" left join "table_2" as "erkmn" on "table_3"."table_2_field" = "erkmn"."id" left join "table_1" as "mvwbm" on "erkmn"."table_1_field" = "mvwbm"."id" where (("table_3"."id" in ($1)) and (("table_3"."table_2_field" is null or "[object Object]"."table_1_field" is null or "mvwbm"."status" = $2))) order by "table_3"."id" asc limit $3 - missing FROM-clause entry for table "[object Object]"
              at Parser.parseErrorMessage (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/home/fedora/project/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/home/fedora/project/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:520:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 127,
      "name": "error",
      "severity": "ERROR",
      "code": "42P01",
      "position": "409",
      "file": "parse_relation.c",
      "line": "3541",
      "routine": "errorMissingRTE"
    }
```

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.3

### What browser are you using?

Firefox

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-136](https://linear.app/directus/issue/ENG-136/error-when-updatingdeleting-an-item-based-on-a-permission-rule-where)

**Comment by paescuj** [comment]
Hey @sarthakgaur, thank you very much for your detailed bug report!

I just tried to reproduce this on the latest version ([v9.22.4](https://github.com/directus/directus/releases/tag/v9.22.4)) but it seems like this is no longer an issue. I was able to successfully update / delete items in `table_2` and `table_3` with the test user and without any error displayed in the log. Can you confirm this on your side?

See here for an upgrade guide: https://docs.directus.io/self-hosted/upgrades-migrations.html#upgrading-updating-a-project

That being said, it seems like there's an(other) issue with either the delete permission set-up or the app itself: The delete button on the detailed item view is grayed out, so I had to delete the item via the content overview.
<img width="800" src="https://user-images.githubusercontent.com/5363448/216083851-4093bc9e-8025-4bf1-a152-6ec05bf43393.png">

**Comment by sarthakgaur** [comment]
@paescuj On (v9.22.4) I am able to delete and update items with the Tester role. Looks like this is fixed now.

> That being said, it seems like there's an(other) issue with either the delete permission set-up or the app itself: The delete button on the detailed item view is grayed out, so I had to delete the item via the content overview.

That's not a big issue for us. From our side this issue is solved. So, if you want, please close this issue.

**Comment by paescuj** [comment]
@sarthakgaur Thank you very much for your response! I'm glad this issue is now fixed on your end as well!

> That's not a big issue for us. From our side this issue is solved. So, if you want, please close this issue.

Okay, great! I'm going to track this in a separate issue.
