### ISSUE TITLE
OAS missing x-metadata and Query schemas

### ISSUE THREAD

**Issue by NickUfer** [directus/directus#16523]
### Describe the Bug

After fix https://github.com/directus/directus/pull/16485 `x-metadata` and `Query` wer supposed to be located at `/components/schemas/` but they are missing. This leads to an invalid spec.

![image](https://user-images.githubusercontent.com/11254522/202806881-9542c0d6-8b6f-46e8-b686-28bfec331d16.png)

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 12, Warning count: 0
Errors: 
        -attribute paths.'/revisions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/permissions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/users'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/folders'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/activity'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/files'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/operations'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/presets'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/flows'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/items/blogs'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/roles'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.#/components/schemas/Query is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

### To Reproduce

Copy spec from `/server/specs/oas` generated by directus 9.21.0 into any OAS validator

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

v16.18.1

### What database are you using?

Postgres 15.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by cf-ts** [comment]
I would suppose to dynamically add schemas with no collection to resulting spec file:

	components.schemas = {};
	// copy schemas without a collection
	if (openapi.components && openapi.components.schemas) {
		for (const schemaName in openapi.components.schemas) {
			const schema: any = openapi.components!.schemas![schemaName];
			if (!schema['x-collection']) {
				components.schemas[schemaName] = schema;
			}
		}
	}
