### ISSUE TITLE
`schema apply` failing

### ISSUE THREAD

**Issue by daawaan4U** [directus/directus#16527]
### Describe the Bug

I am trying to migrate from 9.20.4 -> 9.21.0 and I'm currently trying to test schema migrations but `schema apply` hangs then fails. So far, I've tested both SQLite and Postgres and the command fails regardless of schema complexity.

### To Reproduce

1. Start directus with a fresh database
2. Create a collection and stop directus
3. Snapshot
5. Apply schema to a fresh database

### Errors Shown

Using this sample schema:

**schema.yaml**
```
version: 1
directus: 9.21.0
collections:
  - collection: nyew
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: nyew
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      name: nyew
      sql: CREATE TABLE `nyew` (`id` char(36) not null, primary key (`id`))
fields:
  - collection: nyew
    field: id
    meta:
      collection: nyew
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: nyew
    type: uuid
relations: []
```

**SQLite Error**
```
{"level":50,"time":1668835886061,"pid":730,"hostname":"daawaan4u","msg":"Failed to create collection \"nyew\""}
{"level":50,"time":1668835886061,"pid":730,"hostname":"daawaan4u","err":{"type":"KnexTimeoutError","message":"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?","stack":"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\n    at Client_SQLite3.acquireConnection (/workspace/directus-app/node_modules/.pnpm/knex@2.3.0_2jnbnfc5ay2jsur3mx6zcncoj4/node_modules/knex/lib/client.js:307:26)\n    at async Runner.ensureConnection (/workspace/directus-app/node_modules/.pnpm/knex@2.3.0_2jnbnfc5ay2jsur3mx6zcncoj4/node_modules/knex/lib/execution/runner.js:287:28)\n    at async Runner.run (/workspace/app-dental-clinic/node_modules/.pnpm/knex@2.3.0_2jnbnfc5ay2jsur3mx6zcncoj4/node_modules/knex/lib/execution/runner.js:30:19)","name":"KnexTimeoutError"},"msg":"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?"}
 ELIFECYCLE  Command failed with exit code 1.
```

**Postgres Error**
```
{"level":50,"time":1668834412450,"pid":5616,"hostname":"daawaan4u","msg":"Failed to create field \"nyew.id\""}
{"level":50,"time":1668834412451,"pid":5616,"hostname":"daawaan4u","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'fields')","stack":"TypeError: Cannot read properties of undefined (reading 'fields') at FieldsService.createField (/workspace/directus-app/node_modules/.pnpm/directus@9.21.0_typescript@4.9.3/node_modules/directus/dist/services/fields.js:229:79) at async /workspace/directus-app/node_modules/.pnpm/directus@9.21.0_typescript@4.9.3/node_modules/directus/dist/utils/apply-snapshot.js:146:21"},"msg":"Cannot read properties of undefined (reading 'fields')"}
```

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.0

### What database are you using?

Tested with SQLite 3.35.5 and Postgres 12.12 so far

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by paescuj** [comment]
Can confirm running Directus 9.21.0 inside a Docker container with SQLite. It works with 9.20.4.

**Comment by azrikahar** [comment]
I believe this is the same root cause as #16503 as both occurs in `9.21.0` and relates to transaction & schema not being updated when schema apply is run (eg. when the field is added, it was not able to find the collection in the schema, so `.fields` in `this.schema.collections[collection].fields` fails:

https://github.com/directus/directus/blob/12786728ed3d2c1808863fca3fcdda588d0e2c0f/api/src/services/fields.ts#L256

will re-open if they turn out to be different 👍
