### ISSUE TITLE
500 error after login

### ISSUE THREAD

**Issue by eimhin** [directus/directus#1659]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.0.18
  - MySQL version: 5.7.18
  - Web server: Apache 2.4.18
  - OS name and version: Ubuntu 16.04

## Expected Behavior

After installing Directus, meeting all the requirements, I login for the first time with the default username and password and expect to be directed to the first admin page.

## Actual Behavior

After logging in I receive a "server error occurred" message. If I refresh the page it seems I've been authenticated but all I see is JSON returned in the browser (and error message) and nothing else.

## Steps to Reproduce
 1. Install Directus
 2. Try and log in with default user for the first time

## Logs or Screenshots

After logging in I receive a "server error occurred" message and the log file shows this:

```
ERROR - 2017-07-05T08:47:16-04:00 - Error: Call to undefined function curl_init() in /var/www/html/api/core/functions.php:1153
Stack trace:
#0 /var/www/html/api/core/functions.php(1181): get_contents('https://directu...', Array)
#1 /var/www/html/api/core/functions.php(1230): get_json('https://directu...')
#2 /var/www/html/api/api.php(653): feedback_login_ping('a-kind-of-uniqu...')
#3 [internal function]: {closure}()
#4 /var/www/html/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /var/www/html/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#6 /var/www/html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /var/www/html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /var/www/html/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#9 /var/www/html/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#10 /var/www/html/api/core/Directus/Application/Application.php(84): Slim\Slim->run()
#11 /var/www/html/api/api.php(1930): Directus\Application\Application->run()
#12 {main}
```

Then if I try to reload the page it seems as if I was authenticated, because when I visit the domain I'm not redirected to the login page, but instead I get this JSON returned in the browser:

```
 {
  "code":0,
  "class":"Error",
  "message":"Call to undefined function curl_init()",
  "file":"\/var\/www\/html\/api\/core\/functions.php",
  "line":1153,
  "trace":[
    {
      "file":"\/var\/www\/html\/api\/core\/functions.php",
      "line":1181,
      "function":"get_contents",
      "args":[
        "https:\/\/directus.io\/check-version",
        [
          "Content-Type: application\/json"
        ]
      ]
    },
    {
      "file":"\/var\/www\/html\/api\/core\/functions.php",
      "line":1205,
      "function":"get_json",
      "args":[
        "https:\/\/directus.io\/check-version"
      ]
    },
    {
      "file":"\/var\/www\/html\/index.php",
      "line":292,
      "function":"check_version",
      "args":[
        false
      ]
    },
    {
      "file":"\/var\/www\/html\/index.php",
      "line":325,
      "function":"getVersionNotification",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/html\/index.php",
      "line":497,
      "function":"getLoginNotification",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 \/var\/www\/html\/api\/core\/functions.php(1181): get_contents('https:\/\/directu...', Array)\n#1 \/var\/www\/html\/api\/core\/functions.php(1205): get_json('https:\/\/directu...')\n#2 \/var\/www\/html\/index.php(292): check_version(false)\n#3 \/var\/www\/html\/index.php(325): getVersionNotification()\n#4 \/var\/www\/html\/index.php(497): getLoginNotification()\n#5 {main}"
}
```

And the log file adds:

```
ERROR - 2017-07-05T08:51:52-04:00 - Error: Call to undefined function curl_init() in /var/www/html/api/core/functions.php:1153
Stack trace:
#0 /var/www/html/api/core/functions.php(1181): get_contents('https://directu...', Array)
#1 /var/www/html/api/core/functions.php(1205): get_json('https://directu...')
#2 /var/www/html/index.php(292): check_version(false)
#3 /var/www/html/index.php(325): getVersionNotification()
#4 /var/www/html/index.php(497): getLoginNotification()
#5 {main}
```

**Comment by eimhin** [comment]
My apologies, I was missing the curl php extension. Feel free to close this issue.

**Comment by WellingGuzman** [comment]
These changes were made into 6.4

**Comment by WellingGuzman** [comment]
Also glad you figure it out @eimhin, in 6.4 we are making errors more clear bit by bit.

**Comment by davidchalifoux** [comment]
Just experienced this myself. A proper error description for this would be great!
