### ISSUE TITLE
9.19.0 to 9.21.0 - Cannot query with GraphQL

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#16616]
### Describe the Bug

Performing any GrapQL query will results in the following exception:

Sample query

```
// POST /graphql
query { 
   activities { 
      id
   } 
}
```
```
{
  "errors": [
    {
      "message": "TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Directus 9.18.1 seems to be the latest version where the bug is not detected.

### To Reproduce

Use Directus from 9.19.0 to 9.21.0

Performs a GraphQL query

### Errors Shown

```
{
	"errors": [
		{
			"message": "TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"stack": "Error: TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })\n    at TypeMapper.convertOutputFieldConfig (next-directus\\node_modules\\graphql-compose\\lib\\TypeMapper.js:252:19)\n    at ObjectTypeComposer.setField (next-directus\\node_modules\\graphql-compose\\lib\\ObjectTypeComposer.js:162:46)\n    at next-directus\\node_modules\\graphql-compose\\lib\\ObjectTypeComposer.js:168:18\n    at Array.forEach (<anonymous>)\n    at ObjectTypeComposer.addFields (next-directus\\node_modules\\graphql-compose\\lib\\ObjectTypeComposer.js:167:32)\n    at Function.createTemp (next-directus\\node_modules\\graphql-compose\\lib\\ObjectTypeComposer.js:114:20)\n    at Function.create (next-directus\\node_modules\\graphql-compose\\lib\\ObjectTypeComposer.js:73:25)\n    at SchemaComposer.createObjectTC (next-directus\\node_modules\\graphql-compose\\lib\\SchemaComposer.js:302:56)\n    at getTypes next-directus\\node_modules\\directus\\dist\\services\\graphql\\index.js:220:51)\n    at getReadableTypes (\\next-directus\\node_modules\\directus\\dist\\services\\graphql\\index.js:407:62)"
			}
		}
	]
}
```

### What version of Directus are you using?

9.19.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgre

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by gkielwasser** [comment]
Sorry for the inconvenience,

I have seen this issue was because I had the following graphql constraints
```
"graphql": "^15.5.0",
```

Ater updating this library I do not have anymore the issue
```
"graphql": "^16.6.0",
```

Can you please close the issue ?
