### ISSUE TITLE
can't install any extension in windows

### ISSUE THREAD

**Issue by markqiu** [directus/directus#16697]
### Describe the Bug

I tried a lot of extension, all the same errors:
```
[15:25:09] WARN (20220 on LAPTOP-JIO12MPN): Could not resolve "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js" from "virtual:entry"
              at error (e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:206:30)
              at ModuleLoader.handleInvalidResolvedId (e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:23262:24)     
              at e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:23225:26
      "code": "UNRESOLVED_IMPORT",
      "exporter": "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js",     
      "id": "\u0000virtual:entry",
      "watchFiles": [
        "\u0000virtual:entry"
```

### To Reproduce

npm i directus-extension-schema-management-module

npx directus start

### Errors Shown

[15:25:09] WARN (20220 on LAPTOP-JIO12MPN): Could not resolve "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js" from "virtual:entry"
              at error (e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:206:30)
              at ModuleLoader.handleInvalidResolvedId (e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:23262:24)     
              at e:\markqiu\work\zdinv\node_modules\.pnpm\rollup@3.3.0\node_modules\rollup\dist\shared\rollup.js:23225:26
      "code": "UNRESOLVED_IMPORT",
      "exporter": "./e:/markqiu/work/zdinv/node_modules/.pnpm/directus-extension-display-link@1.6.1/node_modules/directus-extension-display-link/dist/index.js",     
      "id": "\u0000virtual:entry",
      "watchFiles": [
        "\u0000virtual:entry"

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by br41nslug** [comment]
Installed `npm i directus-extension-schema-management-module` in a fresh project and that loaded as expected.
It looks like you're mixing `pnpm` (`/node_modules/.pnpm/directus-extension-display-link`) and `npm` (`npm i directus-extension-... && npx directus start`) use, what steps did you take in your installation? Could you try removing the `node_modules` and reinstalling with the preferred package manager (i'd suggest sticking with `npm` unless you're running of a fork of the project)

**Comment by markqiu** [comment]
```
> zdinv@1.0.0 start
> directus start

[09:03:29] WARN (18412 on LAPTOP-JIO12MPN): Couldn't bundle App extensions
[09:03:29] WARN (18412 on LAPTOP-JIO12MPN): Could not resolve "./e:/markqiu/work/zdinv/node_modules/directus-extension-schema-management-module/dist/index.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./e:/markqiu/work/zdinv/node_modules/directus-extension-schema-management-module/dist/index.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./e:/markqiu/work/zdinv/node_modules/directus-extension-schema-management-module/dist/index.js" from "virtual:entry"       
              at error (e:\markqiu\work\zdinv\node_modules\directus\node_modules\rollup\dist\shared\rollup.js:206:30)
              at ModuleLoader.handleInvalidResolvedId (e:\markqiu\work\zdinv\node_modules\directus\node_modules\rollup\dist\shared\rollup.js:23262:24)
              at e:\markqiu\work\zdinv\node_modules\directus\node_modules\rollup\dist\shared\rollup.js:23225:26
      "code": "UNRESOLVED_IMPORT",
      "exporter": "./e:/markqiu/work/zdinv/node_modules/directus-extension-schema-management-module/dist/index.js",
      "id": "\u0000virtual:entry",
      "watchFiles": [
        "\u0000virtual:entry"
      ]
    }
[09:03:29] INFO (18412 on LAPTOP-JIO12MPN): Loaded extensions: directus-extension-schema-management-module
[09:03:29] WARN (18412 on LAPTOP-JIO12MPN): PUBLIC_URL should be a full URL
[09:03:30] WARN (18412 on LAPTOP-JIO12MPN): PostGIS isn't installed. Geometry type support will be limited.
[09:03:31] INFO (18412 on LAPTOP-JIO12MPN): Server started at http://0.0.0.0:8055
```
I did what you suggest but the problem has not been resolved.

**Comment by rijkvanzanten** [comment]
@markqiu can you share a repo that we can run to reproduce?

**Comment by markqiu** [comment]
https://github.com/markqiu/zdinv

@rijkvanzanten 

Thank you very much!

**Comment by br41nslug** [comment]
@markqiu be careful when committing files with credentials like `.env` 😬 
Gave it another try but without luck, at least on the shared repo side there is nothing that should prevent you from running extensions.
Cloned the repo, installed the same plugin from your logs but unfortunately it ran without the same errors you're running into.
![16697](https://user-images.githubusercontent.com/9389634/205603140-d22e6c54-3f69-49e4-b905-77c806d5f4e9.png)

**Comment by markqiu** [comment]
Oh, No, that so wierd!

Thank you for the warning about the .env. It's not at all cause it's only my expirement environment. It's OK.

What's your node's version please? Maybe the problem is in node's version, so I want to give a try. @br41nslug

**Comment by br41nslug** [comment]
im running node v18 currently but i did those tests on v16 last week

**Comment by markqiu** [comment]
I tested v16 with no luck.

Anyway, I've gived up, now I changed to docker environment and it works.

Thank you for all!!!

@br41nslug
