### ISSUE TITLE
Invalid argument supplied for foreach when accessing table entry

### ISSUE THREAD

**Issue by valgussev** [directus/directus#1670]
## Version Info
  - Directus version and branch: 6.4.0-20170708214029
  - PHP version: 5.6
  - MySQL version: 5.7.13
  - Web server: (Ex. Apache, nginx or IIS?) nginx
  - OS name and version: Mac Os X El Capitan

## Expected Behavior
After creating default table the Table page should show entries.

## Actual Behavior
```
ERROR - 2017-07-09T10:39:11-04:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php:1752
Stack trace:
#0 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(1752): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/Volumes/Macint...', 1752, Array)
#1 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(816): Directus\Database\TableGateway\RelationalTableGateway->countByStatus()
#2 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(795): Directus\Database\TableGateway\RelationalTableGateway->createEntriesMetadata(Array, Object(Directus\Database\Object\Table))
#3 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(780): Directus\Database\TableGateway\RelationalTableGateway->createMetadata(Array, false)
#4 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(772): Directus\Database\TableGateway\RelationalTableGateway->loadMetadata(Array, false)
#5 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(757): Directus\Database\TableGateway\RelationalTableGateway->getItems(Array)
#6 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/routes/A1/Entries.php(44): Directus\Database\TableGateway\RelationalTableGateway->getEntries(Array)
#7 [internal function]: Directus\API\Routes\A1\Entries->rows('testing')
#8 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#9 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#10 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#13 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#14 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#15 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/api/api.php(547): Directus\Application\Application->run()
#16 {main}

```

## Steps to Reproduce
Empty instalation with default table

## Logs or Screenshots
![screen shot 2017-07-09 at 17 39 48](https://user-images.githubusercontent.com/1596020/27994838-06703dbc-64ce-11e7-98d5-6247b735a1c2.png)

**Comment by WellingGuzman** [comment]
Hey @valgussev thanks for reporting this,

How did you install Directus?
How did you create the `testing` table?
Did you update the global status mapping in `api/configuration.php`?
Did you update the table status mapping?

**Comment by valgussev** [comment]
Hi @WellingGuzman ,

1. I've tried on both build and src 6.4.0 versions. The only difference in installation is a composer run.
- download
- unpack
- cp api/config_sample.php api/config.php with only username/password change
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- mysql -h localhost -p -u root directus < api/schema.sql

I've also tried to install Directus using the GUI, but received 404 Not found error after index.php redirect to build-6.4.0-20170708214032/installation/inidex.php page

2. By clicking create "Admin setting" -> "Tables & Inputs" -> "Manage" -> "+" -> Then entered a name and go into created page through the left sidebar menu

3. nope

4. nope

**Comment by WellingGuzman** [comment]
Hey @valgussev, so are you missing `api/configuration.php` file in `api/` directory?

**Comment by valgussev** [comment]
Yes, it seems adding the file has fixed the error but only if to go first through the root link and then point to /tables/test . But if to reload the page with the link /tables/test the following error occures:

```
ERROR - 2017-07-09T13:41:39-04:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/index.php:342
Stack trace:
#0 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/index.php(342): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/Volumes/Macint...', 342, Array)
#1 [internal function]: {closure}(Array)
#2 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/index.php(352): array_map(Object(Closure), Array)
#3 /Volumes/Macintosh HD/Downloads/directus-build-6.4.0-20170708214032/index.php(606): getGroups()
#4 {main}
```

**Comment by WellingGuzman** [comment]
Thanks @valgussev,

Did you add navigation override to your group? can you share the group record information in `directus_groups`?

**Comment by valgussev** [comment]
@WellingGuzman , nope, why?

The group record information below:
```
mysql> select * from directus_groups;
+----+---------------+-------------------------------------------------------------------------------+--------------------------+--------------+---------------+---------------+------------+------------+
| id | name          | description                                                                   | restrict_to_ip_whitelist | nav_override | show_activity | show_messages | show_users | show_files |
+----+---------------+-------------------------------------------------------------------------------+--------------------------+--------------+---------------+---------------+------------+------------+
|  1 | Administrator | Admins have access to all managed data within the system by default           | NULL                     | NULL         |             1 |             1 |          1 |          1 |
|  2 | Public        | This sets the data that is publicly available through the API without a token | NULL                     | NULL         |             1 |             1 |          1 |          1 |
+----+---------------+-------------------------------------------------------------------------------+--------------------------+--------------+---------------+---------------+------------+------------+
2 rows in set (0.00 sec)

```

**Comment by valgussev** [comment]
BTW seems all the links besides root resolve in an error above on page reload

**Comment by WellingGuzman** [comment]
Odd, can you update to the latest build? I fixed two error in the building script, and see if those fixes that problem.

**Comment by valgussev** [comment]
That helps, thank you.

Furthermore, if to create table testing with the following fields:
```
mysql> describe testing;
+--------+------------------+------+-----+---------+----------------+
| Field  | Type             | Null | Key | Default | Extra          |
+--------+------------------+------+-----+---------+----------------+
| id     | int(11)          | NO   | PRI | NULL    | auto_increment |
| status | int(11)          | NO   |     | 2       |                |
| sort   | int(10) unsigned | NO   |     | NULL    |                |
| text   | text             | YES  |     | NULL    |                |
+--------+------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```
On record create (http://localhost:8080/tables/testing/new) I receive:
```
Next exception 'RuntimeException' with message 'This query failed: INSERT INTO `testing` (`text`) VALUES ('TEST TEST')' in /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php:759
Stack trace:
#0 /Volumes/Macintosh HD/Downloads/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#1 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(366): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#2 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(134): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#3 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Services/EntriesService.php(32): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('testing', Array, 1)
#4 /Volumes/Macintosh HD/Downloads/directus/api/routes/A1/Entries.php(26): Directus\Services\EntriesService->createEntry('testing', Array, Array)
#5 [internal function]: Directus\API\Routes\A1\Entries->rows('testing')
#6 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#7 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#11 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#12 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#13 /Volumes/Macintosh HD/Downloads/directus/api/api.php(547): Directus\Application\Application->run()
#14 {main}

```
If to run mentioned query directly through mysql I receive:
```
mysql> INSERT INTO `testing` (`text`) VALUES ('TEST TEST');
ERROR 1364 (HY000): Field 'sort' doesn't have a default value
```
If to remove the sort column from the testing table and insert record:
```
Next exception 'RuntimeException' with message 'This query failed: SELECT `testing`.`id` AS `id`, `testing`.`status` AS `status`, `testing`.`text` AS `text` FROM `testing` WHERE `testing`.`status` IN ('1', '2') ORDER BY `sort` ASC LIMIT 200 OFFSET 0' in /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php:700
Stack trace:
#0 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(659): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array)
#1 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(879): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#2 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(769): Directus\Database\TableGateway\RelationalTableGateway->loadItems(Array)
#3 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(757): Directus\Database\TableGateway\RelationalTableGateway->getItems(Array)
#4 /Volumes/Macintosh HD/Downloads/directus/api/routes/A1/Entries.php(44): Directus\Database\TableGateway\RelationalTableGateway->getEntries(Array)
#5 [internal function]: Directus\API\Routes\A1\Entries->rows('testing')
#6 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#7 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#11 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#12 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#13 /Volumes/Macintosh HD/Downloads/directus/api/api.php(547): Directus\Application\Application->run()
#14 {main}

```

I can close this issue and open another one if you wish.

**Comment by WellingGuzman** [comment]
Thanks for all these information, creating another ticket won't be necessary unless this get bigger than I expect.

How did you delete the `sort` column? it seems Directus still getting the `sort` column information and using to `sort` the values.

**Comment by valgussev** [comment]
@WellingGuzman , I've deleted the 'sort' column through the web interface, right after click on http://localhost:8080/tables/testing I'm getting an error in the right corner:
```
Server Error
`This query failed: SELECT `testing`.`id` AS `id`, `testing`.`status` AS `status`, `testing`.`text` AS `text` FROM `testing` WHERE `testing`.`status` IN ('1', '2') ORDER BY `sort` ASC LIMIT 200 OFFSET 0`
```
the table now is looking like this:
```
mysql> describe testing;
+--------+---------+------+-----+---------+----------------+
| Field  | Type    | Null | Key | Default | Extra          |
+--------+---------+------+-----+---------+----------------+
| id     | int(11) | NO   | PRI | NULL    | auto_increment |
| status | int(11) | NO   |     | 2       |                |
| text   | text    | YES  |     | NULL    |                |
+--------+---------+------+-----+---------+----------------+
3 rows in set (0.00 sec)
```

**Comment by WellingGuzman** [comment]
Hey @valgussev, going to `directus_preferences` and update the `sort` column for `testing` table to `id` would this fixes? if it does, I will work on a fix for a non-existing column name as sorting column.

**Comment by valgussev** [comment]
@WellingGuzman , yes, the update is fixing the select issue, but not the insert issue with empty sort column, i.e.
```
Next exception 'RuntimeException' with message 'This query failed: INSERT INTO `testing` (`text`) VALUES ('TEST TEST')' in /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php:759
Stack trace:
#0 /Volumes/Macintosh HD/Downloads/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#1 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(366): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#2 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(134): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#3 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Services/EntriesService.php(32): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('testing', Array, 1)
#4 /Volumes/Macintosh HD/Downloads/directus/api/routes/A1/Entries.php(26): Directus\Services\EntriesService->createEntry('testing', Array, Array)
#5 [internal function]: Directus\API\Routes\A1\Entries->rows('testing')
#6 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#7 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#11 /Volumes/Macintosh HD/Downloads/directus/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#12 /Volumes/Macintosh HD/Downloads/directus/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#13 /Volumes/Macintosh HD/Downloads/directus/api/api.php(547): Directus\Application\Application->run()
#14 {main}

```
```
mysql> select * from directus_preferences where table_name = 'testing';
+----+------+------------+-------+-----------------+------+------------+--------+---------------+------------------------------------------+
| id | user | table_name | title | columns_visible | sort | sort_order | status | search_string | list_view_options                        |
+----+------+------------+-------+-----------------+------+------------+--------+---------------+------------------------------------------+
| 13 |    1 | testing    | NULL  | text            | id   | ASC        | 1,2    | NULL          | {"spacing":"cozy","currentView":"table"} |
+----+------+------------+-------+-----------------+------+------------+--------+---------------+------------------------------------------+
1 row in set (0.00 sec)

mysql> describe testing;
+--------+------------------+------+-----+---------+----------------+
| Field  | Type             | Null | Key | Default | Extra          |
+--------+------------------+------+-----+---------+----------------+
| id     | int(11)          | NO   | PRI | NULL    | auto_increment |
| status | int(11)          | NO   |     | 2       |                |
| sort   | int(10) unsigned | NO   |     | NULL    |                |
| text   | text             | YES  |     | NULL    |                |
+--------+------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

**Comment by valgussev** [comment]
Furthermore,

When I'm trying to upload an image to the table column, for the following request
```
POST http://localhost:8080/api/1.1/tables/testing/rows
{
  "image": {
    "name": "imgpsh_fullsize.png",
    "title": "imgpsh fullsize",
    "size": 634412,
    "type": "image/png",
    "charset": "binary",
    "data": "data:image/png;base64,iVBOR...",
    "width": 2880,
    "height": 1800
  }
}
```
I receive 404 Not Found
(data field value was cut by me for the comment characters limit purpose)

```
mysql> describe testing;
+--------+---------+------+-----+---------+----------------+
| Field  | Type    | Null | Key | Default | Extra          |
+--------+---------+------+-----+---------+----------------+
| id     | int(11) | NO   | PRI | NULL    | auto_increment |
| status | int(11) | NO   |     | 2       |                |
| text   | text    | YES  |     | NULL    |                |
| file   | int(11) | YES  |     | NULL    |                |
+--------+---------+------+-----+---------+----------------+
4 rows in set (0.01 sec)
```

**Comment by WellingGuzman** [comment]
Hey @valgussev,

can you share your logs in `api/logs`? does your http server user has write permission to `storage/*`?

**Comment by valgussev** [comment]
you will find log file attached
[2017-07-10.log.tar.gz](https://github.com/directus/directus/files/1136547/2017-07-10.log.tar.gz)

yes, write permissions are 755 for the http server user
drwxr-xr-x    3 valgussev  staff      102 Jul  9 21:49 storage

attached is the nginx.conf file
[nginx.conf.tar.gz](https://github.com/directus/directus/files/1136553/nginx.conf.tar.gz)

**Comment by WellingGuzman** [comment]
Hey @valgussev,

I didn't any issues in the configuration or logs. Getting a 404 page seems to be more related to nginx or our server routing.

Are you using MAMP? If you try creating the same item without trying to upload a file, does it work? 

`GET http://localhost:8080/api/1.1/tables/testing/rows` works?

**Comment by valgussev** [comment]
If I understood correctly what MAMP is, no I installed packages separately using homebrew. Without file uploading no error occurs and item is placed into table correctly.

**Comment by WellingGuzman** [comment]
MAMP is a software (stack: MacOS, Apache+Nginx, MySQL, PHP).

How are you trying to upload the files, via WebApp, SDK or Terminal?

**Comment by valgussev** [comment]
I've been trying to upload using WebApp. Since the file to upload has been transformed into base64 form correctly it seems there is no problem with upload itself, but with the POST request.

**Comment by WellingGuzman** [comment]
I really can't tell what's going on, what's the output of the 404 page? Is Directus or any other service throwing the 404?

**Comment by WellingGuzman** [comment]
Also on what's stack is Directus running in your server?

**Comment by valgussev** [comment]
That is a standard nginx 404 page
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```
There is also nothing interesting in headers
Response headers:
```
HTTP/1.1 404 Not Found
Server: nginx/1.8.0
Date: Mon, 10 Jul 2017 20:32:48 GMT
Content-Type: text/html
Content-Length: 570
Connection: close
```

Request headers:
```
POST /api/1.1/tables/test/rows HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 506808
Pragma: no-cache
Cache-Control: no-cache
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Content-Type: application/json
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Referer: http://localhost:8080/tables/test/new
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: PHPSESSID=4sfbh97ueb84rn9n3abemrvpb1
X-Compress: null
```

You can find my stack in the issue description.

**Comment by WellingGuzman** [comment]
Just making sure, you install each package independently yourself or used some popular stack or something.

I believe there's something on your NGINX configuration or setup, because it's not even getting into Directus.

I will try to replicate this myself on our servers and see what we can get from it.

If you have any information that can helps us reproduce this issue is greatly appreciated.

**Comment by valgussev** [comment]
nope, every package have been installed separately using homebrew. On this weekend I will try to reinstall the stack if that helps I will let you know.

**Comment by WellingGuzman** [comment]
Which nginx version are you using? we recently had an issue, with Apache, that on PATCH throws an 403 error by some apache modules installed. So I'm thinking this could be happening here, because it is not even hitting Directus, but as GET works, I suppose this is a NGINX level issue, and not related to nginx locations.

**Comment by valgussev** [comment]
That was nginx/1.8.0 and I've updated it to the latest 1.12.0, but unfortunately still the same error

**Comment by WellingGuzman** [comment]
hey @valgussev, have you try uploading a small file?

**Comment by valgussev** [comment]
That is an interesting guess. I can successfully upload and insert files up to smth about 10kb. 

I've looked into corresponding configuration parameters, but all of them looks right.
php.ini:
```
upload_max_filesize = 2M
post_max_size = 8M
```

nginx.conf
`client_max_body_size 100m;`

Am I missing something?

**Comment by WellingGuzman** [comment]
Yeah, this is something to do with this, maybe the "post data" is bigger than 8MB, so you get to about 10KB free for uploading.

Try to increase it to the values in php.ini to something like: 
```
upload_max_filesize = 64M
post_max_size = 100M
```

And see if this should solve the problem.

As this are configuration problem from nginx and php, and won't be solve within Directus I will close this, unless there's a related issues.

**Comment by benhaynes** [comment]
Let's add a quick note in the FAQ section of the docs about this – then we can close it. Later, we can organize all these into the knowledgebase.

**Comment by valgussev** [comment]
Hm, I still get the same issue on the same file sizes with the suggested configuration:
```
valgussev$ grep _max_ /usr/local/etc/php/5.6/php.ini
log_errors_max_len = 1024
post_max_size = 100M
upload_max_filesize = 64M
```
```
valgussev$ brew services restart php56
Stopping `php56`... (might take a while)
==> Successfully stopped `php56` (label: homebrew.mxcl.php56)
==> Successfully started `php56` (label: homebrew.mxcl.php56)
```

`404 Not Found`

**Comment by WellingGuzman** [comment]
Hey @valgussev, can you increase the php `memory_limit` value to at least the `post_max_size` value? I see if still happening.

**Comment by valgussev** [comment]
@WellingGuzman , memory_limit is already 128M while post_max_size is 100M

**Comment by WellingGuzman** [comment]
Someone reported a similar issue last night, but it was giving him 502 instead of 404, and also on NGINX.

I couldn't have being able to reproduce it. what about `upload_max_filesize`?

can it be possible to teach us how you installed your environment, we haven't had any luck with our servers.

**Comment by valgussev** [comment]
Hi @WellingGuzman , there is actually not much to tell about my configuration - mysql, nginx and php all have been installed using homebrew package manager for mac os. Here are my php.ini and nginx.conf files. upload_max_filesize is set to 64M. Here are versions:
php - 5.5.36
mysql - 5.7.13
nginx - 1.12.0

[cfg.tar.gz](https://github.com/directus/directus/files/1166442/cfg.tar.gz)

**Comment by benhaynes** [comment]
Hey @rijkvanzanten – let's add this as a FAQ item in the new marketing site, then we can close this one I think.
