### ISSUE TITLE
Collection export limit 0 leads to request that throws 500 Internal Server Error

### ISSUE THREAD

**Issue by viters** [directus/directus#16719]
### Describe the Bug

Exporting `0` items throws 500 Internal server error.

![image](https://user-images.githubusercontent.com/13100466/205649848-693c8f81-6c26-4471-a0d3-e8ce02c33588.png)

### To Reproduce

1. Go to any collection
2. Set `0` as limit and leave other stuff with default values
3. See error 500 in logs

### Errors Shown

```json
{
  "level":50,
  "time":1670247237915,
  "pid":18,
  "hostname":"8d68feca5546",
  "err":{
    "type":"Error",
    "message":"Data should not be empty or the \"fields\" option should be included",
    "stack":"Error: Data should not be empty or the \"fields\" option should be included\n    at JSON2CSVParser.preprocessData (/directus/node_modules/json2csv/lib/JSON2CSVParser.js:57:13)\n    at JSON2CSVParser.parse (/directus/node_modules/json2csv/lib/JSON2CSVParser.js:20:32)\n    at ExportService.transform (/directus/node_modules/directus/dist/services/import-export.js:272:33)\n    at /directus/node_modules/directus/dist/middleware/respond.js:72:55\n    at /directus/node_modules/directus/dist/utils/async-handler.js:3:66\n    at Layer.handle [as handle_request] (/directus/node_modules/express/lib/router/layer.js:95:5)\n    at next (/directus/node_modules/express/lib/router/route.js:144:13)\n    at /directus/node_modules/directus/dist/controllers/items.js:77:12\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  },
  "msg":"Data should not be empty or the \"fields\" option should be included"
}
```

```json
{
  "level": 30,
  "time": 1670247237916,
  "pid": 18,
  "hostname": "8d68feca5546",
  "req": {
    "id": 72,
    "method": "GET",
    "url": "/items/leads?access_token=--redacted--&export=csv&sort=id&fields%5B%5D=date_created&fields%5B%5D=date_updated&fields%5B%5D=type&fields%5B%5D=payload&limit=0",
    "query": {
      "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0M2E4ODI2LWEwNWQtNDljMi1hOWZlLTg4ZGM3YjEwNDI2ZiIsInJvbGUiOiIyYzFhYmYyYy04OGUxLTQxZTMtYTAwMS00ZDVkZjY0NzM3Y2EiLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOnRydWUsImlhdCI6MTY3MDI0NjQyMiwiZXhwIjoxNjcwMjQ3MzIyLCJpc3MiOiJkaXJlY3R1cyJ9.XCJ4v1nkeJKDrQ_YH-qjhOwCClWJbquN-BzuzAawouo",
      "export": "csv",
      "sort": "id",
      "fields": ["date_created", "date_updated", "type", "payload"],
      "limit": "0"
    },
    "params": {},
    "headers": {
      // redacted
    }
  },
  "res": {
    "statusCode": 500,
    "headers": {
      "content-security-policy": "script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      "x-powered-by": "Directus",
      "vary": "Origin, Cache-Control",
      "access-control-allow-credentials": "true",
      "access-control-expose-headers": "Content-Range",
      "cache-control": "no-cache",
      "content-type": "text/csv; charset=utf-8",
      "content-disposition": "attachment; filename=\"leads 20221205-133357.csv\"",
      "content-length": "141",
      "etag": "W/\"8d-UpJRA3haAhWTgYTyBPu8RHaaAVs\""
    }
  },
  "err": {
    "type": "Error",
    "message": "failed with status code 500",
    "stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/directus/node_modules/pino-http/logger.js:113:40)\n    at ServerResponse.emit (node:events:525:35)\n    at onFinish (node:_http_outgoing:950:10)\n    at callback (node:internal/streams/writable:554:21)\n    at afterWrite (node:internal/streams/writable:499:5)\n    at afterWriteTick (node:internal/streams/writable:486:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"
  },
  "responseTime": 61,
  "msg": "request errored"
}
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

N/A

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
To export ALL items you'll want to use `-1` instead of `0` but using `0` should definitely not result in this error.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-118](https://linear.app/directus/issue/ENG-118/collection-export-limit-0-leads-to-request-that-throws-500-internal)
