### ISSUE TITLE
Files storage not work in Alibaba OSS service via s3

### ISSUE THREAD

**Issue by kroawen** [directus/directus#16882]
### Describe the Bug

I use Alibaba OSS for files storage, in 9.21.2, it work fine,  .env config:

![image](https://user-images.githubusercontent.com/6927999/209080642-f887a0cb-e309-4496-b009-fc1a2f7960cb.png)

but update to 9.22.1, it not work. then I changed config to：

![image](https://user-images.githubusercontent.com/6927999/209080601-19f2a56c-f2c4-44dc-ace3-c6b4384c01b2.png)

it can upload files , but can not remove it from OSS only remove from collection. Will get error "The specified key does not exist". 

### To Reproduce

Upgrade from 9.21.2 -> 9.22.1

### Errors Shown

![Uploading image.png…]()

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.0

### What database are you using?

MYSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment]
Can you try removing the bucket name from the endpoint? I believe it should be `httes://oss-cn-shenzhen.aliyuncs.com`

**Comment by kroawen** [comment]
> 
I changed endpoint to `https://oss-cn-shenzhen.aliyuncs.com`. Can not upload file:
`[SERVICE_UNAVAILABLE] Couldn't save file 7abeed0e-4839-4dcd-9ddd-605e8ac45072.jpg`.
Only set endpoint to  `https://ABC201.oss-cn-shenzhen.aliyuncs.com` can upload.

**Comment by usman-coe** [comment]
## I confirm this bug
When I update to version 9.22.1, I can't set the endpoint without BUCKET name.
I use digitalocean space

**Comment by silasabbott** [comment]
I have a similar issue with DigitalOcean Spaces. Everything worked just fine in 9.21.2, but updating to 9.22.0 broke uploads with error messages that don't seem relevant. This happens when using the endpoint without my spaces/bucket name at the front (https://nyc3.digitaloceanspaces.com) and putting my spaces name as the BUCKET env variable.

On upload:
<img width="560" alt="Screenshot 2022-12-28 at 12 30 59 AM" src="https://user-images.githubusercontent.com/8752644/209783123-6c987da5-647d-496e-8469-b0272eacdbb7.png">

On deletion (after upload failed and nothing was uploaded to my space):
<img width="561" alt="Screenshot 2022-12-28 at 12 31 27 AM" src="https://user-images.githubusercontent.com/8752644/209783104-06b9b917-14d6-4209-9fb7-223e2604d69a.png">

**Comment by sharkfin009** [comment]
some errors as above , but i am trying to use cloudinary as described in the docs

**Comment by vanling** [comment]
Same is happening here, below config with bucket in the endpoint was te only way i could upload anything.
This results in an extra unwanted folder like this  `bucketname-directus-storage.s3.amazonaws.com/bucketname-directus-storage/something.domain.net`
```
STORAGE_LOCATIONS="amazon,local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

STORAGE_AMAZON_DRIVER="s3"
STORAGE_AMAZON_KEY="*******"
STORAGE_AMAZON_SECRET="**********"
STORAGE_AMAZON_BUCKET="bucketname-directus-storage/"
STORAGE_AMAZON_ROOT="something.domain.net"
STORAGE_AMAZON_REGION="eu-central-1"
STORAGE_AMAZON_ENDPOINT="bucketname-directus-storage.s3.amazonaws.com"
STORAGE_AMAZON_ACL=""
```

```
 "HostId": "****+*****jlk="
      "RequestId": "********H31ADF2F",
      "Key": "bucketname-directus-storage/",
      "Code": "NoSuchKey",
      },
        "totalRetryDelay": 0
        "attempts": 1,
        "extendedRequestId": "****+****jlk=",
        "httpStatusCode": 404,
      "$metadata": {
      "$fault": "client",
      "name": "NoSuchKey",
              at async *****/**** */.*****.net/node_modules/directus/dist/controllers/files.js:250:9
              at async FilesService.deleteMany (*****/**** */.*****.net/node_modules/directus/dist/services/files.js:308:30)
              at async DriverS3.list (file://*****/**** */.*****.net/node_modules/@directus/storage-driver-s3/dist/index.js:127:30)
              at async *****/**** */.*****.net/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
              at async StandardRetryStrategy.retry (*****/**** */.*****.net/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
              at async *****/**** */.*****.net/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
              at async *****/**** */.*****.net/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at deserializeAws_restXmlListObjectsV2CommandError (*****/**** */.*****.net/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5146:51)
              at throwDefaultError (*****/**** */.*****.net/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/*****hy-client/dist-cjs/default-error-handler.js:8:22)
          NoSuchKey: The specified key does not exist.
      "stack":
      "message": "The specified key does not exist.",
      "type": "S3ServiceException",
```

**Comment by narduin** [comment]
I'm having the same issue with `v9.22.1` and an S3 adapter to a local docker minio instance.  
Downgrading directus fixed it.

**Comment by rijkvanzanten** [comment]
@vanling What error did you get without the bucket in the endpoint, or if you omit the endpoint completely? 

I think this is caused by the path style being forced when a custom endpoint is used: 

https://github.com/directus/directus/blob/c6b2d5c4087784aab1f5d56538365003e118f3b6/packages/storage-driver-s3/src/index.ts#L65

**Comment by vanling** [comment]
@rijkvanzanten 
on 9.21.2 i started with. All fine with uploads and deletions.
```
STORAGE_AMAZON_DRIVER="s3"
STORAGE_AMAZON_KEY="***"
STORAGE_AMAZON_SECRET="***"
STORAGE_AMAZON_BUCKET="***-directus-storage"
STORAGE_AMAZON_ROOT="domain.com"
STORAGE_AMAZON_REGION="eu-central-1"
STORAGE_AMAZON_ENDPOINT="s3.amazonaws.com"
```

- Updated one to 9.22.x and all existing files could not be loaded anymore. Quickly reverted back to 9.21.2
- Created a fresh install with same settings _(except other root domain)_ and i got an 301 error telling me to use `bucketname-directus-storage.s3.amazonaws.com` instead of `s3.amazonaws.com`
- After updating the endpoint, uploading works, no more errors
- But now the earlier mentioned error popups up when deleting files, file gets removed from DB, not from s3.

I will try to get the 301 error again in a minute

**Comment by vanling** [comment]
@rijkvanzanten my man! dont know how or why... commented out #STORAGE_AMAZON_ENDPOINT... restarted server and it seems to work upload + delete! 

What is it defaulting to?
