### ISSUE TITLE
Filtering on deeply nested collection inside of "root" collection´s array property results in 403 when the later is empty

### ISSUE THREAD

**Issue by jotatoledo** [directus/directus#16974]
### Describe the Bug

The following SDK function call results in a 403 when the `assessments` property of a `Skill` item is empty.
When at least 1 item is there, the call works as expected. 

**Note: the authenticated user in this case is an administrator**

See the attached .har file for 2 queries where this behavior is displayed (different `department` parameter in the function calls)
I also attached a types file exported with [this extension](https://github.com/maltejur/directus-extension-generate-types)

```typescript
queryEmployeeSkills: (
    organization: number,
    filter: {
      department: number;
      roles: number[];
    }
  ) => {
      const departmentSkills = await client
        .items('Department')
        .readOne(department, {
          // TODO: fix typing
          fields: [
            // @ts-expect-error
            'skills.skill.*',
            // @ts-expect-error
            'skills.skill.assessments.level',
            // @ts-expect-error
            'skills.skill.assessments.assessment_in.*',
            // NOTE: avoid receiver.* in order to not fetch sensitive data
            // @ts-expect-error
            'skills.skill.assessments.receiver.id',
            // @ts-expect-error
            'skills.skill.assessments.receiver.email',
            // @ts-expect-error
            'skills.skill.assessments.receiver.first_name',
            // @ts-expect-error
            'skills.skill.assessments.receiver.last_name',
          ],
          filter: {
            skills: {
              skill: {
                assessments: {
                  receiver: {
                    organization: {
                      id: {
                        _eq: organization,
                      },
                    },
                  },
                },
              },
            },
          },
        })
        .then((r) => r?.skills as unknown as DepartmentSkill[])
        .then((skills) => skills.map<Skill>((s) => s.skill));
}
```

[bug.zip](https://github.com/directus/directus/files/10327274/bug.zip)

### To Reproduce

Recreate the schema, seed some data and run the SDK call

### Errors Shown

Following console output from the running directus instance with `LOG_LEVEL=trace`:

Success call:

```txt
2022-12-31T12:04:36.682299575Z [12:04:36.056] TRACE: [3.312ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [c40f5015-39f6-48b5-b714-9cf9b0b75e7c, 1]
2022-12-31T12:04:36.683283782Z [12:04:36.080] TRACE: [4.882ms] select "Department"."id" from "Department" inner join (select distinct "Department"."id", "Department"."id" as "sort_otcir" from "Department" left join "DepartmentSkill" as "oarlr" on "Department"."id" = "oarlr"."department" left join "Skill" as "enqah" on "oarlr"."skill" = "enqah"."id" left join "SkillAssessment" as "ffqrn" on "enqah"."id" = "ffqrn"."assessment_in" left join "directus_users" as "sciho" on "ffqrn"."receiver" = "sciho"."id" left join "Organization" as "ohzrj" on "sciho"."organization" = "ohzrj"."id" where "ohzrj"."id" = $1 and "Department"."id" = $2 limit $3) as "inner" on "Department"."id" = "inner"."id" order by "inner"."sort_otcir" asc [3, 6, 100]
2022-12-31T12:04:36.684104087Z [12:04:36.092] TRACE: [5.438ms] select "DepartmentSkill"."skill", "DepartmentSkill"."department", "DepartmentSkill"."id" from "DepartmentSkill" where "DepartmentSkill"."department" in ($1) order by "DepartmentSkill"."id" asc limit $2 [6, 25000]
2022-12-31T12:04:36.684912792Z [12:04:36.096] TRACE: [2.918ms] select "Skill"."id", "Skill"."status", "Skill"."user_created", "Skill"."date_created", "Skill"."user_updated", "Skill"."date_updated", "Skill"."name" from "Skill" where "Skill"."id" in ($1, $2, $3, $4, $5, $6) [3, 4, 6, 9, 12, 13]
2022-12-31T12:04:36.686462302Z [12:04:36.102] TRACE: [4.187ms] select "DepartmentSkill"."skill", "DepartmentSkill"."id" from "DepartmentSkill" where "DepartmentSkill"."skill" in ($1, $2, $3, $4, $5, $6) order by "DepartmentSkill"."id" asc limit $7 [3, 4, 6, 9, 12, 13, 25000]
2022-12-31T12:04:36.686484002Z [12:04:36.107] TRACE: [3.714ms] select "SkillAssessment"."level", "SkillAssessment"."assessment_in", "SkillAssessment"."receiver", "SkillAssessment"."id" from "SkillAssessment" where "SkillAssessment"."assessment_in" in ($1, $2, $3, $4, $5, $6) order by "SkillAssessment"."id" asc limit $7 [3, 4, 6, 9, 12, 13, 25000]
2022-12-31T12:04:36.686593603Z [12:04:36.110] TRACE: [2.741ms] select "Skill"."id", "Skill"."status", "Skill"."user_created", "Skill"."date_created", "Skill"."user_updated", "Skill"."date_updated", "Skill"."name" from "Skill" where "Skill"."id" in ($1, $2) [3, 4]
2022-12-31T12:04:36.686605603Z [12:04:36.115] TRACE: [2.873ms] select "DepartmentSkill"."skill", "DepartmentSkill"."id" from "DepartmentSkill" where "DepartmentSkill"."skill" in ($1, $2) order by "DepartmentSkill"."id" asc limit $3 [3, 4, 25000]
2022-12-31T12:04:36.689056219Z [12:04:36.119] TRACE: [3.466ms] select "SkillAssessment"."assessment_in", "SkillAssessment"."id" from "SkillAssessment" where "SkillAssessment"."assessment_in" in ($1, $2) order by "SkillAssessment"."id" asc limit $3 [3, 4, 25000]
2022-12-31T12:04:36.689071919Z [12:04:36.123] TRACE: [3.030ms] select "directus_users"."id", "directus_users"."email", "directus_users"."first_name", "directus_users"."last_name" from "directus_users" where "directus_users"."id" in ($1) [f8bf10d2-522a-4bd1-876e-0e43dde2d972]
2022-12-31T12:04:36.748681808Z [12:04:36] GET /items/Department/6?fields[]=skills.skill.*&fields[]=skills.skill.assessments.level&fields[]=skills.skill.assessments.assessment_in.*&fields[]=skills.skill.assessments.receiver.id&fields[]=skills.skill.assessments.receiver.email&fields[]=skills.skill.assessments.receiver.first_name&fields[]=skills.skill.assessments.receiver.last_name&filter=%7B%22skills%22:%7B%22skill%22:%7B%22assessments%22:%7B%22receiver%22:%7B%22organization%22:%7B%22id%22:%7B%22_eq%22:3%7D%7D%7D%7D%7D%7D%7D 304 85ms
```

403 call:
```txt
2022-12-31T12:05:40.977210995Z [12:05:40.338] TRACE: [3.730ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [c40f5015-39f6-48b5-b714-9cf9b0b75e7c, 1]
2022-12-31T12:05:40.977259496Z [12:05:40.353] TRACE: [4.974ms] select "Department"."id" from "Department" inner join (select distinct "Department"."id", "Department"."id" as "sort_uibmd" from "Department" left join "DepartmentSkill" as "flizy" on "Department"."id" = "flizy"."department" left join "Skill" as "aneld" on "flizy"."skill" = "aneld"."id" left join "SkillAssessment" as "vlbyo" on "aneld"."id" = "vlbyo"."assessment_in" left join "directus_users" as "kwfoo" on "vlbyo"."receiver" = "kwfoo"."id" left join "Organization" as "vagza" on "kwfoo"."organization" = "vagza"."id" where "vagza"."id" = $1 and "Department"."id" = $2 limit $3) as "inner" on "Department"."id" = "inner"."id" order by "inner"."sort_uibmd" asc [3, 7, 100]
2022-12-31T12:05:40.977271696Z [12:05:40.353] DEBUG: You don't have permission to access this.
2022-12-31T12:05:40.977276096Z     err: {
2022-12-31T12:05:40.977302196Z       "type": "ForbiddenException",
2022-12-31T12:05:40.977306296Z       "message": "You don't have permission to access this.",
2022-12-31T12:05:40.977309996Z       "stack":
2022-12-31T12:05:40.977313496Z           Error: You don't have permission to access this.
2022-12-31T12:05:40.977316996Z               at ItemsService.readOne (/directus/node_modules/directus/dist/services/items.js:307:19)
2022-12-31T12:05:40.977320396Z               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-31T12:05:40.977323896Z               at async /directus/node_modules/directus/dist/controllers/items.js:88:20
2022-12-31T12:05:40.977327296Z       "status": 403,
2022-12-31T12:05:40.977330796Z       "code": "FORBIDDEN",
2022-12-31T12:05:40.977334296Z       "extensions": {}
2022-12-31T12:05:40.977337796Z     }
2022-12-31T12:05:41.053806961Z [12:05:40] GET /items/Department/7?fields[]=skills.skill.*&fields[]=skills.skill.assessments.level&fields[]=skills.skill.assessments.assessment_in.*&fields[]=skills.skill.assessments.receiver.id&fields[]=skills.skill.assessments.receiver.email&fields[]=skills.skill.assessments.receiver.first_name&fields[]=skills.skill.assessments.receiver.last_name&filter=%7B%22skills%22:%7B%22skill%22:%7B%22assessments%22:%7B%22receiver%22:%7B%22organization%22:%7B%22id%22:%7B%22_eq%22:3%7D%7D%7D%7D%7D%7D%7D 403 50ms
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 14.5

### What browser are you using?

MS Edge

### How are you deploying Directus?

docker in azure app service

**Comment by jotatoledo** [comment]
I was able to get around the issue by reworking this into a GraphQL query:

```typescript
const query = `
query OverviewPage($organization: GraphQLStringOrFloat!, $department: ID!) {
  department: Department_by_id(id: $department) {
    id
    name
    skills {
      skill {
        id
        name
        assessments(filter: {receiver: {organization: {id: {_eq: $organization}}}}) {
          id
          evaluator {
            id
            email
          }
          receiver {
            id
            email
            first_name
            last_name
          }
          level
        }
      }
    }
  }
}`;

export type OverviewPageQueryResult = {
  department: Pick<Department, 'id' | 'name'> & {
    skills: Array<{
      skill: Pick<Skill, 'id' | 'name'> & {
        assessments: Array<
          Pick<SkillAssessment, 'id' | 'level'> & {
            evaluator: Pick<DirectusUsers, 'id'>;
            receiver: Pick<
              DirectusUsers,
              'id' | 'email' | 'first_name' | 'last_name'
            >;
          }
        >;
      };
    }>;
  };
};

export async function queryOverviewPage(
  organization: number,
  department: number
): Promise<OverviewPageQueryResult> {
  const data = await client.graphql
    .items<OverviewPageQueryResult>(query, {
      organization,
      department,
    })
    .then((r) => r.data);
  return data!;
}
```

**Comment by ComfortablyCoding** [comment]
This does not look to be reproducible any longer, as such I'll go ahead and close this. Happy to reopen if it can still be reproduced on the latest version
