### ISSUE TITLE
Apply snapshot gives error

### ISSUE THREAD

**Issue by falko100** [directus/directus#17244]
### Describe the Bug

I make an export using: `npx directus schema snapshot ./snapshot.yaml`
I download this and add it to my project in a folder called database.
Then I run: `npx directus schema apply ./database/snapshot.yaml --yes`
And get the error:

```
    err: {
      "type": "InvalidPayloadException",
      "message": "Field \"supplier\" doesn't exist in collection \"factory_order_products\"",
      "stack":
          Error: Field "supplier" doesn't exist in collection "factory_order_products"
              at RelationsService.createOne (/directus/node_modules/directus/dist/services/relations.js:144:19)
              at /directus/node_modules/directus/dist/utils/apply-snapshot.js:202:44
      "status": 400,
      "code": "INVALID_PAYLOAD",
      "extensions": {}
    }
```

How can I make an export that cannot be imported?

### To Reproduce

It's a bit hard to reproduce this as it possible is an error of our specific configuration

### Errors Shown

```
    err: {
      "type": "InvalidPayloadException",
      "message": "Field \"supplier\" doesn't exist in collection \"factory_order_products\"",
      "stack":
          Error: Field "supplier" doesn't exist in collection "factory_order_products"
              at RelationsService.createOne (/directus/node_modules/directus/dist/services/relations.js:144:19)
              at /directus/node_modules/directus/dist/utils/apply-snapshot.js:202:44
      "status": 400,
      "code": "INVALID_PAYLOAD",
      "extensions": {}
    }
```

### What version of Directus are you using?

On server 9.22.4 and local on docker 9.22.4

### What version of Node.js are you using?

v19.4.0

### What database are you using?

On server Postgres 12 and local SQLite3

### What browser are you using?

n.a.

### How are you deploying Directus?

Server DigitalOcean one-click and Locally Docker

**Comment by rijkvanzanten** [comment]
Does this error happen when you import the snapshot on to an empty installation? Can you share the snapshot, or a minimal reproduction of a snapshot where this happens?

**Comment by falko100** [comment]
I have e-mailed it to the email address on your profile.
Let me know if you need any more information.

**Comment by rijkvanzanten** [comment]
I'm gonna flip this to a Q&A thread for now, as it feels very specific to this particular setup. We'll reopen it if it turns out to be a bug in the application logic 🙂 Thanks for sharing the snapshot!
