### ISSUE TITLE
Axios 1.2.1 has an issue with Brotli

### ISSUE THREAD

**Issue by christianrr** [directus/directus#17316]
### Describe the Bug

Axios has an issue with Brotli and this causes arbitrary errors in requests (https://github.com/axios/axios/issues/5346).
This is mainly happening if Axios is used in extensions, we have not observed any error within the Directus source yet.

However, since this was fixed in 1.2.2 an upgrade of Axios would make sense.

### To Reproduce

Make some Axios requests pointing to other servers

### Errors Shown

```
err: {
      "message": "unexpected end of file: unexpected end of file",
      "name": "Error",
      "stack":
          Error: unexpected end of file
              at AxiosError.from (/var/www/vhosts/app.schloss-eggenberg.at/httpdocs/cms/node_modules/axios/dist/node/axios.cjs:785:14)
              at BrotliDecompress.handleStreamError (/var/www/vhosts/app.schloss-eggenberg.at/httpdocs/cms/node_modules/axios/dist/node/axios.cjs:2696:29)
              at BrotliDecompress.emit (node:events:525:35)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
          caused by: Error: unexpected end of file
              at BrotliDecoder.zlibOnError [as onerror] (node:zlib:189:17)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "method": "post",
        "url": "....",
        "data": "{"
      },
      "code": "Z_BUF_ERROR",
      "status": null
    }
```

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
We're upgrading dependencies on a cadence (see the "patch tuesday" PRs :) ), so I'll close this for now as that's an ongoing process
