### ISSUE TITLE
"Too many requests" on SQLite3, foreign_key_list

### ISSUE THREAD

**Issue by autr** [directus/directus#17418]
### Describe the Bug

This could be the result of recently migrating from Postgres to SQLite3, however I am getting lots of Too many requests errors when navigating the backend UI.

### To Reproduce

Create a Directus instance with SQLite3. 

### Errors Shown

```
[20:36:10.868] TRACE: [0.071ms] PRAGMA table_xinfo(`segment`) []
[20:36:10.868] TRACE: [0.049ms] select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` []
[20:36:10.868] TRACE: [0.214ms] select `id`, `collection`, `field`, `special`, `note`, `validation` from `directus_fields` []
[20:36:10.869] TRACE: [0.064ms] select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` []
[20:36:10.869] TRACE: [0.224ms] select `id`, `collection`, `field`, `special`, `note`, `validation` from `directus_fields` []
[20:36:10.870] TRACE: [0.097ms] select `directus_relations`.`id`, `directus_relations`.`many_collection`, `directus_relations`.`many_field`, `directus_relations`.`one_collection`, `directus_relations`.`one_field`, `directus_relations`.`one_collection_field`, `directus_relations`.`one_allowed_collections`, `directus_relations`.`junction_field`, `directus_relations`.`sort_field`, `directus_relations`.`one_deselect_action` from `directus_relations` order by `directus_relations`.`id` asc []
[20:36:10.870] TRACE: [0.431ms] select `id`, `collection`, `field`, `special`, `note`, `validation` from `directus_fields` []
[20:36:10.871] TRACE: [0.136ms] select `directus_relations`.`id`, `directus_relations`.`many_collection`, `directus_relations`.`many_field`, `directus_relations`.`one_collection`, `directus_relations`.`one_field`, `directus_relations`.`one_collection_field`, `directus_relations`.`one_allowed_collections`, `directus_relations`.`junction_field`, `directus_relations`.`sort_field`, `directus_relations`.`one_deselect_action` from `directus_relations` order by `directus_relations`.`id` asc []
[20:36:10.871] TRACE: [0.265ms] select `name` from `sqlite_master` where type = 'table' AND name NOT LIKE 'sqlite_%' []
[20:36:10.872] TRACE: [0.174ms] select `directus_relations`.`id`, `directus_relations`.`many_collection`, `directus_relations`.`many_field`, `directus_relations`.`one_collection`, `directus_relations`.`one_field`, `directus_relations`.`one_collection_field`, `directus_relations`.`one_allowed_collections`, `directus_relations`.`junction_field`, `directus_relations`.`sort_field`, `directus_relations`.`one_deselect_action` from `directus_relations` order by `directus_relations`.`id` asc []
[20:36:10.872] TRACE: [0.340ms] select `name` from `sqlite_master` where type = 'table' AND name NOT LIKE 'sqlite_%' []
[20:36:10.872] TRACE: [0.253ms] PRAGMA foreign_key_list(`directus_migrations`) []
[20:36:10.873] TRACE: [0.175ms] PRAGMA foreign_key_list(`directus_folders`) []
[20:36:10.873] TRACE: [0.104ms] PRAGMA foreign_key_list(`directus_relations`) []
[20:36:10.873] TRACE: [0.197ms] PRAGMA foreign_key_list(`directus_revisions`) []
[20:36:10.873] TRACE: [0.083ms] PRAGMA foreign_key_list(`directus_dashboards`) []
[20:36:10.873] TRACE: [0.149ms] PRAGMA foreign_key_list(`directus_files`) []
[20:36:10.873] TRACE: [0.059ms] PRAGMA foreign_key_list(`directus_permissions`) []
[20:36:10.873] TRACE: [0.044ms] PRAGMA foreign_key_list(`directus_webhooks`) []
[20:36:10.873] TRACE: [0.041ms] PRAGMA foreign_key_list(`directus_collections`) []
[20:36:10.873] TRACE: [0.027ms] PRAGMA foreign_key_list(`directus_fields`) []
[20:36:10.874] TRACE: [0.104ms] PRAGMA foreign_key_list(`directus_presets`) []
[20:36:10.874] TRACE: [0.041ms] PRAGMA foreign_key_list(`directus_roles`) []
[20:36:10.874] TRACE: [0.181ms] PRAGMA foreign_key_list(`directus_shares`) []
[20:36:10.874] TRACE: [0.124ms] PRAGMA foreign_key_list(`directus_sessions`) []
[20:36:10.874] TRACE: [0.200ms] PRAGMA foreign_key_list(`directus_settings`) []
[20:36:10.874] TRACE: [0.117ms] PRAGMA foreign_key_list(`directus_users`) []
[20:36:10.875] TRACE: [0.080ms] PRAGMA foreign_key_list(`directus_panels`) []
[20:36:10.875] TRACE: [0.061ms] PRAGMA foreign_key_list(`directus_flows`) []
[20:36:10.875] TRACE: [0.098ms] PRAGMA foreign_key_list(`directus_operations`) []
[20:36:10.875] TRACE: [0.049ms] PRAGMA foreign_key_list(`directus_activity`) []
[20:36:10.875] TRACE: [0.063ms] PRAGMA foreign_key_list(`directus_notifications`) []
[20:36:10.875] TRACE: [0.046ms] PRAGMA foreign_key_list(`newsletter`) []
[20:36:10.875] TRACE: [0.043ms] PRAGMA foreign_key_list(`timezone`) []
[20:36:10.875] TRACE: [0.067ms] PRAGMA foreign_key_list(`blog`) []
[20:36:10.875] TRACE: [0.046ms] PRAGMA foreign_key_list(`page`) []
[20:36:10.875] TRACE: [0.027ms] PRAGMA foreign_key_list(`venues`) []
[20:36:10.875] TRACE: [0.041ms] PRAGMA foreign_key_list(`event`) []
[20:36:10.876] TRACE: [0.502ms] PRAGMA foreign_key_list(`segment`) []
[20:36:10.877] TRACE: [0.800ms] select `name` from `sqlite_master` where type = 'table' AND name NOT LIKE 'sqlite_%' []
[20:36:10.877] TRACE: [0.066ms] PRAGMA foreign_key_list(`directus_migrations`) []
[20:36:10.877] TRACE: [0.110ms] PRAGMA foreign_key_list(`directus_folders`) []
[20:36:10.877] TRACE: [0.042ms] PRAGMA foreign_key_list(`directus_relations`) []
[20:36:10.877] TRACE: [0.064ms] PRAGMA foreign_key_list(`directus_revisions`) []
[20:36:10.877] TRACE: [0.049ms] PRAGMA foreign_key_list(`directus_dashboards`) []
[20:36:10.877] TRACE: [0.089ms] PRAGMA foreign_key_list(`directus_files`) []
[20:36:10.877] TRACE: [0.057ms] PRAGMA foreign_key_list(`directus_permissions`) []
[20:36:10.878] TRACE: [0.036ms] PRAGMA foreign_key_list(`directus_webhooks`) []
[20:36:10.878] TRACE: [0.041ms] PRAGMA foreign_key_list(`directus_collections`) []
[20:36:10.878] TRACE: [0.028ms] PRAGMA foreign_key_list(`directus_fields`) []
[20:36:10.878] TRACE: [0.049ms] PRAGMA foreign_key_list(`directus_presets`) []
[20:36:10.878] TRACE: [0.029ms] PRAGMA foreign_key_list(`directus_roles`) []
[20:36:10.878] TRACE: [0.055ms] PRAGMA foreign_key_list(`directus_shares`) []
[20:36:10.878] TRACE: [0.042ms] PRAGMA foreign_key_list(`directus_sessions`) []
[20:36:10.878] TRACE: [0.049ms] PRAGMA foreign_key_list(`directus_settings`) []
[20:36:10.878] TRACE: [0.037ms] PRAGMA foreign_key_list(`directus_users`) []
[20:36:10.878] TRACE: [0.041ms] PRAGMA foreign_key_list(`directus_panels`) []
[20:36:10.878] TRACE: [0.109ms] PRAGMA foreign_key_list(`directus_flows`) []
[20:36:10.878] TRACE: [0.086ms] PRAGMA foreign_key_list(`directus_operations`) []
[20:36:10.878] TRACE: [0.036ms] PRAGMA foreign_key_list(`directus_activity`) []
[20:36:10.878] TRACE: [0.042ms] PRAGMA foreign_key_list(`directus_notifications`) []
[20:36:10.878] TRACE: [0.036ms] PRAGMA foreign_key_list(`newsletter`) []
[20:36:10.878] TRACE: [0.051ms] PRAGMA foreign_key_list(`timezone`) []
[20:36:10.879] TRACE: [0.047ms] PRAGMA foreign_key_list(`blog`) []
[20:36:10.879] TRACE: [0.044ms] PRAGMA foreign_key_list(`page`) []
[20:36:10.879] TRACE: [0.025ms] PRAGMA foreign_key_list(`venues`) []
[20:36:10.879] TRACE: [0.039ms] PRAGMA foreign_key_list(`event`) []
[20:36:10.879] TRACE: [0.047ms] PRAGMA foreign_key_list(`segment`) []
[20:36:10.879] TRACE: [0.375ms] select count(*) as `count` from `event` limit ? [100]
[20:36:10.880] TRACE: [0.653ms] PRAGMA foreign_key_list(`directus_migrations`) []
[20:36:10.880] TRACE: [0.110ms] PRAGMA foreign_key_list(`directus_folders`) []
[20:36:10.880] TRACE: [0.055ms] PRAGMA foreign_key_list(`directus_relations`) []
[20:36:10.880] TRACE: [0.090ms] PRAGMA foreign_key_list(`directus_revisions`) []
[20:36:10.880] TRACE: [0.054ms] PRAGMA foreign_key_list(`directus_dashboards`) []
[20:36:10.881] TRACE: [0.124ms] PRAGMA foreign_key_list(`directus_files`) []
[20:36:10.881] TRACE: [0.045ms] PRAGMA foreign_key_list(`directus_permissions`) []
[20:36:10.881] TRACE: [0.029ms] PRAGMA foreign_key_list(`directus_webhooks`) []
[20:36:10.881] TRACE: [0.066ms] PRAGMA foreign_key_list(`directus_collections`) []
[20:36:10.881] TRACE: [0.042ms] PRAGMA foreign_key_list(`directus_fields`) []
[20:36:10.881] TRACE: [0.054ms] PRAGMA foreign_key_list(`directus_presets`) []
[20:36:10.881] TRACE: [0.031ms] PRAGMA foreign_key_list(`directus_roles`) []
[20:36:10.881] TRACE: [0.057ms] PRAGMA foreign_key_list(`directus_shares`) []
[20:36:10.881] TRACE: [0.049ms] PRAGMA foreign_key_list(`directus_sessions`) []
[20:36:10.881] TRACE: [0.052ms] PRAGMA foreign_key_list(`directus_settings`) []
[20:36:10.881] TRACE: [0.043ms] PRAGMA foreign_key_list(`directus_users`) []
[20:36:10.882] TRACE: [0.222ms] PRAGMA foreign_key_list(`directus_panels`) []
[20:36:10.882] TRACE: [0.102ms] PRAGMA foreign_key_list(`directus_flows`) []
[20:36:10.882] DEBUG: Too many requests, retry after 375ms.
    err: {
      "type": "HitRateLimitException",
      "message": "Too many requests, retry after 375ms.",
      "stack":
          Error: Too many requests, retry after 375ms.
              at /XXXX/node_modules/.pnpm/directus@9.22.4/node_modules/directus/dist/middleware/rate-limiter.js:26:19
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 429,
      "code": "REQUESTS_EXCEEDED",
      "extensions": {
        "limit": 25,
        "reset": "2023-02-06T19:36:11.257Z"
      }
    }
[20:36:10.883] TRACE: [0.893ms] PRAGMA foreign_key_list(`directus_operations`) []
[20:36:10.883] TRACE: [0.075ms] PRAGMA foreign_key_list(`directus_activity`) []
[20:36:10.883] TRACE: [0.139ms] PRAGMA foreign_key_list(`directus_notifications`) []
[20:36:10.883] TRACE: [0.160ms] PRAGMA foreign_key_list(`newsletter`) []
[20:36:10.883] TRACE: [0.123ms] PRAGMA foreign_key_list(`timezone`) []
[20:36:10.884] TRACE: [0.131ms] PRAGMA foreign_key_list(`blog`) []
[20:36:10.884] TRACE: [0.191ms] PRAGMA foreign_key_list(`page`) []
[20:36:10.884] TRACE: [0.058ms] PRAGMA foreign_key_list(`venues`) []
[20:36:10.884] TRACE: [0.110ms] PRAGMA foreign_key_list(`event`) []
[20:36:10.884] TRACE: [0.104ms] PRAGMA foreign_key_list(`segment`) []
[20:36:10.886] DEBUG: Too many requests, retry after 371ms.
    err: {
      "type": "HitRateLimitException",
      "message": "Too many requests, retry after 371ms.",
      "stack":
          Error: Too many requests, retry after 371ms.
              at /XXXX/node_modules/.pnpm/directus@9.22.4/node_modules/directus/dist/middleware/rate-limiter.js:26:19
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 429,
      "code": "REQUESTS_EXCEEDED",
      "extensions": {
        "limit": 25,
        "reset": "2023-02-06T19:36:11.257Z"
      }
    }
[20:36:10.886] TRACE: [2.064ms] select `event`.`status`, `event`.`title`, `event`.`start_datetime`, `event`.`end_datetime`, `event`.`id` from `event` order by `event`.`id` asc limit ? [25]
[20:36:10.889] TRACE: [1.688ms] select count(*) as `count` from `directus_files` left join `directus_folders` as `aangv` on `directus_files`.`folder` = `aangv`.`id` where `aangv`.`id` = ? limit ? [3237ef75-f1eb-4be5-bdaa-3be8bef073f9, 100]
[20:36:11] GET /admin/assets/material-icons-0c67479a.woff2 200 3ms
[20:36:11] GET /admin/assets/Inter-Regular-c342b1b7.woff2 200 3ms
[20:36:11] PATCH /users/me/track/page 429 12ms
[20:36:11.213] DEBUG: Too many requests, retry after 44ms.
    err: {
      "type": "HitRateLimitException",
      "message": "Too many requests, retry after 44ms.",
      "stack":
          Error: Too many requests, retry after 44ms.
              at /XXXX/backend/node_modules/.pnpm/directus@9.22.4/node_modules/directus/dist/middleware/rate-limiter.js:26:19
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 429,
      "code": "REQUESTS_EXCEEDED",
      "extensions": {
        "limit": 25,
        "reset": "2023-02-06T19:36:11.257Z"
      }
    }

```

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.4.2

### What database are you using?

SQLite3

### What browser are you using?

Brave

### How are you deploying Directus?

locally

**Comment by autr** [comment]
Found the RATE_LIMITER 🙄
