### ISSUE TITLE
intermittent 403 response for image requests

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#17447]
### Describe the Bug

I have Cloudinary integrated using the cloudinary storage driver, which is working fine with directus transformations, except when it doesn't , about half the time. 
Something is causing a state where only a plain url without any parameters will work.
Here is my env :

CORS_ENABLED=true
CORS_ORIGIN=true
STORAGE_LOCATIONS=cloudinary
STORAGE_CLOUDINARY_DRIVER=cloudinary
STORAGE_CLOUDINARY_ROOT=
STORAGE_CLOUDINARY_HEALTHCHECK_THRESHOLD=750
STORAGE_CLOUDINARY_CLOUD_NAME=mateas-pics
STORAGE_CLOUDINARY_API_KEY=[key]
STORAGE_CLOUDINARY_API_SECRET=[secret]
STORAGE_CLOUDINARY_ACCESS_MODE=public

As you can see cors is wide open for now, not great but will tighten that up. But there is something else happening and I don't know what.

### To Reproduce

Set up cloudinary acc and configure env as above

### Errors Shown

403 responses

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

18.0.0

### What database are you using?

postgres 13

### What browser are you using?

chrome

### How are you deploying Directus?

railway.app

**Comment by sharkfin009** [comment]
Strange thing is this state seems to come and go at random

**Comment by sharkfin009** [comment]
thanks Rijk, I see logs of just 403s in the railway deploy logs. Where else can I look? sorry for ignarance

**Comment by rijkvanzanten** [comment]
I'm not quite sure how Railway renders the log output (I don't use it myself), but when Directus gets an unexpected error from the storage provider, it should be logged in stdout before the 403 response is sent to the user. Without those logs, there isn't really any way to know what's going wrong here

**Comment by sharkfin009** [comment]
aha ok i set the log style to raw and heres one of the logs:

{"level":30,"time":1675870894342,"pid":44,"hostname":"railway","req":{"id":111,"method":"GET","url":"/assets/73931747-2af0-4b27-b3e9-c25074488635?key=homepage-dt","query":{"key":"homepage-dt"},"params":{},"headers":{"host":"mateas-directus.up.railway.app","pragma":"no-cache","cache-control":"no-cache","sec-ch-ua":"\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","sec-ch-ua-platform":"\"macOS\"","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-fetch-site":"cross-site","sec-fetch-mode":"no-cors","sec-fetch-dest":"image","referer":"[http://localhost:3001/","accept-encoding":"gzip](http://localhost:3001/%22,%22accept-encoding%22:%22gzip), deflate, br","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","x-forwarded-for":"197.184.182.145","x-forwarded-proto":"https","x-envoy-external-address":"197.184.182.145","x-request-id":"7678e32d-c774-44a2-aa1d-e22d9a8c142d"}},"res":{"statusCode":403,"headers":{"content-security-policy":"default-src none","x-powered-by":"Directus","vary":"Origin","access-control-allow-credentials":"true","access-control-expose-headers":"Content-Range","content-type":"application/json; charset=utf-8","content-length":"102","etag":"W/\"66-OPr7zxcJy7+HqVGdrFe1XpeEIao\""}},"responseTime":668,"msg":"request completed"}

**Comment by rijkvanzanten** [comment]
That seems to be the 403 that was returned itself. Are there any other error logs before this line that would indicate a problem in the connection to cloudinary?

**Comment by sharkfin009** [comment]
`{
    "level": 50,
    "time": 1675870880746,
    "pid": 44,
    "hostname": "railway",
    "err": {
        "type": "Error",
        "message": "Location \"cloudinary\" doesn't exist.",
        "stack": "Error: Location \"cloudinary\" doesn't exist.\n    at StorageManager.location (file:///app/node_modules/@directus/storage/dist/index.js:18:19)\n    at AssetsService.getAsset (/app/node_modules/directus/dist/services/assets.js:75:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/directus/dist/controllers/assets.js:125:36"
    },
    "msg": "Location \"cloudinary\" doesn't exist."
}`
