### ISSUE TITLE
Issue with uploading, playing, and deleting MP4 video

### ISSUE THREAD

**Issue by mcqua007** [directus/directus#17476]
### Describe the Bug

When trying to upload a video I get this error: 
``` json
{
  "errors": [
    {
      "message": "Couldn't save file c039f7b9-8b00-41a9-a084-788b126514a2.mp4",
      "extensions": {
        "code": "SERVICE_UNAVAILABLE",
        "service": "files"
      }
    }
  ]
}
```

The video still shows up in the file manager. When I go to delete it I am getting the following error:
``` json
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file assets/nstk8rib/c039f7b9-8b00-41a9-a084-788b126514a2\n\nError code: CredentialsError\nOriginal stack:\nCredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1\n    at ClientRequest.<anonymous> (/directus/node_modules/aws-sdk/lib/http/node.js:86:34)\n    at Object.onceWrapper (node:events:627:28)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at Socket.emitRequestTimeout (node:_http_client:839:9)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

I am unable to play any videos all of which are mp4 format. I also tried to upload a .webm video but got a similar error. I have tried reseting cache etc...

### To Reproduce

Upload an mp4 file. The size of my files ranged from 20mb- 70mb. Then try and delete it all from the file manager.

### Errors Shown

on upload:
``` json
{
  "errors": [
    {
      "message": "Couldn't save file c039f7b9-8b00-41a9-a084-788b126514a2.mp4",
      "extensions": {
        "code": "SERVICE_UNAVAILABLE",
        "service": "files"
      }
    }
  ]
}
```
on delete:
``` json
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file assets/nstk8rib/c039f7b9-8b00-41a9-a084-788b126514a2\n\nError code: CredentialsError\nOriginal stack:\nCredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1\n    at ClientRequest.<anonymous> (/directus/node_modules/aws-sdk/lib/http/node.js:86:34)\n    at Object.onceWrapper (node:events:627:28)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at Socket.emitRequestTimeout (node:_http_client:839:9)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

on cloud

### What database are you using?

on cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment]
Heya! This seems like a cloud specific issue on your project so I'll pass this along to our cloud team as they will be more suited to look into this matter 👍🏻 Mind opening a support case through the [[the Live Chat in our Cloud Dashboard](https://directus.cloud/)](https://directus.cloud/) as well? That's the quickest way to get this resolved. Thanks!
