### ISSUE TITLE
Issue installing with npm on Windows

### ISSUE THREAD

**Issue by matt-clegg** [directus/directus#17569]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm trying to install Directus via the npm install command on my local Windows machine, but it quickly runs into an error.

I'm not too sure what the issue is but there seems to be wrong with some dependency on my local machine. I'm hoping someone with keener eyes can spot what is going wrong.

This is the full error log:
```
npm init directus-project foo
✖ Installing Directus
Error: npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated keyv-memcache@1.3.3: This project has been renamed to @keyv/memcache which will be updated moving forward.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code 1
npm ERR! path E:\Projects\project\foo\node_modules\argon2
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   opt.c
npm ERR!   argon2.c
npm ERR!   core.c
npm ERR!   blake2b.c
npm ERR!   thread.c
npm ERR!   encoding.c
npm ERR!   win_delay_load_hook.cc
npm ERR!   libargon2.vcxproj -> E:\Projects\mcc\foo\node_modules\argon2\build\Release\\libargon2.lib
npm ERR!   argon2.cpp
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(114,40): error C2666: 'Napi::CallbackInfo::operator []': 2 overloads have similar conversions [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\node-addon-api\napi-inl.h(3477,34): message : could be 'const Napi::Value Napi::CallbackInfo::operator [](size_t) const' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(114,40): message : or       'built-in C++ operator[(napi_callback_info, int)' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(114,40): message : while trying to match the argument list '(const Napi::CallbackInfo, int)' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(114,55): error C2059: syntax error: ')' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(116,68): error C2143: syntax error: missing ';' before '}' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(118,11): error C3927: '->': trailing return type is not allowed after a non-function declarator [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(118,13): error C3613: missing return type after '->' ('int' assumed) [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(118,18): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(118,13): error C2146: syntax error: missing ';' before identifier 'Queue' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(119,5): error C2059: syntax error: 'return' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(120,1): error C2059: syntax error: '}' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(120,1): error C2143: syntax error: missing ';' before '}' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(122,45): error C2143: syntax error: missing ';' before '{' [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(122,45): error C2447: '{': missing function header (old-style formal list?) [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! E:\Projects\mcc\foo\node_modules\argon2\argon2.cpp(127,1): error C2065: 'init': undeclared identifier [E:\Projects\mcc\foo\node_modules\argon2\build\argon2.vcxproj]
npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\Projects\mcc\foo\node_modules\argon2\lib\binding\napi-v3\argon2.node --module_name=argon2 --module_path=E:\Projects\mcc\foo\node_modules\argon2\lib\binding\napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.14.2 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "E:\Projects\mcc\foo\node_modules\argon2\lib\binding\napi-v3\argon2.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.30.2/argon2-v0.30.2-napi-v3-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.30.2/argon2-v0.30.2-napi-v3-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for argon2@0.30.2 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.30.2/argon2-v0.30.2-napi-v3-win32-ia32-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.8.0 found at "C:\Users\Matt\AppData\Local\Programs\Python\Python38\python.exe"
npm ERR! gyp info find VS using VS2019 (16.9.31205.134) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Matt\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Matt\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'E:\\Projects\\mcc\\foo\\node_modules\\argon2\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Matt\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Matt\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Matt\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Matt\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Matt\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=E:\\Projects\\mcc\\foo\\node_modules\\argon2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'E:\\Projects\\mcc\\foo\\node_modules\\argon2\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | win32 | ia32
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Matt\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Projects\\mcc\\foo\\node_modules\\argon2\\lib\\binding\\napi-v3\\argon2.node" "--module_name=argon2" "--module_path=E:\\Projects\\mcc\\foo\\node_modules\\argon2\\lib\\binding\\napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd E:\Projects\mcc\foo\node_modules\argon2
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\Matt\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\Projects\mcc\foo\node_modules\argon2\lib\binding\napi-v3\argon2.node --module_name=argon2 --module_path=E:\Projects\mcc\foo\node_modules\argon2\lib\binding\napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Projects\mcc\foo\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "E:\\Projects\\mcc\\foo\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd E:\Projects\mcc\foo\node_modules\argon2
npm ERR! node-pre-gyp ERR! node -v v16.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok
```

### To Reproduce

Reproducing this might be tricky, but I'm using Node `v16.14.2`, npm `v8.6.0` and Windows 10 `22H2 19045.2486`.  I'm also running this command in a non C:\ drive location.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by jtlindsey** [comment]
You might have better luck [installing docker](https://docs.docker.com/desktop/install/windows-install/) and using ([quickstart](https://docs.directus.io/self-hosted/quickstart.html)) [docker](https://docs.directus.io/self-hosted/docker-guide.html). I remember reading a comment from one of the maintainers saying they purposefully removed the `npm` install options from the docs because of users often failing to get their system dependencies correct for successful startup.

**Comment by matt-clegg** [comment]
Ah that's fair enough, I guess that's the issue I'm running into here. Thanks!
