### ISSUE TITLE
Server Error Undefined index: name when attempting to attach a file to a record using "Choose Existing" button on 2nd attempts

### ISSUE THREAD

**Issue by awbranch** [directus/directus#1765]
## Version Info
 - Directus version and branch: 6.4.2 - 3d7225c
 - PHP version: 5.6.30-12
 - MySQL version: 5.7.19
 - Web server: Apache 2.4.18
 - OS name and version: Ubuntu 16.04.2
 - Browser: Chrome 60.0.3112.90

## Expected Behavior
I have a table with a column with UI: Single File, named "image" that has a related table of "directus_files".

I would like to create multiple records in this table and set the image column using the "Choose Existing" button to select a file from the Directus files.

## Actual Behavior
On a fresh login (with a clean cache) on the first attempt to add a record and attach an image it works as expected. When I try to add a second record and attach an image I get the following error:

`Server Error: Undefined index: name`

Looking in the log I see the following:

```
ERROR - 2017-08-24T14:47:43-04:00 - exception 'ErrorException' with message 'Undefined index: name' in /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php:783
Stack trace:
#0 /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php(783): Slim\Slim::handleErrors(8, 'Undefined index...', '/var/www/html/d...', 783, Array)
#1 /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php(825): Directus\Bootstrap::Directus\{closure}(Array)
#2 [internal function]: Directus\Bootstrap::Directus\{closure}(Object(Directus\Hook\Payload))
#3 /var/www/html/directus-6-4-2/api/core/Directus/Hook/Emitter.php(266): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/directus-6-4-2/api/core/Directus/Hook/Emitter.php(136): Directus\Hook\Emitter->executeListeners(Array, Object(Directus\Hook\Payload), 1)
#5 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(1288): Directus\Hook\Emitter->apply('table.select', Object(Directus\Hook\Payload))
#6 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(723): Directus\Database\TableGateway\BaseTableGateway->applyHook('table.select', Object(Zend\Db\ResultSet\ResultSet), Array)
#7 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(690): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array)
#8 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(857): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#9 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(747): Directus\Database\TableGateway\RelationalTableGateway->loadItems(Array)
#10 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(735): Directus\Database\TableGateway\RelationalTableGateway->getItems(Array)
#11 /var/www/html/directus-6-4-2/api/routes/A1/Files.php(105): Directus\Database\TableGateway\RelationalTableGateway->getEntries(Array)
#12 [internal function]: Directus\API\Routes\A1\Files->files()
#13 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#14 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#15 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#16 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#17 /var/www/html/directus-6-4-2/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#18 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#19 /var/www/html/directus-6-4-2/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#20 /var/www/html/directus-6-4-2/api/api.php(533): Directus\Application\Application->run()
#21 {main}
```

The column in database has the following structure:
```
+-----+------------+-------------+-----------+-------------+-------------------+----------------+----------------+-------------------+--------------------+--------------+----------+------+---------+----------------------+
| id  | table_name | column_name | data_type | ui          | relationship_type | related_table  | junction_table | junction_key_left | junction_key_right | hidden_input | required | sort | comment | options              |
+-----+------------+-------------+-----------+-------------+-------------------+----------------+----------------+-------------------+--------------------+--------------+----------+------+---------+----------------------+
| 220 | tester     | image       | INT       | single_file | MANYTOONE         | directus_files | NULL           | NULL              | image              |            0 |        0 |    4 | Test    | {"id":"single_file"} |
+-----+------------+-------------+-----------+-------------+-------------------+----------------+----------------+-------------------+--------------------+--------------+----------+------+---------+----------------------+
```

## Steps to Reproduce
 1. Create a table
 2. Add a column with User Interface: Single File named "image"
 3. Create a new record for the table.
 4. For the Image field click the "Choose Existing" button.
 5. Click the save button
 6. Repeat step 4 and 5 and you may get the error.

I've been able to reproduce this in multiple tables. Strangely it only occurs with the Administrator account.

## Schema Dump, Logs, or Screenshots
This video shows the error in action.
[Youtube Video Screencast](https://youtu.be/d3TRRbeTQzU)

**Comment by WellingGuzman** [comment]
Hey @awbranch thanks for all the information, I have an extra question, do you have any hooks set?

**Comment by awbranch** [comment]
Just this default in configuration.php

```
    'hooks' => [
        'postInsert' => function ($TableGateway, $record, $db) {

        },
        'postUpdate' => function ($TableGateway, $record, $db) {
            $tableName = $TableGateway->getTable();
            switch ($tableName) {
                // ...
            }
        }
    ],
```

**Comment by WellingGuzman** [comment]
Can you share a schema that we can use to reproduce this?

It seems that fetching those files are failing in the API, also can you please share the request it's being made to `directus_files` when you click "choose existing"?

Thanks!

**Comment by awbranch** [comment]
> Can you share a schema that we can use to reproduce this?

Sure.
[dump.sql.zip](https://github.com/directus/directus/files/1252949/dump.sql.zip)

Also, if it helps, here are the files from storage/ 
[storage.zip](https://github.com/directus/directus/files/1252956/storage.zip)

I did some logging. I can see that when it reaches this line in Bootstrap.php that 'name' doesn't exist in the array:

`$thumbnailFilenameParts = explode('.', $row['name']);`

Here's the logging I added:

```
778         $addFilesUrl = function ($rows) {
 779
 780             $log = static::get('log');
 781             $log->warn('===========================');
 782             foreach ($rows as &$row) {
 783                 $config = Bootstrap::get('config');
 784                 $fileURL = $config['filesystem']['root_url'];
 785                 $thumbnailURL = $config['filesystem']['root_thumb_url'];
 786                 $log->warn('row:     ' . str_replace('=', ':', http_build_query($row, null, ',')));
 787                 $thumbnailFilenameParts = explode('.', $row['name']);
 ```

Here's what that writes to the log file, you can see that it bombs on directus_file id 135 showing that it has no name.

```
WARN - 2017-08-25T16:22:00-04:00 - row:     id:65,status:1,name:661dc79e32e7193f447ab66a0760e2a3.png,title:blog+inside+philanthropy,type:image%2Fpng,width:720,height:222,size:16044,user:2,storage_adapter:local
WARN - 2017-08-25T16:22:00-04:00 - row:     id:124,status:1,name:76db0959bc3d3f18f8a5924147a6f970.ai,title:MFJ+Logo+-+AI,type:application%2Fpostscript,size:70433,user:2,storage_adapter:local
WARN - 2017-08-25T16:22:00-04:00 - row:     id:125,status:1,name:328fb61fddd47015996a9695d3099e1b.eps,title:MFJ+Logo+-+EPS,type:application%2Fpostscript,size:319150,user:2,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - ===========================
WARN - 2017-08-25T16:22:09-04:00 - row:     id:118,status:1,name:1aa41abe7a1653438fe8543c080c1814.png,title:MFJ+Logo,location:,caption:,type:image%2Fpng,charset:binary,tags:,width:401,height:431,size:6278,user:2,date_uploaded:2017-07-21+05%3A31%3A49,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - ===========================
WARN - 2017-08-25T16:22:09-04:00 - row:     id:118,status:1,name:1aa41abe7a1653438fe8543c080c1814.png,title:MFJ+Logo,location:,caption:,type:image%2Fpng,charset:binary,tags:,width:401,height:431,size:6278,user:2,date_uploaded:2017-07-21+05%3A31%3A49,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - ===========================
WARN - 2017-08-25T16:22:09-04:00 - row:     id:73,status:1,name:e9f1b235497162c222a5bd0c225b01be.png,title:blog+doj,location:,caption:Department+of+Justice,type:image%2Fpng,charset:binary,tags:,width:720,height:360,size:163041,user:2,date_uploaded:2017-06-27+17%3A38%3A28,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - row:     id:76,status:1,name:8fbf4513f27a29e9c637e73bcb3da156.png,title:blog+echoing+green,location:,caption:Echoing+Green,type:image%2Fpng,charset:binary,tags:,width:720,height:300,size:12953,user:2,date_uploaded:2017-06-27+17%3A44%3A52,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - row:     id:80,status:1,name:ee5dbbd6a75eee971c3e0b864e1c1cae.jpg,title:history+nyt,location:,caption:The+New+York+Times,type:image%2Fjpg,charset:binary,tags:,width:1202,height:1056,size:87980,user:2,date_uploaded:2017-06-27+14%3A17%3A03,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - row:     id:118,status:1,name:1aa41abe7a1653438fe8543c080c1814.png,title:MFJ+Logo,location:,caption:,type:image%2Fpng,charset:binary,tags:,width:401,height:431,size:6278,user:2,date_uploaded:2017-07-21+05%3A31%3A49,storage_adapter:local
WARN - 2017-08-25T16:22:09-04:00 - row:     id:133,status:1,name:e2a976d2016f8b8c55091ffec45c2852.jpg,title:team+davis,location:,caption:,type:image%2Fjpeg,charset:binary,tags:,width:255,height:255,size:29299,user:2,date_uploaded:2017-07-27+21%3A29%3A45,storage_adapter:local
WARN - 2017-08-25T16:22:56-04:00 - ===========================
WARN - 2017-08-25T16:22:56-04:00 - row:     id:135,status:1,title:charles+bio+pic,location:,caption:,date_uploaded:2017-08-03+10%3A31%3A36
ERROR - 2017-08-25T16:22:56-04:00 - exception 'ErrorException' with message 'Undefined index: name' in /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php:787
Stack trace:
#0 /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php(787): Slim\Slim::handleErrors(8, 'Undefined index...', '/var/www/html/d...', 787, Array)
#1 /var/www/html/directus-6-4-2/api/core/Directus/Bootstrap.php(830): Directus\Bootstrap::Directus\{closure}(Array)
#2 [internal function]: Directus\Bootstrap::Directus\{closure}(Object(Directus\Hook\Payload))
#3 /var/www/html/directus-6-4-2/api/core/Directus/Hook/Emitter.php(266): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/directus-6-4-2/api/core/Directus/Hook/Emitter.php(136): Directus\Hook\Emitter->executeListeners(Array, Object(Directus\Hook\Payload), 1)
#5 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(1288): Directus\Hook\Emitter->apply('table.select', Object(Directus\Hook\Payload))
#6 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(723): Directus\Database\TableGateway\BaseTableGateway->applyHook('table.select', Object(Zend\Db\ResultSet\ResultSet), Array)
#7 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/BaseTableGateway.php(690): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array)
#8 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(857): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#9 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(747): Directus\Database\TableGateway\RelationalTableGateway->loadItems(Array)
#10 /var/www/html/directus-6-4-2/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(735): Directus\Database\TableGateway\RelationalTableGateway->getItems(Array)
#11 /var/www/html/directus-6-4-2/api/routes/A1/Files.php(105): Directus\Database\TableGateway\RelationalTableGateway->getEntries(Array)
#12 [internal function]: Directus\API\Routes\A1\Files->files()
#13 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#14 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#15 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#16 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#17 /var/www/html/directus-6-4-2/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#18 /var/www/html/directus-6-4-2/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#19 /var/www/html/directus-6-4-2/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#20 /var/www/html/directus-6-4-2/api/api.php(533): Directus\Application\Application->run()
#21 {main}
```

Which I found odd because that row in directus_files does have a name:

```
mysql> select * from directus_files where id = 135;
+-----+--------+--------------------------------------+-----------------+----------+---------+------------+---------+------+-------+--------+-------+----------+------+---------------------+-----------------+
| id  | status | name                                 | title           | location | caption | type       | charset | tags | width | height | size  | embed_id | user | date_uploaded       | storage_adapter |
+-----+--------+--------------------------------------+-----------------+----------+---------+------------+---------+------+-------+--------+-------+----------+------+---------------------+-----------------+
| 135 |      1 | 4ec3e0eaf21a2c9a8889cfb2e3d84068.jpg | charles bio pic |          |         | image/jpeg | binary  |      |   255 |    255 | 12769 | NULL     |    2 | 2017-08-03 10:31:36 | local           |
+-----+--------+--------------------------------------+-----------------+----------+---------+------------+---------+------+-------+--------+-------+----------+------+---------------------+-----------------+
```

**Comment by awbranch** [comment]
Hey - I figured it out!!!

The problem was that directus_preferences had the following entry for the columns_visible for my user: 
`item,title,location,caption`

I changed it to the following and it works:
`name,title,location,caption`

item doesn't exist in directus_files. I suppose 'item' was left over from the 5.x version?

**Comment by WellingGuzman** [comment]
Thanks @awbranch for all these information on how to solve this issue, we have managed to find a solution were we force the `name` to be query, but it will be not returned if the user didn't add it as visible column.

Closed by https://github.com/directus/directus/commit/76e7262b2918817f40fe2a96b9acae754ff7f697
