### ISSUE TITLE
SSO with Google: user registration fails with "[OpenID] Couldn't verify OpenID cookie"

### ISSUE THREAD

**Issue by tadeussenf** [directus/directus#17684]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When registering in using Google as SSO provider the process fails. It seems to work when starting he registration flow from `/directus/admin/login`.

Directus is installed via the CLI flow described at: https://docs.directus.io/self-hosted/cli.html

**relevant configuration**
AUTH_PROVIDERS="google"
```

AUTH_GOOGLE_DRIVER="openid"
AUTH_GOOGLE_CLIENT_ID="REDACTED"
AUTH_GOOGLE_CLIENT_SECRET="REDACTED"
AUTH_GOOGLE_ISSUER_URL="https://accounts.google.com"
AUTH_GOOGLE_IDENTIFIER_KEY="email"
AUTH_GOOGLE_ICON="google"
AUTH_GOOGLE_LABEL="Google"
AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_GOOGLE_DEFAULT_ROLE_ID="REDACTED" 
```

### To Reproduce

1. Install Directus
2. Setup Google SSO using instructions outlined in https://docs.directus.io/self-hosted/sso.html
3. In the SPA on the frontend include a html like
4. `<a href="/directus/auth/login/google">Google Login</a>&nbsp;`
5. Klick the link and login using your google credentials

**This result in the browser results with** 
`{"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}`

**directus log:**
```
[20:22:40.437] WARN: [OpenID] Couldn't verify OpenID cookie
    err: {
      "type": "JsonWebTokenError",
      "message": "jwt must be provided",
      "stack":
          JsonWebTokenError: jwt must be provided
              at module.exports [as verify] (/srv/directus/node_modules/jsonwebtoken/verify.js:60:17)
              at /srv/directus/node_modules/directus/dist/auth/drivers/openid.js:261:48
              at /srv/directus/node_modules/directus/dist/utils/async-handler.js:3:66
              at Layer.handle [as handle_request] (/srv/directus/node_modules/express/lib/router/layer.js:
95:5)
              at next (/srv/directus/node_modules/express/lib/router/route.js:144:13)
              at Route.dispatch (/srv/directus/node_modules/express/lib/router/route.js:114:3)
              at Layer.handle [as handle_request] (/srv/directus/node_modules/express/lib/router/layer.js:
95:5)
              at /srv/directus/node_modules/express/lib/router/index.js:284:15
              at Function.process_params (/srv/directus/node_modules/express/lib/router/index.js:346:12)
              at next (/srv/directus/node_modules/express/lib/router/index.js:280:10)
      "name": "JsonWebTokenError"
    }
```

### Hosting Strategy

Self-Hosted (Custom)

**Comment by tadeussenf** [comment]
It works when the SPA is not running on localhost (but is deployed)
