### ISSUE TITLE
Issue when building extensions with global dependencies. 

### ISSUE THREAD

**Issue by peauc** [directus/directus#17724]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

We have a Dockerfile that copies our custom extensions, install their node modules and then build them. 

This build process was getting pretty long (600s) due to the multiple installation of each dependencies as we have more than 20 extensions now. To fix that i've tried installing the npm dependencies at a global state with `RUN cd extensions_src/modules/dev-toolkit && npm install --global --unsafe-perm --save-dev && npm run build`.
However it does not work due to a `require` error.
```
[09:22:55.347] WARN: require() of ES Module /directus/node_modules/nanoid/index.js from /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js not supported.
Instead change the require of index.js in /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js to a dynamic import() which is available in all CommonJS modules.
    err: {                                                                                                                                                                      
      "type": "Error",                                                                                                                                                          
      "message": "require() of ES Module /directus/node_modules/nanoid/index.js from /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js not supported.\nInstead change
 the require of index.js in /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js to a dynamic import() which is available in all CommonJS modules.",
      "stack":                                                                                                                          
          Error [ERR_REQUIRE_ESM]: require() of ES Module /directus/node_modules/nanoid/index.js from /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js not supported
.                                                                                                                                                     
          Instead change the require of index.js in /directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js to a dynamic import() which is available in all CommonJS module
s.                                                                                                                                                    
              at Object.<anonymous> (/directus/node_modules/@directus/shared/dist/cjs/composables/use-custom-selection.js:4:18)         
              at Object.<anonymous> (/directus/node_modules/@directus/shared/dist/cjs/composables/index.js:26:14)                                     
              at Object.<anonymous> (/directus/node_modules/@directus/extensions-sdk/dist/cjs/index.js:16:21)                           
              at Object.<anonymous> (/directus/extensions/endpoints/custom-api/index.js:1:20)                                        
              at ExtensionManager.registerEndpoints (/directus/node_modules/directus/dist/extensions.js:315:42)                         
              at ExtensionManager.load (/directus/node_modules/directus/dist/extensions.js:190:20)                                      
              at async ExtensionManager.initialize (/directus/node_modules/directus/dist/extensions.js:97:13)                           
              at async createCli (/directus/node_modules/directus/dist/cli/index.js:27:5)                                               
      "code": "ERR_REQUIRE_ESM"                                                                                                                                                 
    }                                                                                                                                   
[09:22:55.398] WARN: Couldn't bundle App extensions
```

### To Reproduce

Here is a dockerfile to reproduce the issue. It seems to happen only on endpoints.

```
FROM node:18.9.0 as builder-extensions

# Fetch the globaly installed packages
ENV PATH=$PATH:/usr/local/bin

COPY ./extensions extensions_src
RUN npm install --global --unsafe-perm "@directus/extensions-sdk"
RUN cd extensions_src/endpoints/custom-api && npm install --global --unsafe-perm --save-dev && npm run build


FROM directus/directus:9.23.1
RUN mkdir -p    extensions/endpoints/custom-api

COPY --from=builder-extensions extensions_src/endpoints/custom-api/dist/* extensions/endpoints/custom-api/
```

### Hosting Strategy

Self-Hosted (Custom)

**Comment by peauc** [comment]
I removed the installation of global dependencies for the `endpoint` & `hooks` extentions and it works fine.

**Comment by br41nslug** [comment]
With the eco system move to ESM some packages have stopped supporting CJS. Because global dependencies use the CJS `require` to import the llibrary this won't work any longer for ESM only packages. While it was working in the past installing it is not officially supported to install global dependendencies, instead you should use a `bundle` type extension to share dependencies between multiple extensions.
