### ISSUE TITLE
Error with Hooks Extension, first parameter is a function rather than object

### ISSUE THREAD

**Issue by navanshu** [directus/directus#17761]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I recently built a directus hook extension and I am getting this error
```console
directus  | [09:38:40.187] INFO: Done
directus  | function
directus  | [
directus  |   'params',
directus  |   '_params',
directus  |   'caseSensitive',
directus  |   'mergeParams',
directus  |   'strict',
directus  |   'stack'
directus  | ]
directus  | [09:38:39.732] WARN: init is not a function
directus  |     err: {
directus  |       "type": "TypeError",
directus  |       "message": "init is not a function",
directus  |       "stack":
directus  |           TypeError: init is not a function
directus  |               at /directus/extensions/endpoints/firebase_hook/index.js:74619:3
directus  |               at ExtensionManager.registerEndpoint (/directus/node_modules/directus/dist/extensions.js:451:9)
directus  |               at ExtensionManager.registerEndpoints (/directus/node_modules/directus/dist/extensions.js:317:22)
directus  |               at ExtensionManager.load (/directus/node_modules/directus/dist/extensions.js:190:20)
directus  |               at async ExtensionManager.initialize (/directus/node_modules/directus/dist/extensions.js:97:13)
directus  |               at async createCli (/directus/node_modules/directus/dist/cli/index.js:27:5)
directus  |     }
```

The first parameter of the hook is a function while the documentation says it should be a object.
The second parameter is an object with all the correct properties.

### To Reproduce

```typescript
import { defineHook } from '@directus/extensions-sdk';

export default defineHook((register, context) => {
 console.log(typeof register);
 console.log(Object.keys(register));
 const { filter, init } = register;
 const { env, exceptions, logger } = context;

init("middlewares.after", () => {
// Custom Logic
})

})
```

I used npm run dev to build the output file for debugging. The error is same throughout.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by navanshu** [comment]
Oh, It was my mistake, I was uploading it to wrong endpoint folder.
It would be great if directus had some error detection againts this
