### ISSUE TITLE
File upload from compresed folder

### ISSUE THREAD

**Issue by Csaba19999** [directus/directus#17999]
### Description
When you try to upload a file from a compressed folder like zip, rar etc.. directly on directus drag and drop file input,
the application crashes. I did not try with third-party inputs like a form on my own project, but I assumed that the same thing could happen. But the real problem is, after restarting the app, some of the files are corrupted and the directus cant recognizes them.

### Error
```terminal
ERROR: The "path" argument must be of type string. Received null
directus-directus-1    |     err: {
directus-directus-1    |       "type": "TypeError",
directus-directus-1    |       "message": "The \"path\" argument must be of type string. Received null",
directus-directus-1    |       "stack":
directus-directus-1    |           TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
directus-directus-1    |               at new NodeError (node:internal/errors:400:5)
directus-directus-1    |               at validateString (node:internal/validators:163:11)
directus-directus-1    |               at join (node:path:1172:7)
directus-directus-1    |               at DriverLocal.fullPath (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:11:32)
directus-directus-1    |               at DriverLocal.exists (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:40:28)
directus-directus-1    |               at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:75:61)
directus-directus-1    |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus-directus-1    |               at async /directus/node_modules/directus/dist/controllers/assets.js:125:36
directus-directus-1    |       "code": "ERR_INVALID_ARG_TYPE"
```

The big problem with that is, if an employee wants to upload, let's say 100 pdf or images and they got it in compressed format when they try to upload from there they can accidentally crash the app.

### To Reproduce

Docker image: directus/directus:9.22.4
db: mssql
host: aws s3

1. Create a collection with a file or input.
2. compress the file into rar or zip format.
3. open the compressed folder, grab the file, and drop it into created collection file input field.

Same could be true for directus folders.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am not entirely sure this is something we can or should fix on our end as unpacking the file before upload is something that either the operation system or the browser should handle.

But this does indeed not work in both chrome and firefox. What does work as workaround is to open the zip using the browser "open file" dialog

**Comment by rijkvanzanten** [comment]
But when you "open the compressed file", doesn't it just decompress into a folder of regular files again? Or is that just a macOS thing 🙃

**Comment by Nitwel** [comment]
That's a macOS thing then because on Windows and assuming on Linux, you can browse the zip file without fully decompressing it.

**Comment by br41nslug** [comment]
Would surprise me if apple always extracts the entire archive that would be highly inefficient when working with multi-gig archives. What seems more likely is that "it's just working" for apple 🤷

**Comment by rijkvanzanten** [comment]
https://user-images.githubusercontent.com/9141017/229141044-c3d1dcf6-8655-425f-9fe6-0f1a79a71f1b.mp4

🥳
