### ISSUE TITLE
SSO: [OAuth2] Unknown RP error: wrong username/password

### ISSUE THREAD

**Issue by soulseekah** [directus/directus#18074]
### Describe the Bug

We're using Ory as our OAuth2 provider. We got a message similar to #15879

We have the following:

```
RPError: id_token detected in the response you must use client.callback() instead of client.oauthCallback()
at Client.oauthCallback (/directus/node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js:615:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at OAuth2AuthDriver.getUserID (/directus/api/src/auth/drivers/oauth2.ts:119:15)
    at AuthenticationService.login (/directus/api/src/services/authentication.ts:61:13)
    at /directus/api/src/auth/drivers/oauth2.ts:320:20 {
  params: {
    code: 'ory_ac_Y7zbK5UkCYrYFGczQsTpkd9o_sx32DRgZgGAqpyl0qo.SugAeiYRAtTq9GNRD2rONw_E5-DYODJ5CXkgujnR_YI',
    state: '4Awxf3fi2uhLnG0O5MJsrbtNdhV2tldw1kg8x42FOq0'
  }
}
```

### To Reproduce

We can privately provide access to our Ory setup, let us know how to do this securely.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Romakita** [comment]
Hello @soulseekah 
As I see, the used auth is OAuth2AuthDriver. But Ory seems to be an openid provider, because id_token is delivered only by an OIDC server. Maybe switching your configuration on openid will fix your issue. 

```dotenv
AUTH_ORY_DRIVER="openid"
AUTH_ORY_ISSUER_URL="https://oryhost"  // replace by the correct issuer host (not necessary to git .well-known/openid-configuration path)
...
```

See you
Romain
