### ISSUE TITLE
EXTENSION HOOKS - ES issue

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#18177]
### Describe the Bug

I know that there was a breaking change in todays 9.25 release around ES... currently trying to make it work... but failing. Really not sure whether its a bug - but definitely MANY others will have the same challenges. So - any guidance / ideas on how to solve this would be VERY MUCH appreciated - thanks a lot in advance

**1) Using Directus Standard Extension Code (generated from NPM INIT DIRECTUS-EXTENSION)  =>  results in the following error:**

WARN: Couldn't register hook "webpage-hooks"
WARN: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/directus/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2023-04-13 23:23:01     err: {
2023-04-13 23:23:01       "type": "ReferenceError",
2023-04-13 23:23:01       "message": "exports is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/directus/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
2023-04-13 23:23:01       "stack":
2023-04-13 23:23:01           ReferenceError: exports is not defined in ES module scope
2023-04-13 23:23:01           This file is being treated as an ES module because it has a '.js' file extension and '/directus/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2023-04-13 23:23:01               at file:///directus/extensions/hooks/webpage-hooks/index.js:1:36
2023-04-13 23:23:01               at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
2023-04-13 23:23:01     }

**2) Trying to work around it by renaming the output file to .CJS => results in the following error:**

WARN: Couldn't register hook "webpage-hooks"
WARN: register is not a function
2023-04-13 23:28:44     err: {
2023-04-13 23:28:44       "type": "TypeError",
2023-04-13 23:28:44       "message": "register is not a function",
2023-04-13 23:28:44       "stack":
2023-04-13 23:28:44           TypeError: register is not a function
2023-04-13 23:28:44               at ExtensionManager.registerHook (file:///directus/node_modules/.pnpm/@directus+api@9.25.0/node_modules/@directus/api/dist/extensions.js:435:9)
2023-04-13 23:28:44               at ExtensionManager.registerHooks (file:///directus/node_modules/.pnpm/@directus+api@9.25.0/node_modules/@directus/api/dist/extensions.js:300:22)
2023-04-13 23:28:44               at async ExtensionManager.load (file:///directus/node_modules/.pnpm/@directus+api@9.25.0/node_modules/@directus/api/dist/extensions.js:183:9)
2023-04-13 23:28:44               at async file:///directus/node_modules/.pnpm/@directus+api@9.25.0/node_modules/@directus/api/dist/extensions.js:98:17
2023-04-13 23:28:44               at async JobQueue.run (file:///directus/node_modules/.pnpm/@directus+api@9.25.0/node_modules/@directus/api/dist/utils/job-queue.js:18:13)

### To Reproduce

Upgrade to latest 9.25 Directus release - and try to run an EXTENSION HOOK

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
Have you tried updating the `path` output to use the `cjs` extension

```
"directus:extension": {
		"type": "module",
		"path": ../extensions/hooks/items/index.cjs",
		"source": "src/index.ts",
		"host": "^9.25.1"
	},
	```

**Comment by br41nslug** [comment]
First things first when using the directus-extension SDK you are not using CJS so renaming will not help in this case. Are you sure you were using the latest version of the extension sdk when creating the new extension? `npm init directus-extension@latest` probably not as that one is broken at the moment see https://github.com/directus/directus/issues/18183

**Comment by br41nslug** [comment]
This one will likely be solved by https://github.com/directus/directus/pull/18187 but have not been able to confirm

**Comment by ernst86913** [comment]
For now you can close it - I will test again once a new release is available which contains latest bug fixes in this area

Thx
Roman

Von meinem iPhone gesendet

On 14.04.2023, at 16:52, Brainslug ***@***.***> wrote:

﻿

This one will likely be solved by #18187<https://github.com/directus/directus/pull/18187> but have not been able to confirm

**Comment by stoverb** [comment]
We ran into this issue with a cross version declaration:

Docker container used :latest tag for container image

While our package.json specified Directus 9.23.1 

Just in case our mistake can help anybody else out there...

**Comment by kgkg** [comment]
In our case removing `type: "module"` from extension's `package.json`, then rebuilding extension and restart Directus fixes this issue.
