### ISSUE TITLE
LDAP - Service returned unexpected error

### ISSUE THREAD

**Issue by franzpro** [directus/directus#18182]
### Describe the Bug

I am trying to activate the LDAP service. I have tried different settings. My last attempt looks like this:

AUTH_PROVIDERS: 'ldap'
AUTH_LDAP_DRIVER: 'ldap'
AUTH_LDAP_CLIENT_URL: 'ldap://xxxxxx.xxxxx.xxxxx:389'
AUTH_LDAP_BIND_DN: 'string:CN=xxxxx,CN=Users,DC=xxxxx,DC=xxxxx'
AUTH_LDAP_BIND_PASSWORD: 'xxxxx'
AUTH_LDAP_USER_DN: 'string:CN=MUC,CN=Users,CN=xxxxxxxx,DC=xxxxxxxx,DC=xxxxxxxx'
AUTH_LDAP_USER_ATTRIBUTE: 'sAMAccountName'
AUTH_LDAP_USER_SCOPE: 'sub'
AUTH_LDAP_GROUP_DN: 'string:CN=All,CN=Security Groups,CN=MyBusiness,DC=xxxxxxx,DC=xxxxxxxxx'       
AUTH_LDAP_GROUP_ATTRIBUTE: "memberUid"
AUTH_LDAP_GROUP_SCOPE: 'base'
AUTH_LDAP_MAIL_ATTRIBUTE: 'mail'
AUTH_LDAP_FIRST_NAME_ATTRIBUTE: 'givenName'
AUTH_LDAP_LAST_NAME_ATTRIBUTE: 'sn'

Unfortunately, I get this error message:

`[09:28:55.560] DEBUG: Service returned unexpected error

    err: {

      "type": "ServiceUnavailableException",

      "message": "Service returned unexpected error",

      "stack":

          Error: Service returned unexpected error

              at handleError (/directus/dist/auth/drivers/ldap.js:292:12)

              at CorkedEmitter.<anonymous> (/directus/dist/auth/drivers/ldap.js:143:28)

              at CorkedEmitter.emit (node:events:513:28)

              at CorkedEmitter.emit (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/corked_emitter.js:44:33)

              at sendResult (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:1194:22)

              at messageCallback (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:1220:18)

              at Parser.onMessage (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:888:14)

              at Parser.emit (node:events:513:28)

              at Parser.write (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/messages/parser.js:107:8)

              at Socket.onData (/directus/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:875:22)

      "status": 503,

      "code": "SERVICE_UNAVAILABLE",

      "extensions": {

        "service": "ldap",

        "message": "0000208D: NameErr: DSID-0310028C, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=xxxxxxx,DC=xxxxxxx'\n\u0000"

      }

    }`

i just don't know anymore. Could someone help me further? 

### To Reproduce

try to login with LDAP with sAMAccountName and Password.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by franzpro** [comment]
Sorry, I have searched for several days in despair, but no sooner do I ask here for help, I have identified the problem and fixed it. The problem sits like most in front of the screen.

the DN strings were wrong.

**Comment by rijkvanzanten** [comment]
Glad to hear you figured it out @franzpro 🙂  LDAP config is a special type of beast..
