### ISSUE TITLE
error on schema apply

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#18207]
### Describe the Bug

node error:
   err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'filter')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'filter')
              at getSnapshotDiff (file:///workspace/computravel_directus/node_modules/@directus/api/dist/utils/get-snapshot-diff.js:16:18)
              at Command.apply (file:///workspace/computravel_directus/node_modules/@directus/api/dist/cli/commands/schema/apply.js:33:30)
              at async Command.parseAsync (/workspace/computravel_directus/node_modules/commander/lib/command.js:935:5)
    }

### To Reproduce

i used the schema/snapshot endpoint to grab the schema from one instance. Then used 
npx directus schema apply ./schema.yaml  
( tried JSON also) 

Result, above error

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I was unable to reproduce this importing an arbitrary schema. Could you provide extra information on the specific schema migration that is failing?

Happy to re-open when more information becomes available 😄

**Comment by sharkfin009** [comment]
@br41nslug thanks so much . Sorry for not thinking this through more clearly... I was trying to migrate from a postgres db to an sqllite db. Cleary that was the problem
