### ISSUE TITLE
Cannot start v9.25.2 

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18281]
### Describe the Bug

`>npx directus start

file:///C:/Direct/23/node_modules/@directus/api/dist/operations/exec/index.js:3
import { isBuiltin } from 'node:module';
         ^^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'isBuiltin'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async ExtensionManager.registerOperations (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:330:39)
    at async ExtensionManager.load (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:184:9)
    at async ExtensionManager.initialize (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:81:13)
    at async createCli (file:///C:/Direct/23/node_modules/@directus/api/dist/cli/index.js:21:5)`

### To Reproduce

update v9.24.0 to v9.25.2

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Directus is targeting the latest LTS version of Node.js which currently is v18 (see https://github.com/nodejs/release#release-schedule). Please update to this version.

**Comment by Pachat** [comment]
The current version of Node.js that installs is `Node.js v19.8.1`
Should it be `v18` precisely ?
Because `Node.js v19.8.1` it gives
```
npx directus start
node:internal/modules/cjs/loader:1361
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: error: 193\\?\C:\Direct\23\node_modules\argon2\lib\binding\napi-v3\argon2.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Direct\23\node_modules\argon2\argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Pachat** [comment]
It does not work either with Node.js `v18.15.0`
```
>npx directus start
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: error: 193\\?\C:\Direct\23\node_modules\argon2\lib\binding\napi-v3\argon2.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Direct\23\node_modules\argon2\argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Pachat** [comment]
Going back to previous installation that was working, recompiling all the extensions and restoring the database
I get now this error

C:\Direct\23>npm -v
9.6.5

C:\Direct\23>node -v
v16.14.0
```
>npx directus start
file:///C:/Direct/23/node_modules/@directus/api/dist/operations/exec/index.js:3
import { isBuiltin } from 'node:module';
         ^^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'isBuiltin'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async ExtensionManager.registerOperations (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:330:39)
    at async ExtensionManager.load (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:184:9)
    at async ExtensionManager.initialize (file:///C:/Direct/23/node_modules/@directus/api/dist/extensions.js:81:13)
    at async createCli (file:///C:/Direct/23/node_modules/@directus/api/dist/cli/index.js:21:5)

```
I think I'll have to restart from a new installation.

**Comment by paescuj** [comment]
>  Has it to be node v18 or can it be on node v19?

Node.js LTS is what we test and recommend

**Comment by Pachat** [comment]
I installed Node.js LTS (v18.16.0)
```
>node -v
v18.16.0
>npm -v
9.6.5
>npx directus database migrate:latest
>npm install create-directus-extension --save
>npx directus database migrate:latest

```
and got this error
```
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: error: 193\\?\C:\Direct\23\node_modules\argon2\lib\binding\napi-v3\argon2.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Direct\23\node_modules\argon2\argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0
```
The installation was working previously working on Node v16.14.
It brake when I updated from Directus v9.24.0 to v9.25.2

(I tried to make the previous version alive - I have a complete backup of the directory - but I did not succeed to make the corresponding node version working properly and still get errors)

What can I do?
Try to get the latest working or try to make the previous version alive?

Any hint would be very much appreciated because I'm stopped and cannot develop anymore.

**Comment by rijkvanzanten** [comment]
> > Has it to be node v18 or can it be on node v19?
> 
> Node.js LTS is what we test and recommend

Node.js "Active LTS" to be exact 🙂 Which at time of writing is Node 18

> What can I do?
> Try to get the latest working or try to make the previous version alive?

This error sounds to me like there's some sort of problem in your exact copy of node, the installation of the argon2 subpackage, any of it's required system packages (like glib), or having the compiled binaries for argon2 on node 16 running in node 18. You can try it by rebuilding the dependencies on installation, but honestly, this is exactly the reason why we recommend using Docker as the main deployment strategy, as you don't have any of these environment issues with it 👍🏻

**Comment by Pachat** [comment]
Thank you for your answer.
For the present I succeeded to get it to work.
I installed `Node LTS` (under Windows 10) with compiling tools. Then

```
node -v : v18.16.0
npm -v : 9.6.5
npm install directus –save
npm install create-directus-extension –save
npm install graphql –save
npx directus database migrate:latest => ERR_DLOPEN_FAILED
npm install
npm rebuild argon2 --build-from-source -m
npx directus database migrate:latest => Something went wrong installing the "sharp" module
npm install --platform=win32 --arch=x64 sharp
npx directus database migrate:latest OK
npx directus start OK
```
 I'll certainly follow your guidelines on Docker when installing the production server.

**Comment by younky-yang** [comment]
You may need to add "@napi-rs/snappy": "1.0.2" to your dependencies.

**Comment by michael-scheurer** [comment]
Run into the same problem. I got it running with the exact versioning like @Pachat mentioned.

```
node -v : v18.16.0
npm -v : 9.6.5
```

**Comment by connor11528** [comment]
```sh
nvm install 20
nvm use 20
npx directus init
```
fixed it for me
