### ISSUE TITLE
npx directus init package.json error

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#18319]
### Describe the Bug

I'm getting a package.json not found when trying to run `npx directus init` 
This is impacting 9.26 and 9.25.2 

<img width="630" alt="Screenshot 2023-04-25 at 15 36 07" src="https://user-images.githubusercontent.com/21194068/234311664-10f160e4-42e9-4836-a9ed-900a7cb10408.png">

### To Reproduce

npx directus init

### Directus Version

9.26

### Hosting Strategy

Self-Hosted (Custom)

**Comment by M-GRV** [comment]
Copying the release into the folder that is trying to init will work. Something is up with the package download for sure

**Comment by alexvdvalk** [comment]
You can run ```npm init``` first to generate a package.json, but this wasn't neccessary previously.

**Comment by licitdev** [comment]
The `npm init` instruction would be a good addition for the documentation.

The warning exists `< 9.19.0`, but the error was made more verbose `>= 9.19.0` after `pino` was updated in #16052.
The error object was formatted differently where `pino-colada` would print the error message only.

### 9.18.0
```
~/directus/test % npx directus@9.18.0 init
20:09:16 ⚠️  Couldn't load extensions
20:09:16 ⚠️  Current folder does not contain a package.json file
? Choose your database client (Use arrow keys)
❯ PostgreSQL / Redshift 
  CockroachDB (Beta) 
  MySQL / MariaDB / Aurora 
  SQLite 
  Microsoft SQL Server 
  Oracle Database 
```

### 9.19.0
```
~/directus/test % npx directus@9.19.0 init
? Choose your database client (Use arrow keys)
❯ PostgreSQL / Redshift 
  CockroachDB (Beta) 
  MySQL / MariaDB / Aurora 
  SQLite 
  Microsoft SQL Server 
  Oracle Database [20:09:26] WARN (76697 on local): Couldn't load extensions
[20:09:26] WARN (76697 on local): Current folder does not contain a package.json file
    err: {
      "type": "Error",
      "message": "Current folder does not contain a package.json file",
      "stack":
          Error: Current folder does not contain a package.json file
              at getPackageExtensions (/Users/ian/.npm/_npx/66fdfd267ab7218c/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js:76:15)
              at async ExtensionManager.getExtensions (/Users/ian/.npm/_npx/66fdfd267ab7218c/node_modules/directus/dist/extensions.js:210:35)
              at async ExtensionManager.load (/Users/ian/.npm/_npx/66fdfd267ab7218c/node_modules/directus/dist/extensions.js:144:31)
              at async ExtensionManager.initialize (/Users/ian/.npm/_npx/66fdfd267ab7218c/node_modules/directus/dist/extensions.js:93:13)
              at async createCli (/Users/ian/.npm/_npx/66fdfd267ab7218c/node_modules/directus/dist/cli/index.js:27:5)
    }
```
