### ISSUE TITLE
MSSQL: TypeError: Cannot read properties of undefined (reading 'primary')

### ISSUE THREAD

**Issue by ni-mb** [directus/directus#18437]
### Describe the Bug

I have an issue when starting a fresh new installation of directus with a fresh and new installation auf Microsft SQL Server 2019.
When i want to start the app after installation (via NPM CLI or as Docker Image) I get the following error:

> TypeError: Cannot read properties of undefined (reading 'primary')
>     at getASTFromQuery (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/utils/get-ast-from-query.js:47:56)
>     at ItemsService.readByQuery (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/services/items.js:283:25)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async RelationsService.readAll (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/services/relations.js:53:17)
>     at async getDatabaseSchema (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/utils/get-schema.js:129:24)
>     at async getSchema (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/utils/get-schema.js:30:22)
>     at async registerAuthProviders (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/auth.js:19:52)
>     at async createApp (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/app.js:78:5)
>     at async createServer (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/server.js:17:38)
>     at async Command.startServer (file:///C:/Directus/testapp1/node_modules/@directus/api/dist/server.js:105:20)
> [14:34:39.445] WARN: Collection "directus_notifications" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_fields" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_activity" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_permissions" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_presets" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_relations" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_revisions" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_settings" doesn't have a primary key column and will be ignored
> [14:34:39.446] WARN: Collection "directus_webhooks" doesn't have a primary key column and will be ignored

I´ve already trie to run: `npx directus database migrate:latest` which outputs a success, but i cannot start the Server.

My Database server is a new Installation of Microsoft SQL Server 2019 on a Windows Server 2019.
I tried to start Directus from a different Ubuntu Server (same VLAN/Network) via Docker and directly via NPM and get the same error message.
I´ve also tried to run Directus on the same Windows Server where the SQL Server is installed, but i got the same error.

There was a an issue where somone else got the same error, but the fix in this issue didn´t work for me:
https://github.com/directus/directus/issues/12319
I´ve noticed that the Task for this fix was for PostgreSQL not for MSSQL.

This is my last try to start the Application (on the Same Server with the SQL Server):
![image](https://user-images.githubusercontent.com/103439358/235955499-c49f61ad-53bb-4241-b5cf-7f13b902a43a.png)

### To Reproduce

Create a Windows Server 2019 with Microsoft SQL Server 2019 Standard.

Setup Docker and create a new Directus app
or
Setup NodeJS and create a new project:
`npm init directus-project testapp`
`cd .\testapp\`
`npx directus database migrate:latest` (Optional)
`npx directus start`

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
This is most likely a database permission issue and not a issue with Directus itself, considering similar issues from the past:
- #16221
- #12319
- #10063

**Comment by iksent** [comment]
I had the same problem after updating to the latest version.
I ran the migration and the error went away.

**Comment by cdwmhcc** [comment]
```
npx directus database migrate:latest
```
```bash
[03:24:36.885] WARN: Couldn't load extensions
[03:24:36.886] WARN: Cannot read properties of undefined (reading 'primary')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'primary')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'primary')
              at getASTFromQuery (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/utils/get-ast-from-query.js:47:56)
              at ItemsService.readByQuery (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/services/items.js:310:25)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async getExtensionsSettings (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/extensions/lib/get-extensions-settings.js:16:22)
              at async ExtensionManager.load (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:138:39)
              at async ExtensionManager.initialize (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:122:13)
              at async createCli (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.0_vue@3.3.4/node_modules/@directus/api/dist/cli/index.js:23:9)
    }
[03:24:36.942] INFO: Running migrations...
[03:24:36.949] INFO: Applying Add Content Versioning...
[03:24:36.954] ERROR: create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) default character set utf8mb4 - ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists
    err: {
      "type": "Error",
      "message": "create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) default character set utf8mb4 - ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists",
      "stack":
          Error: ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists
              at Sequence._packetToError (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:517:28)
              at addChunk (node:internal/streams/readable:335:12)
              --------------------
              at Protocol._enqueue (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/apps/web/api/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
              at /apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)
              at Runner.query (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:217:21)
              at Runner.queryArray (/apps/web/api/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:31)
      "code": "ER_TABLE_EXISTS_ERROR",
      "errno": 1050,
      "sqlMessage": "Table 'directus_versions' already exists",
      "sqlState": "42S01",
      "index": 0,
      "sql": "create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) default character set utf8mb4"
    }
```

**Comment by cdwmhcc** [comment]
verson: 10.7.0

**Comment by rijkvanzanten** [comment]
@cdwmhcc Looks like your error is unrelated to this issue. [Mind opening a new issue?](https://github.com/directus/directus/issues/new?assignees=&labels=&projects=&template=bug_report.yml) Thanks!
