### ISSUE TITLE
Applying snapshot fail to create relation and drop foreign keys

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#18689]
### Describe the Bug

Applying a snapshot done from a Postgres 14.5 instance to a production Postgres 14.5 instance fail. 
During the failure it also drop 2/3 foreign keys of the table.

Here is the error log.

```
ERROR: Failed to create relation "explore_filters.primary_label"
ERROR: "collection" is required
err: {
"type": "InvalidPayloadException",
"message": "\"collection\" is required",
"stack": Error: "collection" is required
at RelationsService.createOne (file:///usr/src/app/node_modules/@directus/api/dist/services/relations.js:113:19)
at file:///usr/src/app/node_modules/@directus/api/dist/utils/apply-diff.js:201:44
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
"status": 400,
"code": "INVALID_PAYLOAD",
"extensions": {}
}
```

foreign keys `primary_label` and `secondary_label` are not created.

Table overview from the source database
![valid](https://github.com/directus/directus/assets/1532438/29a99096-e0ef-4b3f-99ae-111402b4888a)

Table overview from where the snapshot is applied
![invalid](https://github.com/directus/directus/assets/1532438/61a6e3ca-ae94-4d63-a31c-bc7f40c901e1)

I have tried to locally apply the snapshot on an empty instance with Postgre 14.5 and there is no error. Also all foreign keys are well created. An obvious difference would be that it is working when there is no data in this table while there is in myproduction env,

### To Reproduce

Here is part of my snapshot related to this table
```
    version: 1
    directus: 10.2.0
    vendor: postgres
    [...]
  - collection: explore_filters
    field: primary_label
    type: uuid
    meta:
      collection: explore_filters
      conditions: null
      display: related-values
      display_options:
        template: '{{key}}'
      field: primary_label
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{key}}'
      readonly: false
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: primary_label
      table: explore_filters
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: front_dictionaries
      foreign_key_column: id
  - collection: explore_filters
    field: secondary_label
    type: uuid
    meta:
      collection: explore_filters
      conditions: null
      display: related-values
      display_options:
        template: '{{key}}'
      field: secondary_label
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{key}}'
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: secondary_label
      table: explore_filters
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: front_dictionaries
      foreign_key_column: id
[...]
```

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gkielwasser** [comment]
I think we need to pass `collection` and  `field` that would not be in the diff
https://github.com/directus/directus/blob/6141092f298c87e54efcaf4e7f1dddf092868100/api/src/utils/apply-diff.ts#L274:L281

Suggestion:
```
await relationsService.createOne({
  ...(diff[0] as DiffNew<Relation>).rhs,
  collection,
  field
}, mutationOptions);
```
