### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'insertBefore')

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#18714]
### Describe the Bug

Front-end bug in Vue components. 

So this bug seems to have started showing up in v10.1.0. and persists in v10.1.1 I have tested it with v10.0.0 too and it does not seem to happen in that version or versions before that. 

In my custom modules randomly sometimes this error will be thrown on the front-end and then lock it down so nothing can be done until the page is reloaded.

```
runtime-core.esm-bundler-e449c3c6.js:1 TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (vue.runtime.esm-bundler-39a4d064.js:1:1466)
    at N (runtime-core.esm-bundler-e449c3c6.js:1:50880)
    at F (runtime-core.esm-bundler-e449c3c6.js:1:50344)
    at P (runtime-core.esm-bundler-e449c3c6.js:1:49774)
    at yn.E [as fn] (runtime-core.esm-bundler-e449c3c6.js:1:53947)
    at yn.run (runtime-core.esm-bundler-e449c3c6.js:1:5089)
    at Z.c.update (runtime-core.esm-bundler-e449c3c6.js:1:54215)
    at Z (runtime-core.esm-bundler-e449c3c6.js:1:54241)
    at L (runtime-core.esm-bundler-e449c3c6.js:1:53086)
    at J (runtime-core.esm-bundler-e449c3c6.js:1:52882)
```

### To Reproduce

In my custom module data is loaded and using `v-if=` and `v-for=` to populate data, I have added null checks so all variables are initialized before being loaded. Bug showed up in v10.1.0 and persists in v10.1.1 

I see a similar bug also showed up in v10.1.0 #18569 
This might be a larger issue. 

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
> In my custom module data is loaded and using v-if= and v-for= to populate data

Can you share the relevant part of your extension? I'm wondering if this is caused by Directus, or the same Vue bug we ran into in the linked PR

**Comment by NecoHorne** [comment]
Hi @rijkvanzanten sure. 

```vue
<template>
  <private-view :title="this.title">

    <template #title-outer:prepend>
      <v-button
          class="header-icon" rounded icon secondary enabled
          @click="$emit('onBackPressed')"
      >
        <font-awesome-icon :icon="['fa', 'arrow-left']" />
      </v-button>
    </template>

    <template #navigation>
      <navigation></navigation>
    </template>

    <template #sidebar>
      <sidebar-detail icon="info" :title="'information'" close>
        <div
            v-md="`This is a list of all your commissions for ${this.statementPeriod} for ${this.insurerName}, Movement code: ${this.movementCodeString} - ${this.movementDescription}`"
            class="page-description"
        >
        </div>
      </sidebar-detail>
    </template>

    <div class="body_content" id="body_div">
      <table>
        <thead class="table-header">
        <tr>
          <th class="cell">Policy Number</th>
          <th class="cell">Client Name</th>
          <th class="cell">Total Commission</th>
          <th class="cell">Policy Age</th>
        </tr>
        </thead>

        <tbody v-if="items">
        <tr class="table-row clickable" v-for="rowItem in items"
            @click="$emit('policyUpdated', rowItem.policy_number)"
        >
          <td class="cell align-left">{{ rowItem.policy_number }}</td>
          <td class="cell align-left">{{ rowItem.client_name }}</td>
          <td class="cell align-left">{{ rowItem.total_commission }}</td>
          <td class="cell align-left">{{ rowItem.policy_age }}</td>
        </tr>
        </tbody>


      </table>

      <div class="footer">
        <div class="pagination">
          <v-pagination
              v-if="this.totalPages > 1"
              :length="this.totalPages"
              :total-visible="7"
              show-first-last
              :model-value="this.page"
              @update:model-value="toPage"
          />
        </div>
      </div>
    </div>

  </private-view>
</template>
```

In the mounted method I make 2 calls to the Directus API to get the number of pages. I re-use a few Directus components in this component too. I see this bug occurs more often when the Directus `v-pagination` component needs to be rendered. 

The mounted API calls: 

```js
  mounted() {
    this.api.get(`/items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&limit=50&page=${this.page}`)
        .then((res) => {
          if (res.data) {
            this.items = res.data.data;
          }
        });

    this.api.get(`items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&aggregate[count]=*`).then((res) => {
      if (res.data) {
        let totalNumItems = res.data.data[0].count;
        this.totalPages = Math.floor(totalNumItems / 50) + 1;
      }
    });
  },
```

I have tested it with versions 10.0.0, 10.1.0 and 10.1.1 and it looks like the bug starts showing up in v10.1.0. I first thought it had something to do with the new pressure limiter because I would also get random responses that the server was under pressure even if it wasn't but I set the limiter to false and the vue bug still occurs so I think you can rule that one out.

**Comment by rijkvanzanten** [comment]
I'm fairly sure that this is a bug in Vue rather than how Directus is handling extensions 🤔 We did update Vue around that time too, so I think that's when the bug snuck in. Just to be sure, can you share the full component rather than just the mounted block? It could be that the bug exists in the code that isn't currently shared

**Comment by NecoHorne** [comment]
Hi @rijkvanzanten, sure here is the full component code, 

I see this bug happen when the pagination/footer needs to be generated. I am trying to re-use as many of the built in Directus components as I can to keep the UI looking the same as the rest of the platform. 

```vue
<template>
  <private-view :title="this.title">

    <template #title-outer:prepend>
      <v-button
          class="header-icon" rounded icon secondary enabled
          @click="$emit('onBackPressed')"
      >
        <font-awesome-icon :icon="['fa', 'arrow-left']"/>
      </v-button>
    </template>
    <template #headline>
      <slot name="subtitle">
        <p class="subtitle">Broker Data Module</p>
      </slot>
    </template>

    <template #actions>
      <search-input
          v-model="this.search"
          collection="commission_line_items"
          @search-update="searchInput"
      ></search-input>
    </template>

    <template #navigation>
      <navigation></navigation>
    </template>

    <template #sidebar>
      <sidebar-detail icon="info" :title="'information'" close>
        <div
            v-md="`This is a list of all your commissions for ${this.statementPeriod} for ${this.insurerName}, Movement code: ${this.movementCodeString} - ${this.movementDescription}`"
            class="page-description"
        >
        </div>
      </sidebar-detail>

      <export-sidebar-detail
          :collection="'commission_line_items'"
          :filter="this.filter"
          :layoutQuery="{
            limit: -1,
            fields: ['policy_number', 'client_name', 'total_commission', 'policy_age', 'commission_period', 'calculation_date']
          }"
      />
    </template>

    <div class="body_content" id="body_div">
      <table>
        <thead class="table-header">
        <tr>
          <th class="cell">Policy Number</th>
          <th class="cell">Client Name</th>
          <th class="cell">Total Commission</th>
          <th class="cell">Policy Age</th>
        </tr>
        </thead>

        <tbody v-if="items">
        <tr class="table-row clickable" v-for="rowItem in items"
            @click="$emit('policyUpdated', rowItem.policy_number)"
        >
          <td class="cell align-left">{{ rowItem.policy_number }}</td>
          <td class="cell align-left">{{ rowItem.client_name }}</td>
          <td class="cell align-left">R{{ Intl.NumberFormat().format(rowItem.total_commission) }}</td>
          <td class="cell align-left">{{ rowItem.policy_age }}</td>
        </tr>
        </tbody>


      </table>

      <div class="footer">
        <div class="pagination">
          <v-pagination
              v-if="this.totalPages > 1"
              :length="this.totalPages"
              :total-visible="7"
              show-first-last
              :model-value="this.page"
              @update:model-value="toPage"
          />
        </div>
      </div>
    </div>

  </private-view>
</template>

<script>
import {library} from '@fortawesome/fontawesome-svg-core'
import {faArrowLeft} from '@fortawesome/free-solid-svg-icons'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'
import Navigation from "./navigation.vue";
import SearchInput from "./search-input.vue";

library.add(faArrowLeft)
export default {
  components: {
    FontAwesomeIcon,
    Navigation,
    SearchInput
  },
  emits: [
    'onBackPressed',
    'policyUpdated',
    'movementPageUpdate'
  ],
  name: "movement_component",
  inject: ['api'],
  props: {
    title: String,
    statementPeriod: String,
    movementCode: Number,
    insurerId: Number,
    page: Number,
    insurerName: String,
    movementCodeString: String,
    movementDescription: String
  },
  data() {
    return {
      items: [],
      totalPages: 1,
      filter: {
        "_and": [
          {
            "creditor": {
              "_eq": this.insurerId
            }
          },
          {
            "movement_code": {
              "_eq": this.movementCode
            }
          },
          {
            "commission_period": {
              "_eq": this.statementPeriod
            }
          }
        ]
      }
    }
  },
  mounted() {
    this.api.get(`/items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&limit=50&page=${this.page}`)
        .then((res) => {
          if (res.data) {
            this.items = res.data.data;
          }
        });

    this.api.get(`items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&aggregate[count]=*`).then((res) => {
      if (res.data) {
        let totalNumItems = res.data.data[0].count;
        this.totalPages = Math.floor(totalNumItems / 50) + 1;
      }
    });
  },
  methods: {
    toPage: function (page) {
      this.$emit('movementPageUpdate', page);
      this.api.get(`/items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&limit=50&page=${page}`)
          .then((res) => {
            if (res.data) {
              this.items = res.data.data;
            }
          });
      let element = document.getElementById("body_div");
      element.scrollIntoView({behavior: "smooth"});
    },
    searchInput: function (val){

      if (val !== null && val !== undefined && val !== '') {
        //   make a search request
        this.api.get(`/items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&search=${val}&limit=50&page=${this.page}`)
            .then((res) => {
              if (res.data) {
                this.items = res.data.data;
              }
            });

        this.api.get(`items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&search=${val}&aggregate[count]=*`).then((res) => {
          if (res.data) {
            let totalNumItems = res.data.data[0].count;
            this.totalPages = Math.floor(totalNumItems / 50) + 1;
          }
        });
      } else {
        this.api.get(`/items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&limit=50&page=${this.page}`)
            .then((res) => {
              if (res.data) {
                this.items = res.data.data;
              }
            });

        this.api.get(`items/commission_line_items?filter[movement_code][_eq]=${this.movementCode}&filter[creditor][_eq]=${this.insurerId}&filter[commission_period][_eq]=${this.statementPeriod}&aggregate[count]=*`).then((res) => {
          if (res.data) {
            let totalNumItems = res.data.data[0].count;
            this.totalPages = Math.floor(totalNumItems / 50) + 1;
          }
        });
      }
    }
  }
}
</script>

<style scoped>
.body_content {
  margin-left: var(--content-padding);
  margin-right: var(--content-padding);
  margin-bottom: var(--content-padding);
}

table {
  min-width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
}

table tbody {
  display: contents;
}

.cell {
  align-items: center;
  padding: 8px 12px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  background-color: var(--v-table-background-color);
  border-bottom: var(--border-width) solid var(--border-subdued);
}

th {
  text-align: left;
}

tbody tr:hover td {
  /*background: #f9f9f9 !important;*/
  background-color: var(--v-list-item-background-color-hover);
}

.footer {
  margin-top: 20px;
}

td {
  user-select: auto !important;
}

</style>
```

**Comment by NecoHorne** [comment]
Hi @rijkvanzanten, I just tested this on 10.3.0 and it seems the bug is no longer there, not sure if it was just maybe some dependency issues or Vue bugs but it seems to have fixed itself. I am happy if you want to close this bug. Will report if I see it somewhere else again. 

Thanks!
