### ISSUE TITLE
Crash flow when calling throw Error

### ISSUE THREAD

**Issue by info-sapphire** [directus/directus#18751]
### Describe the Bug

```
WARN: Error could not be cloned.
    err: {
      "type": "DOMException",
      "message": "Error could not be cloned.",
      "stack":
          DataCloneError: Error could not be cloned.
              at new DOMException (node:internal/per_context/domexception:53:5)
              at structuredClone (node:internal/structured_clone:23:17)
              at redact (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/utils/redact.js:11:19)
              at FlowManager.executeFlow (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/flows.js:281:31)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Promise.all (index 0)
      "name": "DataCloneError",
      "code": 25,
      "INDEX_SIZE_ERR": 1,
      "DOMSTRING_SIZE_ERR": 2,
      "HIERARCHY_REQUEST_ERR": 3,
      "WRONG_DOCUMENT_ERR": 4,
      "INVALID_CHARACTER_ERR": 5,
      "NO_DATA_ALLOWED_ERR": 6,
      "NO_MODIFICATION_ALLOWED_ERR": 7,
      "NOT_FOUND_ERR": 8,
      "NOT_SUPPORTED_ERR": 9,
      "INUSE_ATTRIBUTE_ERR": 10,
      "INVALID_STATE_ERR": 11,
      "SYNTAX_ERR": 12,
      "INVALID_MODIFICATION_ERR": 13,
      "NAMESPACE_ERR": 14,
      "INVALID_ACCESS_ERR": 15,
      "VALIDATION_ERR": 16,
      "TYPE_MISMATCH_ERR": 17,
      "SECURITY_ERR": 18,
      "NETWORK_ERR": 19,
      "ABORT_ERR": 20,
      "URL_MISMATCH_ERR": 21,
      "QUOTA_EXCEEDED_ERR": 22,
      "TIMEOUT_ERR": 23,
      "INVALID_NODE_TYPE_ERR": 24,
      "DATA_CLONE_ERR": 25
    }
```

### To Reproduce

call throw new Error() in flows (blocking operation)

### Directus Version

V10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by lasseklein** [comment]
I have the same issue, and the same happens when returning an item from the last operation

**Comment by rasco** [comment]
I solved this temporarily by disabling activity tracking for the flow.
