### ISSUE TITLE
Internal server error when starting directus

### ISSUE THREAD

**Issue by Yvan2XEro** [directus/directus#18766]
### Describe the Bug

When I launch my Directus application,
I immediately have this internal error, also when I perform actions in my collections

![image](https://github.com/directus/directus/assets/63490400/833ac65f-beb0-4a3f-8502-5a917fa5da47)

I think the error comes from version 10.2 because I had never had this error when in recent versions.

### To Reproduce

Trying to start an old Directus project with version 10.2

### Directus Version

10.2.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by mannyyang** [comment]
I have the same issue once I upgrade to 10.2. Works fine in 10.1.1 though.

**Comment by rijkvanzanten** [comment]
@Yvan2XEro / @mannyyang any errors in the server logs that correspond with this? And/or can you hit the copy button on that error and paste the output here? Ty!

**Comment by mannyyang** [comment]
I was trying to reproduce the error with 10.2 but got a different error this time lol. Page didn't render at all either, only had a full error info component in the center.

```
[20:39:29] GET /auth 200 24ms
[20:39:29] GET /collections 200 81ms
[20:39:29] GET /admin/assets/material-symbols-11d716c0.woff2 200 17ms
[20:39:29] GET /admin/assets/Inter-Bold-f0f54a06.woff2 200 8ms
[20:39:29] GET /admin/assets/Inter-Medium-a4e1e7e6.woff2 200 2ms
[20:39:29] GET /admin/assets/FiraMono-Medium-33e88fa9.woff2 200 4ms
[20:39:29] GET /panels?fields[]=*&sort[]=dashboard&limit=-1 200 47ms
[20:39:29] GET /relations 200 70ms
[20:39:29] GET /dashboards?fields[]=*&sort[]=name&limit=-1 200 67ms
[20:39:29] GET /flows?fields[]=*&fields[]=operations.*&limit=-1 200 75ms
[20:39:29] GET /notifications?filter[_and][0][recipient][_eq]=b48bb9a6-646b-40e7-8ec4-7d6e9c868269&filter[_and][1][status][_eq]=inbox&aggregate[count]=id 200 48ms
[20:39:29.534] ERROR: select "directus_settings"."id", "directus_settings"."project_name", "directus_settings"."project_url", "directus_settings"."project_color", "directus_settings"."project_logo", "directus_settings"."public_foreground", "directus_settings"."public_background", "directus_settings"."public_note", "directus_settings"."auth_login_attempts", "directus_settings"."auth_password_policy", "directus_settings"."storage_asset_transform", "directus_settings"."storage_asset_presets", "directus_settings"."custom_css", "directus_settings"."storage_default_folder", "directus_settings"."basemaps", "directus_settings"."mapbox_key", "directus_settings"."module_bar", "directus_settings"."project_descriptor", "directus_settings"."translation_strings", "directus_settings"."default_language", "directus_settings"."custom_aspect_ratios" from "directus_settings" order by "directus_settings"."id" asc limit $1 - column directus_settings.translation_strings does not exist
    err: {
      "type": "DatabaseError",
      "message": "select \"directus_settings\".\"id\", \"directus_settings\".\"project_name\", \"directus_settings\".\"project_url\", \"directus_settings\".\"project_color\", \"directus_settings\".\"project_logo\", \"directus_settings\".\"public_foreground\", \"directus_settings\".\"public_background\", \"directus_settings\".\"public_note\", \"directus_settings\".\"auth_login_attempts\", \"directus_settings\".\"auth_password_policy\", \"directus_settings\".\"storage_asset_transform\", \"directus_settings\".\"storage_asset_presets\", \"directus_settings\".\"custom_css\", \"directus_settings\".\"storage_default_folder\", \"directus_settings\".\"basemaps\", \"directus_settings\".\"mapbox_key\", \"directus_settings\".\"module_bar\", \"directus_settings\".\"project_descriptor\", \"directus_settings\".\"translation_strings\", \"directus_settings\".\"default_language\", \"directus_settings\".\"custom_aspect_ratios\" from \"directus_settings\" order by \"directus_settings\".\"id\" asc limit $1 - column directus_settings.translation_strings does not exist",
      "stack":
          error: select "directus_settings"."id", "directus_settings"."project_name", "directus_settings"."project_url", "directus_settings"."project_color", "directus_settings"."project_logo", "directus_settings"."public_foreground", "directus_settings"."public_background", "directus_settings"."public_note", "directus_settings"."auth_login_attempts", "directus_settings"."auth_password_policy", "directus_settings"."storage_asset_transform", "directus_settings"."storage_asset_presets", "directus_settings"."custom_css", "directus_settings"."storage_default_folder", "directus_settings"."basemaps", "directus_settings"."mapbox_key", "directus_settings"."module_bar", "directus_settings"."project_descriptor", "directus_settings"."translation_strings", "directus_settings"."default_language", "directus_settings"."custom_aspect_ratios" from "directus_settings" order by "directus_settings"."id" asc limit $1 - column directus_settings.translation_strings does not exist
              at Parser.parseErrorMessage (/Users/manuelyang/git/supernovo.ai-directus/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/Users/manuelyang/git/supernovo.ai-directus/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/Users/manuelyang/git/supernovo.ai-directus/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/Users/manuelyang/git/supernovo.ai-directus/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:324:12)
              at readableAddChunk (node:internal/streams/readable:297:9)
              at Readable.push (node:internal/streams/readable:234:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 136,
      "name": "error",
      "severity": "ERROR",
      "code": "42703",
      "position": "696",
      "file": "parse_relation.c",
      "line": "3651",
      "routine": "errorMissingColumn"
    }
```

**Comment by br41nslug** [comment]
> I was trying to reproduce the error with 10.2

Did you downgrade the migration from 10.2.1 when testing? Judging from the error it tries to read the `translation_strings` column which was removed in 10.2.1

> column directus_settings.translation_strings does not exist

Make sure all caches are cleared after upgrading 😄 In this light the original error could have been the effect of the newly created `directus_translations` table not being in the cached schema.

**Comment by mannyyang** [comment]
Might be a dumb question, but when you're referring to caches, are you referring to the browser cache?

**Comment by br41nslug** [comment]
@mannyyang i meant all the caches 😄 including browser cache but also (optionally) Redis and Directus internal cache https://github.com/directus/directus/issues/18782

**Comment by br41nslug** [comment]
Awesome, do make sure you run that or `bootstrap` after each update make sure all migrations have been run 😄
