### ISSUE TITLE
Unable to connect with localhost MYSQL from direct us docker image

### ISSUE THREAD

**Issue by bondmojo** [directus/directus#18845]
### Describe the Bug

I am unable to connect with my mysql instance when I run following command:

_docker run --env-file .env directus/directus:9_

I get following error :

[09:30:14.386] INFO: Initializing bootstrap...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user '"root"'@'172.20.0.1' (using password: YES)
    at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:116:18)
    at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/client.js:254:39) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: `Access denied for user '"root"'@'172.20.0.1' (using password: YES)`,
  sqlState: '28000',
  fatal: true
}

Node.js v18.16.0

### To Reproduce

1. Run on Latest macos.
2. Have mysql running inside your MAC docker.
3. Download directus image.
4. change directus/.env file to following configuration:
HOST="0.0.0.0"
PORT=8055

KEY="255d861b-5ea1-5996-9aa3-922530ec40b1"
SECRET="6116487b-cda1-52c2-b5b5-c8022c45e263"

DB_CLIENT="mysql" 
DB_DATABASE="db_name" 
DB_HOST="host.docker.internal" 
DB_PORT=3306 
DB_USER="root"
DB_PASSWORD="passwprd"

ADMIN_EMAIL="something@something.com"
ADMIN_PASSWORD="something@123"

### Directus Version

Latest, 10, 9

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by bondmojo** [comment]
I am unable to run it using docker run but if I run it using docker-compose up . this works perfectly fine

**Comment by paescuj** [comment]
You need to pass the config options to the `docker run` command like
```bash
docker run -p 8055:8055 -e KEY=... -e SECRET=... -e DB_CLIENT=mysql -e DB_HOST=host.docker.internal -e DB_PORT=3306 -e DB_DATABASE=... -e DB_USER=... -e DB_PASSWORD=... directus/directus
```

See also https://docs.directus.io/self-hosted/docker-guide.html.
