### ISSUE TITLE
Custom Endpoints couldn't register for latest version.

### ISSUE THREAD

**Issue by khunsatant** [directus/directus#18909]
### Describe the Bug

I create a custom endpoint extension with the latest version. when I load this extension to directus and I face with below error:

`[15:05:20.513] INFO: Reloading extensions
[15:05:20.527] WARN: Couldn't register endpoint "gb_test"
[15:05:20.527] WARN: Unexpected token 'export'
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token 'export'",
      "stack":
          /Users/khunsatant/Development/0-Projects/golden_brain/extensions/endpoints/gb_test/index.js:1
          var e=e=>{e.get("/",((e,l)=>l.send("Hello, World!")))};export{e as default};
                                                                 ^^^^^^
          
          SyntaxError: Unexpected token 'export'
              at Object.compileFunction (node:vm:360:18)
              at wrapSafe (node:internal/modules/cjs/loader:1088:15)
              at Module._compile (node:internal/modules/cjs/loader:1123:27)
              at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
              at Module.load (node:internal/modules/cjs/loader:1037:32)
              at Module._load (node:internal/modules/cjs/loader:878:12)
              at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
              at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
              at async Promise.all (index 0)
              at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
              at async ExtensionManager.registerEndpoints (file:///Users/khunsatant/Development/0-Projects/golden_brain/node_modules/@directus/api/dist/extensions.js:316:42)
              at async ExtensionManager.load (file:///Users/khunsatant/Development/0-Projects/golden_brain/node_modules/@directus/api/dist/extensions.js:183:9)
              at async file:///Users/khunsatant/Development/0-Projects/golden_brain/node_modules/@directus/api/dist/extensions.js:97:17
              at async JobQueue.run (file:///Users/khunsatant/Development/0-Projects/golden_brain/node_modules/@directus/api/dist/utils/job-queue.js:18:13)
    }`

### To Reproduce

1. create new extension with `npm init directus-extension@latest`.
2. select `endpoints` and choose `javascript` language.
3. use the default code then build and copy `index.js` to `/extensions/endpoints/gb_test/index.js`.
4. when run `npx directus start` will face the error!

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by khunsatant** [comment]
I just found the solution, the built extension `index.js` use ES6 `export { index as default };`
then I added `"type": "module"` in `package.json` and I have to change the old extension to `.cjs` to tell Node.js which one is ES6 or common js.

**Comment by br41nslug** [comment]
Glad you found the solution, extensions indeed either need to be ESM (with `"type": "module"` in `package.json`) or use CJS with a `*.cjs` extension
