### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by ps73** [directus/directus#18935]
### Describe the Bug

I have create a new directus project with the cli.
The project runs correctly but listing roles is not working.
Every time opening the roles page following error occures:
Cannot read properties of undefined (reading 'id')

```json
{
  "stack": "TypeError: Cannot read properties of undefined (reading 'id')\n    at http://localhost:8055/admin/assets/index.aa47f040.entry.js:2949:339979\n    at Array.map (<anonymous>)\n    at l (http://localhost:8055/admin/assets/index.aa47f040.entry.js:2949:339906)",
  "message": "Cannot read properties of undefined (reading 'id')"
}
```
![Screenshot 2023-06-19 at 15 39 02](https://github.com/directus/directus/assets/17291660/3edea181-9f28-496a-ba6b-00b63117ce8d)

### To Reproduce

- Init directus through cli
  - Postgres (Docker Image postgis/postgis:13-master)
- Opening http://localhost:8055/admin/settings/roles

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This looks like it could be same as #18917

**Comment by ps73** [comment]
Okay, I have to withdraw my message from yesterday. Since today the error appears again.

I think this issue is related to #17142. Something with deep aggregations is not working.
