### ISSUE TITLE
Parts of field validations are not working as expected

### ISSUE THREAD

**Issue by Triggsy22** [directus/directus#18955]
### Describe the Bug

Hello,

parts of field validations are not working as expected.

### To Reproduce

Example 1
1. Create a simple String Field 'A' in Directus Users. 
2. Create Many to One Field 'B' in Directus Users, that has a relationship to Directus Users
3. In Field 'B' add a validation 'B -> A Isn't null'
4. Edit a User and write any value in Field A.
5. Edit an other User and add in Field B, the User that was edited before (that has a value in Field A)
Now an Error Message appears: {"errors":[{"message":"\"B\" must be of type object","extensions":{"code":"FAILED_VALIDATION","field":"B"}}]}

Example 2
1. Create Many to One Field 'C' in Directus Users, that has a relationship to Directus Users
2. Add to this Field a Validation: 'C Contains $CURRENT_USER'
3. Edit a User and add the Current User to Field C.
4. {"errors":[{"message":"\"C\" must contain [$CURRENT_USER]","extensions":{"code":"FAILED_VALIDATION","field":"C","type":"contains","substring":"$CURRENT_USER"}}]}

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
Might be related to #18898 ?

**Comment by Triggsy22** [comment]
I dont think so, cause the Bug from #18898 do exist only since 10.3.0
My Bug was also present in Version 10.1.1
But i dont know if it was fixed and was added again with Version 10.3.0

**Comment by Triggsy22** [comment]
Since Directus 10.4 both examples have got new error messages:

in example 1: `{"errors":[{"message":"Couldn't extract validation error type from Joi validation error item","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

example 2: `{"errors":[{"message":"Validation failed for field \"C\". Value has to contain \"$CURRENT_USER\".","extensions":{"code":"FAILED_VALIDATION","field":"C","type":"contains","substring":"$CURRENT_USER"}}]}`

$CURRENT_USER is normaly a dynamic variable, like explained here: https://docs.directus.io/reference/filter-rules.html#dynamic-variables

**Comment by AKhateeb** [comment]
I've just encoutered just error whiule trying to import an image using Directus Flows, I'm using Fillout to get user image (because we don't have public forms in Directus :))

This is the error from logs:
```
{"severity":"ERROR","level":50,"time":1735939760382,"pid":28,"hostname":"srv604752","err":{"type":"Error","message":"Couldn't extract validation error type from Joi validation error item","stack":"Error: Couldn't extract validation error type from Joi validation error item\n    at joiValidationErrorItemToErrorExtensions (file:///directus/node_modules/.pnpm/@directus+validation@file+packages+validation_vue@3.5.11_typescript@5.6.3_/node_modules/@directus/validation/dist/index.js:168:11)\n    at file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:70:86\n    at Array.map (<anonymous>)\n    at file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:70:43\n    at Array.map (<anonymous>)\n    at processPayload (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:70:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/items.js:125:19"},"message":"Couldn't extract validation error type from Joi validation error item"}
```
