### ISSUE TITLE
issues with using a migrated database

### ISSUE THREAD

**Issue by Aprilswind** [directus/directus#19035]
### Describe the Bug

```
placement-website-gct-api-1       | [21:43:30.612] INFO: Initializing bootstrap...
placement-website-gct-postgres-1  | 2023-06-29 21:43:35.670 UTC [70] ERROR:  constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
placement-website-gct-postgres-1  | 2023-06-29 21:43:35.670 UTC [70] STATEMENT:  alter table "directus_fields" drop constraint "directus_fields_collection_foreign"
placement-website-gct-api-1       | error: alter table "directus_fields" drop constraint "directus_fields_collection_foreign" - constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
placement-website-gct-api-1       |     at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
placement-website-gct-api-1       |     at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
placement-website-gct-api-1       |   detail: undefined,
placement-website-gct-api-1       |   hint: undefined,
placement-website-gct-api-1       |   position: undefined,
placement-website-gct-api-1       |   internalPosition: undefined,
placement-website-gct-api-1       |   internalQuery: undefined,
placement-website-gct-api-1       |   where: undefined,
placement-website-gct-api-1       |   schema: undefined,
placement-website-gct-api-1       |   table: undefined,
placement-website-gct-api-1       |   column: undefined,
placement-website-gct-api-1       |   dataType: undefined,
placement-website-gct-api-1       |   constraint: undefined,
placement-website-gct-api-1       |   file: 'tablecmds.c',
placement-website-gct-api-1       |   line: '12027',
placement-website-gct-api-1       |   routine: 'ATExecDropConstraint'
placement-website-gct-api-1       | }
placement-website-gct-api-1       | [21:43:35.662] INFO: Database already initialized, skipping install
placement-website-gct-api-1       | [21:43:35.662] INFO: Running migrations...
placement-website-gct-api-1       | [21:43:35.668] INFO: Applying Remove Collection Foreign Keys...
placement-website-gct-api-1 exited with code 1
```

### To Reproduce

docker compose - postgres and directus
after setting up and logging in directus web gui, pg_dump the postgres database with only schema for all the tables
stop all the containers and spin up the compose again but this time use the sql dump for migration 

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Aprilswind** [comment]
https://github.com/directus/directus/issues/3551
close to this but i havent deleted any tables in the database

**Comment by paescuj** [comment]
Please make sure that the constraints are properly backed up & restored. As you can see in the error message, it seems like these are missing.
Since this is not an issue with Directus itself, please follow https://docs.directus.io/getting-started/support.html#community-support if you have any further questions.
