### ISSUE TITLE
Node:module isBuiltin does not provide an export named "isBuiltIn"

### ISSUE THREAD

**Issue by com-pote** [directus/directus#19195]
### Describe the Bug

I try to update directus then when i launch it here is what the cli prompt :

```
file:///home/cubwolf/oriflamme/directus/node_modules/@directus/api/dist/operations/exec/index.js:2
import { isBuiltin } from 'node:module';
         ^^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'isBuiltin'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async ExtensionManager.registerOperations (file:///home/cubwolf/oriflamme/directus/node_modules/@directus/api/dist/extensions.js:328:39)
    at async ExtensionManager.load (file:///home/cubwolf/oriflamme/directus/node_modules/@directus/api/dist/extensions.js:182:9)
    at async ExtensionManager.initialize (file:///home/cubwolf/oriflamme/directus/node_modules/@directus/api/dist/extensions.js:79:13)
    at async createCli (file:///home/cubwolf/oriflamme/directus/node_modules/@directus/api/dist/cli/index.js:21:5)```
```

### To Reproduce

Install directus with the CLI :

- npx directus start
- edit the package.json and add "directus": "^10.4.3" in dependencies
- launch npm update
- and try to start directus for example with npx directus start

### Directus Version

V10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Make sure your Node version is up to date (LTS or current, 18 or 20 at time of writing) 👍🏻

**Comment by com-pote** [comment]
I got v18.4.0 and the bug is still there :/

**Comment by rijkvanzanten** [comment]
Node LTS is 18.16, not 18.4 👍🏻 Seems like `isBuiltin` was added in 18.6, which explains why you were seeing the error in 18.4 🙂 Either 18.16 or 20.4 should work 🚀 

<img width="400" alt="CleanShot 2023-07-18 at 16 03 31@2x" src="https://github.com/directus/directus/assets/9141017/51388345-07ad-4e87-8ab2-c3a9f911a2ef">
