### ISSUE TITLE
Latest directus docker tag, after pulling, break the current App.

### ISSUE THREAD

**Issue by amitshuklabag** [directus/directus#19306]
### Describe the Bug

My Application crashed with this message on Sunday after pulling the latest tag of the Directus image.

Along with Directus, I'm using the Postgres DB docker image.

I have manually tried to remove the foreign key constraint in db but no luck.

```
directus    | Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'
directus    |     at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus    |     at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus    |     at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus    |     at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus    |     at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus    |     at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus    |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
directus    |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
directus    |     at Socket.emit (node:events:514:28)
directus    |     at addChunk (node:internal/streams/readable:324:12)
directus    |     at readableAddChunk (node:internal/streams/readable:297:9)
directus    |     at Readable.push (node:internal/streams/readable:234:10)
directus    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus    |     --------------------
directus    |     at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus    |     at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
directus    |     at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18
directus    |     at new Promise (<anonymous>)
directus    |     at Client_MySQL._query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)
directus    |     at executeQuery (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
directus    |     at Client_MySQL.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)
directus    |     at Runner.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)
directus    |     at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
directus    |     at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:20)
directus    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus    |     at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)
directus    |     at async Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:20)
directus    |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:14)
directus    |     at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)
directus    |     at async up (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5) {
directus    |   code: 'ER_FK_COLUMN_CANNOT_CHANGE',
directus    |   errno: 1832,
directus    |   sqlMessage: "Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'",
directus    |   sqlState: 'HY000',
directus    |   index: 0,
directus    |   sql: 'alter table `directus_shares` modify  `collection  varchar(64) not null '

```

### To Reproduce

I always update my image using the latest tag on Sundays since I use it. However, this past Sunday, when I pulled the latest  tag, the problem began to appear.

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by miknyko** [comment]
same issue here with dockertag==10.5.2, and mysql==5.7.37

**Comment by DanielBiegler** [comment]
Same error in #19335 and can be fixed by upgrading to mysql8 - mysql5 is end-of-life in 3months and should be replaced.
