### ISSUE TITLE
globalThis.fetch is not a function

### ISSUE THREAD

**Issue by 50l3r** [directus/directus#19322]
### Describe the Bug

When i try to execute `readItems`  on a Node environment i recieve this error:

```
TypeError: globalThis.fetch is not a function
    at request (D:\Git\anomaly\node_modules\@directus\sdk\src\utils\request.ts:30:4)
    at Object.request (D:\Git\anomaly\node_modules\@directus\sdk\src\rest\composable.ts:73:28)
    at DirectusService.onModuleInit (D:\Git\anomaly\src\providers\directus\directus.service.ts:40:32)
```

This is a minimal repo por the problem:

```
@Injectable()
export class DirectusService implements OnModuleInit {
    private url = ''
    private token = ''

    public client: DirectusClient<Schema> & RestClient<Schema> & StaticTokenClient<Schema>

    constructor(private $config: ConfigService) {
        this.url = $config.get('directus.url')
        this.token = $config.get('directus.token')

        this.client = createDirectus<Schema>(this.url).with(staticToken(this.token)).with(rest())
    }

    async onModuleInit() {
        try {
            const plattforms = await this.client.request(readItems('plattform'))

            if (plattforms.length > 0) {
                console.log('Connected to Directus API')
            } else {
                throw new Error('No plattforms found')
            }
        } catch (error) {
            console.error(error)
        }
    }
}
```

Nodejs: 16.16
Directus SDK: 11.0.1

### To Reproduce

1. Instance a directus client with static token and rest composable
2. Execute readItems for a specific collection 

### Directus Version

10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by 50l3r** [comment]
I solve it installing `node-fetch@2` and assign to globalThis

```
import fetch, { Headers, Request, Response } from 'node-fetch'

if (!('fetch' in globalThis)) {
    Object.assign(globalThis, { fetch, Headers, Request, Response })
}
```

**Comment by br41nslug** [comment]
Correct the SDK is relying on the globbally provided fetch function (same for WebSocket and URL) which would need to be polyfilled for runtimes that do not provide it. NodeJS only includes `fetch` from v18 and up so as you've already found <18 will require this polyfill https://github.com/node-fetch/node-fetch#providing-global-access
