### ISSUE TITLE
directus bootstrap error

### ISSUE THREAD

**Issue by leosin** [directus/directus#19335]
### Describe the Bug

i'm install with manual 
already created database
when i bootstrap directus it make this error

```bash
[11:20:35.192] INFO: Applying Add Preview Settings...
[11:20:35.221] INFO: Applying Migrate Translation Strings...
Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'
    at Sequence._packetToError (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
    at /www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:300:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:30:19)
    at async Runner.queryArray (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:269:20)
    at async Runner.ensureConnection (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:300:14)
    at async Runner.run (/www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/knex@2.4.2_j3aeqb6pdcaevsexibjmrswwki/node_modules/knex/lib/execution/runner.js:30:19)
    at async up (file:///www/.pnpm-store/v3/tmp/dlx-2121047/node_modules/.pnpm/@directus+api@12.1.2/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5) {
  code: 'ER_FK_COLUMN_CANNOT_CHANGE',
  errno: 1832,
  sqlMessage: "Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'",
  sqlState: 'HY000',
  index: 0,
  sql: 'alter table `directus_shares` modify  `collection` varchar(64) not null '
}
[11:20:35.307] INFO: Applying Require Shares Fields...

 ERROR  Command failed with exit code 1: directus bootstrap

pnpm: Command failed with exit code 1: directus bootstrap
    at makeError (/www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:23105:17)
    at handlePromise (/www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:23676:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:215761:7)
    at async /www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:223352:21
    at async main (/www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:223321:34)
    at async runPnpm (/www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:223551:5)
    at async /www/ois/node/lib/node_modules/pnpm/dist/pnpm.cjs:223543:7
```

### To Reproduce

```bash
pnpm dlx directus bootstrap
# or
pnpm directus bootstrap
#or
pnpx directus bootstrap
```

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by leosin** [comment]
then. i fallback to v10.4.3
it works

**Comment by miknyko** [comment]
same issue here with 10.5.2

**Comment by DanielBiegler** [comment]
Tested with a new sqlite DB and it runs successfully. Then started up a MySQL Server 8.1.0-1.el8 instance and ran bootstrap, also runs successfully.

```log
[12:05:14.436] INFO: Applying Add Origin to Accountability...
[12:05:14.467] INFO: Applying Update Material Icons...
[12:05:14.508] INFO: Applying Add Preview Settings...
[12:05:14.534] INFO: Applying Migrate Translation Strings...
[12:05:14.574] INFO: Applying Require Shares Fields...
[12:05:14.697] INFO: Setting up first admin role...
[12:05:14.707] INFO: Adding first admin user...
[12:05:14.810] INFO: Done
```

Which version are you running?

**Comment by miknyko** [comment]
Yes, MySql==5.7.37. Then I switched to 8.0.25, and it worked!

**Comment by DanielBiegler** [comment]
Great! Since MySql 5.7 is reaching [end of life support](https://endoflife.date/mysql) in 3 months, I'd say this is the path forward.

**Comment by leosin** [comment]
i use MySQL 8.0.25

**Comment by Sothos** [comment]
I have the same issue using AWS Aurora (MySQL 8.0.3) when upgrading from Directus 10.4.3 to 10.5.3

```Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'
at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)	
at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)	
at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)	
at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)	
at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)	
at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)	
at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)	
at Socket.emit (node:events:514:28)	
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)	
at Readable.push (node:internal/streams/readable:234:10)	
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)	
at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)	
at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)	
at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18	
at new Promise (<anonymous>)	
at Client_MySQL._query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)	
at executeQuery (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)	
at Client_MySQL.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)	
at Runner.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)	
at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)	
at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:20)	
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)	
at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)	
at async Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:20)	
at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:14)	
at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)	
at async up (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5) {	
code: 'ER_FK_COLUMN_CANNOT_CHANGE',	
errno: 1832,	
sqlMessage: "Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'",	
sqlState: 'HY000',	
index: 0,	
sql: 'alter table `directus_shares` modify `collection` varchar(64) not null '	
}
```
