### ISSUE TITLE
Upgrading from Docker image 10.4.3 to 10.5.3 breaks the app on database migration

### ISSUE THREAD

**Issue by Sothos** [directus/directus#19399]
### Describe the Bug

I have this issue using AWS Aurora (MySQL 8.0.3) when upgrading from Directus 10.4.3 to 10.5.3.
This was already reported twice, I believe. I am running the latest version of MySQL on AWS.
I do not use sharing, and all collections "sharing" column is "No Access" in project settings.

```
Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'
at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)	
at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)	
at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)	
at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)	
at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)	
at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)	
at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)	
at Socket.emit (node:events:514:28)	
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)	
at Readable.push (node:internal/streams/readable:234:10)	
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)	
at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)	
at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)	
at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18	
at new Promise (<anonymous>)	
at Client_MySQL._query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)	
at executeQuery (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)	
at Client_MySQL.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)	
at Runner.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)	
at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)	
at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:20)	
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)	
at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)	
at async Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:20)	
at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:300:14)	
at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:30:19)	
at async up (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5) {	
code: 'ER_FK_COLUMN_CANNOT_CHANGE',	
errno: 1832,	
sqlMessage: "Cannot change column 'collection': used in a foreign key constraint 'directus_shares_collection_foreign'",	
sqlState: 'HY000',	
index: 0,	
sql: 'alter table `directus_shares` modify `collection` varchar(64) not null '	
}
```

### To Reproduce

Changed my Dockerfile from

```
FROM directus/directus:10.4.3
COPY . .
```

to 

```
FROM directus/directus:10.5.3
COPY . .
```

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by andreacocci95** [comment]
Hi, I had the same problem of @Sothos and I waited until next release was released. I updated directus from 10.4.3 to 10.5.3 and everything fine except form db migration. When 10.6.0 was relesed, I updated directus and after tried to do the migration command for the database, but I receive the same error:

```
ERROR: alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists
    err: {
      "type": "Error",
      "message": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists",
      "stack":
          Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists
              at Sequence._packetToError (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:324:12)
              at readableAddChunk (node:internal/streams/readable:297:9)
              at Readable.push (node:internal/streams/readable:234:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              --------------------
              at Protocol._enqueue (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:198:25)
              at /home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/client.js:146:12)
              at Runner.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:217:21)
              at Runner.queryArray (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:269:31)
              at ensureConnectionCallback (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
              at Runner.ensureConnection (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:300:20)
              at async Runner.run (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:30:19)
              at async up (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5)
              at async latest (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/run.js:101:17)
              at async run (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/run.js:43:9)
      "code": "ER_CANT_DROP_FIELD_OR_KEY",
      "errno": 1091,
      "sqlMessage": "Can't DROP 'directus_shares_collection_foreign'; check that column/key exists",
      "sqlState": "42000",
      "index": 0,
      "sql": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign`"
    }
```

What can I do? Thanks!

**Comment by br41nslug** [comment]
Seems this issue may not have been completely resolved, will require some re-testing

**Comment by paescuj** [comment]
> Hi, I had the same problem of @Sothos and I waited until next release was released. I updated directus from 10.4.3 to 10.5.3 and everything fine except form db migration. When 10.6.0 was relesed, I updated directus and after tried to do the migration command for the database, but I receive the same error:
> 
> ```
> ERROR: alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists
>     err: {
>       "type": "Error",
>       "message": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists",
>       "stack":
>           Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_shares_collection_foreign'; check that column/key exists
>               at Sequence._packetToError (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>               at Query.ErrorPacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
>               at Protocol._parsePacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:291:23)
>               at Parser._parsePacket (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Parser.js:433:10)
>               at Parser.write (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Parser.js:43:10)
>               at Protocol.write (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>               at Socket.<anonymous> (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:88:28)
>               at Socket.<anonymous> (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:526:10)
>               at Socket.emit (node:events:513:28)
>               at addChunk (node:internal/streams/readable:324:12)
>               at readableAddChunk (node:internal/streams/readable:297:9)
>               at Readable.push (node:internal/streams/readable:234:10)
>               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
>               --------------------
>               at Protocol._enqueue (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>               at Connection.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/mysql/lib/Connection.js:198:25)
>               at /home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/dialects/mysql/index.js:132:18
>               at new Promise (<anonymous>)
>               at Client_MySQL._query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/dialects/mysql/index.js:126:12)
>               at executeQuery (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
>               at Client_MySQL.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/client.js:146:12)
>               at Runner.query (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:123:36)
>               at Runner.queryArray (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:217:21)
>               at Runner.queryArray (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:269:31)
>               at ensureConnectionCallback (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
>               at Runner.ensureConnection (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:300:20)
>               at async Runner.run (/home/andreacocci/Projects/fantacalcista_admin/node_modules/knex/lib/execution/runner.js:30:19)
>               at async up (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/20230721A-require-shares-fields.js:2:5)
>               at async latest (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/run.js:101:17)
>               at async run (file:///home/andreacocci/Projects/fantacalcista_admin/node_modules/@directus/api/dist/database/migrations/run.js:43:9)
>       "code": "ER_CANT_DROP_FIELD_OR_KEY",
>       "errno": 1091,
>       "sqlMessage": "Can't DROP 'directus_shares_collection_foreign'; check that column/key exists",
>       "sqlState": "42000",
>       "index": 0,
>       "sql": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign`"
>     }
> ```
> 
> What can I do? Thanks!

What database are you using? I've tested the migration against MySQL on AWS before submitting #19407 🤔

**Comment by andreacocci95** [comment]
I'm using MySQL.

**Comment by Sothos** [comment]
I have not tried to upgrade to 10.6.0 yet, so I can't confirm if the fix works for me or not. I won't be able to test the upgrade until next week.

**Comment by prikr** [comment]
Upgraded to 10.6.1 today and stumbled on this exact same error to. Even when not editing anything in collections, a database migration issued this.

**Comment by paescuj** [comment]
> Upgraded to 10.6.1 today and stumbled on this exact same error too. Even when not editing anything in collections, a database migration issued this.

Which one of the errors, the one in the original post or the one posted in https://github.com/directus/directus/issues/19399#issuecomment-1695659393?
What database are you using (version, hosting, ...)?

Currently a bit hard to reproduce because of the general lack of information.

**Comment by prikr** [comment]
> > Upgraded to 10.6.1 today and stumbled on this exact same error too. Even when not editing anything in collections, a database migration issued this.
> 
> Which one of the errors, the one in the original post or the one posted in [#19399 (comment)](https://github.com/directus/directus/issues/19399#issuecomment-1695659393)? What database are you using (version, hosting, ...)?
> 
> Currently a bit hard to reproduce because of the general lack of information.

`   err: {
      "type": "Error",
      "message": "alter table `applications` modify `app_connection_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
      "stack":
          Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'
              at Query.Sequence._packetToError (/app/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/app/admin/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/app/admin/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              --------------------
              at Protocol._enqueue (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/app/admin/node_modules/mysql/lib/Connection.js:198:25)
              at /app/admin/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/app/admin/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/app/admin/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/app/admin/node_modules/knex/lib/client.js:146:12)
              at /app/admin/node_modules/knex/lib/execution/transaction.js:363:24
              at new Promise (<anonymous>)
              at Client_MySQL.trxClient.query (/app/admin/node_modules/knex/lib/execution/transaction.js:358:12)
              at Runner.query (/app/admin/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/app/admin/node_modules/knex/lib/execution/runner.js:217:21)
              at ensureConnectionCallback (/app/admin/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
              at Runner.ensureConnection (/app/admin/node_modules/knex/lib/execution/runner.js:300:20)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async Runner.run (/app/admin/node_modules/knex/lib/execution/runner.js:30:19)
      "code": "ER_FK_COLUMN_CANNOT_CHANGE",
      "errno": 1832,
      "sqlMessage": "Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
      "sqlState": "HY000",
      "index": 0,
      "sql": "alter table `applications` modify `app_connection_id` int"
    }`
    
    @paescuj  This is the full error log!

**Comment by prikr** [comment]
Any update on this? I cant downgrade too, so all my development is stuck atm.

**Comment by paescuj** [comment]
Unfortunately, I'm still not able to reproduce the newer error `ER_CANT_DROP_FIELD_OR_KEY`, even tried with Percona 5.7.

I'll create a PR with a potential solution, but since I'm unable to reproduce, I cannot guarantee that it will actually fix the issue.

Can you please run `SHOW CREATE TABLE directus_shares;` in your database instance and share the output here?
In general, any additional information like database configuration, version, and so on would be appreciated.

**Comment by prikr** [comment]
@paescuj sure.

`SHOW CREATE TABLE directus_shares; :`
<html>
<body>


Table | Create Table |  
-- | -- | --
directus_shares | CREATE TABLE `directus_shares` (   `id` char(36) NOT NULL,   `name` varchar(255) DEFAULT NULL,   `collection` varchar(64) NOT NULL,   `item` varchar(255) NOT NULL,   `role` char(36) DEFAULT NULL,   `password` varchar(255) DEFAULT NULL,   `user_created` char(36) DEFAULT NULL,   `date_created` timestamp NOT NULL DEFAULT current_timestamp(),   `date_start` timestamp NULL DEFAULT NULL,   `date_end` timestamp NULL DEFAULT NULL,   `times_used` int(11) DEFAULT 0,   `max_uses` int(11) DEFAULT NULL,   PRIMARY KEY (`id`),   KEY `directus_shares_role_foreign` (`role`),   KEY `directus_shares_user_created_foreign` (`user_created`),   KEY `directus_shares_collection_foreign` (`collection`),   CONSTRAINT `directus_shares_collection_foreign` FOREIGN KEY (`collection`) REFERENCES `directus_collections` (`collection`) ON DELETE CASCADE,   CONSTRAINT `directus_shares_role_foreign` FOREIGN KEY (`role`) REFERENCES `directus_roles` (`id`) ON DELETE CASCADE,   CONSTRAINT `directus_shares_user_created_foreign` FOREIGN KEY (`user_created`) REFERENCES `directus_users` (`id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3


</body>
</html>



Usage of Database:
<html>
<body>


Service | Version
-- | --
MariaDB | 10.6.8-0


</body>
</html>

**Comment by paescuj** [comment]
Thank you very much @prikr! However, I've just noticed that the error you shared in https://github.com/directus/directus/issues/19399#issuecomment-1705595755 is not related to the migration. May I ask you to open a new issue for this, possibly including the corresponding schema snapshot?

**Comment by prikr** [comment]
> Thank you very much @prikr! However, I've just noticed that the error you shared in [#19399 (comment)](https://github.com/directus/directus/issues/19399#issuecomment-1705595755) is not related to the migration. May I ask you to open a new issue for this, possibly including the corresponding schema snapshot?

@paescuj Sure, i created #19615.
