### ISSUE TITLE
Drag and Drop Collections in Data Model products Axios 400 error in console and server logs

### ISSUE THREAD

**Issue by bamboowonder** [directus/directus#19494]
### Describe the Bug

When dragging and dropping to rearrange the order of Collections in the Data Model area,the new position is not saved to the PG15 database.

Errors in console log is:

{"errors":[{"message":"Invalid payload. Collection in update misses collection key.","extensions":{"code":"INVALID_PAYLOAD","reason":"Collection in update misses collection key"}}]}

https://xxxxxx.xxxxxx.com/collections 400
(anonymous) @ index-31135a8b.js:3
xhr @ index-31135a8b.js:3
Dt @ index-31135a8b.js:3
Promise.then (async)
request @ index-31135a8b.js:3
(anonymous) @ index-31135a8b.js:3
(anonymous) @ index-31135a8b.js:1
c @ index.01542e04.entry.js:2949
N.onUpdate:modelValue.f.<computed>.f.<computed> @ index.01542e04.entry.js:2949
$e @ runtime-core.esm-bundler-474556af.js:1
Ae @ runtime-core.esm-bundler-474556af.js:1
di @ runtime-core.esm-bundler-474556af.js:1
alterList @ index.01542e04.entry.js:61
updatePosition @ index.01542e04.entry.js:61
onDragUpdate @ index.01542e04.entry.js:61
(anonymous) @ index.01542e04.entry.js:61
(anonymous) @ index.01542e04.entry.js:61
S3 @ index.01542e04.entry.js:58
mp @ index.01542e04.entry.js:58
_onDrop @ index.01542e04.entry.js:58
index-31135a8b.js:3 Uncaught (in promise) g {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: {id: 'vDwugzjWV334O3-HJhq_V', transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), …}message: "Request failed with status code 400"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}response: {data: {…}, status: 400, statusText: '', headers: Ce, config: {…}, …}stack: "AxiosError: Request failed with status code 400\n    at na (https://xxxxxx.xxxxxx.com/admin/assets/index-31135a8b.js:3:947)\n    at XMLHttpRequest.h (https://xxxxxx.xxxxxx.com/admin/assets/index-31135a8b.js:3:4080)"[[Prototype]]: Error
XMLHttpRequest.send (async)
(anonymous) @ index-31135a8b.js:3
xhr @ index-31135a8b.js:3
Dt @ index-31135a8b.js:3
Promise.then (async)
request @ index-31135a8b.js:3
(anonymous) @ index-31135a8b.js:3
(anonymous) @ index-31135a8b.js:1
c @ index.01542e04.entry.js:2949
N.onUpdate:modelValue.f.<computed>.f.<computed> @ index.01542e04.entry.js:2949
$e @ runtime-core.esm-bundler-474556af.js:1
Ae @ runtime-core.esm-bundler-474556af.js:1
di @ runtime-core.esm-bundler-474556af.js:1
alterList @ index.01542e04.entry.js:61
updatePosition @ index.01542e04.entry.js:61
onDragUpdate @ index.01542e04.entry.js:61
(anonymous) @ index.01542e04.entry.js:61
(anonymous) @ index.01542e04.entry.js:61
S3 @ index.01542e04.entry.js:58
mp @ index.01542e04.entry.js:58
_onDrop @ index.01542e04.entry.js:58

### To Reproduce

Drag and drop Collections in DataModel and reload page to see the new ordering isn't saved.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by bamboowonder** [comment]
Ok, it seems I solved it.   Somehow one of our automations was able to create a Collection in the directus table that had a blank name (not null, just empty).   Removing it solved the issue.
