### ISSUE TITLE
Error doesn't seem to indicate the full root-cause

### ISSUE THREAD

**Issue by arladmin** [directus/directus#19523]
### Describe the Bug

Upon a POST request to create a new directus_user, the following error is returned:

```
[04:36:42] POST /users 400 173ms
[04:36:42.537] DEBUG: Value in collection "directus_users" is too long.
    err: {
      "type": "",
      "message": "Value in collection \"directus_users\" is too long.",
      "stack":
          DirectusError: Value in collection "directus_users" is too long.
              at valueLimitViolation (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/errors/dialects/postgres.js:62:12)
              at translateDatabaseError (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/errors/translate.js:26:28)
              at extractError (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/database/errors/dialects/postgres.js:17:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/items.js:136:29
      "name": "DirectusError",
      "extensions": {
        "collection": "directus_users",
        "field": null
      },
      "code": "VALUE_TOO_LONG",
      "status": 400
    }
```

Maybe i'm missing something here, but based on this error, i'm unable to figure out which particular 'value' is too long?

### To Reproduce

.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This is a limitation of PostgreSQL, unfortunately there is nothing we can do here:
https://github.com/directus/directus/blob/7aedf763c0afc730cd2660ab9f7a46df0037c5de/api/src/database/errors/dialects/postgres.ts#L69-L72

I assume you're on PostgreSQL, so I'll close this issue for now. Please let me know if that isn't the case. Thanks!
