### ISSUE TITLE
Error when creating a collection with "m2m" field type using API

### ISSUE THREAD

**Issue by zhsu-borsen** [directus/directus#19570]
### Describe the Bug

When attempting to create a collection with a field that has a "m2m" type using the API, I encountered an error.
**TypeError: table[field.type] is not a function**

Here's the payload I sent:

```
{
  "collection": "card_image_card",
  "field": "global_cards",
  "type": "m2m",
  "schema": null,
  "meta": {
    "id": 99,
    "collection": "card_image_card",
    "field": "global_cards",
    "special": ["m2m"],
    "interface": "many-to-many",
    "options": null,
    "display": null,
    "display_options": null,
    "readonly": false,
    "hidden": false,
    "sort": 4,
    "width": "full",
    "group": null,
    "translations": null,
    "note": null
  }
}
```

Error Log:
```
^[[33mservice-rabbit-directus |^[[0m Migrating: 2023_08_22_065928_create_card_image_card
^[[33mservice-rabbit-directus |^[[0m 11:09:07 :sparkles: request completed GET 200 /collections/card_image_card 14ms
^[[33mservice-rabbit-directus |^[[0m 11:09:07 :rotating_light: table[field.type] is not a function
^[[33mservice-rabbit-directus |^[[0m TypeError: table[field.type] is not a function
^[[33mservice-rabbit-directus |^[[0m     at FieldsService.addColumnToTable (/usr/src/app/node_modules/directus/dist/services/fields.js:314:39)
^[[33mservice-rabbit-directus |^[[0m     at TableBuilder._fn (/usr/src/app/node_modules/directus/dist/services/collections.js:90:43)
^[[33mservice-rabbit-directus |^[[0m     at TableBuilder.toSQL (/usr/src/app/node_modules/knex/lib/schema/tablebuilder.js:44:14)
^[[33mservice-rabbit-directus |^[[0m     at SchemaCompiler_MySQL.createTable (/usr/src/app/node_modules/knex/lib/schema/compiler.js:101:25)
^[[33mservice-rabbit-directus |^[[0m     at SchemaCompiler_MySQL.toSQL (/usr/src/app/node_modules/knex/lib/schema/compiler.js:63:26)
^[[33mservice-rabbit-directus |^[[0m     at SchemaBuilder.toSQL (/usr/src/app/node_modules/knex/lib/schema/builder.js:35:45)
^[[33mservice-rabbit-directus |^[[0m     at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
^[[33mservice-rabbit-directus |^[[0m     at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:272:20)
^[[33mservice-rabbit-directus |^[[0m     at runMicrotasks (<anonymous>)
^[[33mservice-rabbit-directus |^[[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
^[[33mservice-rabbit-directus |^[[0m 11:09:07 :sparkles: request errored POST 500 /collections 12ms
^[[33mservice-rabbit-directus |^[[0m string(216) "Server error: `POST http://localhost:8055/collections` resulted in a `500 Internal Server Error` response:
^[[33mservice-rabbit-directus |^[[0m {"errors":[{"message":"table[field.type] is not a function","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
^[[33mservice-rabbit-directus |^[[0m "
^[[33mservice-rabbit-directus |^[[0m Migrated:  2023_08_22_065928_create_card_image_card (35.99ms)
^[[33mservice-rabbit-directus |^[[0m Migrating: 2023_08_22_065947_create_global_cards
^[[33mservice-rabbit-directus |^[[0m 11:09:07 :sparkles: request completed GET 200 /collections/global_cards 17ms
^[[33mservice-rabbit-directus |^[[0m 11:09:07 :rotating_light: table[field.type] is not a function
^[[33mservice-rabbit-directus |^[[0m TypeError: table[field.type] is not a function
```

![image](https://github.com/directus/directus/assets/110393003/a367a44d-58b1-4000-bb74-f2f427a88195)

### To Reproduce

1. Use the Directus API to create a new collection.
2. Use the above payload to add a field with the "m2m" type. (I have made sure the related table is realdy created in database / directus)
3. Observe the error in the error logs.

### Directus Version

v9.0.0-rc.49

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
It looks like you're only creating the `field` but not creating the `relation`. I am unable to reproduce this issue on the latest version.

Be aware that `v9.0.0-rc.49` was [released 2.5years ago](https://github.com/directus/directus/releases/tag/v9.0.0-rc.49), please update to the latest version and create a new issue if this persists.
