### ISSUE TITLE
Can't apply any snapshot schema because of foreign keys: ER_FK_COLUMN_CANNOT_CHANGE

### ISSUE THREAD

**Issue by prikr** [directus/directus#19615]
### Describe the Bug

Hi team, when upgrading from 10.2.1 to 10.6.1 i was able to run directus locally. In my CI/CD pipeline it applies the latest schema snapshot that is created at every push to Github. But, the apply is not succeeding currently.

Currently my pipeline works as follows:
1. Create a snapshot in my local environment
2. The push to github is being done.
3. Automatic deployment in Heroku is called.
4. `npm install && npx directus bootstrap` is runned
5. After that, my dyno is running `npx directus schema apply --yes ci/$CICD_SNAPSHOT_PATH/snapshot.yaml && npm run start`
6. This will fire the following npm scripts in my package.json:
    ```
    "start": "npx directus bootstrap && npx directus start",
    "prestart": "npx directus schema snapshot ./snapshots/\"$(date \"+%F\")\"-snapshot-\"$(date \"+%s\")\".yaml"
    ```

Unfortunately, the schema cannot be applied, because it gives me the following error:
```
err: {
      "type": "Error",
      "message": "alter table `applications` modify `app_connection_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
      "stack":
          Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'
              at Query.Sequence._packetToError (/app/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/app/admin/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/app/admin/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              --------------------
              at Protocol._enqueue (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/app/admin/node_modules/mysql/lib/Connection.js:198:25)
              at /app/admin/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/app/admin/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/app/admin/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/app/admin/node_modules/knex/lib/client.js:146:12)
              at /app/admin/node_modules/knex/lib/execution/transaction.js:363:24
              at new Promise (<anonymous>)
              at Client_MySQL.trxClient.query (/app/admin/node_modules/knex/lib/execution/transaction.js:358:12)
              at Runner.query (/app/admin/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/app/admin/node_modules/knex/lib/execution/runner.js:217:21)
              at ensureConnectionCallback (/app/admin/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
              at Runner.ensureConnection (/app/admin/node_modules/knex/lib/execution/runner.js:300:20)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async Runner.run (/app/admin/node_modules/knex/lib/execution/runner.js:30:19)
      "code": "ER_FK_COLUMN_CANNOT_CHANGE",
      "errno": 1832,
      "sqlMessage": "Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
      "sqlState": "HY000",
      "index": 0,
      "sql": "alter table `applications` modify `app_connection_id` int"
    }
}
```

What I can think of what caused this, is that I visually showed a m2m relation table inside the application and added custom fields to this relation table. Multiple connections can have multiple applications, but each combination has one config. The config field is what i have added to this. 

I would actually not print my full schema here, so if someone would like to receive it, they can message me here and i will e-mail it.

<html>
<body>

Service | Version
-- | --
MariaDB | 10.6.8-0
NodeJS | 16.20.2
NPM | 8.19.4

</body>
</html>

### To Reproduce

There should be a running database, which where a schema can be applied on. 

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
On first glance it seems to be the same issue we encountered with the share-column in #19619 - so far this seems to only affect MySQL DBs, mhh. Dropping the constraint, altering the column, re-applying the constraint seems to do the trick but in your case this seems to affect your own non-directus collection `applications` caused by the apply-diff functionality?

We could insert the drop-alter-reapply there if we knew the exact reason why MySQL rejects altering.

**Comment by paescuj** [comment]
From debugging in #19399 I got the impression that this is related to the SQL Mode [^1], in particular MySQL instances with non-standard SQL Modes.
At a quick glance, I couldn't find out from the documentation which mode could be responsible for this (maybe `strict`?), but it seemed to be reproducible when disabling all modes (`sql_mode = ''`).
But perhaps also a special engine or its configuration could be the reason for this.

@prikr Would you mind running the following command in your instance and posting the output here?
```sql
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```

If it turns out that it's indeed a SQL Mode, we would have to consider whether we need to define this as a prerequisite to run Directus with MySQL.

[^1]: https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html

**Comment by paescuj** [comment]
Thanks @prikr! Are you still experiencing this issue?

**Comment by prikr** [comment]
I'm still running Directus on v10.6.1 and still experiencing this issue. I will try to update to an higher version this afternoon.

**Comment by prikr** [comment]
@paescuj, still encountering this problem with Directus v10.8.3.

details:
```
node version: 20.11
npm version: 10.2.4
directus version: 10.8.3
database type: mariadb
version: 10.8.4-0

```

```
2024-01-19T10:17:06.253225+00:00 app[web.1]: [10:17:05.412] ERROR: alter table `applications` modify `app_connection_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'
2024-01-19T10:17:06.253226+00:00 app[web.1]:     err: {
2024-01-19T10:17:06.253226+00:00 app[web.1]:       "type": "Error",
2024-01-19T10:17:06.253227+00:00 app[web.1]:       "message": "alter table `applications` modify `app_connection_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
2024-01-19T10:17:06.253228+00:00 app[web.1]:       "stack":
2024-01-19T10:17:06.253228+00:00 app[web.1]:           Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'
2024-01-19T10:17:06.253229+00:00 app[web.1]:               at Sequence._packetToError (/app/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
2024-01-19T10:17:06.253229+00:00 app[web.1]:               at Query.ErrorPacket (/app/admin/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
2024-01-19T10:17:06.253229+00:00 app[web.1]:               at Protocol._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:291:23)
2024-01-19T10:17:06.253230+00:00 app[web.1]:               at Parser._parsePacket (/app/admin/node_modules/mysql/lib/protocol/Parser.js:433:10)
2024-01-19T10:17:06.253230+00:00 app[web.1]:               at Parser.write (/app/admin/node_modules/mysql/lib/protocol/Parser.js:43:10)
2024-01-19T10:17:06.253230+00:00 app[web.1]:               at Protocol.write (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
2024-01-19T10:17:06.253231+00:00 app[web.1]:               at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:88:28)
2024-01-19T10:17:06.253231+00:00 app[web.1]:               at Socket.<anonymous> (/app/admin/node_modules/mysql/lib/Connection.js:526:10)
2024-01-19T10:17:06.253231+00:00 app[web.1]:               at Socket.emit (node:events:518:28)
2024-01-19T10:17:06.253231+00:00 app[web.1]:               at addChunk (node:internal/streams/readable:559:12)
2024-01-19T10:17:06.253232+00:00 app[web.1]:               --------------------
2024-01-19T10:17:06.253232+00:00 app[web.1]:               at Protocol._enqueue (/app/admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2024-01-19T10:17:06.253232+00:00 app[web.1]:               at Connection.query (/app/admin/node_modules/mysql/lib/Connection.js:198:25)
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at /app/admin/node_modules/knex/lib/dialects/mysql/index.js:137:18
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at new Promise (<anonymous>)
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at Client_MySQL._query (/app/admin/node_modules/knex/lib/dialects/mysql/index.js:131:12)
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at executeQuery (/app/admin/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at Client_MySQL.query (/app/admin/node_modules/knex/lib/client.js:154:12)
2024-01-19T10:17:06.253233+00:00 app[web.1]:               at /app/admin/node_modules/knex/lib/execution/transaction.js:375:24
2024-01-19T10:17:06.253234+00:00 app[web.1]:               at new Promise (<anonymous>)
2024-01-19T10:17:06.253234+00:00 app[web.1]:               at trxClient.query (/app/admin/node_modules/knex/lib/execution/transaction.js:370:12)
2024-01-19T10:17:06.253234+00:00 app[web.1]:       "code": "ER_FK_COLUMN_CANNOT_CHANGE",
2024-01-19T10:17:06.253234+00:00 app[web.1]:       "errno": 1832,
2024-01-19T10:17:06.253235+00:00 app[web.1]:       "sqlMessage": "Cannot change column 'app_connection_id': used in a foreign key constraint 'applications_app_connection_id_foreign'",
2024-01-19T10:17:06.253235+00:00 app[web.1]:       "sqlState": "HY000",
2024-01-19T10:17:06.253236+00:00 app[web.1]:       "index": 0,
2024-01-19T10:17:06.253236+00:00 app[web.1]:       "sql": "alter table `applications` modify `app_connection_id` int"
2024-01-19T10:17:06.253236+00:00 app[web.1]:     }
```

**Comment by prikr** [comment]
Ok. Did some testing and debugging tonight. 

1. I created a new local database with the following docker-compose configuration:
```
  mariadb:
    image: mariadb:10.11.6
    container_name: 'prikxel-mariadb-db'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=prikxel-mariadb-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
```
2. I applied the scheme snapshot of my local InnoDB database. This one got applied succesfully.
3. After that, i tried to re-apply the scheme snapshot and it led me to the same error as my comment above, but; I knew that my database was actually up-to-date.
4. So, what I did is: I created another snapshot of my scheme (this time the local MariaDB). This led to many changes in the scheme-file. I added the files (old and new, so u can check the difference).
5. I uploaded this scheme to Github.com and this fires my Heroku pipeline automatically. This runs the following command via my Procfile: `web: cd admin && npx directus schema apply --yes ci/$CICD_SNAPSHOT_PATH/snapshot.yaml && npm run start`, and this time it got applied succesfully. 👍


[snapshot-innodb.yaml.txt](https://github.com/directus/directus/files/13992602/snapshot-innodb.yaml.txt)
[snapshot-mariadb.yaml.txt](https://github.com/directus/directus/files/13992603/snapshot-mariadb.yaml.txt)
