### ISSUE TITLE
Removing Local Extension crash directus with EXTENSIONS_AUTO_RELOAD

### ISSUE THREAD

**Issue by Zehir** [directus/directus#19755]
### Describe the Bug

When removing [Local Extension](https://docs.directus.io/extensions/creating-extensions.html#local-extension) from the disk with `EXTENSIONS_AUTO_RELOAD=true` directus crashes.

### To Reproduce

- Enable `EXTENSIONS_AUTO_RELOAD` in config
- Create a directory ouside of the project named `foo` with inside a file `index.js` with following content :
```javascript
import { defineHook } from '@directus/extensions-sdk'
export default defineHook(({ filter, action }) => {
  console.log('I\'m a hook!')
  filter('items.create', () => {
    console.log('Creating Item!')
  })

  action('items.create', () => {
    console.log('Item created!')
  })
})
```
- Start directus with `npx directus start`
- Move the `foo` directory to `extensions/hooks/`
- Notice in the console that the `foo` extension was loaded : `[22:20:29.737] INFO: Added extensions: foo`
- Delete the `foo` directory
- Save a file to trigger the file watcher
- Crash directus with following error message :
```javascript
[22:20:29.691] INFO: Reloading extensions
[22:20:29.737] INFO: Added extensions: foo
[22:20:56.851] INFO: Reloading extensions
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module '/workspaces/ddf-tools/packages/ddf-bundle-store/extensions/hooks/foo/index.js'
Require stack:
- /workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at ExtensionManager.unregisterApiExtensions (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:483:42)
    at ExtensionManager.unload (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:190:20)
    at file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:94:28
    at JobQueue.run (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/utils/job-queue.js:18:19)
    at JobQueue.enqueue (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/utils/job-queue.js:11:18)
    at ExtensionManager.reload (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:90:26)
    at FSWatcher.<anonymous> (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:218:38)
    at FSWatcher.emit (node:events:513:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js'
  ]
}

```

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
While we research/resolve this, we should also test the opposite: adding a new extensions while the API is already running 🙂

**Comment by ComfortablyCoding** [comment]
This seems to be due to `deleteFromRequireCache` function.

This function is called in the unregister functions for extensions and is thus triggered on an extension unload call. I believe the error is due to it attempting to find the modulePath that now no longer exists via `require.resolve` https://github.com/directus/directus/blob/main/api/src/utils/delete-from-require-cache.ts#L6.

In terms of a solution I am not sure what would be ideal. The module path does not seem to exist in the require.cache object for local extensions so maybe we should not be attempting to remove from the cache at all for local? This assumption is based on `require.cache[modulePath]` returning undefined.

Potential solutions I see are
1. Remove the `deleteFromRequireCache` call if the extension is local.
2. Attempt to resolve modulePath, if it errors default to module path provided. Module path seems to be the full path to entry point.
```js
export function deleteFromRequireCache(modulePath: string): void {
	let moduleCachePath = modulePath;
	try {
		moduleCachePath = require.resolve(modulePath);
	} catch (error) {}

	delete require.cache[moduleCachePath];
}
```
3. Attempt to resolve modulePath, if it errors do nothing. 
```js
export function deleteFromRequireCache(modulePath: string): void {
	try {
		const moduleCachePath = require.resolve(modulePath);
		delete require.cache[moduleCachePath];
	} catch (error) {}
}
```
Happy to make a PR to resolve this issue.

**Comment by rijkvanzanten** [comment]
@ComfortablyCoding I don't think option 1 will work, as the require cache refresh needs to happen explicitly for local extensions as well. Gut feeling says option 3 is the cleanest, assuming we'll add a `logger.warn` in that catch block so it's not swallowed 🙂

**Comment by ComfortablyCoding** [comment]
Fair point. I will create a PR to resolve this.

@rijkvanzanten What do you think of the message 
```
"Module cache not found for {modulePath}, skipped cache delete."
```

It might be to much to have the entire module path in the message.The module name would be better but that isn't provided.

I can try and extract the module name but that is extra logic that doesn't really give much benefit. Alternatively we pass in the module name.

**Comment by rijkvanzanten** [comment]
Looks good to me! I think showing the path is sufficient for this 👍🏻

**Comment by rijkvanzanten** [comment]
_yes_ 👁️ 👄 👁️
