### ISSUE TITLE
Field 'sort' doesn't have a default value

### ISSUE THREAD

**Issue by stoconnor** [directus/directus#2007]
## Version Info
  - Directus version and branch: master - 257a1319e1f44a212aa728c89539cfccf056a832 (19/12/17)
  - PHP version: 4.7.4
  - MySQL version: 5.7.19
  - Web server: Apache
  - OS name and version: Win 10 

## Expected Behavior
When inserting to the table via the API, record is correctly inserted

## Actual Behavior
An error occurs on insert due to missing default value on the sort column. This was a clean installation, vanilla. I changed the default value from NULL to 0 and works as expected now.

## Steps to Reproduce
 1. Clean Install of Directus
 2. Create a Table in Directus UI
 3. Make an API call to Directus to insert a record into the table

## Schema Dump, Logs, or Screenshots
```
ERROR - 2017-12-21T07:27:16-05:00 - exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'sort' doesn't have a default value' in C:\wamp64\www\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Statement.php:239
Stack trace:
#0 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Statement.php(239): PDOStatement->execute()
#1 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php(757): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#3 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#4 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php(396): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#5 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(156): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#6 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('Dashboardupdate...', Array, 1)
#7 C:\wamp64\www\directus\api\core\Directus\Services\EntriesService.php(39): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#8 C:\wamp64\www\directus\api\routes\A1\Entries.php(29): Directus\Services\EntriesService->createEntry('Dashboardupdate...', Array, Array)
#9 [internal function]: Directus\API\Routes\A1\Entries->rows('Dashboardupdate...')
#10 C:\wamp64\www\directus\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Array, Array)
#11 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#12 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#13 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#14 C:\wamp64\www\directus\api\core\Directus\Slim\CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#15 C:\wamp64\www\directus\api\core\Directus\Slim\HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#16 C:\wamp64\www\directus\api\core\Directus\Slim\ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#17 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#18 C:\wamp64\www\directus\api\core\Directus\Application\Application.php(103): Slim\Slim->run()
#19 C:\wamp64\www\directus\api\api.php(534): Directus\Application\Application->run()
#20 {main}

Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (HY000 - 1364 - Field 'sort' doesn't have a default value)' in C:\wamp64\www\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Statement.php:244
Stack trace:
#0 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php(757): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#2 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#3 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php(396): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#4 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(156): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#5 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('Dashboardupdate...', Array, 1)
#6 C:\wamp64\www\directus\api\core\Directus\Services\EntriesService.php(39): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#7 C:\wamp64\www\directus\api\routes\A1\Entries.php(29): Directus\Services\EntriesService->createEntry('Dashboardupdate...', Array, Array)
#8 [internal function]: Directus\API\Routes\A1\Entries->rows('Dashboardupdate...')
#9 C:\wamp64\www\directus\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Array, Array)
#10 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#11 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#12 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#13 C:\wamp64\www\directus\api\core\Directus\Slim\CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#14 C:\wamp64\www\directus\api\core\Directus\Slim\HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#15 C:\wamp64\www\directus\api\core\Directus\Slim\ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#16 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#17 C:\wamp64\www\directus\api\core\Directus\Application\Application.php(103): Slim\Slim->run()
#18 C:\wamp64\www\directus\api\api.php(534): Directus\Application\Application->run()
#19 {main}

Next exception 'RuntimeException' with message 'This query failed: INSERT INTO `Dashboardupdates` (`title`, `tag`) VALUES ('postman', 'AllGroups')' in C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php:783
Stack trace:
#0 C:\wamp64\www\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#1 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\BaseTableGateway.php(396): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#2 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(156): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#3 C:\wamp64\www\directus\api\core\Directus\Database\TableGateway\RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('Dashboardupdate...', Array, 1)
#4 C:\wamp64\www\directus\api\core\Directus\Services\EntriesService.php(39): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#5 C:\wamp64\www\directus\api\routes\A1\Entries.php(29): Directus\Services\EntriesService->createEntry('Dashboardupdate...', Array, Array)
#6 [internal function]: Directus\API\Routes\A1\Entries->rows('Dashboardupdate...')
#7 C:\wamp64\www\directus\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Array, Array)
#8 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#9 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#10 C:\wamp64\www\directus\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 C:\wamp64\www\directus\api\core\Directus\Slim\CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#12 C:\wamp64\www\directus\api\core\Directus\Slim\HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#13 C:\wamp64\www\directus\api\core\Directus\Slim\ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#14 C:\wamp64\www\directus\vendor\slim\slim\Slim\Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#15 C:\wamp64\www\directus\api\core\Directus\Application\Application.php(103): Slim\Slim->run()
#16 C:\wamp64\www\directus\api\api.php(534): Directus\Application\Application->run()
#17 {main}
```

**Comment by WellingGuzman** [comment]
New table with `sort` are created nullable with `null` by default.

Closed by https://github.com/directus/directus/commit/d758bc5082429154eeb8ef08f48503c77b2db2ad
