### ISSUE TITLE
Extensions throw warning on migration when directus_extensions doesn't exist yet

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20131]
### Describe the Bug

When migrating from < 10.7 to 10.7+, you might get a 

```
[11:24:12.030] WARN: Couldn't load extensions
[11:24:12.030] WARN: Cannot read properties of undefined (reading 'primary')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'primary')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'primary')
              at getASTFromQuery (/Users/rijkvanzanten/Developer/directus/directus/api/src/utils/get-ast-from-query.ts:79:51)
              at ItemsService.readByQuery (/Users/rijkvanzanten/Developer/directus/directus/api/src/services/items.ts:414:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at getExtensionsSettings (/Users/rijkvanzanten/Developer/directus/directus/api/src/extensions/lib/get-extensions-settings.ts:20:19)
              at ExtensionManager.load (/Users/rijkvanzanten/Developer/directus/directus/api/src/extensions/manager.ts:180:30)
              at ExtensionManager.initialize (/Users/rijkvanzanten/Developer/directus/directus/api/src/extensions/manager.ts:160:4)
              at createCli (/Users/rijkvanzanten/Developer/directus/directus/api/src/cli/index.ts:25:3)
    }
```

warning. It importantly doesn't prevent the migration, or prevents extensions from used once the API is started, but it looks scary!

### To Reproduce

Migrate from <10.7 to 10.7.0 with an existing database

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Pretty sure it's thrown here:

https://github.com/directus/directus/blob/9e5b9a78a73e74d3f3e5ae58a0faf8e6c39ac29e/api/src/cli/index.ts#L23-L26

The current check checks if the database is _installed_, but it doesn't confirm if the database is up to date. We should only initialize extensions when the DB is fully up to date
