### ISSUE TITLE
Issue with Require Shares Fields migration with MySQL

### ISSUE THREAD

**Issue by kroawen** [directus/directus#20196]
### Describe the Bug

Running database  migrate command: `npx directus database migrate:latest` throw this error:

[11:06:56.421] WARN: Cannot read properties of undefined (reading 'primary')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'primary')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'primary')
              at getASTFromQuery (file:///D:/github/directus/di9/node_modules/@directus/api/dist/utils/get-ast-from-query.js:47:56)
              at ItemsService.readByQuery (file:///D:/github/directus/di9/node_modules/@directus/api/dist/services/items.js:310:25)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async getExtensionsSettings (file:///D:/github/directus/di9/node_modules/@directus/api/dist/extensions/lib/get-extensions-settings.js:16:22)
              at async ExtensionManager.load (file:///D:/github/directus/di9/node_modules/@directus/api/dist/extensions/manager.js:138:39)
              at async ExtensionManager.initialize (file:///D:/github/directus/di9/node_modules/@directus/api/dist/extensions/manager.js:122:13)
              at async createCli (file:///D:/github/directus/di9/node_modules/@directus/api/dist/cli/index.js:23:9)
    }
[11:06:56.571] INFO: Loaded extensions: account, test
[11:06:56.577] INFO: Running migrations...
[11:06:56.587] INFO: Applying Require Shares Fields...
[11:06:56.617] ERROR: alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_INVALID_DEFAULT: Invalid default value for 'date_start'
    err: {
      "type": "Error",
      "message": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign` - ER_INVALID_DEFAULT: Invalid default value for 'date_start'",
      "stack":
          Error: ER_INVALID_DEFAULT: Invalid default value for 'date_start'
              at Query.Sequence._packetToError (D:\github\directus\di9\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
              at Query.ErrorPacket (D:\github\directus\di9\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
              at Protocol._parsePacket (D:\github\directus\di9\node_modules\mysql\lib\protocol\Protocol.js:291:23)
              at Parser._parsePacket (D:\github\directus\di9\node_modules\mysql\lib\protocol\Parser.js:433:10)
              at Parser.write (D:\github\directus\di9\node_modules\mysql\lib\protocol\Parser.js:43:10)
              at Protocol.write (D:\github\directus\di9\node_modules\mysql\lib\protocol\Protocol.js:38:16)
              at Socket.<anonymous> (D:\github\directus\di9\node_modules\mysql\lib\Connection.js:88:28)
              at Socket.<anonymous> (D:\github\directus\di9\node_modules\mysql\lib\Connection.js:526:10)
              at Socket.emit (node:events:520:28)
              at addChunk (node:internal/streams/readable:315:12)
              --------------------
              at Protocol._enqueue (D:\github\directus\di9\node_modules\mysql\lib\protocol\Protocol.js:144:48)
              at Connection.query (D:\github\directus\di9\node_modules\mysql\lib\Connection.js:198:25)
              at D:\github\directus\di9\node_modules\knex\lib\dialects\mysql\index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (D:\github\directus\di9\node_modules\knex\lib\dialects\mysql\index.js:126:12)
              at executeQuery (D:\github\directus\di9\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
              at Client_MySQL.query (D:\github\directus\di9\node_modules\knex\lib\client.js:146:12)
              at Runner.query (D:\github\directus\di9\node_modules\knex\lib\execution\runner.js:123:36)
              at Runner.queryArray (D:\github\directus\di9\node_modules\knex\lib\execution\runner.js:217:21)
              at ensureConnectionCallback (D:\github\directus\di9\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:11:19)
      "code": "ER_INVALID_DEFAULT",
      "errno": 1067,
      "sqlMessage": "Invalid default value for 'date_start'",
      "sqlState": "42000",
      "index": 0,
      "sql": "alter table `directus_shares` drop foreign key `directus_shares_collection_foreign`"
    }

### To Reproduce

update from 10.6.3 to 10.7.0

### Directus Version

V10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
The first `WARN: Cannot read properties of undefined (reading 'primary')` log related to extensions should be resolved once you are able to run the very recent `20231010A-add-extensions.ts` migration, but your error with the `directus_shares` table leads me to believe your issue is with the `20230721A-require-shares-fields.ts` migration instead.

@paescuj This seems related to #19619 and possibly your findings in https://github.com/directus/directus/issues/19615#issuecomment-1729184925, any thoughts on this?

> update from 10.6.3 to 10.7.0

Out of curiosity, I think the `Require Shares Fields` migration was first introduced in `10.5.0`, does this mean the migration wasn't ran when you upgraded past `10.5.0` to `10.6.3`?

**Comment by azrikahar** [comment]
@kroawen were you able to resolve this, or was this issue closed unintentionally? Just curious to know the reasoning, in case a similar issue ever pops up again 👍

**Comment by paescuj** [comment]
Just leaving as a note: It complains about another column (`date_start`) than the one we're actually modifying (`collection`)... Seems to be related to the SQL mode: https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at

**Comment by kroawen** [comment]
> @kroawen were you able to resolve this, or was this issue closed unintentionally? Just curious to know the reasoning, in case a similar issue ever pops up again 👍

I imported the database from a completely new project to solve the issue; it's not important, and I primarily use it for testing, and there is no data inside.

**Comment by neo7-studio-web** [comment]
FYI I had this exact same error migrating from 10.6 to 10.7 on a MySQL DB. I rolled back.
