### ISSUE TITLE
Uncaught error in health check endpoint on unexpected response from S3

### ISSUE THREAD

**Issue by arladmin** [directus/directus#20220]
### Describe the Bug

The health-check endpoint, `/server/health`, seems to be causing a system crash (instance restart). 
Additionally, this seems to be coinciding with the status of the storageAdapter in the health-check resulting in an `error` state.

Relevant logs:
```
[11:51:29] GET /server/health 200 1.1s
/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9639
        if (parsedObjToReturn[textNodeName]) {
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                             ^
TypeError: Cannot read properties of undefined (reading '#text')
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at /directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9639:30
    at async parseErrorBody (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9648:19)
    at async de_DeleteObjectCommandError (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3550:15)
    at async /directus/node_modules/.pnpm/@aws-sdk+middleware-serde@3.329.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /directus/node_modules/.pnpm/@aws-sdk+middleware-retry@3.329.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /directus/node_modules/.pnpm/@aws-sdk+middleware-signing@3.329.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /directus/node_modules/.pnpm/@aws-sdk+middleware-logger@3.329.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async IncomingMessage.<anonymous> (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/services/server.js:310:25) {
    at async DriverS3.delete (file:///directus/node_modules/.pnpm/file+packages+storage-driver-s3_vue@3.3.4/node_modules/@directus/storage-driver-s3/dist/index.js:142:5)
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
Node.js v18.18.2
[11:51:45.453] INFO: Initializing bootstrap...
[11:51:45.456] INFO: Database already initialized, skipping install
[11:51:45.456] INFO: Running migrations...
[11:51:45.468] INFO: Done
[11:51:49.586] INFO: Server started at http://0.0.0.0:8055
[11:51:52.590] ERROR: storage:DIGITALOCEAN:responseTime in ERROR state
      "type": "TypeError",
    err: {
      "message": "Cannot read properties of undefined (reading '#text')\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.",
      "stack":
            Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
          TypeError: Cannot read properties of undefined (reading '#text')
              at /directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9639:30
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async parseErrorBody (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9648:19)
              at async de_GetObjectCommandError (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.332.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4302:15)
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-signing@3.329.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-serde@3.329.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-flexible-checksums@3.331.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-retry@3.329.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-logger@3.329.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
              at async DriverS3.read (file:///directus/node_modules/.pnpm/file+packages+storage-driver-s3_vue@3.3.4/node_modules/@directus/storage-driver-s3/dist/index.js:76:30)
      "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
      }
    }
[11:51:52] GET /server/health 503 1.2s
```

### To Reproduce

.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This seems to be specific to AWS's SDK not being able to deserialize the API output of the S3 compatible storage adapter. Just based on the logs, are you using DigitalOcean Spaces? 

I followed your reproduction steps and can't reproduce this.

**Comment by arladmin** [comment]
@rijkvanzanten 
> This seems to be specific to AWS's SDK not being able to deserialize the API output of the S3 compatible storage adapter. Just based on the logs, are you using DigitalOcean Spaces?
> 
> I followed your reproduction steps and can't reproduce this.

- Indeed. I'm using DigitalOcean Spaces
- This happened only during the almost 2 hour [outage](https://status.digitalocean.com/incidents/nwm1sn0gjfc3), DO Spaces had earlier today.
- During the outage, all of my Directus instances (all Docker based, on different 10.x versions), suffered this issue, and restarted almost 50 times during that time span!

**Comment by rijkvanzanten** [comment]
> This happened only during the almost 2 hour [outage](https://status.digitalocean.com/incidents/nwm1sn0gjfc3), DO Spaces had earlier today.

Ahh that makes sense. It must've started returning non-s3 compatible responses during that window!

**Comment by arladmin** [comment]
> > This happened only during the almost 2 hour [outage](https://status.digitalocean.com/incidents/nwm1sn0gjfc3), DO Spaces had earlier today.
> 
> Ahh that makes sense. It must've started returning non-s3 compatible responses during that window!

Btw, this type of an issue shouldn't normally cause a 'restart frenzy', like the one i experienced, right?

**Comment by stefanovalentegva** [comment]
We are experiencing the same issue. For reasons we are still investigating, the health check starts failing, returning null instead of any error code, without leaving any logs.
This causes P2 to restart, which in turn triggers the Load Balancer to restart the instance.

I believe the health check should never throw an unhandled error.

**Comment by sguillema** [comment]
> We are experiencing the same issue. For reasons we are still investigating, the health check starts failing, returning null instead of any error code, without leaving any logs. This causes P2 to restart, which in turn triggers the Load Balancer to restart the instance.
> 
> I believe the health check should never throw an unhandled error.

Having the exact same issue. My setup is a self-hosted docker on my local machine. The version I'm on is `11.3.0`.
