### ISSUE TITLE
SAML with ADFS is not working

### ISSUE THREAD

**Issue by marcelhorner** [directus/directus#20290]
### Describe the Bug

SAML with ADFS is not working

### To Reproduce

Hello everyone,

I am running Directus on a Kubernetes cluster and I am having the following problem when trying to setup SAML auth with ADFS.

Using this setup:
          - name: AUTH_PROVIDERS
            value: "ldap,saml"
          - name: AUTH_SAML_DRIVER
            value: "saml"
          - name: AUTH_SAML_ALLOW_PUBLIC_REGISTRATION
            value: "true"
          - name: AUTH_SAML_DEFAULT_ROLE_ID
            value: "********-****-****-****-************"
          - name: AUTH_SAML_IDP_metadata
            value: "..."

Generates this SAML Request:
<samlp:AuthnRequest
      xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
      xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
      ID="*********-****-****-****-************"
      Version="2.0"
      IssueInstant="2023-11-01T12:58:43.251Z"
      Destination="[https://subdomain.domain.com/adfs/ls/"](https://subdomain.domain/adfs/ls/%22)
      ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
      AssertionConsumerServiceURL="undefined">
    <saml:Issuer>undefined</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" AllowCreate="false"/>
</samlp:AuthnRequest>

When AUTH_SAML_ALLOW_PUBLIC_REGISTRATION is true I believe AllowCreate should be true on SAML request, right? How to make AssertionConsumerServiceURL and saml:Issuer get the correct values? 

And what is Directus AssertionConsumerServiceURL? I can't find this information on the documentation. Can someone tell me what value should I use for ACS URL on SAML request and for ADFS Trusted URL and Relying party identifiers?

Thank you!

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Did you set the PUBLIC_URL environment variable?

**Comment by marcelhorner** [comment]
Hello Rijk, yes I did.

**Comment by MaxJacobs213** [comment]
Hi. I'm not sure if you are using the correct variable format. In the documentation it is used as
`
          - name: AUTH_OKTA_DRIVER
          - name: AUTH_OKTA_ALLOW_PUBLIC_REGISTRATION
          - name: AUTH_OKTA_DEFAULT_ROLE_ID
          - name: AUTH_OKTA_IDP_metadata`
          
          This is an example for an Okta vendor, but you need to substitute here the name of the vendor you use(Okta, aws, google etc.), not the provider name (saml, openid, ldap)

**Comment by marcelhorner** [comment]
Hello Max,

Yes, this could be the problem.

Does Directus have support for SAML auth on ADFS? I couldn't find any documentation or example on how to make this setup on Directus.

I also need to know what is Directus AssertionConsumerServiceURL to make this setup on ADFS side.

Thank you,
Marcel Horner

**Comment by ConnorSimply** [comment]
Hi Marcel, You can find a [SSO SAML Example in our Self Hosted docs](https://docs.directus.io/self-hosted/sso-examples.html#google-1 ). This example is for Google, however, it shows how to correctly format the ENV variable names and the ACS url. Hope this helps!

**Comment by marcelhorner** [comment]
Hello Connor,

I've already used those examples when setting up the configuration I've sent on the first post.

I've added AUTH_SAML_sp_metadata that was missing and now I can succesfully authenticate on AD but when redirecting to the location configured at AssertionConsumerService I get the error "route doesn't exist" from Directus:
```
{
    "errors": [
        {
            "message": "Route /auth/login/sso/acs doesn't exist.",
            "extensions": {
                "code": "ROUTE_NOT_FOUND",
                "path": "/auth/login/sso/acs"
            }
        }
    ]
}
```

What is Directus path SAML should call after authenticating the user? Do I need to install any plugin or something like that to make the address as showed on [SSO SAML Example in our Self Hosted docs](https://docs.directus.io/self-hosted/sso-examples.html#google-1) work?
```
<EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="SHOULD_MATCH_GOOGLE_CONFIG">
  <SPSSODescriptor WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService isDefault="true" index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="YOUR_DOMAIN/auth/login/sso/acs"/>
  </SPSSODescriptor>
</EntityDescriptor>
```

**Comment by ConnorSimply** [comment]
Hi @marcelhorner 

Can you try replacing `sso` in that URL with the name of your auth provider. Looking at the docs again, I think there are some naming inconsistencies with the ENV/URL and I will see about getting that fixed. Let me know if the below works?

> _Note that it may be easier to understand that the `AUTH_PROVIDERS` env variable is your own name of the provider, and that name is used in the other ENV and the URL, in the case below the name of this provider is `adfs` so that is what is in the URL. Changing the name to `saml` like your original ENV variables would mean you would replace everywhere it says `adfs` in my example with `saml`._

So something like...
```env
AUTH_PROVIDERS="adfs"
AUTH_ADFS_DRIVER="saml"
AUTH_ADFS_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_ADFS_DEFAULT_ROLE_ID="********-****-****-****-************"
AUTH_ADFS_IDP_metadata="..."
AUTH_ADFS_sp_metadata="..."
```

With the URL...

```
/auth/login/adfs/acs
```

**Comment by ConnorSimply** [comment]
You are getting the route doesn't exist error?

**Comment by marcelhorner** [comment]
I am getting this error:

```
{"level":40,"time":1701198706600,"pid":29,"hostname":"directus-ict-54cff64f95-4krc9","err":{"type":"Error","message":"ERR_FAILED_STATUS with top tier code: urn:oasis:names:tc:SAML:2.0:status:Requester, second tier code: urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy","stack":"Error: ERR_FAILED_STATUS with top tier code: urn:oasis:names:tc:SAML:2.0:status:Requester, second tier code: urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy\n    at checkStatus (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/flow.js:383:11)\n    at /directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/flow.js:206:42\n    at step (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/flow.js:33:23)\n    at Object.next (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/flow.js:14:53)\n    at fulfilled (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/flow.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"[SAML] Unexpected 
error during SAML login"}
```

**Comment by marcelhorner** [comment]
We have a working SAML auth with Gitlab and ADFS; I've changed NameIDFormat to the same value working on that setup:
```<NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat>```

Now I am getting a different errror when trying to authenticate with ADFS SAML on Directus:
```
{"level":40,"time":1701352211682,"pid":30,"hostname":"directus-ict-7ewr48wer6-cs68e","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'toLowerCase')","stack":"TypeError: Cannot read properties of undefined (reading 'toLowerCase')\n    at SAMLAuthDriver.fetchUserID (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:36:75)\n    at SAMLAuthDriver.getUserID (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:44:35)\n    at AuthenticationService.login (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/services/authentication.js:43:37)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:114:60"},"msg":"[SAML] Unexpected error during SAML login"}
```

**Comment by marcelhorner** [comment]
It seems the error I am getting is coming from this line:
https://github.com/directus/directus/blob/main/api/src/auth/drivers/saml.ts#L43

And I assume this is happening because I don't get any attribute named ```http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier```.

I get the NameID on Subject section:
![image](https://github.com/directus/directus/assets/7253341/22657cfe-b3ad-45bc-8e66-f5f2bfa87c6e)
 
I've tried to add user email as ```http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier``` on AttibuteStatement section but this kind of config on ADFS doesn't worked for me on. I've managed to add givenname and surname, as showed on the screenshot, but adding email as nameidentifier doesn't add the information to the SAML Response I get from ADFS.

Wouldn't make sense to get NameID from Subject section?

**Comment by rizz360** [comment]
As of 10.10+ AllowCreate appears to be empty in the saml auth request:

## 10.9 
```xml
<samlp:AuthnRequest ...>
 <saml:Issuer>...</saml:Issuer>
 <samlp:NameIDPolicy ... AllowCreate="false"></samlp:NameIDPolicy>
</samlp:AuthnRequest>
```

## 10.10 
```xml
<samlp:AuthnRequest ...>
 <saml:Issuer>...</saml:Issuer>
 <samlp:NameIDPolicy ... AllowCreate=""></samlp:NameIDPolicy>
</samlp:AuthnRequest>
```


With my local testing setup this leads to the following issue with SimpleSAML:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Invalid value of boolean attribute 'AllowCreate': ''
```


`AUTH_xxxxxx_ALLOW_PUBLIC_REGISTRATION` does not seem to have any effect on this.

**Comment by achille2k** [comment]
I have same issue. I found the error this line https://github.com/directus/directus/blob/main/api/src/auth/drivers/saml.ts#L61
ADFS SAML Responce not include  http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier

**Comment by achille2k** [comment]
I have same issue, follow config to resolve it.
AUTH_ADFS_IDENTIFIER_KEY="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
