### ISSUE TITLE
Unable to create new Docker image with custom extension

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20338]
### Describe the Bug

Following the documentation https://docs.directus.io/extensions/installing-extensions.html on how to install extensions from npm into the Directus docker container, we simply get the following errors:

```
38.97 Progress: resolved 1097, reused 0, downloaded 1042, added 0
39.28  WARN  8 deprecated subdependencies found: @npmcli/move-file@1.1.2, @types/cssnano@5.1.0, consolidate@0.15.1, har-validator@5.1.5, json2csv@5.0.7, request@2.88.2, stable@0.1.8, uuid@3.4.0
39.42 Packages: +1044
39.42 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
39.97 Progress: resolved 1098, reused 0, downloaded 1043, added 21
40.99 Progress: resolved 1098, reused 0, downloaded 1043, added 365
41.99 Progress: resolved 1098, reused 0, downloaded 1043, added 727
42.79 Progress: resolved 1098, reused 0, downloaded 1044, added 1044, done
43.18 .../node_modules/isolated-vm install$ prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
43.25 .../sharp@0.32.5/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
43.42 .../sharp@0.32.5/node_modules/sharp install: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.4/libvips-8.14.4-linuxmusl-arm64v8.tar.br
43.77 .../node_modules/isolated-vm install: prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=arm64 libc=musl platform=linux)
43.84 .../node_modules/isolated-vm install: gyp info it worked if it ends with ok
43.84 .../node_modules/isolated-vm install: gyp info using node-gyp@9.4.1
43.84 .../node_modules/isolated-vm install: gyp info using node@18.18.2 | linux | arm64
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python 
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python Python is not set from command line or npm configuration
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python Python is not set from environment variable PYTHON
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python checking if "python3" can be used
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python - "python3" is not in PATH or produced an error
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python checking if "python" can be used
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python - "python" is not in PATH or produced an error
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python 
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python **********************************************************
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python You need to install the latest version of Python.
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python you can try one of the following options:
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python   (accepted by both node-gyp and npm)
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python - Set the environment variable PYTHON
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python - Set the npm configuration variable python:
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python For more information consult the documentation at:
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python **********************************************************
43.90 .../node_modules/isolated-vm install: gyp ERR! find Python 
43.90 .../node_modules/isolated-vm install: gyp ERR! configure error 
43.90 .../node_modules/isolated-vm install: gyp ERR! stack Error: Could not find any Python installation to use
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at PythonFinder.fail (/home/node/.cache/node/corepack/pnpm/8.10.2/dist/node_modules/node-gyp/lib/find-python.js:330:47)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at PythonFinder.runChecks (/home/node/.cache/node/corepack/pnpm/8.10.2/dist/node_modules/node-gyp/lib/find-python.js:159:21)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at PythonFinder.<anonymous> (/home/node/.cache/node/corepack/pnpm/8.10.2/dist/node_modules/node-gyp/lib/find-python.js:202:16)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at PythonFinder.execFileCallback (/home/node/.cache/node/corepack/pnpm/8.10.2/dist/node_modules/node-gyp/lib/find-python.js:294:16)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at exithandler (node:child_process:430:5)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:290:12)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
43.90 .../node_modules/isolated-vm install: gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
43.90 .../node_modules/isolated-vm install: gyp ERR! System Linux 5.15.49-linuxkit-pr
43.90 .../node_modules/isolated-vm install: gyp ERR! command "/usr/local/bin/node" "/home/node/.cache/node/corepack/pnpm/8.10.2/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
43.90 .../node_modules/isolated-vm install: gyp ERR! cwd /directus/node_modules/.pnpm/isolated-vm@4.6.0/node_modules/isolated-vm
43.90 .../node_modules/isolated-vm install: gyp ERR! node -v v18.18.2
43.90 .../node_modules/isolated-vm install: gyp ERR! node-gyp -v v9.4.1
43.90 .../node_modules/isolated-vm install: gyp ERR! not ok 
43.91 .../node_modules/isolated-vm install: Failed
43.91  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c pnpm install directus-extension-schema-sync" did not complete successfully: exit code: 1
```

### To Reproduce

Here is the Dockerfile you can try to create:

```
FROM directus/directus:10.6 AS base

RUN apk add --update python3 py3-pip

USER root
RUN corepack enable \
 && corepack prepare pnpm@8.9.0 --activate

EXPOSE 8080
ENV NODE_ENV production

USER node
RUN pnpm install directus-extension-schema-sync

```

We have tried both with and without updating python3

### Directus Version

10.6

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
M1 mac book pro (arm)

**Comment by Rafache** [comment]
I'm not sure if it's the same issue, on my end (Mac M1).
I am using the docker version and I want to create a new extension. I am not getting any errors.
The JS bundle directories are correctly created in 'node_modules' but they are empty when I ran "npm install".

<img width="202" alt="Capture d’écran 2023-11-07 à 09 04 48" src="https://github.com/directus/directus/assets/7793847/884bd5d2-1fc9-4a8d-887b-c6a8d6be703f">

When I run "npm run dev" :

<img width="785" alt="Capture d’écran 2023-11-07 à 09 08 10" src="https://github.com/directus/directus/assets/7793847/d8d36e79-2c70-4443-a2d4-9433f872d565">

**Comment by paescuj** [comment]
> I'm not sure if it's the same issue, on my end (Mac M1). I am using the docker version and I want to create a new extension. I am not getting any errors. The JS bundle directories are correctly created in 'node_modules' but they are empty when I ran "npm install".
> <img alt="Capture d’écran 2023-11-07 à 09 04 48" width="202" src="https://user-images.githubusercontent.com/7793847/280963705-884bd5d2-1fc9-4a8d-887b-c6a8d6be703f.png">
> 
> When I run "npm run dev" :
> <img alt="Capture d’écran 2023-11-07 à 09 08 10" width="785" src="https://user-images.githubusercontent.com/7793847/280964496-d8d36e79-2c70-4443-a2d4-9433f872d565.png">

This is a different issue. Please create a separate report for it, if you're still encountering it.
