### ISSUE TITLE
How to properly upgrade Directus on Kubernetes cluster?

### ISSUE THREAD

**Issue by marcelhorner** [directus/directus#20536]
### Describe the Bug

Hello everyone,

I am trying to upgrade Directus hosted on Kubernetes cluster from v10.7.0 to v10.8.2. I've tried to change docker version on image declaration but when pods are created with the new version I get this error:
```
2023-11-27T12:26:34: PM2 log: Launching in no daemon mode
2023-11-27T12:26:34: PM2 log: App [directus:0] starting in -cluster mode-
2023-11-27T12:26:34: PM2 error: Trace: Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at fork (node:child_process:172:10)
    at createWorkerProcess (node:internal/cluster/primary:129:10)
    at cluster.fork (node:internal/cluster/primary:164:25)
    at Object.nodeApp (/usr/local/lib/node_modules/pm2/lib/God/ClusterMode.js:48:21)
    at Object.executeApp (/usr/local/lib/node_modules/pm2/lib/God.js:232:9)
    at inject (/usr/local/lib/node_modules/pm2/lib/God.js:146:18)
    at Object.injectVariables (/usr/local/lib/node_modules/pm2/lib/God.js:571:10)
    at /usr/local/lib/node_modules/pm2/lib/God.js:144:9 {
  errno: -7,
  code: 'E2BIG',
}
    at God.logAndGenerateError (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:34:15)
    at Object.nodeApp (/usr/local/lib/node_modules/pm2/lib/God/ClusterMode.js:50:11)
    at inject (/usr/local/lib/node_modules/pm2/lib/God.js:146:18)
    at Object.injectVariables (/usr/local/lib/node_modules/pm2/lib/God.js:571:10)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/map.js:22:9
    at replenish (/usr/local/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:81:17)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:86:9
    at _asyncMap (/usr/local/lib/node_modules/pm2/node_modules/async/internal/map.js:20:12)
2023-11-27T12:26:34: PM2 error: 0 application started (no apps to run on ecosystem.config.cjs)
2023-11-27T12:26:34: PM2 log: PM2 successfully stopped
```

Is there any detailed documentation about the update proccess for Directus hosted on Kubernetes cluster? I don't know how should I properly update Directus running on Kubernetes cluster.

Thank you!

### To Reproduce

Deploy Directus 10.7.0 on Kubernetes cluster (image: directus/directus:10.7.0).

Confirm it is properly running on the cluster.

Change Directus image to 10.8.2 (image: directus/directus:10.8.2) and apply changes.

Check the error mentioned on Bug description on pod logs.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Odd! Haven't seen that issue myself on our Kubernetes usage. That E2BIG error seems to be related to the starting command being too long. What environment variables do you have set (omit the values) for this container? Maybe we've reached some sort of max amount for this environment 🤔

**Comment by marcelhorner** [comment]
Yes, the amount of env vars seems to be the problem.

It started just fine when I used only the following env vars:
```
  - name: PUBLIC_URL
  - name: KEY
  - name: SECRET
  - name: CACHE_ENABLED
  - name: CACHE_AUTO_PURGE
  - name: DB_CLIENT
  - name: DB_HOST
  - name: DB_PORT
  - name: DB_DATABASE
  - name: DB_USER
  - name: DB_PASSWORD
```

**Comment by marcelhorner** [comment]
Do you think using an yaml config file for Directus, instead of env vars, could fix this issue?

**Comment by xlmnxp** [comment]
@rijkvanzanten Can I know why you closed the ticket without it being solved?
I'm facing same issue in 10.8

**Comment by rijkvanzanten** [comment]
> how to implement that config file

See https://docs.directus.io/self-hosted/config-options.html#configuration-files for Directus' config file options. 

> also why there 1 of replicas work and others down and face same issue

There's tons of permutations when it comes to k8s config and usage, so I can't assist debugging everybody's individual setups unfortunately

**Comment by marcelhorner** [comment]
I've created an yaml file called directus-config.yaml with the configs I needed:
```
PUBLIC_URL: ...
ADMIN_EMAIL: ...
CACHE_ENABLED: true
CACHE_AUTO_PURGE: true
...
```

I've created the configmap from the yaml file using this command:
```kubectl create configmap directus-config --from-file=directus-config.yaml -n directus```

After that I've used the configmap to mount volume, and referenced it on CONFIG_PATH var. Following is the part addressing that on my helm yaml file:
```
          - name: CONFIG_PATH
            value: "/config/directus-config.yaml"
        volumeMounts:
        - name: config
          mountPath: "/config/"
      volumes:
      - name: config
        configMap:
          name: directus-config
```

Hope this helps!
