### ISSUE TITLE
TypeError: _m.themes is not iterable (cannot read property undefined) after upgrade from 10.5.3 to 10.8.2

### ISSUE THREAD

**Issue by bfour** [directus/directus#20589]
### Describe the Bug

After upgrading from 10.5.3 to 10.8.2 on fresh start and loading login page, getting:

🐰 Starting Directus...
index.2a491b91.entry.js:4008 Uncaught (in promise) TypeError: _m.themes is not iterable (cannot read property undefined)
    at bct (index.2a491b91.entry.js:4008:2224)
    at v2t (index.2a491b91.entry.js:4995:362)

### To Reproduce

Have an initialized instance of 10.5.3, upgrade to 10.8.2 and load login page.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by bfour** [comment]
Seems to have been caused by cloudflare cache.
