### ISSUE TITLE
Directus Update 10.6.1 to 10.8.2 failes "Error: ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists"

### ISSUE THREAD

**Issue by bastian-41** [directus/directus#20592]
### Describe the Bug

When Updating from Directus 10.6.1 to 10.8.2, Directus complains about an existing table `directus_versions`.

```
directus-local-directus-1  | [14:38:07.295] INFO: Skipping CLI extensions initialization due to outstanding migrations.
directus-local-directus-1  | [14:38:07.302] INFO: Initializing bootstrap...
directus-local-directus-1  | [14:38:07.305] INFO: Database already initialized, skipping install
directus-local-directus-1  | [14:38:07.305] INFO: Running migrations...
directus-local-directus-1  | Error: ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists
directus-local-directus-1  |     at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus-local-directus-1  |     at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus-local-directus-1  |     at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus-local-directus-1  |     at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus-local-directus-1  |     at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus-local-directus-1  |     at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus-local-directus-1  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
directus-local-directus-1  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
directus-local-directus-1  |     at Socket.emit (node:events:517:28)
directus-local-directus-1  |     at addChunk (node:internal/streams/readable:335:12)
directus-local-directus-1  |     --------------------
directus-local-directus-1  |     at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus-local-directus-1  |     at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
directus-local-directus-1  |     at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18
directus-local-directus-1  |     at new Promise (<anonymous>)
directus-local-directus-1  |     at Client_MySQL._query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)
directus-local-directus-1  |     at executeQuery (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
directus-local-directus-1  |     at Client_MySQL.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)
directus-local-directus-1  |     at Runner.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)
directus-local-directus-1  |     at Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:217:21)
directus-local-directus-1  |     at Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:31) {
directus-local-directus-1  |   code: 'ER_TABLE_EXISTS_ERROR',
directus-local-directus-1  |   errno: 1050,
directus-local-directus-1  |   sqlMessage: "Table 'directus_versions' already exists",
directus-local-directus-1  |   sqlState: '42S01',
directus-local-directus-1  |   index: 0,
directus-local-directus-1  |   sql: 'create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`))'
directus-local-directus-1  | }
directus-local-directus-1  | [14:38:07.314] INFO: Applying Add Content Versioning...
```
I found issue [20175](https://github.com/directus/directus/issues/20175) and learned, that the table `directus_versions` shouldn't exist in Directus prior 10.7.0. We are hosting Directus in a kubernetes Cluster running multiple replicas of Directus. It might be that the rolling update confused Directus due to multiple containers migrating simultaneously.
For the future I've to rethink our deployment strategy.

But right now I'm concerned about repairing the database in order to get the latest Directus version up and running. The solution in issue 20175 is dropping the table `directus_version'. Our table is empty so no problems there. But fk contraints prohibit the deletion.

```
mysql> drop table directus_versions;
ERROR 3730 (HY000): Cannot drop table 'directus_versions' referenced by a foreign key constraint 'directus_revisions_version_foreign' on table 'directus_revisions'.
```

Now I was able to delete the `directus_verisions` table. Now Directus complains about an existing column `versioning` in table `directus_collections'. I fear our database is corrupted on several levels.

Any ideas how I could repair my database?

Regards,
Bastian

### To Reproduce

I can reproduce the situation by using a dump of our corrupted database.
But I cannot describe the steps to reproduce the initial corruption of our database.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Sounds like a migration may have been aborted or failed at some point. Have you tried downgrading the migrations "migrate:down" and then re-applying them?
https://docs.directus.io/self-hosted/cli.html#upgrade-the-database

**Comment by bastian-41** [comment]
Hey @br41nslug , thanks for your comment.

No, I didn't. I made some experiments (with a dumped database, since I don't want to ride myself into deeper sh...) but no success so far.

I can rollback some migrations and did so several times.
```
/directus $ npx directus database migrate:down
[08:41:58.253] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[08:41:58.259] INFO: Running migrations...
[08:41:58.272] INFO: Undoing Require Shares Fields...
[08:41:59.290] INFO: Downgrade successful
/directus $ npx directus database migrate:down
[08:42:10.643] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[08:42:10.648] INFO: Running migrations...
[08:42:10.662] INFO: Undoing Migrate Translation Strings...
[08:42:10.852] INFO: Downgrade successful
```
I'm not sure how far back I'll have to migrate down. I was expecting the offending table `directus_version` to disappear when downgrading. But no success there.

Nevertheless I tried to migrate into the latest migration. As you can see, I downgraded several steps. But in the end the original error appears again.

```
/directus $ npx directus database migrate:latest
[08:50:11.310] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[08:50:11.314] INFO: Running migrations...
[08:50:11.318] INFO: Applying Add Color to Insights Icon...
[08:50:11.389] INFO: Applying Drop Non Null From IP of Activity...
[08:50:56.853] INFO: Applying Drop Non Null From Sender of Notifications...
[08:50:57.079] INFO: Applying Rename Hook Trigger to Event...
[08:50:57.114] INFO: Applying Update Notifications Timestamp Column...
[08:50:57.343] INFO: Applying Add Custom Aspect Ratios...
[08:50:57.438] INFO: Applying Add Origin to Accountability...
[08:50:57.584] INFO: Applying Update Material Icons...
[08:50:57.652] INFO: Applying Add Preview Settings...
[08:50:57.776] INFO: Applying Migrate Translation Strings...
[08:50:58.443] INFO: Applying Require Shares Fields...
[08:50:59.354] INFO: Applying Add Content Versioning...
[08:50:59.357] ERROR: create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) - ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists
    err: {
      "type": "Error",
      "message": "create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) - ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists",
      "stack":
          Error: ER_TABLE_EXISTS_ERROR: Table 'directus_versions' already exists
              at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:517:28)
              at addChunk (node:internal/streams/readable:335:12)
              --------------------
              at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
              at /directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:146:12)
              at Runner.query (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:217:21)
              at Runner.queryArray (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/execution/runner.js:269:31)
      "code": "ER_TABLE_EXISTS_ERROR",
      "errno": 1050,
      "sqlMessage": "Table 'directus_versions' already exists",
      "sqlState": "42S01",
      "index": 0,
      "sql": "create table `directus_versions` (`id` char(36) not null, `key` varchar(64) not null, `name` varchar(255), `collection` varchar(64) not null, `item` varchar(255) not null, `hash` varchar(255), `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`))"
    }
```

I suspect that downgrading doesn't help since the failed migration left the database in a state partly 'above' the latest successful migration which the downgrading won't address.

Now I'm thinking about other ways of reparing the database. Something like snapshot schema, data and so on and reapplying these into a freshly directus database. I'd appreciate your opinons about this...

**Comment by paescuj** [comment]
Have you been on the [v10.7.0-beta.0](https://github.com/directus/directus/releases/tag/v10.7.0-beta.0) release by any chance? Just curious.

Could you try this on your dump?:

```bash
# Optionally, to ensure you're on latest (v10.8.2) again
npx directus database migrate:latest

# Revert last 4 migrations (directus_versions is fourth-last)
for run in {1..4}; do npx directus database migrate:down; done

# Then apply the migrations again
npx directus database migrate:latest
```

**Comment by bastian-41** [comment]
Just for the record: We found out what killed the database migration initially. Our liveness probes in kubernetes were wrongly configured, killing a directus container if it doesn't startup within a minute.

@br41nslug initial idea was totally correct - Directus was aborted while migrating. 🤯

Thanks for Your help!
