### ISSUE TITLE
A Flow is still active even after deleting it in the database

### ISSUE THREAD

**Issue by ogabrielluiz** [directus/directus#20643]
### Describe the Bug

If you define a flow and delete it in the database that flow still runs even if its row and operations don't exist anymore.

### To Reproduce

1. Build a flow that block login (e.g trigger with auth.login and some operation after it)
2. Sign out and you will be blocked from logging back in
3. Delete the row in the database
4. Try logging in again and you'll get error 500 because the payload is incorrect due to the flow you've created.

```
[5/Dec/2023:18:36:19] [18:36:19] POST /auth/login 500 515ms
[5/Dec/2023:18:36:19] [18:36:19.436] ERROR: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[5/Dec/2023:18:36:19] err: {
[5/Dec/2023:18:36:19] "type": "TypeError",
[5/Dec/2023:18:36:19] "message": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined",
[5/Dec/2023:18:36:19] "stack":
[5/Dec/2023:18:36:19] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[5/Dec/2023:18:36:19] at new NodeError (node:internal/errors:405:5)
[5/Dec/2023:18:36:19] at Function.from (node:buffer:333:9)
[5/Dec/2023:18:36:19] at Object.verify (/directus/node_modules/.pnpm/argon2@0.31.1/node_modules/argon2/argon2.js:107:31)
[5/Dec/2023:18:36:19] at LocalAuthDriver.verify (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/local.js:30:46)
[5/Dec/2023:18:36:19] at LocalAuthDriver.login (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/local.js:35:20)
[5/Dec/2023:18:36:19] at AuthenticationService.login (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/services/authentication.js:111:28)
[5/Dec/2023:18:36:19] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[5/Dec/2023:18:36:19] at async file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/local.js:69:56
[5/Dec/2023:18:36:19] "code": "ERR_INVALID_ARG_TYPE"
[5/Dec/2023:18:36:19] }
```

### Directus Version

10.8.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I'm sorry i must have missed the part about deleting it directly from the database yesterday. Unfortunately unloading/reloading Flows only happens if Flows are enabled/disabled/changed using the API. Directus has no way of knowing that anything has changed when doing updates directly in the database.
