### ISSUE TITLE
Login failed using SDK SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by luistar15** [directus/directus#20689]
### Describe the Bug

I have installed directus with nginx and a ssl certificate signed by a custom local CA.

Trying to login using the SDK from CLI gives an error:
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async y (file:///path/to/app/node_modules/@directus/sdk/dist/chunk-GJVD322O.js:1:872)
    at async Object.login (file:///path/to/app/node_modules/@directus/sdk/dist/chunk-GJVD322O.js:1:25911)
    at async file:///path/to/app/index.js:8:1 {
  cause: Error: self-signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
      at TLSSocket.emit (node:events:514:28)
      at TLSSocket._finishInit (node:_tls_wrap:1070:8)
      at ssl.onhandshakedone (node:_tls_wrap:856:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
}
```

I have the Intermediate and Root CA certificate files (.crt) that I use for singing.

How can I use these certificates to connect to my directus site? Or bypass the certificate verification?

I only need it for development.

### To Reproduce

```javascript
import { createDirectus, authentication } from '@directus/sdk';

const client = createDirectus('https://directus.mypage.com').with( authentication() );

await client.login('user@email.com', 'password');
```

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
You can set the following variable on client side to disable validation of the certificate:
```shell
NODE_TLS_REJECT_UNAUTHORIZED='0'
```
See https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue for more information.

I highly recommend to use that only in development environment, as it makes the connection insecure.
