### ISSUE TITLE
upload image using service failing

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#20688]
### Describe the Bug

I'm not absolutley sure this is a bug as documentation is not describing how to use the uploadOne method. But I believe I am doing the right thing after reading the source code.
There is a 403 response coming back from S3 on upload of an image from a readable stream using FilesService in a Hook extension.
 

### To Reproduce

In any extension, try to use the filesService to upload an image.
My code :
```
`async function uploadFile(raw_file, ct_ref, filesService) {
  let res = await filesService.uploadOne(raw_file, {
    storage: "do",
    filename_storage: "package_card_" + ct_ref,
    filename_download: "package_card_" + ct_ref,
    type: "image/png",
  });
  console.log(res);`
```

error is :
```
    err: {
      "type": "S3ServiceException",
      "message": "UnknownError",
      "stack":
          InvalidAccessKeyId: UnknownError
              at throwDefaultError (/Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
              at /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
              at de_PutObjectCommandError (/Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5701:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
              at async /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
              at async /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
              at async /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
              at async /Users/Ben.Amato/Documents/computravel/ct-directus/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
              at async Promise.all (index 0)
      "name": "InvalidAccessKeyId",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 403,
        "requestId": "tx00000d79c1c13b581c76e-0065750334-bc9d9e44-fra1b",
        "attempts": 1,
        "totalRetryDelay": 0
      }

```
### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by sharkfin009** [comment]
sorry , my mistake. My access token for dev was invalid

**Comment by sharkfin009** [comment]
It is in fact working fine, sorry
