### ISSUE TITLE
Unable to open collection item from admin or filter on primary key. Validation failed for parameter 'p1'. Invalid string."

### ISSUE THREAD

**Issue by Heroeskitchen** [directus/directus#21016]
### Describe the Bug

I've been using Directus since v9 and have been updating the database consistently and am currently on v10.8.3.  Not exactly sure what happened, but I am suddenly unable to open a collection item.  Whenever I try to open it or filter the collection via the primary key, I get the following error:

`
ERROR: select top (@p0) [appointment].[id], [appointment].[user_created], [appointment].[date_created], [appointment].[date_updated], [appointment].[appointment_data], [appointment].[retailerID] from [appointment] where [appointment].[id] = @p1 order by [appointment].[id] asc - Validation failed for parameter 'p1'. Invalid string.
    err: {
      "type": "RequestError",
      "message": "select top (@p0) [appointment].[id], [appointment].[user_created], [appointment].[date_created], [appointment].[date_updated], [appointment].[appointment_data], [appointment].[retailerID] from [appointment] where [appointment].[id] = @p1 order by [appointment].[id] asc - Validation failed for parameter 'p1'. Invalid string.",
      "stack":
          Error: select top (@p0) [appointment].[id], [appointment].[user_created], [appointment].[date_created], [appointment].[date_updated], [appointment].[appointment_data], [appointment].[retailerID] from [appointment] where [appointment].[id] = @p1 order by [appointment].[id] asc - Validation failed for parameter 'p1'. Invalid string.
              at Request.validateParameters (...\node_modules\tedious\lib\request.js:331:15)
              at Connection.execSql (...\node_modules\tedious\lib\connection.js:1611:15)
              at Client_MSSQL._chomp (...\node_modules\knex\lib\dialects\mssql\index.js:215:20)
              at Client_MSSQL._enqueueRequest (...\node_modules\knex\lib\dialects\mssql\index.js:222:10)
              at ...\node_modules\knex\lib\dialects\mssql\index.js:410:12
              at new Promise (<anonymous>)
              at Client_MSSQL._query (...\node_modules\knex\lib\dialects\mssql\index.js:390:12)
              at executeQuery (...\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
              at Client_MSSQL.query (...\node_modules\knex\lib\client.js:154:12)
              at Runner.query (...\node_modules\knex\lib\execution\runner.js:141:36)
      "code": "EPARAM"
    }
`

### To Reproduce

Open a record for this collection or filter on the primary key.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks for opening the issue! A couple of questions:

- Is only a specific item affected in this collection? If so, are there any abnormalities with it?
- Would you be able to share the data model of the affected collection, specifically the primary key?
- Do you know whether this only happens with v10.8.3, i.e. not with v10.8.2?
- Have you made any other changes, e.g. update of the database, item changes, etc.?

**Comment by Heroeskitchen** [comment]
It seems to be locked to a specific collection, but every item is inaccessible.
what format would be best for the data model? I attached a screenshot of the primary key, but if you need me to export the schema, just let me know.

There were no issues in 10.8.2.  I will attempt a rollback and see if I have any issues.

Nothing as of late other than updating a couple of extensions.  An endpoint and a hook, but no schema changes in 10.8.3

![image](https://github.com/directus/directus/assets/3160388/31615933-89d9-46ed-903f-b27f94a7e99e)

**Comment by paescuj** [comment]
Most likely related to #20744, seems like Knex -> MSSQL doesn't support literal big int.
