### ISSUE TITLE
M2A Field documentation under Global Query Parameters doesn't seem to work in hook extensions

### ISSUE THREAD

**Issue by Healios** [directus/directus#21019]
### Describe the Request

I have a collection called "pages" with a field called "blocks" that is of the type M2A. I've created a hook extension and have an action that runs on "pages.items.update", which tries to read the page from the directus database.

```
action("pages.items.update", async (meta, context) =>
{
	// Create items service.
	const itemsService = new ItemsService("pages", { schema: await getSchema(), accountability: context.accountability });

	// Get page id.
	const pageId = meta.keys[0];

	// Get page from database.
	const page = await itemsService.readOne(pageId,
	{
		fields: [
			"title",
			"category",
			"category.name",
			{
				blocks: [
					{
						item: {
							text_hero_blocks: [ "title", "content" ]
						}
					}
				]
			},
		],
	});
	console.log(page);
});
```

The above yields the error:
```
[14:41:26.360] WARN: An error was thrown while executing action "pages.items.update"
[14:41:26.360] WARN: fieldKey.includes is not a function
    err: {
      "type": "TypeError",
      "message": "fieldKey.includes is not a function",
      "stack":
          TypeError: fieldKey.includes is not a function
              at convertWildcards (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/utils/get-ast-from-query.js:228:26)
              at parseFields (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/utils/get-ast-from-query.js:68:24)
              at getASTFromQuery (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/utils/get-ast-from-query.js:63:26)
              at ItemsService.readByQuery (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/items.js:310:25)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async ItemsService.readOne (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/items.js:365:25)
              at async EventEmitter.<anonymous> (file:///directus/extensions/hooks/directus-meilisearch-integration-extension/index.js?t=1704809744166:1:81871)
              at async Promise.all (index 0)
    }
```

I have tried defining the fields property in so many different ways (by being specific by "walking the tree" and by using wildcards, and a mix of the two), but none of them work. The closest I've gotten is being returned the id or an empty object.
I have written the above code based on the documentation presented here: https://docs.directus.io/reference/query.html#fields

Unless I have implemeted the documented functionality incorrectly, then either the documentation should be corrected or an extra section should be added specifically for hooks.

### Maintainence Strategy

I'm not sure how to answer this, but an answer is needed.

**Comment by br41nslug** [comment]
You're using the `fields` format exclusively used in the SDK. Make sure you use the regular format (REST format https://docs.directus.io/reference/query.html#fields) which is just an array of strings no nested objects.

**Comment by br41nslug** [comment]
The last output seems fine, the nested `[Object]` should hold the `text_hero_blocks` you're requesting.

**Comment by Healios** [comment]
Thank you! That's my bad.

I'm mainly a C# developer and I wasn't aware that "console.log" isn't capable of going that deep.
