### ISSUE TITLE
Can't setup S3 inside docker

### ISSUE THREAD

**Issue by rohatin-codemelt** [directus/directus#21058]
### Describe the Bug

While setting up s3 bucket for directus file storage I've encountered this error that I can't bypass
`err: {
root-directus-1  |       "type": "Error",
root-directus-1  |       "message": "Location \"S3\" doesn't exist.",
root-directus-1  |       "stack":
root-directus-1  |           Error: Location "S3" doesn't exist.
root-directus-1  |               at StorageManager.location (file:///directus/node_modules/.pnpm/file+packages+storage/node_modules/@directus/storage/dist/index.js:19:13)
root-directus-1  |               at AssetsService.getAsset (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/assets.js:46:38)
root-directus-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
root-directus-1  |               at async file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/controllers/assets.js:152:36
root-directus-1  |     }`

Here is my current docker compose file

version: "3"
services:
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    environment:
      KEY: "secret_random_value_i_guess"
      SECRET: "another_secret_random_value_i_guess"
      ADMIN_EMAIL: "adminadmin123@gmail.com"
      ADMIN_PASSWORD: "admin123!"
      DB_CLIENT: "pg"
      DB_HOST: "my_db_host"
      DB_USER: "my_db_user"
      DB_PORT: "5432"
      DB_PASSWORD: "my_db_pass"
      DB_DATABASE: "my_db_name"
      DB_SSL: "false"
      RATE_LIMITER_ENABLED: "false"
      CACHE_STORAGE: "memory"
      STORAGE_LOCATIONS: "s3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: "digital_ocean_public_key"
      STORAGE_S3_SECRET: "digital_ocean_secret_key"
      STORAGE_S3_ENDPOINT: "https://fra1.digitaloceanspaces.com"
      STORAGE_S3_BUCKET: "my_bucket_name"
      STORAGE_S3_REGION: "fra1"
      STORAGE_S3_ACL: "public"
      STORAGE_S3_ROOT: "/"
      STORAGE_S3_HEALTHCHECK_TRESHOLD: "750ms"

### To Reproduce

Run the docker compose file and try to upload/fetch anything
When uploading any file they get blocked at 100%
When trying to fetch I receive that error
The S3 bucket is working fine, I've tested it with a node sample project

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rohatin-codemelt** [comment]
Maybe this is helpful, I've let it do the upload at 100% for a few minutes. Got back again and saw this error:
```[01:27:04.209] WARN: Couldn't save file f2eb3faa-f82c-48c9-967c-803b6fbdb096.ico
documents-directus-1  | [01:27:04.210] WARN: UnknownError
documents-directus-1  |     err: {
documents-directus-1  |       "type": "S3ServiceException",
documents-directus-1  |       "message": "UnknownError",
documents-directus-1  |       "stack":
documents-directus-1  |           SignatureDoesNotMatch: UnknownError
documents-directus-1  |               at throwDefaultError (/directus/node_modules/.pnpm/@smithy+smithy-client@2.1.18/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
documents-directus-1  |               at /directus/node_modules/.pnpm/@smithy+smithy-client@2.1.18/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
documents-directus-1  |               at de_PutObjectCommandError (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.477.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4841:12)
documents-directus-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
documents-directus-1  |               at async /directus/node_modules/.pnpm/@smithy+middleware-serde@2.0.15/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-signing@3.468.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
documents-directus-1  |               at async /directus/node_modules/.pnpm/@smithy+middleware-retry@2.0.24/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-flexible-checksums@3.468.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.474.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.474.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
documents-directus-1  |       "name": "SignatureDoesNotMatch",
documents-directus-1  |       "$fault": "client",
documents-directus-1  |       "$metadata": {
documents-directus-1  |         "httpStatusCode": 403,
documents-directus-1  |         "requestId": "tx000000de69b66862eaf09-0065a094f0-d4d5fc87-fra1b",
documents-directus-1  |         "attempts": 1,
documents-directus-1  |         "totalRetryDelay": 0
documents-directus-1  |       },
documents-directus-1  |       "Code": "SignatureDoesNotMatch",
documents-directus-1  |       "RequestId": "tx000000de69b66862eaf09-0065a094f0-d4d5fc87-fra1b",
documents-directus-1  |       "HostId": "d4d5fc87-fra1b-fra1-zg02"
documents-directus-1  |     }
documents-directus-1  | [01:27:04.993] WARN: Couldn't delete file f2eb3faa-f82c-48c9-967c-803b6fbdb096.ico
documents-directus-1  | [01:27:04.993] WARN: UnknownError
documents-directus-1  |     err: {
documents-directus-1  |       "type": "S3ServiceException",
documents-directus-1  |       "message": "UnknownError",
documents-directus-1  |       "stack":
documents-directus-1  |           SignatureDoesNotMatch: UnknownError
documents-directus-1  |               at throwDefaultError (/directus/node_modules/.pnpm/@smithy+smithy-client@2.1.18/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
documents-directus-1  |               at /directus/node_modules/.pnpm/@smithy+smithy-client@2.1.18/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
documents-directus-1  |               at de_DeleteObjectCommandError (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.477.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:2706:12)
documents-directus-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
documents-directus-1  |               at async /directus/node_modules/.pnpm/@smithy+middleware-serde@2.0.15/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-signing@3.468.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
documents-directus-1  |               at async /directus/node_modules/.pnpm/@smithy+middleware-retry@2.0.24/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.474.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.474.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
documents-directus-1  |               at async /directus/node_modules/.pnpm/@aws-sdk+middleware-logger@3.468.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
documents-directus-1  |       "name": "SignatureDoesNotMatch",
documents-directus-1  |       "$fault": "client",
documents-directus-1  |       "$metadata": {
documents-directus-1  |         "httpStatusCode": 403,
documents-directus-1  |         "requestId": "tx000005e2417132e3f0d4c-0065a09568-d4d58440-fra1b",
documents-directus-1  |         "attempts": 1,
documents-directus-1  |         "totalRetryDelay": 0
documents-directus-1  |       },
documents-directus-1  |       "Code": "SignatureDoesNotMatch",
documents-directus-1  |       "RequestId": "tx000005e2417132e3f0d4c-0065a09568-d4d58440-fra1b",
documents-directus-1  |       "HostId": "d4d58440-fra1b-fra1-zg02"
documents-directus-1  |     }```

**Comment by AMB-Informacio** [comment]
It seems more a problem with STORAGE_S3_KEY  STORAGE_S3_SECRET and it's associated permissions. Not a Directus issue. Try to do the same operation (delete file f2eb3faa-f82c-48c9-967c-803b6fbdb096.ico) with an HTTP call (using Postman, cURL or a basic Node project).

**Comment by paescuj** [comment]
Hey @rohatin-codemelt! Thanks for opening the issue!
I agree with @AMB-Informacio that this seems to be a misconfiguration of the S3 bucket, rather than an issue with Directus itself.
Please double check your configuration. Previous issues with DigitalOcean buckets configs may lead you into the right direction, for example https://github.com/directus/directus/issues/16876#issuecomment-1418931059.

I'm closing this issue for now, but we'll reopen if it should turn out that it is an actual issue in Directus 👍🏻
