### ISSUE TITLE
UpdateCheck leads to endless restarts

### ISSUE THREAD

**Issue by feitzi** [directus/directus#21192]
### Describe the Bug

With 10.8.3 the update check leads to a endless restart loop if the check triggers a failure. 
Here is the log:
```

Jan 25 10:52:28 DIRECTUS_HOST systemd[1]: Started Directus 9.
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]: file:///opt/directus/node_modules/@directus/update-check/dist/index.js:62
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]:  const latestVersion = packageManifest["dist-tags"]["latest"];
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]:                                                    ^
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]: TypeError: Cannot read properties of undefined (reading 'latest')
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]:    at updateCheck (file:///opt/directus/node_modules/@directus/update-check/dist/index.js:62:53)
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]:    at async file:///opt/directus/node_modules/directus/cli.js:6:2
Jan 25 10:52:28 DIRECTUS_HOST npx[16194]: Node.js v18.17.1
Jan 25 10:52:28 DIRECTUS_HOST systemd[1]: directus.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 10:52:28 DIRECTUS_HOST systemd[1]: directus.service: Failed with result 'exit-code'.
Jan 25 10:52:30 DIRECTUS_HOST systemd[1]: directus.service: Scheduled restart job, restart counter is at 234.
Jan 25 10:52:30 DIRECTUS_HOST systemd[1]: Stopped Directus 9.
Jan 25 10:52:30 DIRECTUS_HOST systemd[1]: Started Directus 9.
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]: file:///opt/directus/node_modules/@directus/update-check/dist/index.js:62
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]:  const latestVersion = packageManifest["dist-tags"]["latest"];
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]:                                                    ^
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]: TypeError: Cannot read properties of undefined (reading 'latest')
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]:    at updateCheck (file:///opt/directus/node_modules/@directus/update-check/dist/index.js:62:53)
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]:    at async file:///opt/directus/node_modules/directus/cli.js:6:2
Jan 25 10:52:30 DIRECTUS_HOST npx[16225]: Node.js v18.17.1
Jan 25 10:52:30 DIRECTUS_HOST systemd[1]: directus.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 10:52:30 DIRECTUS_HOST systemd[1]: directus.service: Failed with result 'exit-code'.
Jan 25 10:52:31 DIRECTUS_HOST systemd[1]: directus.service: Scheduled restart job, restart counter is at 235.
```

We have downgraded to 10.8.2 and now everything is working fine!
In our opinion, directus should not cause an error if the update check fails! Maybe directus should try/catch the whole update check method?

### To Reproduce

Update from 10.8.3 from 10.8.2 via NPM

### Directus Version

V10.8.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by feitzi** [comment]
Perfect, thanks for the fast replay and the PR! We will wait for the release :)
