### ISSUE TITLE
Bundle cant get registered after update / URL is invalid

### ISSUE THREAD

**Issue by FirstSanny** [directus/directus#21487]
### Describe the Bug

After Updating from directus 10.8.3 to 10.9.2 our bundle isnt getting registered anymore. 

This is the error message. 
``` 
err: {
      "type": "TypeError",
      "message": "Invalid URL",
      "stack":
          TypeError [ERR_INVALID_URL]: Invalid URL
              at new NodeError (node:internal/errors:405:5)
              at new URL (node:internal/url:778:13)
              at xO (D:\code\VS - Operations - Inventory Management Experience\product-information-manager\app\extensions\directus-extension-rebolet-bundle\dist\api.js:8:684206)
              at new SA.AbstractDirectusApi (D:\code\VS - Operations - Inventory Management Experience\product-information-manager\app\extensions\directus-extension-rebolet-bundle\dist\api.js:8:710899)
              at new IA (D:\code\VS - Operations - Inventory Management Experience\product-information-manager\app\extensions\directus-extension-rebolet-bundle\dist\api.js:8:712826)
              at Object.<anonymous> (D:\code\VS - Operations - Inventory Management Experience\product-information-manager\app\extensions\directus-extension-rebolet-bundle\dist\api.js:8:722867)
              at Module._compile (node:internal/modules/cjs/loader:1241:14)
              at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
              at Module.load (node:internal/modules/cjs/loader:1091:32)
              at Module._load (node:internal/modules/cjs/loader:938:12)
              at cjsLoader (node:internal/modules/esm/translators:283:17)
              at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:233:7)
              at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
              at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
              at async ExtensionManager.registerBundles (file:///D:/code/VS%20-%20Operations%20-%20Inventory%20Management%20Experience/product-information-manager/node_modules/@directus/api/dist/extensions/manager.js:491:41)
              at async ExtensionManager.load (file:///D:/code/VS%20-%20Operations%20-%20Inventory%20Management%20Experience/product-information-manager/node_modules/@directus/api/dist/extensions/manager.js:158:9)
      "input": "undefined",
      "code": "ERR_INVALID_URL"
    }
```

Already put some console logs in the calling file and the error seems to happen in the `importFileUrl` line of the `registerBundle` function.
![image](https://github.com/directus/directus/assets/23708333/04213776-9153-4504-b2dd-f487ebb3aeca)

### To Reproduce

Set up a bundle extension on windows machine with directus version 10.8.3 and add at least an extension for hook, endpoint, display, interface and module. Try upgrading and starting the app.

### Directus Version

10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by itszeeshan** [comment]
Yeah, I'm receiving the same error for some reason. And also this error doesn't say a lot as well, so cant figure it out.

**Comment by Nitwel** [comment]
I was not able to reproduce this with the provided information. Please update to the latest version and see if it still persists. In case it does it would be helpful if you could provide the extension source code. If you don't want to share it publicly, you can send it to nils@directus.io . I'll close it for now (also because of the old age) but am happy to reopen it if I'm able to reproduce this bug.
