### ISSUE TITLE
directus_users get error when used as Global Relational Variable as filter in Insights Panels

### ISSUE THREAD

**Issue by floux-digital** [directus/directus#21529]
### Describe the Bug

In insights, using model directus_users as Global Relational Variable to filter another model (thats have O2M field pointing to directus_users), I get the the GraphQL validation error.

```
[02:30:34.823] DEBUG: GraphQL validation error.
    err: {
      "type": "",
      "message": "GraphQL validation error.",
      "stack":
          DirectusError: GraphQL validation error.
              at GraphQLService.execute (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/services/graphql/index.js:79:19)
              at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/controllers/graphql.js:25:43
              at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/utils/async-handler.js:1:66
              at Layer.handle [as handle_request] (/directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
              at trim_prefix (/directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:328:13)
              at /directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:286:9
              at Function.process_params (/directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:346:12)
              at next (/directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:280:10)
              at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/middleware/graphql.js:64:12
              at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/utils/async-handler.js:1:66
      "name": "DirectusError",
      "extensions": {
        "errors": [
          {
            "message": "Field \"_eq\" is not defined by type \"directus_users_filter\". Did you mean \"_or\"?",
            "locations": [
              {
                "line": 1,
                "column": 165
              }
            ],
            "path": [
              "query_32002623"
            ]
          }

]
      },
      "code": "GRAPHQL_VALIDATION",
      "status": 400
    }
[02:30:34.827] TRACE: [339.661ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [4bca7a5f-****-****-****-****, 1]
```

### To Reproduce

1. Create a custom model with field user pointing to directus_users
2. Create some registers into new custom model
3. Create a dashboard
4. Add a Global Relational Variable using the model directus_users
5. Add a Panel to count data from custom model, using the Global Relational Variable to filter the data
6. Apply the changes and try to filter the data.

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Can you try setting the filter to be `users.id` instead of `users`?
