### ISSUE TITLE
schema: Cannot set properties of undefined (setting 'primary')

### ISSUE THREAD

**Issue by wenerme** [directus/directus#21545]
### Describe the Bug

```log
[15:59:22.746] WARN: Cannot set properties of undefined (setting 'primary')
    err: {
      "type": "TypeError",
      "message": "Cannot set properties of undefined (setting 'primary')",
      "stack":
          TypeError: Cannot set properties of undefined (setting 'primary')
              at Postgres.overview (file:///directus/node_modules/.pnpm/file+packages+schema_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/@directus/schema/dist/index.js:383:36)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async getDatabaseSchema (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/utils/get-schema.js:53:28)
              at async getSchema (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/utils/get-schema.js:32:22)
              at async getExtensionsSettings (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/extensions/lib/get-extensions-settings.js:14:17)
              at async ExtensionManager.load (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/extensions/manager.js:150:39)
              at async ExtensionManager.initialize (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/extensions/manager.js:126:13)
              at async loadExtensions (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/cli/load-extensions.js:19:5)
              at async createCli (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/cli/index.js:20:5)
    }
```

https://github.com/directus/directus/blob/7f4d4319718d6542e63594fd2b532056c9ad98c7/packages/schema/src/dialects/postgres.ts#L202-L204

### To Reproduce

using pg with muti schema

```
DB_SEARCH_PATH=array:directus,public
```

BTW, v10.8 is ok

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by wenerme** [comment]
Caused by perm, maybe add a precheck ?

**Comment by ricricucit** [comment]
JFYI: just experienced this at startup with Directus `10.10.4` and `AWS RDS aurora-postgresql13` (with empty database or `directus_X` tables), same results.
I've [asked in Discord](https://discord.com/channels/725371605378924594/1151320093565927504/1220011973379625032) for help.

**Comment by rijkvanzanten** [comment]
@ricricucit Same exact error stack, or same error in a different place?

**Comment by ricricucit** [comment]
@rijkvanzanten I'm running: 

```
npx directus bootstrap && npx directus schema apply --yes /directus/snapshots/latest.yaml && npx directus start
```

#### see here:
<img width="2408" alt="Screenshot 2024-04-04 at 16 19 31" src="https://github.com/directus/directus/assets/1016775/ce055a34-4af8-4714-8f61-54ef5270dcdc">

#### full log file:
[web-65c5f95647-22d55_web.log](https://github.com/directus/directus/files/14872597/web-65c5f95647-22d55_web.log)

**Comment by Hamzaahmed742** [comment]
> @rijkvanzanten I'm running:
> 
> ```
> npx directus bootstrap && npx directus schema apply --yes /directus/snapshots/latest.yaml && npx directus start
> ```
> 
> #### see here:
> <img alt="Screenshot 2024-04-04 at 16 19 31" width="2000" src="https://private-user-images.githubusercontent.com/1016775/319626286-ce055a34-4af8-4714-8f61-54ef5270dcdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjMyNjksIm5iZiI6MTcxMzI2Mjk2OSwicGF0aCI6Ii8xMDE2Nzc1LzMxOTYyNjI4Ni1jZTA1NWEzNC00YWY4LTQ3MTQtOGY2MS01NGVmNTI3MGRjZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTAyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjRjZjBkNzc5Mjk0YTBlMjE2MTljOTIwNTkyZmY5MmE3YThhMGFlYWFlZjQ2ODE2YWE2MTBjNDQyMjZiOGRlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E_vHJlyBL2bhF7UVGWvQQdkaf7h-obXqxrGwjfKXyq8">
> #### full log file:
> [web-65c5f95647-22d55_web.log](https://github.com/directus/directus/files/14872597/web-65c5f95647-22d55_web.log)
> 
> #### More ℹ️
> * I am not setting `DB_SEARCH_PATH`
> * Locally, using `image: postgis/postgis:13-master` everything's fine. 🥲

@rijkvanzanten any hints or suggestions ? Stuck here for quite a long time. Thanks for the help
