### ISSUE TITLE
Graphql: Subscribing to same event more than 10 times throws a warning

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21570]
### Describe the Bug

While trying to subscribe to same event more than 10 times, Directus throws the following warning:
```
(node:99122) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at __node_internal_genericNodeError (node:internal/errors:865:15)
    at _addListener (node:events:591:17)
    at EventEmitter.addListener (node:events:609:10)
    at on (node:events:1124:13)
    at Object.subscribe (/directus/api/src/services/graphql/subscription.ts:93:26)
    at subscribe.next (<anonymous>)
    at <anonymous> (/directus/api/src/services/graphql/subscription.ts:26:20)
    at AsyncGenerator.next (<anonymous>)
    at Object.next (/directus/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/mapAsyncIterator.js:43:39)
    at onMessage (file:///directus/directus/node_modules/.pnpm/graphql-ws@5.15.0_graphql@16.8.1/node_modules/graphql-ws/lib/server.mjs:207:180)
```

### To Reproduce

In order to replicate this issue you need to:
- set `WEBSOCKETS_ENABLED: 'true'`
- create collection `example` with string fields `id` and `name`
- start listening with the following code and it will throw a warning on Directus
<details><summary>Code</summary>

```ts
import { createClient } from "graphql-ws";
import WebSocket from "ws";

async function start() {
  try {
    const client = createClient({
      url: "ws://localhost:8055/graphql",
      keepAlive: 30000,
      webSocketImpl: WebSocket,
      connectionParams: async () => {
        return { access_token: "123456789" };
      },
    });

    const subscription = client.iterate({
      query: "subscription { example_mutated { key event data { id name } } }",
    });

    for await (const event of subscription) {
      console.log(event);
    }
  } catch (error) {
    console.log(error);
  }
}

(async function () {
  const items = Array(15).fill(0);

  for (let i of items) {
    start();
    await new Promise((res) => setTimeout(res, 1000));
  }
})();
```

</details>

~~In docs says that `WEBSOCKETS_GRAPHQL_CONN_LIMIT` is set to `Infinity`: https://docs.directus.io/self-hosted/config-options.html#graphql
Although this configuration seems to not be used anywhere.~~
It is being set properly as mentioned by @br41nslug here: https://github.com/directus/directus/issues/21570#issuecomment-1964997327

## Suggestion
Maybe this could be as simple as setting this:
```ts
const emitter = new EventEmitter();
emitter.setMaxListeners(Number(env['WEBSOCKETS_GRAPHQL_CONN_LIMIT']));
const messages = createPubSub(emitter);
```

In the following line?
https://github.com/directus/directus/blob/3e9e5ecbf40a6de122eb44e238642e46b9dc35a1/api/src/services/graphql/subscription.ts#L11

### Directus Version

main (10.9.3)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Important to note: This is a warning only, nothing is actually blocked!

**Comment by joselcvarela** [comment]
Also it looks like the configuration `WEBSOCKETS_REST_CONN_LIMIT` is not being used

**Comment by br41nslug** [comment]
Both the connection limit variables are being managed here: https://github.com/directus/directus/blob/main/api/src/websocket/controllers/base.ts#L79

**Comment by joselcvarela** [comment]
You are right @br41nslug. Apologies for pointing out wrong 🙏

**Comment by rijkvanzanten** [comment]
Thank you for taking the time to report this issue. We really appreciate the help in improving Directus. Due to limited resources, we’re unable to address every reported bug and must choose what to work on wisely. Based on the information available at present, this issue cannot be prioritized at this time. Please see our bug triaging process for more information on how we evaluate and manage our GitHub issue backlog. We’ll close this issue as a wontfix, but are happy to revisit at a later date. If you would like to open a PR to resolve this issue, you’re more than welcome to do so. Thanks!
