### ISSUE TITLE
Unable to initiate MSSQL database due to incorrect use of dedicated administrator connection (DAC)

### ISSUE THREAD

**Issue by richardwhatever** [directus/directus#21595]
### Describe the Bug

I'm using SQL Server 16.0.1000.6 (2022), with a brand new untouched database.

The initialisation procedure fails when adding DIrectus to a database on MSSQL when a dedicated administrator connection (DAC) is utililised.

```

Attaching to directus-directus-1
directus-directus-1  | [08:52:22.431] INFO: Initializing bootstrap...
directus-directus-1  | [08:52:22.448] INFO: Installing Directus system tables...
directus-directus-1  | [08:52:22.548] INFO: Running migrations...
directus-directus-1  | [08:52:22.556] INFO: Applying Remove Collection Foreign Keys...
directus-directus-1  | [08:52:22.580] INFO: Applying Remove System Relations...
directus-directus-1  | [08:52:22.588] INFO: Applying Remove System Collections...
directus-directus-1  | [08:52:22.599] INFO: Applying Remove System Fields...
directus-directus-1  | [08:52:22.617] INFO: Applying Add Cascade System Relations...
directus-directus-1  | [08:52:22.686] INFO: Applying Change Webhook URL Type...
directus-directus-1  | [08:52:22.696] INFO: Applying Add Relations Sort Field...
directus-directus-1  | [08:52:22.705] INFO: Applying Remove Locked Fields...
directus-directus-1  | [08:52:22.797] INFO: Applying Webhooks Collections Text...
directus-directus-1  | [08:52:22.803] INFO: Applying Add Refresh Interval...
directus-directus-1  | [08:52:22.810] INFO: Applying Make Filesize Nullable...
directus-directus-1  | [08:52:22.879] INFO: Applying Add Collections Accountability...
directus-directus-1  | [08:52:22.888] INFO: Applying Remove Files Interface...
directus-directus-1  | [08:52:22.896] INFO: Applying Rename Interfaces...
directus-directus-1  | [08:52:22.999] INFO: Applying Restructure Relations...
directus-directus-1  | [08:52:23.198] INFO: Applying Add Foreign Key Constraints...
directus-directus-1  | [08:52:23.221] INFO: Applying Add System Fk Triggers...
directus-directus-1  | [08:52:23.271] INFO: Applying Add Collections Icon Color...
directus-directus-1  | [08:52:23.277] INFO: Applying Add Insights...
directus-directus-1  | [08:52:23.289] INFO: Applying Add Deep Clone Config...
directus-directus-1  | [08:52:23.299] INFO: Applying Change Filesize Bigint...
directus-directus-1  | [08:52:23.366] INFO: Applying Add Conditions to Fields...
directus-directus-1  | [08:52:23.372] INFO: Applying Add Default Folder...
directus-directus-1  | [08:52:23.380] INFO: Applying Replace Groups...
directus-directus-1  | [08:52:23.387] INFO: Applying Add Required to Fields...
directus-directus-1  | [08:52:23.395] INFO: Applying Update Groups...
directus-directus-1  | [08:52:23.403] INFO: Applying Change Image Metadata Structure...
directus-directus-1  | [08:52:23.409] INFO: Applying Add Geometry Config...
directus-directus-1  | [08:52:23.414] INFO: Applying Remove Limit Column...
directus-directus-1  | [08:52:23.480] INFO: Applying Add Auth Provider...
directus-directus-1  | [08:52:23.502] INFO: Applying Webhooks Collections Not Null...
directus-directus-1  | [08:52:23.510] INFO: Applying Move Module Setup...
directus-directus-1  | [08:52:23.580] INFO: Applying Webhooks URL Not Null...
directus-directus-1  | [08:52:23.587] INFO: Applying Add Collection Organization...
directus-directus-1  | [08:52:23.595] INFO: Applying Replace Fields Group...
directus-directus-1  | [08:52:23.668] INFO: Applying Replace M2M Interface...
directus-directus-1  | [08:52:23.676] INFO: Applying Rename Login Action...
directus-directus-1  | [08:52:23.682] INFO: Applying Update Presets...
directus-directus-1  | [08:52:23.752] INFO: Applying Add Auth Data...
directus-directus-1  | [08:52:23.757] INFO: Applying Add Webhook Headers...
directus-directus-1  | [08:52:23.762] INFO: Applying Set Unique to User Token...
directus-directus-1  | [08:52:23.767] INFO: Applying Update Special Geometry...
directus-directus-1  | [08:52:23.775] INFO: Applying Remove Collections Listing...
directus-directus-1  | [08:52:23.840] INFO: Applying Add Notifications...
directus-directus-1  | [08:52:23.852] INFO: Applying Add Shares...
directus-directus-1  | ConnectionError: Connection lost - socket hang up
directus-directus-1  |     at Connection.socketError (/directus/node_modules/.pnpm/tedious@16.7.1/node_modules/tedious/lib/connection.js:1344:26)
directus-directus-1  |     at Connection.socketEnd (/directus/node_modules/.pnpm/tedious@16.7.1/node_modules/tedious/lib/connection.js:1357:12)
directus-directus-1  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/tedious@16.7.1/node_modules/tedious/lib/connection.js:1053:12)
directus-directus-1  |     at Socket.emit (node:events:529:35)
directus-directus-1  |     at endReadableNT (node:internal/streams/readable:1400:12)
directus-directus-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
directus-directus-1  |   code: 'ESOCKET'
directus-directus-1  | }
directus-directus-1 exited with code 1
```

This raises the following event log:
```
Could not connect because the maximum number of '1' dedicated administrator connections already exists. Before a new connection can be made, the existing dedicated administrator connection must be dropped, either by logging off or ending the process. [CLIENT: 127.0.0.1]
```

My thought is that this is not being recreated in your tests etc because you are not connecting to the database in such a way as to trigger a DAC.

I'm definitely out of my experience/depth here, but DACs seem to be triggered by it being a local connection and user being a member of the sysadmin group.

The resolution would be to not create more than one simultaneous connection, or someother way don't trigger a DAC.

My setup involves me using Directus in Docker and then connecting to a local SQL Server, via the following docker-compose section:

```
      DB_CLIENT: 'mssql' #DB Client Type you can use other type of clients
      DB_HOST: 'host.docker.internal' # host name of the DB container, using host.docker.internal, you can use container name
      DB_PORT: '1434' #port on which DB Container is listening
      DB_DATABASE: 'DirectusTest' #Database name
      DB_USER: 'directus' #Newly created Database User
      DB_PASSWORD: 'directus' #Newly Created database password
```

### To Reproduce

I'm using SQL Server 16.0.1000.6 (2022), with a brand new untouched database.
Just try and initiate Docker an the error occurs.

### Directus Version

10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by richardwhatever** [comment]
Can i bump this somehow? This is a critical issue that renders Directus unusable.

**Comment by rijkvanzanten** [comment]
Can you try setting `DB_POOL__MAX` to `1`? That might prevent the underlying driver to create multiple connections. 

> Can i bump this somehow? This is a critical issue that renders Directus unusable.

While I understand the urgency for you, I'm not able to treat this as a high/urgent prio issue for the project, as the reported behavior strongly suggests a configuration mismatch between SQL Server's `'remote admin connections'`, Directus' default connection pooling configuration, and SQL Server seeing the traffic from Directus as "remote" rather than local, most likely due to how Docker's networking mode is configured. 🤔

**Comment by richardwhatever** [comment]
My understanding was that it was treating it as local, which then triggered a dedicated administrator connection (DAC). DACs can't haven multiple concurrent connections, which then causes the crash.

I'm trying to set  `DB_POOL__MAX` to `1` in the docker-compose file,

```
 environment:
      DB_POOL__MAX: 1
```

but when i then run `docker-compose up` i'm getting:

```
 ✔ Container directus-directus-1  Recreated                                                                                       0.1s Attaching to directus-directus-1
directus-directus-1  | Error: Tarn: opt.max is smaller than opt.min
directus-directus-1  |     at new Pool (/directus/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/Pool.js:26:19)
directus-directus-1  |     at Client_MSSQL.initializePool (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/client.js:301:17)
directus-directus-1  |     at new Client (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/client.js:85:14)
directus-directus-1  |     at new Client_MSSQL (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/dialects/mssql/index.js:26:5)
directus-directus-1  |     at Function.knex (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/knex-builder/Knex.js:16:28)
directus-directus-1  |     at getDatabase (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/index.js:123:28)
directus-directus-1  |     at getSchemaInspector (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/index.js:141:22)
directus-directus-1  |     at isInstalled (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/index.js:207:23)
directus-directus-1  |     at loadExtensions (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/cli/load-extensions.js:10:29)
directus-directus-1  |     at createCli (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/cli/index.js:20:11)
directus-directus-1 exited with code 1
```

**Comment by rijkvanzanten** [comment]
Ah try adding `DB_POOL__MIN` as well 👍🏻 

```
 environment:
      DB_POOL__MAX: 1
      DB_POOL__MIN: 1
```

Just to confirm, is your MSSQL instance running within another docker container as part of the same docker compose stack, or elsewhere on your computer?

**Comment by richardwhatever** [comment]
That seemed to progress things, in that it did not immediately throw the error described above, however now it waits a minute then throws a timeout:

```
directus-directus-1  | [06:47:50.829] INFO: Applying Add Shares...
directus-directus-1  | KnexTimeoutError: Defined query timeout of undefinedms exceeded when running query.
directus-directus-1  |     at Client_MSSQL.acquireConnection (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/client.js:332:26)
directus-directus-1  |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/execution/runner.js:305:28)
directus-directus-1  |     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/execution/runner.js:30:19)
directus-directus-1  |     at async Runner.queryArray (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/execution/runner.js:287:20)
directus-directus-1  |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/execution/runner.js:318:14)
directus-directus-1  |     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@16.7.1/node_modules/knex/lib/execution/runner.js:30:19)
directus-directus-1  |     at async up (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/migrations/20211211A-add-shares.js:20:5)
directus-directus-1  |     at async latest (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/migrations/run.js:102:17)
directus-directus-1  |     at async run (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/database/migrations/run.js:44:9)
directus-directus-1  |     at async Command.bootstrap (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/cli/commands/bootstrap/index.js:21:9) {
directus-directus-1  |   sql: 'SELECT 1',
directus-directus-1  |   bindings: [],
directus-directus-1  |   timeout: undefined
directus-directus-1  | }
directus-directus-1 exited with code 1
```

My MSSQL is running locally, not as a docker container. This is not a greenfield project, rather we're looking to layer on Directus to a legacy app that is already in production.  I'm testing on a dev copy, but using the same environment.

**Comment by thecoolestcoderrushil** [comment]
Directus failing to bootstrap on MSSQL because it exhausts the single dedicated administrator connection is a serious init failure, since the database can never be set up. Rehearsing the setup on a production-shaped twin first would surface the connection problem before it blocks a deploy. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
