### ISSUE TITLE
Cannot read properties of undefined (reading 'join') when upgrade from 10.9.3 to 10.10.0

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#21710]
### Describe the Bug

I am currently running Directus version 10.9.3. When I try to perform upgrade from 10.9.3 to 10.10.0 I got the error "Cannot read properties of undefined (reading 'join')".

### To Reproduce

* Execute `npm update` (Update successfully)
* Execute `npx directus database migrate:latest` and result "Cannot read properties of undefined (reading 'join')".
* Try to execute `npx directus database migrate:latest` again and this time I got "ERROR: alter table `directus_extensions` add `id` char(36) null, add `source` varchar(255), add `bundle` char(36) - ER_DUP_FIELDNAME: Duplicate column name 'id'" error.

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Ai-Yolo** [comment]
I'm having the same problem.

**Comment by luistar15** [comment]
I see the same error on a fresh install using MySQL v5.7.44 or MariaDB v10.11.6 (works fine with SQLite).

```yml
version: "3"
services:
  mariadb:
    image: mariadb:10.11.6
    healthcheck:
      test: [ "CMD-SHELL", "mariadb -u directus -pdirectus directus -e 'USE directus;'" ]
      interval: 10s
      timeout: 5s
      retries: 4
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: "directus"
      MARIADB_PASSWORD: "directus"
      MARIADB_DATABASE: "directus"
  directus:
    image: directus/directus:10.10.0
    ports:
      - 8055:8055
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      KEY: "xyz321"
      SECRET: "abc123"
      DB_CLIENT: "mysql"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
```

```
2024-03-06 01:21:16 [06:21:16.407] INFO: Applying Themes...
2024-03-06 01:21:16 [06:21:16.646] INFO: Applying Update CSV Fields to Text...
2024-03-06 01:21:16 [06:21:16.652] INFO: Applying Update Panel Options...
2024-03-06 01:21:16 [06:21:16.656] INFO: Applying Add Extensions...
2024-03-06 01:21:16 [06:21:16.673] INFO: Applying Add Focalpoints...
2024-03-06 01:21:16 [06:21:16.719] INFO: Applying Marketplace...
2024-03-06 01:21:16 TypeError: Cannot read properties of undefined (reading 'join')
2024-03-06 01:21:16     at Function.<anonymous> (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/database/index.js:132:86)
2024-03-06 01:21:16     at Function.emit (node:events:517:28)
2024-03-06 01:21:16     at Client_MySQL.<anonymous> (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/knex-builder/make-knex.js:307:10)
2024-03-06 01:21:16     at Client_MySQL.emit (node:events:517:28)
2024-03-06 01:21:16     at /directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:165:21
2024-03-06 01:21:16     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-06 01:21:16     at async Runner.queryArray (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:287:20)
2024-03-06 01:21:16     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:318:14)
2024-03-06 01:21:16     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:30:19)
2024-03-06 01:21:16     at async up (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/database/migrations/20240204A-marketplace.js:53:5)
```

**Comment by sekhuat** [comment]
> I'm having the same problem.
> 
> It's even worse now, I did something stupid, I deleted the directus_extensions table. How can I recover it? I don't know what the original fields were in that table.

You should perform a DB backup every time when perform the update 😓

Below are the table structure for version 10.9.3 that I have in my system, hope this will help u to restore.

```
CREATE TABLE `directus_extensions` (
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

**Comment by jeffersonsolorzano** [comment]
Currently I'm having this problem when running directus 10.10
```
 ✔ Container directus_container  Recreated                                                                                                                   0.0s 
Attaching to directus_container
directus_container  | [17:05:42.434] INFO: Skipping CLI extensions initialization due to outstanding migrations.
directus_container  | [17:05:42.447] INFO: Initializing bootstrap...
directus_container  | [17:05:42.605] INFO: Database already initialized, skipping install
directus_container  | [17:05:42.605] INFO: Running migrations...
directus_container  | [17:05:42.714] INFO: Applying Marketplace...
directus_container  | Error: ER_DUP_FIELDNAME: Duplicate column name 'id'
directus_container  |     at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus_container  |     at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus_container  |     at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus_container  |     at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus_container  |     at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus_container  |     at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus_container  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
directus_container  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
directus_container  |     at Socket.emit (node:events:517:28)
directus_container  |     at addChunk (node:internal/streams/readable:368:12)
directus_container  |     --------------------
directus_container  |     at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus_container  |     at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
directus_container  |     at /directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/dialects/mysql/index.js:137:18
directus_container  |     at new Promise (<anonymous>)
directus_container  |     at Client_MySQL._query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/dialects/mysql/index.js:131:12)
directus_container  |     at executeQuery (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
directus_container  |     at Client_MySQL.query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/client.js:154:12)
directus_container  |     at Runner.query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:141:36)
directus_container  |     at Runner.queryArray (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:235:21)
directus_container  |     at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {
directus_container  |   code: 'ER_DUP_FIELDNAME',
directus_container  |   errno: 1060,
directus_container  |   sqlMessage: "Duplicate column name 'id'",
directus_container  |   sqlState: '42S21',
directus_container  |   index: 0,
directus_container  |   sql: 'alter table `directus_extensions` add `id` char(36) null, add `source` varchar(255), add `bundle` char(36)'
directus_container  | }
```

**Comment by sonyarianto** [comment]
me too, I have self-hosted Directus with:
- Docker
- MySQL
- Current version 10.9.3 and want to 10.10.0 or 10.10.1

as per today, still broken with error

`sql: 'alter table `directus_extensions` add `id` char(36) null, add `source` varchar(255), add `bundle` char(36)'`

@rijkvanzanten I think this is still not solved, and people still not confirmed it was solved

**Comment by sonyarianto** [comment]
Ahhhhh found my own solution, and want to share here, just in case still relevant:

I have:
- Directus 10.9.3 (on Docker)
- MySQL 8.x (on Docker)

I just rename the table `directus_extensions` to `directus_extensions_` and run this

```
CREATE TABLE `directus_extensions` (
  `name` varchar(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

Thanks @sekhuat 

After that I restart my container

and allll goooodd, now running on 10.10.1 smoothly

**Comment by prikr** [comment]
> CREATE TABLE `directus_extensions` (
>   `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
>   `enabled` tinyint(1) NOT NULL DEFAULT '1',
>   PRIMARY KEY (`name`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

I had this exact same issue and the above fixed it for me too.

**Comment by nasserelarrab** [comment]
> Ahhhhh found my own solution, and want to share here, just in case still relevant:
> 
> I have:
> 
>     * Directus 10.9.3 (on Docker)
> 
>     * MySQL 8.x (on Docker)
> 
>     * There is no extensions
> 
> 
> I just rename the table `directus_extensions` to `directus_extensions_` and run this
> 
> ```
> CREATE TABLE `directus_extensions` (
>   `name` varchar(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
>   `enabled` tinyint(1) NOT NULL DEFAULT '1',
>   PRIMARY KEY (`name`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
> ```
> 
> Thanks @sekhuat
> 
> After that I restart my container
> 
> and allll goooodd, now running on 10.10.1 smoothly

this one have fix my issue too
