### ISSUE TITLE
Migration "Marketplace" causes an error when setting up a new project using Directus 10.10.4 with a MSSQL database

### ISSUE THREAD

**Issue by bvolz** [directus/directus#21828]
### Describe the Bug

When starting a new project bootstrapping fails when executing the latest migration.

Error shown in the Docker log for the Directus container:

```
Applying Marketplace...
2024-03-12T20:54:36.169775378Z AggregateError: ALTER TABLE [directus_extensions] DROP COLUMN [name] - 
2024-03-12T20:54:36.169794086Z     at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/handler.js:297:30)
2024-03-12T20:54:36.169795503Z     at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-03-12T20:54:36.169796878Z     at Readable.emit (node:events:517:28)
2024-03-12T20:54:36.169797878Z     at addChunk (node:internal/streams/readable:368:12)
2024-03-12T20:54:36.169798669Z     at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-12T20:54:36.169799419Z     at Readable.push (node:internal/streams/readable:278:10)
2024-03-12T20:54:36.169807169Z     at next (node:internal/streams/from:98:31)
2024-03-12T20:54:36.169808044Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-03-12T20:54:36.169808878Z   [errors]: [
2024-03-12T20:54:36.169809586Z     RequestError: The object 'directus_extensions_pkey' is dependent on column 'name'.
2024-03-12T20:54:36.169810419Z         at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/handler.js:287:21)
2024-03-12T20:54:36.169811461Z         at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-03-12T20:54:36.169812378Z         at Readable.emit (node:events:517:28)
2024-03-12T20:54:36.169813128Z         at addChunk (node:internal/streams/readable:368:12)
2024-03-12T20:54:36.169813878Z         at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-12T20:54:36.169814628Z         at Readable.push (node:internal/streams/readable:278:10)
2024-03-12T20:54:36.169815544Z         at next (node:internal/streams/from:98:31)
2024-03-12T20:54:36.169816294Z         at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-03-12T20:54:36.169817086Z       code: 'EREQUEST',
2024-03-12T20:54:36.169817836Z       number: 5074,
2024-03-12T20:54:36.169818669Z       state: 1,
2024-03-12T20:54:36.169819461Z       class: 16,
2024-03-12T20:54:36.169820253Z       serverName: 'directus-test-db',
2024-03-12T20:54:36.169821003Z       procName: '',
2024-03-12T20:54:36.169821711Z       lineNumber: 1
2024-03-12T20:54:36.169822336Z     },
2024-03-12T20:54:36.169823003Z     RequestError: ALTER TABLE DROP COLUMN name failed because one or more objects access this column.
2024-03-12T20:54:36.169823794Z         at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/handler.js:287:21)
2024-03-12T20:54:36.169824753Z         at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-03-12T20:54:36.169825669Z         at Readable.emit (node:events:517:28)
2024-03-12T20:54:36.169826919Z         at addChunk (node:internal/streams/readable:368:12)
2024-03-12T20:54:36.169827711Z         at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-12T20:54:36.169828419Z         at Readable.push (node:internal/streams/readable:278:10)
2024-03-12T20:54:36.169829169Z         at next (node:internal/streams/from:98:31)
2024-03-12T20:54:36.169830003Z         at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-03-12T20:54:36.169831086Z       code: 'EREQUEST',
2024-03-12T20:54:36.169832128Z       number: 4922,
2024-03-12T20:54:36.169833836Z       state: 9,
2024-03-12T20:54:36.169834544Z       class: 16,
2024-03-12T20:54:36.169835211Z       serverName: 'directus-test-db',
2024-03-12T20:54:36.169835878Z       procName: '',
2024-03-12T20:54:36.169836544Z       lineNumber: 1
2024-03-12T20:54:36.169837211Z     }
2024-03-12T20:54:36.169837878Z   ]
2024-03-12T20:54:36.169838544Z }
```

After manually removing the primary key from `directus_extensions`, the process slightly continues but won't finish.

The automated tests show exactly the same error for MSSQL and Directus v10.10.4 (https://github.com/directus/directus/actions/runs/8253251370/job/22574655449)

### To Reproduce

Set up a new project with Directus 10.10.4 using Docker and a MSSQL database.

### Directus Version

v10.10.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by alexvdvalk** [comment]
Confirmed this issue on a fresh install of 10.10.4

**Comment by gyasca** [comment]
I have this issue too

**Comment by jsalichos** [comment]
The error states:

ALTER TABLE [directus_extensions] ADD [id] uniqueidentifier null, [folder] nvarchar(255), [source] nvarchar(255), [bundle] uniqueidentifier - Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once.

For me the solution was to table directus_extensions and then create it again:

```
DROP TABLE [dbo].[directus_extensions]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[directus_extensions] (
    [name] NVARCHAR (255) NOT NULL
);
```
Then the migration can run smoothly!

**Comment by fawadtariq** [comment]
I can confirm the issue is still there when trying to create a new project using NPM CLI Installation.

- Created a fresh database
- I can see the tables in my database
- but the installation stops at the below error

`Something went wrong while seeding the database:
[Error] ALTER TABLE [directus_extensions] DROP COLUMN [name] -
Please try again`

- Installation fails and unable to proceed.
- Env Windows 11

**Comment by florianbepunkt** [comment]
Not sure, if this is related, but we are using directus in a docker env with Cockroach DB. Our CD pipeline crashed due to this migration error

```
stdout: [13:39:10.548] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[13:39:10.555] INFO: Initializing bootstrap...
[13:39:10.577] INFO: Database already initialized, skipping install
[13:39:10.577] INFO: Running migrations...
[13:39:10.592] INFO: Applying Marketplace...
, stderr: error: alter table "directus_extensions" add column "id" uuid null, add column "folder" varchar(255), add column "source" varchar(255), add column "bundle" uuid - column "id" of relation "directus_extensions" already exists
    at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 133,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'errors.go',
  line: '178',
  routine: 'NewColumnAlreadyExistsError'
}
```
