### ISSUE TITLE
Mail template not found

### ISSUE THREAD

**Issue by ymc-sise** [directus/directus#21851]
### Describe the Bug

When sending a mail from operation "Send Mail" and using a custom template, the template is not found anymore.

```
[14:22:13.060] ERROR: Could not send mail in "mail" operation
    err: {
      "type": "",
      "message": "Invalid payload. Template \"custom-template\" doesn't exist.",
      "stack":
          DirectusError: Invalid payload. Template "custom-template" doesn't exist.
              at MailService.renderTemplate (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/services/mail/index.js:65:19)
              at async MailService.send (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/services/mail/index.js:48:20)
      "name": "DirectusError",
      "extensions": {
        "reason": "Template \"custom-template\" doesn't exist"
      },
      "code": "INVALID_PAYLOAD",
      "status": 400
    }

```

The templates folder with custom-template.liquid and a base.liquid template exists in our docker container.

This worked some versions before, I think it was 10.9.3.

We use a self hosted directus instance.

### To Reproduce

1. Create custom template in templates folder
2. Create a flow with Send Mail operation
3. Use custom template
4. Trigger flow
5. Template is not found and no mail is sent

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ymc-sise** [comment]
https://docs.directus.io/releases/breaking-changes.html#moved-email-templates-out-of-extensions

Ok I have to set the new template path!
