### ISSUE TITLE
Deleting User  violates foreign key constraint "directus_files_uploaded_by_foreign"

### ISSUE THREAD

**Issue by garytube** [directus/directus#21924]
### Describe the Bug

I have a admin user (initial account) which i wanted to delete and re-create.
The Account does had a avatar once but I removed it. Now when i try to delete the account i get:

```bash
[14:21:08.680] ERROR: delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
    err: {
      "type": "DatabaseError",
      "message": "delete from \"directus_users\" where \"id\" in ($1) - update or delete on table \"directus_users\" violates foreign key constraint \"directus_files_uploaded_by_foreign\" on table \"directus_files\"",
      "stack":
          error: delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
              at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:517:28)
              at addChunk (node:internal/streams/readable:368:12)
              at readableAddChunk (node:internal/streams/readable:341:9)
              at Readable.push (node:internal/streams/readable:278:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 364,
      "name": "error",
      "severity": "ERROR",
      "code": "23503",
      "detail": "Key (id)=(ec95c57f-df0d-477c-bd22-720ab65eafb6) is still referenced from table \"directus_files\".",
      "schema": "public",
      "table": "directus_files",
      "constraint": "directus_files_uploaded_by_foreign",
      "file": "ri_triggers.c",
      "line": "2478",
      "routine": "ri_ReportViolation"
    }
```
<img width="597" alt="image" src="https://github.com/directus/directus/assets/3823504/771a7444-c667-49eb-b96a-ce468a43b3f1">

### To Reproduce

- upload an image to the first admi
- generate a new admin
- login as new admin
- delete first admin

### Directus Version

10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by joselcvarela** [comment]
We have customers that once in a while ask why removing a user is failing and the majority of the cases this issue is the culprit.
The workaround provided is to make user `suspended` and maybe change some fields to anonymize, but it's not a great experience.

Instead we should either:
- Archive user and anonymize it automatically
- Make fields `uploaded_by` and  `modified_by` on `directus_files` nullable.

**Comment by rijkvanzanten** [comment]
@joselcvarela That's tracked in https://github.com/directus/directus/issues/9507 🙂 Closing this in favor of that issue
