### ISSUE TITLE
SAML with keycloak not working

### ISSUE THREAD

**Issue by varnoatanil** [directus/directus#21940]
### Describe the Bug

Trying to use keycloak as saml oauth provider. After redirect to keycloak and SUCCESSFULL authorization get an error:
```
directus  | [15:43:14.473] WARN: [SAML] Unexpected error during SAML login
directus  |     err: {
directus  |       "type": "TypeError",
directus  |       "message": "Cannot read properties of undefined (reading 'toLowerCase')",
directus  |       "stack":
directus  |           TypeError: Cannot read properties of undefined (reading 'toLowerCase')
directus  |               at SAMLAuthDriver.fetchUserID (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:36:75)
directus  |               at SAMLAuthDriver.getUserID (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:44:35)
directus  |               at AuthenticationService.login (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/services/authentication.js:43:37)
directus  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus  |               at async file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/saml.js:114:60
directus  |     }
```

When use latest directus v10.10.4 get different error:
```
directus  | [15:47:56.790] DEBUG: Invalid payload. URL "http://localhost:8055/admin/login?continue=" can't be used to redirect after login.
directus  |     err: {
directus  |       "type": "",
directus  |       "message": "Invalid payload. URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login.",
directus  |       "stack":
directus  |           DirectusError: Invalid payload. URL "http://localhost:8055/admin/login?continue=" can't be used to redirect after login.
directus  |               at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/auth/drivers/saml.js:99:23
directus  |               at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/utils/async-handler.js:1:66
directus  |               at Layer.handle [as handle_request] (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/layer.js:95:5)
directus  |               at next (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/route.js:149:13)
directus  |               at Route.dispatch (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/route.js:119:3)
directus  |               at Layer.handle [as handle_request] (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/layer.js:95:5)
directus  |               at /directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:284:15
directus  |               at Function.process_params (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:346:12)
directus  |               at next (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:280:10)
directus  |               at Function.handle (/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:175:3)
directus  |       "name": "DirectusError",
directus  |       "extensions": {
directus  |         "reason": "URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login"
directus  |       },
directus  |       "code": "INVALID_PAYLOAD",
directus  |       "status": 400
directus  |     }
```

All settings are the same.

### To Reproduce

Setup keycloak as auth provider:
```
AUTH_PROVIDERS="keycloak"
AUTH_KEYCLOAK_DRIVER="saml"
AUTH_KEYCLOAK_IDP_metadata_FILE="/directus/config/idp.xml"
AUTH_KEYCLOAK_SP_metadata_FILE="/directus/config/sp.xml"
AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_KEYCLOAK_DEFAULT_ROLE_ID="***"
AUTH_KEYCLOAK_IDENTIFIER_KEY="email"
AUTH_KEYCLOAK_EMAIL_KEY="email"
AUTH_KEYCLOAK_ICON="Key"
AUTH_KEYCLOAK_LABEL="Keycloak"
```

sp.xml:
```
<EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="http://localhost:8080/realms/myrealm">
  <SPSSODescriptor WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService isDefault="true" index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8055/auth/login/keycloak/acs"/>
  </SPSSODescriptor>
</EntityDescriptor>
```

### Directus Version

v10.8.2 and v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by franco-viotti** [comment]
Same issue here but trying to connect Keycloak via OIDC.

I'm using Keycloak  25.0.1 and 11.1.0.

This is my OIDC config:

 - name: AUTH_PROVIDERS
    value: "keycloak"
  - name: AUTH_KEYCLOAK_DRIVER
    value: "openid"
  - name: AUTH_KEYCLOAK_MODE
    value: "session"
  - name: AUTH_KEYCLOAK_CLIENT_ID
    value: "directus"
  - name: AUTH_KEYCLOAK_CLIENT_SECRET
    value: "***"
  - name: AUTH_KEYCLOAK_ISSUER_URL
    value: "https://<my-instance>/realms/<my-realm>/.well-known/openid-configuration"
  - name: AUTH_KEYCLOAK_IDENTIFIER_KEY
    value: "email"
  - name: AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION
    value: "\"true\""
    
    
When I press the "Login with Keycloak" button, I'm redirected to this JSON:

    {"errors":[{"message":"Invalid payload. URL \"https://<my-directus-instance>/admin/login?continue=\" can't be used to redirect after login.","extensions":{"reason":"URL \"https://<my-directus-instance>/admin/login?continue=\" can't be used to redirect after login","code":"INVALID_PAYLOAD"}}]}

**Comment by zakeri-dev** [comment]
i have this problem too

**Comment by Blinxuu** [comment]
Was this ever fixed?

**Comment by Blinxuu** [comment]
I found a fix:

by setting the PUBLIC_URL in the env variable inside the docker-compose.yml:

(in my case):

`AUTH_PROVIDERS: "keycloak"`
 `AUTH_KEYCLOAK_DRIVER: "openid"`
 `AUTH_KEYCLOAK_CLIENT_ID: "directus"`
 `AUTH_KEYCLOAK_CLIENT_SECRET: <secret>"`
 `AUTH_KEYCLOAK_ISSUER_URL: "http://<keycloak>/realms/TestLDAP2/.well-known/openid-configuration"`
 `AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"`
 `AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"`
 `AUTH_KEYCLOAK_SCOPE: "openid profile email"`
 `AUTH_KEYCLOAK_DEFAULT_ROLE_ID: "<role>"`


`LOG_LEVEL: "debug"`

 `PUBLIC_URL: "<directus> (eg. 'http://directus.com')"`

the reason why it is not working is because whenever it tries to redirect to your IdP, it just appends it to your current url because the PUBLIC_URL is set on "/" by default. So by defining the PUBLIC_URL with your actual ip or url of your directus instance, it will be able to properly redirect it to your provider.

Note:

You also have to set the AUTH_<provider>_DEFAULT_ROLE_ID for account provisioning or else it will result to an error in Directus Login Page `Invalid foreign key`.
