### ISSUE TITLE
Installation of directus according to the documentation results in error caused by node-gyp (gyp issue)

### ISSUE THREAD

**Issue by Oleksii909** [directus/directus#22003]
### Page

https://docs.directus.io/getting-started/quickstart.html

### Describe the Inaccuracy

See the first issue report: [origin issue with description of the problem and workaround](https://github.com/directus/directus/issues/22001)

```
➜  directus-monospace npm init directus-project monospace
✖     Installing Directus
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rollup-plugin-styles@4.0.0
npm WARN Found: rollup@3.29.4
npm WARN node_modules/@directus/extensions-sdk/node_modules/rollup
npm WARN   rollup@"3.29.4" from @directus/extensions-sdk@11.0.1
npm WARN   node_modules/@directus/extensions-sdk
npm WARN     @directus/extensions-sdk@"11.0.1" from @directus/api@18.2.1
npm WARN     node_modules/@directus/api
npm WARN   1 more (rollup-plugin-esbuild)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm WARN node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm WARN   rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@11.0.1
npm WARN   node_modules/@directus/extensions-sdk
npm WARN 
npm WARN Conflicting peer dependency: rollup@2.79.1
npm WARN node_modules/rollup
npm WARN   peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm WARN   node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm WARN     rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@11.0.1
npm WARN     node_modules/@directus/extensions-sdk
npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code 1
npm ERR! path /Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/isolated-vm
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.20.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.20.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.2 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/isolated-vm/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/oleksiibondarenko/Library/Caches/node-gyp/18.20.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/oleksiibondarenko/Library/Caches/node-gyp/18.20.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/oleksiibondarenko/Library/Caches/node-gyp/18.20.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/isolated-vm',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Darwin 23.3.0
npm ERR! gyp ERR! command "/Users/oleksiibondarenko/.nvm/versions/node/v18.20.0/bin/node" "/Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/.bin/node-gyp" "rebuild" "--release" "-j" "max"
npm ERR! gyp ERR! cwd /Users/oleksiibondarenko/Projects/directus-monospace/monospace/node_modules/isolated-vm
npm ERR! gyp ERR! node -v v18.20.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
```

**Comment by paescuj** [comment]
For some reason an older version of `node-gyp` is used (v8 instead of v10). I assume this is the case because you're relying on `nvm`.
In order to continue, please either ensure the latest version of `node-gyp` is used or alternatively install the Python library `distutils`. See https://github.com/nodejs/node-gyp/issues/2869 for more information.

Such setup issues are the exact reason why we're recommending to use Docker over other installation methods, since  Docker removes environment-specific quirks.
