### ISSUE TITLE
INVALID_TOKEN

### ISSUE THREAD

**Issue by slavakurilyak** [directus/directus#22039]
### Describe the Bug

Running

```sh
bunx directus start
```

gives

```sh
[12:44:37.083] WARN: Spatialite isn't installed. Geometry type support will be limited.
[12:44:37.207] INFO: Server started at http://0.0.0.0:8055
[12:44:40] GET / 302 101ms
[12:44:40] GET /admin 304 4ms
[12:44:41] GET /extensions/sources/index.js 403 14ms
[12:44:42] POST /auth/refresh 403 28ms
[12:44:41.750] DEBUG: Invalid token.
    err: {
      "type": "",
      "message": "Invalid token.",
      "stack":
          DirectusError: Invalid token.
              at verifyJWT (file:///Users/slava/dev/test-bun/node_modules/@directus/api/dist/utils/jwt.js:15:19)
              at verifyAccessJWT (file:///Users/slava/dev/test-bun/node_modules/@directus/api/dist/utils/jwt.js:24:21)
              at getAccountabilityForToken (file:///Users/slava/dev/test-bun/node_modules/@directus/api/dist/utils/get-accountability-for-token.js:18:29)
              at handler (file:///Users/slava/dev/test-bun/node_modules/@directus/api/dist/middleware/authenticate.js:36:32)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "name": "DirectusError",
      "code": "INVALID_TOKEN",
      "status": 403
    }
[12:44:42] GET /server/info 403 10ms
[12:44:42] GET /auth 403 3ms
```

### To Reproduce

```
bun create directus-project@latest test-bun
cd test-bun
bunx directus start
```

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Directus does not explicitly support Bun, make sure to use nodejs v18.
![image](https://github.com/directus/directus/assets/9389634/75de8a28-1679-4ac9-aca6-8246ba3c1218)

https://docs.directus.io/self-hosted/cli.html#command-line-interface

**Comment by br41nslug** [comment]
Having said that, that error is likely just the browser trying to refresh the session while you're not yet logged in. That should not be an issue by itself.

**Comment by slavakurilyak** [comment]
@br41nslug wen Bun?

**Comment by br41nslug** [comment]
At some point when Bun is stable, production ready and feature complete with nodejs (or at least the things we depend on)

**Comment by slavakurilyak** [comment]
> Bun is stable and production-ready

[Bun 1.0](https://bun.sh/blog/bun-v1.0) become stable last year

**Comment by br41nslug** [comment]
They definitely claimed that indeed, but last time i checked it out (after that release) it was not stable enough to run large scale projects in production. Their speed comes at trade-offs for stability.
