### ISSUE TITLE
Restarting 10.10.5 after migration fails to start

### ISSUE THREAD

**Issue by cdemi** [directus/directus#22161]
### Describe the Bug

Upgrading to 10.10.5 went smoothly. All migrations executed and database upgraded.

After some time, the container needed to be restarted and it doesn't start on 10.10.5. Downgrading to 10.10.4 it starts again.

I suspect it's related to #21824

The error log:

```
file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:21
        throw new Error(`Failed to get Schema information: hit infinite loop`);
              ^

Error: Failed to get Schema information: hit infinite loop
    at getSchema (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:21:15)
    at callback (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:46:38)
    at Timeout.<anonymous> (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:53:17)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.20.0
```

### To Reproduce

Upgrade to 10.10.5 and restart the container afterwards.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Can you provide more information on the specific situation cause the issue you're describing? The issue sounds like it is likely to be a database issue.

> Upgrade to 10.10.5 and restart the container afterwards.

I am unable to reproduce the issue using these steps.

**Comment by cdemi** [comment]
Database is Postgres 15 and using Redis 6 as cache. I don't suspect a database issue because v10.10.4 starts and works normally.

**Comment by br41nslug** [comment]
Do you have a "healthcheck" in your postgres/directus docker-compose? to make sure Directus only starts after the database is ready for connections, if not then i expect this recursive check to kick in while the database docker is still starting up.

https://github.com/directus/directus/issues/20542#issuecomment-1981591509

**Comment by cdemi** [comment]
I do have a health check but the container is terminating itself with an exit code.

I also have a startup probe health check for 5 minutes:
```
        startupProbe:
          httpGet:
            path: /server/health
            port: 8055
          failureThreshold: 30
          periodSeconds: 10
```

This is the full trace log:

```
[14:17:09.368] TRACE: [2.945ms] 
		 SELECT
			rel.relname AS name
		 FROM
			pg_class rel
		 WHERE
			rel.relnamespace IN ('public'::regnamespace)
			AND rel.relkind = 'r'
			AND rel.relname = $1
		 ORDER BY rel.relname
	   [directus_collections]
[14:17:09.373] TRACE: [2.135ms] select "version" from "directus_migrations" []
[14:17:09.384] TRACE: Schema cache is prepared in another process, waiting for result.
[14:17:19.385] TRACE: Did not receive schema callback message in time. Pulling schema...
[14:17:19.386] TRACE: Schema cache is prepared in another process, waiting for result.
[14:17:29.387] TRACE: Did not receive schema callback message in time. Pulling schema...
[14:17:29.388] TRACE: Schema cache is prepared in another process, waiting for result.
[14:17:39.388] TRACE: Did not receive schema callback message in time. Pulling schema...
file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:21
        throw new Error(`Failed to get Schema information: hit infinite loop`);
              ^

Error: Failed to get Schema information: hit infinite loop
    at getSchema (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:21:15)
    at callback (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:46:38)
    at Timeout.<anonymous> (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/@directus/api/dist/utils/get-schema.js:53:17)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.20.0
```

**Comment by br41nslug** [comment]
That looks like a directus healthcheck not the postgres healthcheck i was suggesting.

**Comment by cdemi** [comment]
You are right it is a directus healthcheck, however I can see that the database is online and even the tracing logs I pasted above show that it's online and queryable by directus so it's not a database issue. It's related to a change in #21824 where for some reason it's thinking that another process is building the schema cache

**Comment by cdemi** [comment]
I figured out the issue. For some reason in Redis the key `directus:lock:schemaCache--preparing` was not deleted after the first run:
![image](https://github.com/directus/directus/assets/8025435/c1d48cc9-c5da-49eb-97ca-da711e42dcda)

This means that all new starting containers won't ever start because they think someone else is updating the schema

**Comment by br41nslug** [comment]
> For some reason in Redis the key directus:lock:schemaCache--preparing was not deleted after the first run

If the instance crashed that first run that is to be expected, generally a good idea to also restart redis clearing it's storage when restarting Directus.

**Comment by NilsBaumgartner1994** [comment]
Facing the same issue
