### ISSUE TITLE
Error at first login after install

### ISSUE THREAD

**Issue by costa974** [directus/directus#2228]
windows 10 x64
xampp
php 7.1
mariadb 10.3.10

[2018-11-01 03:45:35] api[_].ERROR: TypeError: Argument 1 passed to Directus\Util\DateTimeUtils::createFromDateTime() must be an instance of DateTime, boolean given, called in C:\xampp\htdocs\directus.test\src\core\Directus\Util\DateTimeUtils.php on line 123 and defined in C:\xampp\htdocs\directus.test\src\core\Directus\Util\DateTimeUtils.php:96
Stack trace:
#0 C:\xampp\htdocs\directus.test\src\core\Directus\Util\DateTimeUtils.php(123): Directus\Util\DateTimeUtils::createFromDateTime(false)
#1 C:\xampp\htdocs\directus.test\src\core\Directus\Util\DateTimeUtils.php(109): Directus\Util\DateTimeUtils::createDateFromFormat('Y-m-d H:i:s', 'NULL', 'UTC')
#2 C:\xampp\htdocs\directus.test\src\core\Directus\Database\Schema\SchemaManager.php(568): Directus\Util\DateTimeUtils::createFromDefaultFormat('NULL', 'UTC')
#3 C:\xampp\htdocs\directus.test\src\core\Directus\Database\Schema\SchemaManager.php(268): Directus\Database\Schema\SchemaManager->createFieldFromArray(Array)
#4 C:\xampp\htdocs\directus.test\src\core\Directus\Database\TableGateway\BaseTableGateway.php(998): Directus\Database\Schema\SchemaManager->getFields('directus_activi...')
#5 C:\xampp\htdocs\directus.test\src\core\Directus\Database\TableGateway\BaseTableGateway.php(279): Directus\Database\TableGateway\BaseTableGateway->parseRecordValuesByType(Array)
#6 C:\xampp\htdocs\directus.test\src\core\Directus\Database\TableGateway\BaseTableGateway.php(817): Directus\Database\TableGateway\BaseTableGateway->find('2')
#7 C:\xampp\htdocs\directus.test\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(276): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#8 C:\xampp\htdocs\directus.test\src\core\Directus\Database\TableGateway\DirectusActivityTableGateway.php(66): Zend\Db\TableGateway\AbstractTableGateway->insertWith(Object(Zend\Db\Sql\Insert))
#9 C:\xampp\htdocs\directus.test\src\core\Directus\Services\AuthService.php(56): Directus\Database\TableGateway\DirectusActivityTableGateway->recordLogin('1')
#10 C:\xampp\htdocs\directus.test\src\endpoints\Auth.php(49): Directus\Services\AuthService->loginWithCredentials('admin@admin.com', 'xxxxxxxxxxxxx!')
#11 [internal function]: Directus\Api\Routes\Auth->authenticate(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#12 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#13 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#14 C:\xampp\htdocs\directus.test\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#15 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#16 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#17 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#18 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#19 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#20 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#21 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#22 C:\xampp\htdocs\directus.test\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#23 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#24 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#25 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#26 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#27 C:\xampp\htdocs\directus.test\vendor\akrabat\rka-ip-address-middleware\src\IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#28 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#29 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#30 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#31 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#32 C:\xampp\htdocs\directus.test\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#33 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#34 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#35 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#36 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#37 C:\xampp\htdocs\directus.test\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#38 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#39 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#40 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#41 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#42 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#43 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#44 C:\xampp\htdocs\directus.test\vendor\slim\slim\Slim\App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#45 C:\xampp\htdocs\directus.test\src\core\Directus\Application\Application.php(161): Slim\App->run(false)
#46 C:\xampp\htdocs\directus.test\public\index.php(5): Directus\Application\Application->run()
#47 {main} [] []

**Comment by costa974** [comment]
I have also noticed that the password is written in the log.

#10 C:\xampp\htdocs\directus.test\src\endpoints\Auth.php(49): Directus\Services\AuthService->loginWithCredentials('admin@admin.com', 'xxxxxxxxxxxxx!')
