### ISSUE TITLE
Redis/Memcache cache is not implemented?

### ISSUE THREAD

**Issue by fikriauliya** [directus/directus#2233]
I encountered this error when setting Redis as the cache store:

```

Fatal error: Uncaught Error: Class 'Redis' not found in /var/www/html/src/core/Directus/Application/CoreServicesProvider.php:880 Stack trace: #0 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}(Object(Directus\Application\Container)) #1 /var/www/html/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet('cache') #2 /var/www/html/src/core/Directus/Application/CoreServicesProvider.php(164): Directus\Container\Container->get('cache') #3 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}(Object(Directus\Application\Container)) #4 /var/www/html/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet('hook_emitter') #5 /var/www/html/src/helpers/all.php(413): Directus\Container\Container->get('hook_emitter') #6 /var/www/html/src/helpers/all.php(397): Directus\register_hooks(Object(Directus\Application\Application in /var/www/html/src/core/Directus/Application/CoreServicesProvider.php on line 880
```

Upon checking the file, it seems Redis and Memcached caching is not available/imported correctly?

**Comment by WellingGuzman** [comment]
I added a note in the documentation: https://github.com/directus/docs/commit/27817b830433b793ee265bbbdeb5fb4692b68a14.

Also make sure to install and run the redis server.
