### ISSUE TITLE
10.11.1 breaks our SSO

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#22584]
### Describe the Bug

After upgrading to 10.11.1 our Azure SSO doesn't work anymore. Reverting back to 10.11.0 makes it work again.

Logs tell me the SSO part tries to query column `next_token` from `directus_sessions` which doesn't seem to exist?

The error in the logs of 10.11.1:
```
select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5 - column s.next_token does not exist
```
Any thoughts?

### To Reproduce

hard. Setup SSO on Azure is a workload :) but if you have to happen a working environment that has Azure SSO in it, you can reproduce it by upgrading to 10.11.1 to see the error and downgrade to 10.11.0 to fix it again

### Directus Version

v10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PG15

**Comment by paescuj** [comment]
Did you run the migration [^1] when updating to 10.11.1?

[^1]: https://docs.directus.io/self-hosted/upgrades-migrations.html#upgrading-updating-a-project

**Comment by keesvanbemmel** [comment]
Yes I did, happens through our CICD pipeline. This is the migration that got logged:
![CleanShot 2024-05-27 at 11 48 34](https://github.com/directus/directus/assets/4633876/30f41b78-c066-4c76-8890-45c650b09646)

**Comment by keesvanbemmel** [comment]
So yeah, issue is resurfacing and I think I know where the problem lies:

After migrations we apply our own schema. When applying this schema the schema diff tells us that it will remove next_token from directus_sessions. 

Now I know in the past, that these directus fields should be excluded from the diff alltogether? So definitely seems like a bug

**Comment by paescuj** [comment]
Good catch! Thanks @keesvanbemmel!

**Comment by ricricucit** [comment]
Just updated to `10.11.2`, and confirm the resurfacing. Getting this while trying to log in:


```
database-1  | 2024-05-31 15:08:54.780 UTC [62] ERROR:  column s.next_token does not exist at character 44
database-1  | 2024-05-31 15:08:54.780 UTC [62] STATEMENT:  select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5
directus-1  | [15:08:54] POST /auth/refresh 500 115ms
directus-1  | [15:08:54.782] ERROR: select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5 - column s.next_token does not exist
directus-1  |     err: {
directus-1  |       "type": "DatabaseError",
directus-1  |       "message": "select \"s\".\"expires\" as \"session_expires\", \"s\".\"next_token\" as \"session_next_token\", \"u\".\"id\" as \"user_id\", \"u\".\"first_name\" as \"user_first_name\", \"u\".\"last_name\" as \"user_last_name\", \"u\".\"email\" as \"user_email\", \"u\".\"password\" as \"user_password\", \"u\".\"status\" as \"user_status\", \"u\".\"provider\" as \"user_provider\", \"u\".\"external_identifier\" as \"user_external_identifier\", \"u\".\"auth_data\" as \"user_auth_data\", \"r\".\"id\" as \"role_id\", \"r\".\"admin_access\" as \"role_admin_access\", \"r\".\"app_access\" as \"role_app_access\", \"d\".\"id\" as \"share_id\", \"d\".\"item\" as \"share_item\", \"d\".\"role\" as \"share_role\", \"d\".\"collection\" as \"share_collection\", \"d\".\"date_start\" as \"share_start\", \"d\".\"date_end\" as \"share_end\", \"d\".\"times_used\" as \"share_times_used\", \"d\".\"max_uses\" as \"share_max_uses\" from \"directus_sessions\" as \"s\" left join \"directus_users\" as \"u\" on \"s\".\"user\" = \"u\".\"id\" left join \"directus_shares\" as \"d\" on \"s\".\"share\" = \"d\".\"id\" left join \"directus_roles\" as \"r\" on \"r\".\"id\" in (\"u\".\"role\", \"d\".\"role\") where \"s\".\"token\" = $1 and \"s\".\"expires\" >= $2 and (\"d\".\"date_end\" is null or \"d\".\"date_end\" >= $3) and (\"d\".\"date_start\" is null or \"d\".\"date_start\" <= $4) limit $5 - column s.next_token does not exist",
directus-1  |       "stack":
directus-1  |           error: select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5 - column s.next_token does not exist
directus-1  |               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
directus-1  |               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
directus-1  |               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
directus-1  |               at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
directus-1  |               at Socket.emit (node:events:517:28)
directus-1  |               at addChunk (node:internal/streams/readable:368:12)
directus-1  |               at readableAddChunk (node:internal/streams/readable:341:9)
directus-1  |               at Readable.push (node:internal/streams/readable:278:10)
directus-1  |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus-1  |       "length": 110,
directus-1  |       "name": "error",
directus-1  |       "severity": "ERROR",
directus-1  |       "code": "42703",
directus-1  |       "position": "44",
directus-1  |       "file": "parse_relation.c",
directus-1  |       "line": "3713",
directus-1  |       "routine": "errorMissingColumn"
directus-1  |     }
```

**Comment by keesvanbemmel** [comment]
The fix has not been released yet, so that seems right

**Comment by ricricucit** [comment]
(reverting to `10.11.0` works fine and I do understand that this is going to be included only from next release, onward 🙂 thanks everyone)

**Comment by j0weiss** [comment]
We are having the same issue when upgrading from 10.11.0 to 10.13.0. The Migration is present in the `directus_migrations` table but the column `next_token` is missing. I don't understand why this migration is not running? The Migration "Add Tus Data" ran successfully.

**Comment by ricricucit** [comment]
@j0weiss are there specific upgrading steps you'd recommend? (we're currently on `10.11.0`)

**Comment by keesvanbemmel** [comment]
Should be fine now if you upgrade to latest version. Issue was solved.

If you still encounter this problem do what @j0weiss said: remove the Add Session Window from the directus_migration table and restart Directus.
