### ISSUE TITLE
Error on instaling the extension using S3 storage

### ISSUE THREAD

**Issue by mpinzariu** [directus/directus#22615]
### Describe the Bug

ex of error for extension iconify: 
```
[10:57:15.635] WARN: Couldn't register bundle "directus-extension-iconify"
[10:57:15.635] WARN: Cannot find module '/directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js' imported from /directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_crtpmuhomzjtudzfxjp6matirq/node_modules/@directus/api/dist/utils/import-file-url.js
    err: {
      "type": "Error",
      "message": "Cannot find module '/directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js' imported from /directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_crtpmuhomzjtudzfxjp6matirq/node_modules/@directus/api/dist/utils/import-file-url.js",
      "stack":
          Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js' imported from /directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_crtpmuhomzjtudzfxjp6matirq/node_modules/@directus/api/dist/utils/import-file-url.js
              at new NodeError (node:internal/errors:405:5)
              at finalizeResolution (node:internal/modules/esm/resolve:327:11)
              at moduleResolve (node:internal/modules/esm/resolve:980:10)
              at defaultResolve (node:internal/modules/esm/resolve:1193:11)
              at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
              at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
              at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
              at ModuleLoader.import (node:internal/modules/esm/loader:336:34)
              at importModuleDynamically (node:internal/modules/esm/translators:143:35)
              at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
      "url": "file:///directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js?t=1717066635634",
      "code": "ERR_MODULE_NOT_FOUND"
    }

[10:57:15.653] WARN: Couldn't bundle App extensions
[10:57:15.653] WARN: Could not resolve "./extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/app.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/app.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/app.js" from "virtual:entry"
              at getRollupError (file:///directus/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
              at error (file:///directus/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
              at ModuleLoader.handleInvalidResolvedId (file:///directus/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19106:24)
              at file:///directus/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19066:26
      "code": "UNRESOLVED_IMPORT",
      "exporter": "./extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/app.js",
      "id": "\u0000virtual:entry"
    }
[10:57:15.655] INFO: Extensions reloaded
```

### To Reproduce

1. Instaling Directur using docker-compose
2. Adding S3 Minio storage (the files are uploaded correctly on storage)
3. Instaling\reinstaling extension from directus marketplace
4. The extension does not install but is enabled on the extensions page

![Screenshot 2024-05-30 at 14 09 21](https://github.com/directus/directus/assets/37148227/e8179c76-8172-43da-a9ec-4a9ab5a4cdfd)

### Directus Version

v10.11.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

**Comment by br41nslug** [comment]
Is your local `./extensions/.registry` folder writeable?

**Comment by mpinzariu** [comment]
> Is your local `./extensions/.registry` folder writeable?

Yes

![image](https://github.com/directus/directus/assets/37148227/c294ab44-640e-4c29-80d5-9e2dcb539d2c)

**Comment by br41nslug** [comment]
Does the file exist it is trying to import? https://www.npmjs.com/package/directus-extension-iconify?activeTab=code Looks like that specific extension did not ship their `dist/` folder. For the future please check the extension you've just installed first 😄

**Comment by mpinzariu** [comment]
> Does the file exist it is trying to import? https://www.npmjs.com/package/directus-extension-iconify?activeTab=code Looks like that specific extension did not ship their `dist/` folder. For the future please check the extension you've just installed first 😄

the files exist 
![image](https://github.com/directus/directus/assets/37148227/fcf7776d-3a52-424a-b3a5-874c31f033f7)

**Comment by br41nslug** [comment]
The `dist/` folder (the actual extension) is not there, only the `src/` folder
```
/directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js'
```

**Comment by mpinzariu** [comment]
> The `dist/` folder (the actual built version of the extension) is not there, only the `src/` folder
> 
> ```
> Cannot find module '/directus/extensions/.registry/f4894687-a96c-4391-b47f-1589b4d3f25e/dist/api.js'
> ```

correct it seems that during the installation of the extension, the folder dist is not created, so how can I solve this?

**Comment by br41nslug** [comment]
That is not something that happens "during installation", you can either download and build the extension locally or find the author's github repo and ask him to update the extension.
