### ISSUE TITLE
Missing CSS files for WYSIWYG editors so they don't work

### ISSUE THREAD

**Issue by truecastdesign** [directus/directus#2265]
# Bug Report

## Steps to Reproduce

1. Go to '/admin/#/collections/pages' 
Console errors for missing css files:
GET http://www.directus.test/extensions/core/layouts/tabular/layout.css net::ERR_ABORTED 404 (Not Found)
GET http://www.directus.test/extensions/core/interfaces/text-input/display.css net::ERR_ABORTED 404 (Not Found)
GET http://www.directus.test/extensions/core/interfaces/wysiwyg/display.css net::ERR_ABORTED 404 (Not Found)

2. Go to '/admin/#/collections/pages/1'
3. Look at WYSIWYG editors on page. Both basic and advanced. The tool bars are missing.
Console errors:

DOMException: Failed to execute 'querySelector' on 'Document': '[
    [
        "bold",
        "italic",
        "underline",
        "strike"
    ],
    [
        "blockquote",
        "code-block"
    ],
    [
        {
            "header": 1
        },
        {
            "header": 2
        }
    ],
    [
        {
            "list": "ordered"
        },
        {
            "list": "bullet"
        }
    ],
    [
        {
            "script": "sub"
        },
        {
            "script": "super"
        }
    ],
    [
        {
            "indent": "-1"
        },
        {
            "indent": "+1"
        }
    ],
    [
        {
            "header": [
                1,
                2,
                3,
                4,
                5,
                6,
                false
            ]
        }
    ],
    [
        {
            "color": []
        },
        {
            "background": []
        }
    ],
    [
        {
            "align": []
        }
    ],
    [
        "clean"
    ]
]' is not a valid selector.
    at new e (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:155065)
    at e.value (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:106329)
    at e.value (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:118866)
    at http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:106204
    at Array.forEach (<anonymous>)
    at e.value (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:106162)
    at new t (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:14:17101)
    at o.init (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:20:526)
    at o.mounted (http://www.directus.test/extensions/core/interfaces/wysiwyg-full/input.js:20:356)
    at Gt (http://www.directus.test/admin/js/chunk-vendors.758fb20b.js:25:19880)

## Expected Behavior

To see tool bars above both editors.

## Actual Behavior

Just plain textareas with no tools bars.

## Other Context & Screenshots

https://snag.gy/OQJFbS.jpg

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.1
- Web Server: Apache 2.4.37
- PHP Version:7.2.0
- Database: MySQL 8.0.12
- Install Method: cloned `master` branch

**Comment by benhaynes** [comment]
For the wsyiwyg editor (not the advanced one) did you try entering text and selecting it? That interface only shows buttons for highlighted text.
