### ISSUE TITLE
Accessing item with share URL throws SQL error

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#22693]
### Describe the Bug

When trying to access a shared item with its URL `verifySessionJWT` is called with unexpected parameters causing a SQL error along the lines of 

```
Undefined binding(s) detected when compiling FIRST. Undefined column(s): [user] query: select 1 from `directus_sessions` where `token` = ? and `user` = ? and `expires` >= ? limit ?
```

### To Reproduce

- Create a share
- Copy URL
- Open URL in private window

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by cosigyn** [comment]
Experiencing this in v10.12.1

**Comment by alexanderstoll-ibm** [comment]
Experiencing this in v10.11.0, self hosted using docker and SQLite.

```
[06:41:34.938] ERROR: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [user] query: select 1 from `directus_sessions` where `token` = ? and `user` = ? and `expires` >= ? limit ?
err: {
"type": "Error",
"message": "Undefined binding(s) detected when compiling FIRST. Undefined column(s): [user] query: select 1 from `directus_sessions` where `token` = ? and `user` = ? and `expires` >= ? limit ?",
"stack":
Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [user] query: select 1 from `directus_sessions` where `token` = ? and `user` = ? and `expires` >= ? limit ?
at QueryCompiler_SQLite3.toSQL (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.11.5/node_modules/knex/lib/query/querycompiler.js:112:13)
at QueryBuilder_SQLite3.toSQL (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.11.5/node_modules/knex/lib/query/querybuilder.js:84:44)
at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.11.5/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.11.5/node_modules/knex/lib/execution/runner.js:318:20)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.11.5/node_modules/knex/lib/execution/runner.js:30:19)
at async verifySessionJWT (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/utils/verify-session-jwt.js:10:21)
at async getAccountabilityForToken (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/utils/get-accountability-for-token.js:20:17)
at async handler (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/middleware/authenticate.js:36:26)
}
```

**Comment by ikovac** [comment]
I am working on this and will raise a pull request soon.
