### ISSUE TITLE
Deployment Error on Azure

### ISSUE THREAD

**Issue by Mikoyzskie** [directus/directus#22745]
### Describe the Bug

Logs on Azure

```2024-06-13T05:32:12.888762324Z RequestError: ALTER TABLE [directus_extensions] ADD [id] uniqueidentifier null, [folder] nvarchar(255), [source] nvarchar(255), [bundle] uniqueidentifier - Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once.
2024-06-13T05:32:12.888824025Z at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/handler.js:286:21)
2024-06-13T05:32:12.888831325Z at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-06-13T05:32:12.888837425Z at Readable.emit (node:events:517:28)
2024-06-13T05:32:12.888841525Z at addChunk (node:internal/streams/readable:368:12)
2024-06-13T05:32:12.888845625Z at readableAddChunk (node:internal/streams/readable:341:9)
2024-06-13T05:32:12.888849725Z at Readable.push (node:internal/streams/readable:278:10)
2024-06-13T05:32:12.888881425Z at next (node:internal/streams/from:98:31)
2024-06-13T05:32:12.888886325Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-06-13T05:32:12.888890326Z code: 'EREQUEST',
2024-06-13T05:32:12.888894226Z number: 2705,
2024-06-13T05:32:12.888898026Z state: 4,
2024-06-13T05:32:12.888901826Z class: 16,
2024-06-13T05:32:12.888905526Z serverName: 'servername',
2024-06-13T05:32:12.888909426Z procName: '',
2024-06-13T05:32:12.888913226Z lineNumber: 1
2024-06-13T05:32:12.888917026Z }
2024-06-13T05:32:12.967985705Z [05:32:12.724] INFO: Skipping CLI extensions initialization due to outstanding migrations.
2024-06-13T05:32:12.968990113Z [05:32:12.752] INFO: Initializing bootstrap...
2024-06-13T05:32:12.975221167Z [05:32:12.782] INFO: Database already initialized, skipping install
2024-06-13T05:32:12.975839072Z [05:32:12.782] INFO: Running migrations...
2024-06-13T05:32:12.976547078Z [05:32:12.841] INFO: Applying Marketplace...
2024-06-13T05:32:27.907142341Z RequestError: ALTER TABLE [directus_extensions] ADD [id] uniqueidentifier null, [folder] nvarchar(255), [source] nvarchar(255), [bundle] uniqueidentifier - Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once.
2024-06-13T05:32:27.907233042Z at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/handler.js:286:21)
2024-06-13T05:32:27.907259142Z at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-06-13T05:32:27.907264842Z at Readable.emit (node:events:517:28)
2024-06-13T05:32:27.907268542Z at addChunk (node:internal/streams/readable:368:12)
2024-06-13T05:32:27.907272142Z at readableAddChunk (node:internal/streams/readable:341:9)
2024-06-13T05:32:27.907275943Z at Readable.push (node:internal/streams/readable:278:10)
2024-06-13T05:32:27.907280043Z at next (node:internal/streams/from:98:31)
2024-06-13T05:32:27.907283843Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-06-13T05:32:27.907287443Z code: 'EREQUEST',
2024-06-13T05:32:27.907290943Z number: 2705,
2024-06-13T05:32:27.907294443Z state: 4,
2024-06-13T05:32:27.907297843Z class: 16,
2024-06-13T05:32:27.907301243Z serverName: 'zanda',
2024-06-13T05:32:27.907304743Z procName: '',
2024-06-13T05:32:27.907308343Z lineNumber: 1
2024-06-13T05:32:27.907311743Z }
2024-06-13T05:32:28.073267872Z [05:32:27.786] INFO: Skipping CLI extensions initialization due to outstanding migrations.
2024-06-13T05:32:28.074945087Z [05:32:27.806] INFO: Initializing bootstrap...
2024-06-13T05:32:28.075191089Z [05:32:27.828] INFO: Database already initialized, skipping install
2024-06-13T05:32:28.076011796Z [05:32:27.828] INFO: Running migrations...
2024-06-13T05:32:28.076497000Z [05:32:27.858] INFO: Applying Marketplace...

2024-06-13T05:32:29.163Z INFO - Stopping site cms because it failed during startup.```

### To Reproduce

Set up a new project with Directus 10.12 using Docker and a MSSQL database.

### Directus Version

10.12

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MSSQL

**Comment by hanneskuettner** [comment]
Are you running this on a clean database? Judging from the partial logs it looks like some bootstrapping has already happened (`[05:32:12.782] INFO: Database already initialized, skipping install`) (and may have been cancelled while bootstrapping?) and might have left the database in an unwanted state. 

Do you have the option to set up the project with a clean database again?

**Comment by Mikoyzskie** [comment]
I can't actually since this instance is already the working setup for our apps

**Comment by hanneskuettner** [comment]
So does this problem occur only after updating Directus?

**Comment by Mikoyzskie** [comment]
I can't push through the update because of the error so i have to go back to version 10.8. since this is the only version that works for me

**Comment by hanneskuettner** [comment]
Okay, so the problem actually is updating from 10.8 -> 10.12, am I understanding that correctly? Mind updating the initial bug report title, description and reproduction steps to reflect that?

**Comment by Mikoyzskie** [comment]
Yes, thats correct. I'll be updating it now

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the information provided. If possible, mind sharing a database dump of a reproduction where this issue happens? Thanks!

Until then, I'll close this for now as I can't reproduce the issue.
