### ISSUE TITLE
GraphQL "users" only works with excessive permissions

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#22897]
### Describe the Bug

When trying to access users via /grapqhl/system the following error is thrown unless excessive permissions for the caller are configured:

```
directus-1  | [11:24:32.659] ERROR: Cannot read properties of undefined (reading 'List')
directus-1  |     err: {
directus-1  |       "type": "TypeError",
directus-1  |       "message": "Cannot read properties of undefined (reading 'List')",
directus-1  |       "stack":
directus-1  |           TypeError: Cannot read properties of undefined (reading 'List')
directus-1  |               at GraphQLService.injectSystemResolvers (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_oxnsowrs7rdaq4kqnoch3wflwa/node_modules/@directus/api/dist/services/graphql/index.js:2699:65)
directus-1  |               at GraphQLService.getSchema (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_oxnsowrs7rdaq4kqnoch3wflwa/node_modules/@directus/api/dist/services/graphql/index.js:195:18)
directus-1  |               at async GraphQLService.execute (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_oxnsowrs7rdaq4kqnoch3wflwa/node_modules/@directus/api/dist/services/graphql/index.js:89:24)
directus-1  |               at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_oxnsowrs7rdaq4kqnoch3wflwa/node_modules/@directus/api/dist/controllers/graphql.js:13:29
directus-1  |     }
directus-1  | [11:24:32] POST /graphql/system 500 50ms
```

### To Reproduce

Execute the following GraphQL query against /graphql/system, authenticated as a user with the following permissions:
```
{
  users {
    id
  }
}
```

<img width="822" alt="image" src="https://github.com/directus/directus/assets/6235675/7e41f0de-4cb5-4057-aaec-a6e59c85a08c">
Observe the described error is being thrown.

Now change the permissions to the following:
<img width="817" alt="image" src="https://github.com/directus/directus/assets/6235675/744f2a4e-992c-4c05-b6b8-7a64184216dd">

Observe that no error is being thrown anymore. Removing any of the unrelated permissions causes the error to come back.

### Directus Version

11.0.0-rc.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Fixed in https://github.com/directus/directus/pull/22916
