### ISSUE TITLE
O2M fails on attaching existing element on item creation

### ISSUE THREAD

**Issue by vwasteels** [directus/directus#23029]
### Describe the Bug

I have a collection ```companies```. 

It has an O2M relation with ```directus_users``` : ```companies.owners```

(On the ```directus_users``` side, there is a ```directus_users.company``` related field.)

When I try to attach an existing user to a company while creating it, I get a Forbidden error

this is the payload for the ```POST /items/companies```
```json
{
    "name": "My company name",
    "owners": [
        "{{CLIENT_UUID}}"
    ]
}
```

By looking at the trace log, I can see it is trying to fetch all fields from the ```directus_users``` collection at the ```validatePayload``` function : 
```
POST /items/companies 403 139ms
TRACE: [69.214ms] select "directus_users"."id", "directus_users"."role", "directus_roles"."admin_access", "directus_roles"."app_access" from "directus_users" left join "directus_roles" on "directus_users"."role" = "directus_roles"."id" where "directus_users"."token" = $1 and "status" = $2 limit $3 [Avo0k3uLKMCmYyXyU6YZKPpyAj15TswD, active, 1]
TRACE: [1.476ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [42863d43-b742-48aa-8a02-970840240743, 1]
TRACE: [3.008ms] select * from "directus_permissions" where "role" = $1 [42863d43-b742-48aa-8a02-970840240743]
TRACE: [20.909ms] insert into "companies" ("date_created", "display_name", "id", "immatriculation", "official_name", "siret", "user_created", "valid") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" [Tue Jul 16 2024 08:44:56 GMT+0000 (GMT), Test compagnie display, 3047fee6-7a91-46e8-96c4-e09c068e4d74, 987654321, Test compagnie, 123456789, 4c3ec146-50e6-4b47-8bfb-7868b48d62f7, false]
TRACE: [1.072ms] select "id", "company" from "directus_users" where "id" = $1 limit $2 [4c3ec146-50e6-4b47-8bfb-7868b48d62f7, 1]
TRACE: [0.771ms] select "id" from "directus_users" where "id" = $1 limit $2 [4c3ec146-50e6-4b47-8bfb-7868b48d62f7, 1]
TRACE: [3.736ms] select "directus_users"."first_name", "directus_users"."last_name", "directus_users"."email", "directus_users"."password", "directus_users"."location", "directus_users"."title", "directus_users"."description", "directus_users"."avatar", "directus_users"."language", "directus_users"."appearance", "directus_users"."theme_light", "directus_users"."theme_dark", "directus_users"."theme_light_overrides", "directus_users"."theme_dark_overrides", "directus_users"."tfa_secret", "directus_users"."company", "directus_users"."id" from "directus_users" where (("directus_users"."id" in ($1)) and ("directus_users"."id" = $2)) order by "directus_users"."id" asc limit $3 [4c3ec146-50e6-4b47-8bfb-7868b48d62f7, 4c3ec146-50e6-4b47-8bfb-7868b48d62f7, 1]
DEBUG: You don't have permission to access this.
err: {
  "type": "",
  "message": "You don't have permission to access this.",
  "stack":
      DirectusError: You don't have permission to access this.
          at AuthorizationService.validatePayload (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/authorization.js:366:27)
          at ItemsService.updateMany (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:487:36)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async ItemsService.updateOne (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:407:9)
          at async ItemsService.upsertOne (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:621:20)
          at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:641:36
          at async ItemsService.upsertMany (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:633:29)
          at async PayloadService.processO2M (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/payload.js:516:43)
          at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_nogpcmhnljm46iilmpvjfvq4be/node_modules/@directus/api/dist/services/items.js:169:92
  "name": "DirectusError",
  "code": "FORBIDDEN",
  "status": 403
}
```

_NOTE : the TOKEN and UUID in this example are not used in production environment_

This is causing the issue, but I can't find why it is doing this when it only needs to update ```directus_users.company``` field and it is allowed in Access Control.

am I missing something here ?

Thank you !

### To Reproduce

send a REST request on POST /items/companies with the payload mentioned above, you should receive a Forbidden error

### Directus Version

10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Does the user doing the create request have permissions to update this new `directus_users.company` field?

**Comment by vwasteels** [comment]
Hello, yes sure, here it is : 

On the user side :

![Capture d’écran 2024-07-16 à 14 57 23](https://github.com/user-attachments/assets/89ac60eb-f946-4b44-820f-b522a4b616bb)

And on the company side :

![Capture d’écran 2024-07-16 à 14 58 01](https://github.com/user-attachments/assets/3a63e59f-7f7e-49c0-a788-2285d9620cf9)

Thanks

**Comment by vwasteels** [comment]
NOTE : In my screenshots you might be confused by the presence of ```directus_users.companies``` and ```companies.owner``` , but there are just temporary workaround solutions
