### ISSUE TITLE
Installation of directus according to the documentation results in error caused by node-gyp (gyp issue)

### ISSUE THREAD

**Issue by liuzz99** [directus/directus#23117]
### Describe the Bug

Cannot successfully install directUs locally. The latest version of gpy has been installed, but the initialization still fails
```
 ~/ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.17.1 | darwin | arm64
18.17.1
18.20.4
20.15.0
20.16.0
gyp info ok
```

### To Reproduce

I have install the latest gyp
```
 ~/ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.17.1 | darwin | arm64
18.17.1
18.20.4
20.15.0
20.16.0
gyp info ok
```
But when I install directUs , it still have the below error

```
npm error code 1
npm error path /Users/liuzhengzhao/directus/node_modules/isolated-vm
npm error command failed
npm error command sh -c prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
npm error prebuild-install warn install No prebuilt binaries found (target=18.17.1 runtime=node arch=arm64 libc= platform=darwin)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@8.4.1
npm error gyp info using node@18.17.1 | darwin | arm64
npm error gyp info find Python using Python version 3.12.4 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm error gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm error gyp info spawn args [
npm error gyp info spawn args   '/Users/liuzhengzhao/directus/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'make',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/Users/liuzhengzhao/directus/node_modules/isolated-vm/build/config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/Users/liuzhengzhao/directus/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/Users/liuzhengzhao/Library/Caches/node-gyp/18.17.1/include/node/common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=/Users/liuzhengzhao/Library/Caches/node-gyp/18.17.1',
npm error gyp info spawn args   '-Dnode_gyp_dir=/Users/liuzhengzhao/directus/node_modules/node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=/Users/liuzhengzhao/Library/Caches/node-gyp/18.17.1/<(target_arch)/node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=/Users/liuzhengzhao/directus/node_modules/isolated-vm',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error Traceback (most recent call last):
npm error   File "/Users/liuzhengzhao/directus/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error     ^^^^^^^^^^
npm error   File "/Users/liuzhengzhao/directus/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/Users/liuzhengzhao/directus/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm error     from distutils.version import StrictVersion
npm error ModuleNotFoundError: No module named 'distutils'
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onCpExit (/Users/liuzhengzhao/directus/node_modules/node-gyp/lib/configure.js:259:16)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm error gyp ERR! System Darwin 23.5.0
npm error gyp ERR! command "/Users/liuzhengzhao/.nvm/versions/node/v18.17.1/bin/node" "/Users/liuzhengzhao/directus/node_modules/.bin/node-gyp" "rebuild" "--release" "-j" "max"
npm error gyp ERR! cwd /Users/liuzhengzhao/directus/node_modules/isolated-vm
npm error gyp ERR! node -v v18.17.1
npm error gyp ERR! node-gyp -v v8.4.1
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/liuzhengzhao/.npm/_logs/2024-07-27T16_25_13_277Z-debug-0.log
npm error code 1
npm error path /Users/liuzhengzhao
npm error command failed
npm error command sh -c cdp directus
npm error A complete log of this run can be found in: /Users/liuzhengzhao/.npm/_logs/2024-07-27T16_25_11_776Z-debug-0.log
```

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
I believe this is because you've upgraded the global version of python on your mac to 3.12+. According to the linked issue on the node-gyp repo there's an additional package you can install to get it back up and running:

https://github.com/nodejs/node-gyp/issues/2869#issuecomment-1769572922

**Comment by liuzz99** [comment]
> I believe this is because you've upgraded the global version of python on your mac to 3.12+. According to the linked issue on the node-gyp repo there's an additional package you can install to get it back up and running:
> 
> [nodejs/node-gyp#2869 (comment)](https://github.com/nodejs/node-gyp/issues/2869#issuecomment-1769572922)

ok , thanks a lot ,let me have a try
