### ISSUE TITLE
ForbiddenCollectionReadException when trying to list collections.

### ISSUE THREAD

**Issue by syslogic** [directus/directus#2318]
# Bug Report

## Steps to Reproduce
1. Go to `/_/collections`

## Expected Behavior
it should list possibly list 15 collections... or is error `300` the expected behavior?

## Actual Behavior
`{"error":{"code":300,"message":"Reading items from \"directus_collections\" collection was denied","class":"Directus\\Permissions\\Exception\\ForbiddenCollectionReadException","file":"\/var\/www\/local.directus\/src\/core\/Directus\/Permissions\/Acl.php","line":988}}`

## Other Context & Screenshots

I have no clue, what this line is good for, but it returns 15 collections, when I remove it:
https://github.com/directus/directus/blob/9fa13f475ee73fe0cf1393eadcf34b9094b99d56/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L1018

The actual cause might still be a CMS permission problem, stemming from incomplete setup.

Also noticed that at one time I've had a `Public` user, possibly when installing from the `api` repository and so I wonder, if this `ForbiddenCollectionReadException` can be caused by such a missing user record? Would need to test this with the other version once again, or even install them side by side to compare.

Admin login `/api/auth/authenticate` also gives me `HTTP 404`... where I at first had issues accessing the page because of `DirectoryIndex index.php` instead of `DirectoryIndex index.php index.html`.

## Technical Details

```
api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException:
Reading items from "directus_collections" collection was denied in /var/www/local.directus/src/core/Directus/Permissions/Acl.php:988
Stack trace:
#0 /var/www/local.directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1148): Directus\Permissions\Acl->enforceReadOnce
#1 /var/www/local.directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1018): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
#2 /var/www/local.directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1137): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
#3 /var/www/local.directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(819): Directus\Database\TableGateway\RelationalTableGateway->fetchData
#4 /var/www/local.directus/src/core/Directus/Services/TablesService.php(67): Directus\Database\TableGateway\RelationalTableGateway->getItems
#5 /var/www/local.directus/src/endpoints/Collections.php(58): Directus\Services\TablesService->findAll
#6 [internal function]: Directus\Api\Routes\Collections->all
#7 /var/www/local.directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#8 /var/www/local.directus/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#9 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#11 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#16 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#21 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#24 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#25 /var/www/local.directus/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#26 /var/www/local.directus/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#27 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#29 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/local.directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#33 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#35 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#36 [internal function]: Slim\DeferredCallable->__invoke
#37 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#38 /var/www/local.directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#39 [internal function]: RKA\Middleware\IpAddress->__invoke
#40 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#41 [internal function]: Slim\DeferredCallable->__invoke
#42 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#43 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#45 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#48 /var/www/local.directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#50 /var/www/local.directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#53 /var/www/local.directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#54 /var/www/local.directus/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#55 /var/www/local.directus/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#56 /var/www/local.directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#57 /var/www/local.directus/public/index.php(3): Directus\Application\Application->run [] []
```
- Device: [Desktop]
- OS: [Redhat Linux, Kernel 3.10]
- Web Server: [Apache 2.4.37]
- PHP Version: [7.1.26]
- Database: [MariaDB 10.2.22]
- Install Method: [cloned the `master` branch]

**Comment by syslogic** [comment]
It turned out to be `/#/collections` ...once having used api & app repositories.
