### ISSUE TITLE
Created user role can't update relational fields items in collections

### ISSUE THREAD

**Issue by prettyGitty** [directus/directus#2320]
# Bug Report
Created user role can't update relational field items in collections. I created two main collections (companies, cooperations) and several junction-, lookup- and metadata collections. 

The issue appears after creating an item in the main collections with some information in the related fields. Once after a related field is filled with information (add new or select existing) it is not possible to update those related fields. Thrown error: 'Updating item from "directus_users" collection was denied'

NOTE: Admin role doesn't have any problem to create, update or delete any items.

## Steps to Reproduce

1. Created 2 main and several junction-, lookup-, metadata collections (all managed).
2. Relational fields in main and metadata collections have been created beside other fields.
3. Created a new user role
    - Admin set permissions for every custom collection (create, read etc. ) and it fields. (set to all)
    - For testing I also set every directus collections to "all" except directus_users, but it didn't solve the issue.
4. Created a new user for the custom user role. Any action from that point was done by the new user role.
4. Created a new item in collection company. (m2m relational fields such as company has services been filled)
5. Saved the new company item
6. Trying to update already created relational fields within this new company item is throwing an error (Updating item from "directus_users" collection was denied)

## Expected Behavior
New user role should be able to update relational fields of already created items.

## Actual Behavior
Updating relational fields is being denied from directus for the new user role

## Other Context & Screenshots

All the relational fields (fields are mostly in Unternehmen/company and Kooperationen/cooperation) like those I marked in red can't been updated by the new user role 
![grafik](https://user-images.githubusercontent.com/33925696/54919494-3c7e9100-4f01-11e9-9bd6-31c7ce549525.png)

Full error message:
[2019-03-25 12:50:36] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionUpdateException: Updating item from "directus_users" collection was denied in /var/www/directus/src/core/Directus/Permissions/Acl.php:1072
Stack trace:
#0 /var/www/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1275): Directus\Permissions\Acl->enforceUpdateAll
#1 /var/www/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(852): Directus\Database\TableGateway\BaseTableGateway->enforceUpdatePermission
#2 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(361): Directus\Database\TableGateway\BaseTableGateway->executeUpdate
#3 /var/www/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(455): Zend\Db\TableGateway\AbstractTableGateway->updateWith
#4 /var/www/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(362): Directus\Database\TableGateway\BaseTableGateway->updateRecordByArray
#5 /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(197): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray
#6 /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(608): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate
#7 /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(170): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateManyToOneRelationships
#8 /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(684): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate
#9 /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(519): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateToManyRelationships
#10 /var/www/directus/src/core/Directus/Services/ItemsService.php(156): Directus\Database\TableGateway\RelationalTableGateway->updateRecord
#11 /var/www/directus/src/endpoints/Items.php(121): Directus\Services\ItemsService->update
#12 [internal function]: Directus\Api\Routes\Items->update
#13 /var/www/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#14 /var/www/directus/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#15 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#16 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#17 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#21 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#22 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 /var/www/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#26 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#27 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#28 [internal function]: Slim\DeferredCallable->__invoke
#29 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#30 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#31 /var/www/directus/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#32 /var/www/directus/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#33 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#34 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#35 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#36 [internal function]: Slim\DeferredCallable->__invoke
#37 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#38 /var/www/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#39 /var/www/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#40 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#41 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /var/www/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#45 [internal function]: RKA\Middleware\IpAddress->__invoke
#46 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#50 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#51 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#52 [internal function]: Slim\DeferredCallable->__invoke
#53 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#54 /var/www/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#55 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#56 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#57 [internal function]: Slim\DeferredCallable->__invoke
#58 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#59 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#60 /var/www/directus/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#61 /var/www/directus/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#62 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#63 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []

## Technical Details

- Device: Virtual Server
- OS: Ubuntu 16.04 TLS
- Web Server: Apache 2.4.18
- PHP Version: v7.1.27
- Database: Ver 14.14 Distrib 5.7.25
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
Hey @prettyGitty! Do those collections have any `user_updated` or `user_created` fields?

**Comment by prettyGitty** [comment]
Yes some have indeed. All junction tables do have the "modified by" as user_updated field

**Comment by prettyGitty** [comment]
After deleting the "modified by" field it is working like it supposed to be. But isn't there another way to do this? It is quite useless in junction tables, but important in other collections. I also tried just to delete the permission for that user role to write into that field, while hopping directus does it in another way then, but it didn't help
