### ISSUE TITLE
Directus does not start if the client_id in the SSO consists only of numbers

### ISSUE THREAD

**Issue by skoif** [directus/directus#23291]
### Describe the Bug

My oauth 2 provider gives out client_id which consists only of numbers. If the id consists of letters and numbers, everything is ok, but if it consists only of numbers then when starting directus, this error occurs:

```
TypeError: client_id is required
    at new BaseClient (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:185:13)
    at new Client (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:1841:7)
    at new OAuth2AuthDriver (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth/drivers/oauth2.js:49:23)
    at getProviderInstance (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth.js:57:20)
    at file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth.js:44:26
    at Array.forEach (<anonymous>)
    at registerAuthProviders (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth.js:33:19)
    at async createApp (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/app.js:84:5)
    at async createServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/server.js:23:38)
    at async Command.startServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/server.js:118:20)
```

### To Reproduce

Add SSO provider configuration, set client_id which consist only of numbers

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by azrikahar** [comment]
This should be the same issue as #9521. In the meantime, you can use the [`string` syntax prefix](https://docs.directus.io/self-hosted/config-options.html#environment-syntax-prefix) to cast the number-only client_id to a string, such as `AUTH_<PROVIDER>_CLIENT_ID="string:<number-only-client-id>"`.
