### ISSUE TITLE
Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be \"http:\".

### ISSUE THREAD

**Issue by InstantlyMoist** [directus/directus#23325]
### Describe the Bug

The application does not boot when setting the 

GLOBAL_AGENT_HTTPS_PROXY="https://redacted.com"
GLOBAL_AGENT_HTTP_PROXY="http://redacted.com"

With the following error:
```
2024-08-13 18:23:43 [16:23:42.932] ERROR: [OpenID] Failed to fetch provider config
2024-08-13 18:23:43     err: {
2024-08-13 18:23:43       "type": "UnexpectedStateError",
2024-08-13 18:23:43       "message": "Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be \"http:\".",
2024-08-13 18:23:43       "stack":
2024-08-13 18:23:43           UnexpectedStateError: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".
2024-08-13 18:23:43               at parseProxyUrl (/directus/node_modules/.pnpm/global-agent@3.0.0/node_modules/global-agent/dist/utilities/parseProxyUrl.js:24:11)
2024-08-13 18:23:43               at BoundHttpsProxyAgent.getUrlProxy (/directus/node_modules/.pnpm/global-agent@3.0.0/node_modules/global-agent/dist/factories/createGlobalProxyAgent.js:108:43)
2024-08-13 18:23:43               at BoundHttpsProxyAgent.addRequest (/directus/node_modules/.pnpm/global-agent@3.0.0/node_modules/global-agent/dist/classes/Agent.js:62:24)
2024-08-13 18:23:43               at new ClientRequest (node:_http_client:342:16)
2024-08-13 18:23:43               at request (node:https:366:10)
2024-08-13 18:23:43               at /directus/node_modules/.pnpm/global-agent@3.0.0/node_modules/global-agent/dist/utilities/bindHttpMethod.js:53:14
2024-08-13 18:23:43               at Issuer.request (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/helpers/request.js:123:73)
2024-08-13 18:23:43               at Issuer.discover (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/issuer.js:143:36)
2024-08-13 18:23:43               at file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth/drivers/openid.js:44:20
2024-08-13 18:23:43               at new Promise (<anonymous>)
2024-08-13 18:23:43       "code": "UNEXPECTED_STATE_ERROR"
2024-08-13 18:23:43     }
```

### To Reproduce

Set the flags in your .env
Boot the application (in docker)

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this problem with the env vars provided. Given the error I'm assuming there's an SSO requirement to reproduce this as well? Are you using the Docker image that we distribute, or are you using a custom Dockerfile? I'll close this for now as there's not enough information to reproduce this issue.

**Comment by InstantlyMoist** [comment]
> I haven't been able to reproduce this problem with the env vars provided. Given the error I'm assuming there's an SSO requirement to reproduce this as well? Are you using the Docker image that we distribute, or are you using a custom Dockerfile? I'll close this for now as there's not enough information to reproduce this issue.

I'm not using a custom Dockerfile as far as own customization, I added the ecosystem patch as described in the documentation. Is there any other information I could provide you with?
