### ISSUE TITLE
Discord SSO error

### ISSUE THREAD

**Issue by devsecur** [directus/directus#23351]
### Describe the Bug

I try to setup discord SSO and get the following error:

```sh
directus-1  | TypeError: client_id is required
directus-1  |     at new BaseClient (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:185:13)
directus-1  |     at new Client (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:1841:7)
directus-1  |     at new OAuth2AuthDriver (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/auth/drivers/oauth2.js:48:23)
directus-1  |     at getProviderInstance (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/auth.js:57:20)
directus-1  |     at file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/auth.js:44:26
directus-1  |     at Array.forEach (<anonymous>)
directus-1  |     at registerAuthProviders (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/auth.js:33:19)
directus-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus-1  |     at async createApp (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/app.js:83:5)
directus-1  |     at async createServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/server.js:22:38)
```

### To Reproduce

Start simple docker-compose.yml:

```docker-compose
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      AUTH_PROVIDERS: "discord"
      AUTH_DISABLE_DEFAULT: true
      AUTH_DISCORD_DRIVER: "oauth2"
      AUTH_DISCORD_CLIENT_ID: "xxx"
      AUTH_DISCORD_CLIENT_SECRET: "xxx"
      AUTH_DISCORD_AUTHORIZE_URL: "https://discord.com/api/oauth2/authorize"
      AUTH_DISCORD_ACCESS_URL: "https://discord.com/api/oauth2/token"
      AUTH_DISCORD_PROFILE_URL: "https://discord.com/api/users/@me"
      AUTH_DISCORD_ALLOW_PUBLIC_REGISTRATION: "true"
```

### Directus Version

10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Duplicate of #9521, see also https://github.com/directus/directus/issues/23291#issuecomment-2283090674 for a workaround.
