### ISSUE TITLE
You don't have permission to access collection \"directus_translations\" or it does not exist. Queried in root.

### ISSUE THREAD

**Issue by khangcnttspkt** [directus/directus#23422]
### Describe the Bug

I cannot login after authentication with Keycloak

[10:14:38.316] DEBUG: You don't have permission to access collection "directus_translations" or it does not exist. Queried in root.
    err: {
      "type": "",
      "message": "You don't have permission to access collection \"directus_translations\" or it does not exist. Queried in root.",
      "stack":
          DirectusError: You don't have permission to access collection "directus_translations" or it does not exist. Queried in root.
              at createCollectionForbiddenError (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/permissions/modules/process-ast/utils/validate-path/create-error.js:4:12)
              at validatePathPermissions (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/permissions/modules/process-ast/utils/validate-path/validate-path-permissions.js:5:15)
              at processAst (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/permissions/modules/process-ast/process-ast.js:31:9)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TranslationsService.readByQuery (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/services/items.js:372:15)
              at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/controllers/translations.js:61:18
      "name": "DirectusError",
      "extensions": {
        "reason": "You don't have permission to access collection \"directus_translations\" or it does not exist. Queried in root."
      },
      "code": "FORBIDDEN",
      "status": 403
    }
[10:14:38] GET /translations?fields[]=language&fields[]=key&fields[]=value&filter[language][_eq]=en-US&limit=-1 403 21ms

![image](https://github.com/user-attachments/assets/b13c50f6-7c3b-4e57-afa5-c7861ecf53b1)

### To Reproduce

^

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis/postgis:16-3.4

**Comment by khangcnttspkt** [comment]
![image](https://github.com/user-attachments/assets/2a5d98be-3616-4c8c-8e75-c651aaf48b42)
User I'm using to login via Keycloak

**Comment by LevelUpGit** [comment]
Same thing, but regular login.

**Comment by hanneskuettner** [comment]
The error you are seeing has nothing to do with a login failure. This is normal, an expected behavior, as the Directus Studio tries to optimistically query the `/translations` endpoint. If the public user does not have access to it, this is the error you will see, which is fully expected. 

The error you are having with Keycloak should show up after this error in your logs. I'm closing this, as the error you are seeing is unrelated to the login failure. If you have new information with the error that is actually causing the login problem (most likely a configuration problem tho) I'm happy to reopen this and adjust the title/description accordingly.
