### ISSUE TITLE
Migration Error: Missing `uploaded_on` Field in `directus_files` Table After Update to 11.0.2

### ISSUE THREAD

**Issue by leorott** [directus/directus#23496]
### Describe the Bug

After upgrading Directus from version `10.10.2` to `11.0.2`, the migration process fails due to an error related to the `uploaded_on` field in the `directus_files` table. 

The migration script [20240716A-update-files-date-fields.ts ](https://github.com/directus/directus/blob/103a4c96e4dbbe008841ed82eea2fcee7385ac22/api/src/database/migrations/20240716A-update-files-date-fields.ts#L8) attempts to modify the directus_files table, but it encounters the following error:

```
directus-docker  | Error: alter table `directus_files` add `uploaded_on` timestamp - Invalid default value for 'uploaded_on'
directus-docker  |     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packets/packet.js:728:17)
directus-docker  |     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/commands/command.js:29:26)
directus-docker  |     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:481:34)
directus-docker  |     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:97:12)
directus-docker  |     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packet_parser.js:75:16)
directus-docker  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:104:25)
directus-docker  |     at Socket.emit (node:events:517:28)
directus-docker  |     at addChunk (node:internal/streams/readable:368:12)
directus-docker  |     at readableAddChunk (node:internal/streams/readable:341:9)
directus-docker  |     at Readable.push (node:internal/streams/readable:278:10) {
directus-docker  |   code: 'ER_INVALID_DEFAULT',
directus-docker  |   errno: 1067,
directus-docker  |   sqlState: '42000',
directus-docker  |   sqlMessage: "Invalid default value for 'uploaded_on'",
directus-docker  |   sql: 'alter table `directus_files` add `uploaded_on` timestamp'
directus-docker  | }

```
When looking at the `directus_files` table in version `11.0.2` it looks like this:

```

mysql> desc directus_files;
+-------------------+------------------+------+-----+-------------------+-------+
| Field             | Type             | Null | Key | Default           | Extra |
+-------------------+------------------+------+-----+-------------------+-------+
| id                | char(36)         | NO   | PRI | NULL              |       |
| storage           | varchar(255)     | NO   |     | NULL              |       |
| filename_disk     | varchar(255)     | YES  |     | NULL              |       |
| filename_download | varchar(255)     | NO   |     | NULL              |       |
| title             | varchar(255)     | YES  |     | NULL              |       |
| type              | varchar(255)     | YES  |     | NULL              |       |
| folder            | char(36)         | YES  | MUL | NULL              |       |
| uploaded_by       | char(36)         | YES  | MUL | NULL              |       |
| created_on        | timestamp        | NO   |     | CURRENT_TIMESTAMP |       |
| modified_by       | char(36)         | YES  | MUL | NULL              |       |
| modified_on       | timestamp        | NO   |     | CURRENT_TIMESTAMP |       |
| charset           | varchar(50)      | YES  |     | NULL              |       |
| filesize          | bigint(20)       | YES  |     | NULL              |       |
| width             | int(10) unsigned | YES  |     | NULL              |       |
| height            | int(10) unsigned | YES  |     | NULL              |       |
| duration          | int(10) unsigned | YES  |     | NULL              |       |
| embed             | varchar(200)     | YES  |     | NULL              |       |
| description       | text             | YES  |     | NULL              |       |
| location          | text             | YES  |     | NULL              |       |
| tags              | text             | YES  |     | NULL              |       |
| metadata          | json             | YES  |     | NULL              |       |
| focal_point_x     | int(11)          | YES  |     | NULL              |       |
| focal_point_y     | int(11)          | YES  |     | NULL              |       |
| tus_id            | varchar(64)      | YES  |     | NULL              |       |
| tus_data          | json             | YES  |     | NULL              |       |
+-------------------+------------------+------+-----+-------------------+-------+
25 rows in set (0.01 sec)

```

The `uploaded_on` field is missing, and therefore the migration is failing. For comparison, here’s the structure of the `directus_files` table before the update (version `10.0.2`):

```
mysql> desc directus_files;
+-------------------+------------------+------+-----+-------------------+-------+
| Field             | Type             | Null | Key | Default           | Extra |
+-------------------+------------------+------+-----+-------------------+-------+
| id                | char(36)         | NO   | PRI | NULL              |       |
| storage           | varchar(255)     | NO   |     | NULL              |       |
| filename_disk     | varchar(255)     | YES  |     | NULL              |       |
| filename_download | varchar(255)     | NO   |     | NULL              |       |
| title             | varchar(255)     | YES  |     | NULL              |       |
| type              | varchar(255)     | YES  |     | NULL              |       |
| folder            | char(36)         | YES  | MUL | NULL              |       |
| uploaded_by       | char(36)         | YES  | MUL | NULL              |       |
| uploaded_on       | timestamp        | NO   |     | CURRENT_TIMESTAMP |       |
| modified_by       | char(36)         | YES  | MUL | NULL              |       |
| modified_on       | timestamp        | NO   |     | CURRENT_TIMESTAMP |       |
| charset           | varchar(50)      | YES  |     | NULL              |       |
| filesize          | bigint(20)       | YES  |     | NULL              |       |
| width             | int(10) unsigned | YES  |     | NULL              |       |
| height            | int(10) unsigned | YES  |     | NULL              |       |
| duration          | int(10) unsigned | YES  |     | NULL              |       |
| embed             | varchar(200)     | YES  |     | NULL              |       |
| description       | text             | YES  |     | NULL              |       |
| location          | text             | YES  |     | NULL              |       |
| tags              | text             | YES  |     | NULL              |       |
| metadata          | json             | YES  |     | NULL              |       |
| focal_point_x     | int(11)          | YES  |     | NULL              |       |
| focal_point_y     | int(11)          | YES  |     | NULL              |       |
+-------------------+------------------+------+-----+-------------------+-------+
23 rows in set (0.01 sec)
```

The uploaded_on field, which exists in version 10.10.2, appears to be missing after upgrading to 11.0.2, leading to the migration error. What could be the reason for this?

### To Reproduce

- Start a Directus App with the Version `10.10.2` and Mysql `5.7.38` 
- Update Directus to`11.0.2` 

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Mysql 5.7.38

**Comment by leorott** [comment]
Could it be that the migration somehow gets executed twice, and therefore this error occurs?

**Comment by hanneskuettner** [comment]
This seems to be caused by some DB configuration values. 
Maybe it can be solved by the solution suggested in this comment https://github.com/directus/directus/issues/23390#issuecomment-2311833688 (Though this is MariaDB specific, I don't know if there is overlap between MariaDB 10.4 and MySQL 5.7)

As a side note, MySQL 5.7 is EOL for quite a while now and not officially supported by Directus anymore, see https://docs.directus.io/self-hosted/docker-guide.html#supported-databases
