### ISSUE TITLE
LDAP authentication error with INVALID_CREDENTIALS

### ISSUE THREAD

**Issue by yosapontha** [directus/directus#23497]
### Describe the Bug

This is my current settings.

```
AUTH_PROVIDERS="ldap"

AUTH_LDAP_DRIVER="ldap"
AUTH_LDAP_CLIENT_URL="ldap://x.x.x.x:389"
AUTH_LDAP_BIND_DN="string:CN=binduser,OU=subdeptou,OU=deptou,DC=org,DC=local"
AUTH_LDAP_BIND_PASSWORD="Password"
AUTH_LDAP_USER_DN="string:DC=org,DC=local"
```

When login with LDAP, I get this error log.

```
[10:28:29] POST /auth/login/ldap 401 505ms
directus-1  | [10:28:29.140] DEBUG: Invalid user credentials.
directus-1  |     err: {
directus-1  |       "type": "",
directus-1  |       "message": "Invalid user credentials.",
directus-1  |       "stack":
directus-1  |           DirectusError: Invalid user credentials.
directus-1  |               at LDAPAuthDriver.getUserID (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth/drivers/ldap.js:181:19)
directus-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus-1  |               at async AuthenticationService.login (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/services/authentication.js:46:22)
directus-1  |               at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.43_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_xkwz2vmva5vj7v4jqlt2f5ginm/node_modules/@directus/api/dist/auth/drivers/ldap.js:317:56
directus-1  |       "name": "DirectusError",
directus-1  |       "code": "INVALID_CREDENTIALS",
directus-1  |       "status": 401
directus-1  |     }
```

But weirdly, When I tested the same config with the "ldap-authentication" npm lib, It works perfectly fine. As the picture below.

![Screenshot 2024-08-27 173841](https://github.com/user-attachments/assets/cd70b216-2250-4000-aab9-dc125687268f)

### To Reproduce

setup with this config

```
AUTH_PROVIDERS="ldap"

AUTH_LDAP_DRIVER="ldap"
AUTH_LDAP_CLIENT_URL="ldap://x.x.x.x:389"
AUTH_LDAP_BIND_DN="string:CN=binduser,OU=subdeptou,OU=deptou,DC=org,DC=local"
AUTH_LDAP_BIND_PASSWORD="Password"
AUTH_LDAP_USER_DN="string:DC=org,DC=local"
```

and try to login with AD Account

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 13

**Comment by rijkvanzanten** [comment]
Does your LDAP provider return the `identifier` field to Directus? That's what it saves and checks against for user access. If that's missing the invalid credentials error is thrown.

https://github.com/directus/directus/blob/231dd0e6e6951606f1003f1f0d795bcbedee1249/api/src/auth/drivers/ldap.ts#L236-L238

**Comment by yosapontha** [comment]
this is all of the return field that I got when use ldap-authentication lib

- dn
- objectClass
- cn
- sn
- title
- description
- telephoneNumber
- facsimileTelephoneNumber
- givenName
- initials
- distinguishedName
- instanceType
- whenCreated
- whenChanged
- displayName
- uSNCreated
- info
- memberOf
- uSNChanged
- department
- employeeType
- name
- objectGUID
- userAccountControl
- badPwdCount
- codePage
- countryCode
- badPasswordTime
- lastLogoff
- lastLogon
- pwdLastSet
- primaryGroupID
- objectSid
- adminCount
- accountExpires
- logonCount
- sAMAccountName
- sAMAccountType
- userPrincipalName
- objectCategory
- dSCorePropagationData
- lastLogonTimestamp
- mail
- extensionAttribute12
- extensionAttribute2
- extensionAttribute9
- optionalEmail
- extensionAttribute14
- extensionAttribute6
- extensionAttribute11
- extensionAttribute5
- extensionAttribute13
- extensionAttribute4
- extensionAttribute10
- extensionAttribute7
- extensionAttribute8
- extensionAttribute15
- extensionAttribute3
- extensionAttribute1

**Comment by rijkvanzanten** [comment]
Right, so no `identifier`

**Comment by yosapontha** [comment]
So that means there is no other way to use the LDAP authentication with my current AD?

**Comment by yosapontha** [comment]
Solved.

I added this the configuration.

AUTH_LDAP_AUTO_CREATE_USER="true"
AUTH_LDAP_USER_SCOPE="sub"
AUTH_LDAP_USER_ATTRIBUTE="userPrincipalName"

For searching in all subdirectories and use userPrincipalName as a search key. Because my org use the account along with the domain like xxx@xxx.com to login.

**Comment by yosapontha** [comment]
Solved.

I added this the configuration.

AUTH_LDAP_AUTO_CREATE_USER="true"
AUTH_LDAP_USER_SCOPE="sub"
AUTH_LDAP_USER_ATTRIBUTE="userPrincipalName"

For searching in all subdirectories and use userPrincipalName as a search key. Because my org use the account along with the domain like xxx@xxx.com to login.
