### ISSUE TITLE
Health check "storage:CLOUDINARY:responseTime" breaks after update to 11.1.0

### ISSUE THREAD

**Issue by hofstettera** [directus/directus#23635]
### Describe the Bug

Since the update from 11.0.2 to 11.1.0, the endpoint "/server/health" returns error.

The reason is the check “storage:CLOUDINARY:responseTime". It has the error code "ERR_INVALID_ARG_TYPE"

Here is the complete response:
```javascript
{
  "status": "error",
  "releaseId": "11.1.0",
  "serviceId": "/",
  "checks": {
    "pg:responseTime": [
      {
        "status": "ok",
        "componentType": "datastore",
        "observedUnit": "ms",
        "observedValue": 1.838,
        "threshold": 500
      }
    ],
    "pg:connectionsAvailable": [
      {
        "status": "ok",
        "componentType": "datastore",
        "observedValue": 11
      }
    ],
    "pg:connectionsUsed": [
      {
        "status": "ok",
        "componentType": "datastore",
        "observedValue": 0
      }
    ],
    "cache:responseTime": [
      {
        "status": "ok",
        "componentType": "cache",
        "observedValue": 1.891,
        "observedUnit": "ms",
        "threshold": 150
      }
    ],
    "storage:CLOUDINARY:responseTime": [
      {
        "status": "error",
        "componentType": "objectstore",
        "observedValue": 0.881,
        "observedUnit": "ms",
        "threshold": 1500,
        "output": {
          "code": "ERR_INVALID_ARG_TYPE"
        }
      }
    ],
    "email:connection": [
      {
        "status": "ok",
        "componentType": "email"
      }
    ]
  }
}
``` 

### To Reproduce

1. Update to v11.1.0
2. Request /server/health
3. See status "error"

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Does the Cloudinary storage itself work, e.g. can you see & create files via Directus?
Could you please also check the server logs for detailed info about the error when calling the `server/health` endpoint?

If it turns out to be a problem with the Cloudinary storage driver, it's most likely related to the recent changes in #23554.

**Comment by hofstettera** [comment]
Cloudinary storage works. It can see existing files in Directus and Upload new files.

Here the error message in the logs when I calling server/health

```
ERROR: storage:CLOUDINARY:responseTime in ERROR state
    err: {
      "type": "TypeError",
      "message": "The \"list[1]\" argument must be an instance of Buffer or Uint8Array. Received type string ('check')",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be an instance of Buffer or Uint8Array. Received type string ('check')
              at new NodeError (node:internal/errors:405:5)
              at Function.concat (node:buffer:604:13)
              at DriverCloudinary.write (file:///directus/node_modules/.pnpm/@directus+storage-driver-cloudinary@file+packages+storage-driver-cloudinary_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/storage-driver-cloudinary/dist/index.js:274:25)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async testStorage (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/services/server.js:329:21)
              at async Promise.all (index 4)
              at async ServerService.health (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/services/server.js:125:31)
              at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/controllers/server.js:49:18
      "code": "ERR_INVALID_ARG_TYPE"
    }
```
