### ISSUE TITLE
Sentry setup guide does not work

### ISSUE THREAD

**Issue by BorisKamp** [directus/directus#23646]
### Page

https://docs.directus.io/blog/hooks-monitoring-error-tracking-sentry.html

### Describe the Inaccuracy

I've set it up according to the docs but I get the following error when running directus:
```shell
boriskamp@MacBook-Pro cebv-portal-directus % docker compose up
[+] Running 2/0
 ✔ Container cebv-portal-directus-cache-1     Created                                                                                                                                                  0.0s 
 ✔ Container cebv-portal-directus-directus-1  Created                                                                                                                                                  0.0s 
Attaching to cache-1, directus-1
cache-1     | 1:C 12 Sep 2024 08:06:45.273 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache-1     | 1:C 12 Sep 2024 08:06:45.273 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
cache-1     | 1:C 12 Sep 2024 08:06:45.273 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache-1     | 1:M 12 Sep 2024 08:06:45.273 * monotonic clock: POSIX clock_gettime
cache-1     | 1:M 12 Sep 2024 08:06:45.275 * Running mode=standalone, port=6379.
cache-1     | 1:M 12 Sep 2024 08:06:45.275 # Server initialized
cache-1     | 1:M 12 Sep 2024 08:06:45.277 * Loading RDB produced by version 6.2.14
cache-1     | 1:M 12 Sep 2024 08:06:45.277 * RDB age 16 seconds
cache-1     | 1:M 12 Sep 2024 08:06:45.277 * RDB memory usage when created 0.82 Mb
cache-1     | 1:M 12 Sep 2024 08:06:45.277 # Done loading RDB, keys loaded: 34, keys expired: 0.
cache-1     | 1:M 12 Sep 2024 08:06:45.279 * DB loaded from disk: 0.002 seconds
cache-1     | 1:M 12 Sep 2024 08:06:45.279 * Ready to accept connections
directus-1  | [08:06:47.905] INFO: Loaded extensions: stripe, directus-hook-create-stripe-customer, directus-hook-sentry
directus-1  | [08:06:47.911] INFO: Initializing bootstrap...
directus-1  | [08:06:47.913] INFO: Database already initialized, skipping install
directus-1  | [08:06:47.913] INFO: Running migrations...
directus-1  | [08:06:47.920] INFO: Done
directus-1  | 2024-09-12T08:06:48: PM2 log: Launching in no daemon mode
directus-1  | 2024-09-12T08:06:48: PM2 log: App [directus:0] starting in -cluster mode-
directus-1  | [08:06:49.909] INFO: Loaded extensions: stripe, directus-hook-create-stripe-customer, directus-hook-sentry
directus-1  | [08:06:49.918] WARN: PostGIS isn't installed. Geometry type support will be limited.
directus-1  | [08:06:49.929] WARN: An error was thrown while executing init "routes.before"
directus-1  | [08:06:49.929] WARN: Cannot read properties of undefined (reading 'requestHandler')
directus-1  |     err: {
directus-1  |       "type": "TypeError",
directus-1  |       "message": "Cannot read properties of undefined (reading 'requestHandler')",
directus-1  |       "stack":
directus-1  |           TypeError: Cannot read properties of undefined (reading 'requestHandler')
directus-1  |               at EventEmitter.<anonymous> (file:///directus/extensions/directus-hook-sentry/dist/index.js?t=1726128409589:1:209)
directus-1  |               at EventEmitter.emitAsync (/directus/node_modules/.pnpm/eventemitter2@6.4.9/node_modules/eventemitter2/lib/eventemitter2.js:1157:36)
directus-1  |               at Emitter.emitInit (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/emitter.js:57:36)
directus-1  |               at createApp (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/app.js:205:19)
directus-1  |               at async createServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/server.js:23:38)
directus-1  |               at async Command.startServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/server.js:120:20)
directus-1  |               at async Command.parseAsync (/directus/node_modules/.pnpm/commander@12.0.0/node_modules/commander/lib/command.js:1015:5)
directus-1  |     }
directus-1  | [08:06:49.930] WARN: An error was thrown while executing init "routes.custom.after"
directus-1  | [08:06:49.930] WARN: Cannot read properties of undefined (reading 'errorHandler')
directus-1  |     err: {
directus-1  |       "type": "TypeError",
directus-1  |       "message": "Cannot read properties of undefined (reading 'errorHandler')",
directus-1  |       "stack":
directus-1  |           TypeError: Cannot read properties of undefined (reading 'errorHandler')
directus-1  |               at EventEmitter.<anonymous> (file:///directus/extensions/directus-hook-sentry/dist/index.js?t=1726128409589:1:334)
directus-1  |               at EventEmitter.emitAsync (/directus/node_modules/.pnpm/eventemitter2@6.4.9/node_modules/eventemitter2/lib/eventemitter2.js:1157:36)
directus-1  |               at Emitter.emitInit (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/emitter.js:57:36)
directus-1  |               at createApp (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/app.js:243:19)
directus-1  |               at async createServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/server.js:23:38)
directus-1  |               at async Command.startServer (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/server.js:120:20)
directus-1  |               at async Command.parseAsync (/directus/node_modules/.pnpm/commander@12.0.0/node_modules/commander/lib/command.js:1015:5)
directus-1  |     }
directus-1  | [08:06:49.940] INFO: GraphQL Subscriptions started at 0.0.0.0:8055/graphql
directus-1  | [08:06:49.940] INFO: WebSocket Server started at 0.0.0.0:8055/websocket
directus-1  | [08:06:49.941] INFO: Logs WebSocket Server started at ws://0.0.0.0:8055/websocket/logs
directus-1  | [08:06:49.958] INFO: Server started at http://0.0.0.0:8055
directus-1  | 2024-09-12T08:06:49: PM2 log: App [directus:0] online
```

What am I doing wrong?

p.s. a TS version of this extension did not work either.

**Comment by paescuj** [comment]
Thanks for opening the issue!
The guide was initially written for an older Sentry SDK version. We'll see how we can adjust the guide to make it compatible with newer versions.
In the meantime, you should be able to get it up and running by explicitly using version 7 of the Sentry SDK:
```shell
npm install @sentry/node@7
```

---

When updating the guide, we should either pin the version (`@sentry/node@8`) or leave a note specifying which version was used by the time the guide was written/last updated.

**Comment by danybol** [comment]
If it's helpful this hook works for me for v8 (it doesn't seem to work for flows, but does capture errors in application startup and in requests):

```
import { createRequire } from "module"
const require = createRequire(import.meta.url)
const Sentry = require('@sentry/node')
let loadedNodeProfilingIntegration = null
const { nodeProfilingIntegration } = require("@sentry/profiling-node")
loadedNodeProfilingIntegration = nodeProfilingIntegration


export default ({ init }, { env }) => {
	if (!env.SENTRY_DSN) return
	const integrations = [Sentry.captureConsoleIntegration({ levels: ["error"] })]
	if (loadedNodeProfilingIntegration) {
		integrations.push(loadedNodeProfilingIntegration)
		console.log("Added node profiling to sentry")
	}
	Sentry.init({
		dsn: env.SENTRY_DSN,
		integrations: integrations,
		environment: process.env.SENTRY_ENVIRONMENT || 'develop',
		tracesSampleRate: process.env.SENTRY_SAMPLE_RATE || 0.0,
		// Set sampling rate for profiling - this is relative to tracesSampleRate
		profilesSampleRate: 1.0,
	})

	init('routes.custom.after', ({ app }) => {
		Sentry.setupExpressErrorHandler(app)
		console.log('-- Sentry Error Handler Added --')
	})
}
```

**Comment by BorisKamp** [comment]
> If it's helpful this hook works for me for v8 (it doesn't seem to work for flows, but does capture errors in application startup and in requests):

This works indeed, but I have several questions:

1. This only works on custom routes, what if I want to manually trigger an error somewhere else in an extension? How do I access this Sentry instance?
2. There's little to no data sent with the error to Sentry, I get the following (see screenshot), but Im missing important data such as the url used, the body sent etc etc. basically, all the `req` data.


![image](https://github.com/user-attachments/assets/ccfcc91a-7c40-46cb-9018-096732cbc7a2)
