### ISSUE TITLE
S3 Access Denied Error When Updating an Existing File

### ISSUE THREAD

**Issue by TarekTolba1** [directus/directus#23759]
### Describe the Bug

Access to S3 is denied while updating an existing file.

Files are saved to a subdirectory in the s3 bucket. However, access to subdirectories are supposed to be provided by specifying `arn:aws:s3:::b10124/*`.

I thought it should be related to https://github.com/directus/directus/issues/18171 but I couldn't spot any issues in my AWS policy.

```ERROR: Access Denied.
    err: {
      "type": "S3ServiceException",
      "message": "Access Denied.",
      "stack":
          AccessDenied: Access Denied.
              at throwDefaultError (/directus/node_modules/.pnpm/@smithy+smithy-client@2.5.1/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
              at /directus/node_modules/.pnpm/@smithy+smithy-client@2.5.1/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
              at de_CommandError (/directus/node_modules/.pnpm/@aws-sdk+client-s3@3.569.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /directus/node_modules/.pnpm/@smithy+middleware-serde@2.3.0/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-signing@3.567.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
              at async /directus/node_modules/.pnpm/@smithy+middleware-retry@2.3.1/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.569.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.569.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
              at async /directus/node_modules/.pnpm/@aws-sdk+middleware-logger@3.568.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
      "name": "AccessDenied",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 403,
        "requestId": "17F9E72412CF7DA3",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "Code": "AccessDenied",
      "Key": "cms/staging/f5beed07-29f4-4b5b-8d33-3a4af4544686.png",
      "BucketName": "b10124",
      "Resource": "/b10124/cms/staging/f5beed07-29f4-4b5b-8d33-3a4af4544686.png",
      "RequestId": "17F9E72412CF7DA3",
      "HostId": 
    }
```

S3 policy:

```{
  "CreateDate": "2022-04-04T15:58:19.501Z",
  "Policy": {
    "Statement": [
      {
        "Action": [
          "s3:GetBucketLocation",
          "s3:ListBucket",
          "s3:ListBucketMultipartUploads"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::b10124"
        ]
      },
      {
        "Action": [
          "s3:AbortMultipartUpload",
          "s3:DeleteObject",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:ListMultipartUploadParts",
          "s3:PutObject"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::b10124/*"
        ]
      }
    ],
    "Version": "2012-10-17"
  },
  "PolicyName": "b10124",
  "UpdateDate": "2022-04-04T15:58:19.501Z"
}
```

### To Reproduce

Use itemService.updateOne() or use PATCH /files API to update an existing file.
<img width="814" alt="image" src="https://github.com/user-attachments/assets/57289bef-d301-4b97-b697-3082ea9bb711">

### Directus Version

v10.13.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by TarekTolba1** [comment]
I thought it should be related to #18171 but I couldn't spot any issues in my AWS policy
