### ISSUE TITLE
Relational m2m query filter & sort count() fails with a database error

### ISSUE THREAD

**Issue by domdus** [directus/directus#23862]
### Describe the Bug

The issue appeared after upgrade from 10.10.5 to 11.1.1.
Read item queries seem to break when applying a relational (m2m) filter condition combined with a relational sort on count().
- It does not break when one part left out of the statement: filter OR sort
- It was working at least until 10.10.5
- Maybe related to [#23838](https://github.com/directus/directus/issues/23838)

**Logs**
```
[21:00:28.212] ERROR: select "videos"."id", "videos"."title" from "videos" inner join (select distinct "videos"."id", (select count(*) from "categories_videos" as "wkqdd" where "wkqdd"."videos_id" = "videos"."id") AS "sort_tsech" from "videos" left join "categories_videos" as "sarpd" on "videos"."id" = "sarpd"."videos_id" left join "categories" as "cbjtw" on "sarpd"."categories_id" = "cbjtw"."id" where "cbjtw"."status" = $1 order by (select count(*) from "categories_videos" as "bguuh" where "bguuh"."videos_id" = "videos"."id") desc limit $2) as "inner" on "videos"."id" = "inner"."id" order by "inner"."sort_tsech" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list
    err: {
      "type": "DatabaseError",
      "message": "select \"videos\".\"id\", \"videos\".\"title\" from \"videos\" inner join (select distinct \"videos\".\"id\", (select count(*) from \"categories_videos\" as \"wkqdd\" where \"wkqdd\".\"videos_id\" = \"videos\".\"id\") AS \"sort_tsech\" from \"videos\" left join \"categories_videos\" as \"sarpd\" on \"videos\".\"id\" = \"sarpd\".\"videos_id\" left join \"categories\" as \"cbjtw\" on \"sarpd\".\"categories_id\" = \"cbjtw\".\"id\" where \"cbjtw\".\"status\" = $1 order by (select count(*) from \"categories_videos\" as \"bguuh\" where \"bguuh\".\"videos_id\" = \"videos\".\"id\") desc limit $2) as \"inner\" on \"videos\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_tsech\" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list",
      "stack":
          error: select "videos"."id", "videos"."title" from "videos" inner join (select distinct "videos"."id", (select count(*) from "categories_videos" as "wkqdd" where "wkqdd"."videos_id" = "videos"."id") AS "sort_tsech" from "videos" left join "categories_videos" as "sarpd" on "videos"."id" = "sarpd"."videos_id" left join "categories" as "cbjtw" on "sarpd"."categories_id" = "cbjtw"."id" where "cbjtw"."status" = $1 order by (select count(*) from "categories_videos" as "bguuh" where "bguuh"."videos_id" = "videos"."id") desc limit $2) as "inner" on "videos"."id" = "inner"."id" order by "inner"."sort_tsech" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list
              at Parser.parseErrorMessage (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:283:98)
              at Parser.handlePacket (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:122:29)
              at Parser.parse (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:35:38)
              at TLSSocket.<anonymous> (/opt/node/directus/node_modules/pg-protocol/dist/index.js:11:42)
              at TLSSocket.emit (node:events:514:28)
              at addChunk (node:internal/streams/readable:343:12)
              at readableAddChunk (node:internal/streams/readable:316:9)
              at Readable.push (node:internal/streams/readable:253:10)
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 148,
      "name": "error",
      "severity": "ERROR",
      "code": "42P10",
      "position": "416",
      "file": "parse_clause.c",
      "line": "2888",
      "routine": "transformDistinctClause"
    }
[21:00:28] GET /items/videos?fields=id,title,categories&filter[categories][categories_id][status][_eq]=published&sort=-count(categories) 500 9.6s
```

### To Reproduce

- Create any items collection (e.g. videos)
- Create categories collection
- Create m2m between these two collections
- Add some test data & relational data

Example requests:
`GET /items/videos?fields=id,categories&filter[categories][categories_id][status][_eq]=published&sort=-count(categories)`
`GET /items/videos?fields=id,categories&filter[categories][_none][categories_id][id][_eq]=3e0ab3ea-b0ff-492d-abb6-b6051e7a309a&sort=-count(categories)`

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres 15

**Comment by domdus** [comment]
**Some more logs from another app**

```
[21:16:41.068] ERROR: select "com_users"."id", "com_users"."username", "com_users"."image" from "com_users" inner join (select distinct "com_users"."id", (select count(*) from "com_follow" as "xrbkw" where "xrbkw"."follower_id" = "com_users"."id") AS "sort_jtqhj" from "com_users" left join "com_follow" as "wlrio" on "com_users"."id" = "wlrio"."follower_id" left join "com_users" as "otafg" on "wlrio"."following_id" = "otafg"."id" where (("com_users"."status" = $1 and "otafg"."id" = $2)) order by (select count(*) from "com_follow" as "pmsuj" where "pmsuj"."follower_id" = "com_users"."id") desc limit $3) as "inner" on "com_users"."id" = "inner"."id" order by "inner"."sort_jtqhj" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list
    err: {
      "type": "DatabaseError",
      "message": "select \"com_users\".\"id\", \"com_users\".\"username\", \"com_users\".\"image\" from \"com_users\" inner join (select distinct \"com_users\".\"id\", (select count(*) from \"com_follow\" as \"xrbkw\" where \"xrbkw\".\"follower_id\" = \"com_users\".\"id\") AS \"sort_jtqhj\" from \"com_users\" left join \"com_follow\" as \"wlrio\" on \"com_users\".\"id\" = \"wlrio\".\"follower_id\" left join \"com_users\" as \"otafg\" on \"wlrio\".\"following_id\" = \"otafg\".\"id\" where ((\"com_users\".\"status\" = $1 and \"otafg\".\"id\" = $2)) order by (select count(*) from \"com_follow\" as \"pmsuj\" where \"pmsuj\".\"follower_id\" = \"com_users\".\"id\") desc limit $3) as \"inner\" on \"com_users\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_jtqhj\" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list",
      "stack":
          error: select "com_users"."id", "com_users"."username", "com_users"."image" from "com_users" inner join (select distinct "com_users"."id", (select count(*) from "com_follow" as "xrbkw" where "xrbkw"."follower_id" = "com_users"."id") AS "sort_jtqhj" from "com_users" left join "com_follow" as "wlrio" on "com_users"."id" = "wlrio"."follower_id" left join "com_users" as "otafg" on "wlrio"."following_id" = "otafg"."id" where (("com_users"."status" = $1 and "otafg"."id" = $2)) order by (select count(*) from "com_follow" as "pmsuj" where "pmsuj"."follower_id" = "com_users"."id") desc limit $3) as "inner" on "com_users"."id" = "inner"."id" order by "inner"."sort_jtqhj" desc - for SELECT DISTINCT, ORDER BY expressions must appear in select list
              at Parser.parseErrorMessage (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:283:98)
              at Parser.handlePacket (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:122:29)
              at Parser.parse (/opt/node/directus/node_modules/pg-protocol/dist/parser.js:35:38)
              at TLSSocket.<anonymous> (/opt/node/directus/node_modules/pg-protocol/dist/index.js:11:42)
              at TLSSocket.emit (node:events:514:28)
              at addChunk (node:internal/streams/readable:343:12)
              at readableAddChunk (node:internal/streams/readable:316:9)
              at Readable.push (node:internal/streams/readable:253:10)
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 148,
      "name": "error",
      "severity": "ERROR",
      "code": "42P10",
      "position": "479",
      "file": "parse_clause.c",
      "line": "2888",
      "routine": "transformDistinctClause"
    }
[21:16:41] GET /items/com_users?fields=id,username,image,follower&filter={%22status%22:{%22_eq%22:%22published%22},%22follower%22:{%22following_id%22:{%22id%22:{%22_eq%22:%220fc77db3-eceb-48ab-babf-1326a7eacb73%22}}}}&sort=-count(follower) 500 30ms
```

**Comment by carlo-salinari** [comment]
Hi, author of (possibly related) issue #23838 here.

I've noticed a somewhat similar error recurring in my logs, I'm pasting it here for reference.
Context is similar (upgraded from 10.13.x to 11.1.1, Postgres 16.4).
Maybe a Knex issue limited to Postgres?

```
[12:07:47.399] ERROR: select count("directus_activity"."id") as "count->id" from "directus_activity" where (("directus_activity"."collection" = $1 and "directus_activity"."item" = $2 and "directus_activity"."action" = $3) and ("directus_activity"."user" = $2)) limit $4 - operator does not exist: uuid = text
    err: {
      "type": "DatabaseError",
      "message": "select count(\"directus_activity\".\"id\") as \"count->id\" from \"directus_activity\" where ((\"directus_activity\".\"collection\" = $1 and \"directus_activity\".\"item\" = $2 and \"directus_activity\".\"action\" = $3) and (\"directus_activity\".\"user\" = $2)) limit $4 - operator does not exist: uuid = text",
      "stack":
          error: select count("directus_activity"."id") as "count->id" from "directus_activity" where (("directus_activity"."collection" = $1 and "directus_activity"."item" = $2 and "directus_activity"."action" = $3) and ("directus_activity"."user" = $2)) limit $4 - operator does not exist: uuid = text
              at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
              at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
              at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:517:28)
              at addChunk (node:internal/streams/readable:368:12)
              at readableAddChunk (node:internal/streams/readable:341:9)
              at Readable.push (node:internal/streams/readable:278:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 197,
      "name": "error",
      "severity": "ERROR",
      "code": "42883",
      "hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
      "position": "233",
      "file": "parse_oper.c",
      "line": "647",
      "routine": "op_error"
    }
```

**Comment by arladmin** [comment]
I seem to be encountering a related issue, in v11.1.1

```
"code": "22P02",
"file": "numutils.c",
"length": 141,
"line": "320",
"message": "select \"whatsapp_text\".\"id\", \"whatsapp_text\".\"sort\", \"whatsapp_text\".\"user_created\", \"whatsapp_text\".\"date_created\", \"whatsapp_text\".\"user_updated\", \"whatsapp_text\".\"date_updated\", \"whatsapp_text\".\"content\", \"whatsapp_text\".\"raw\" from \"whatsapp_text\" where \"whatsapp_text\".\"id\" in ($1, $2, $3, $4, $5) limit $6 - invalid input syntax for type integer: \"NaN\"",
"name": "error",
"routine": "pg_strtoint32"
"severity": "ERROR",
"stack":
"type": "DatabaseError",
"where": "unnamed portal parameter $4 = '...'",
```

---

And this is what GPT had to say about this issue:

Based on the error logs you've provided, the issue arises because a `NaN` (Not a Number) value is being passed where an integer is expected in your SQL query parameters. Here's a detailed analysis and steps to resolve the problem:

### **Error Analysis**

1. **Error Message:**

   ```
   invalid input syntax for type integer: "NaN"
   ```

   - This indicates that the database expected an integer but received "NaN" instead.

2. **SQL Query Involved:**

   ```sql
   SELECT "whatsapp_text"."id", "whatsapp_text"."sort", "whatsapp_text"."user_created", 
   "whatsapp_text"."date_created", "whatsapp_text"."user_updated", "whatsapp_text"."date_updated", 
   "whatsapp_text"."content", "whatsapp_text"."raw" 
   FROM "whatsapp_text" 
   WHERE "whatsapp_text"."id" IN ($1, $2, $3, $4, $5) 
   LIMIT $6
   ```

   - The error occurs in the `WHERE` clause with the `IN` condition.

3. **Parameter Details:**

   - The error log mentions:

     ```
     unnamed portal parameter $4 = '...'
     ```

   - This suggests that the fourth parameter (`$4`) is problematic.

4. **HTTP Request:**

   ```
   GET /items/message?limit=-1&fields=%2A.%2A.%2A
   ```

   - The `limit=-1` might be contributing to the issue if not handled properly.

### **Possible Causes**

1. **`NaN` Value in Parameters:**

   - A variable intended to be an integer is `NaN` due to a computational error or uninitialized value.

2. **Negative Limit Handling:**

   - Some systems interpret `limit=-1` as unlimited results, but your database or ORM might not handle negative limits correctly.

3. **Data Type Mismatch:**

   - Passing a non-integer value (like `NaN` or `undefined`) where an integer is expected.

4. **Parameter Binding Issues:**

   - Incorrect binding of parameters leading to improper values being passed to the query.

### **Solutions**

1. **Validate Parameters Before Query Execution:**

   - **Check for `NaN`:** Before passing parameters to the query, ensure none of them are `NaN`.

     ```javascript
     if (isNaN(parameter)) {
       // Handle the error: set a default value or throw an exception
     }
     ```

   - **Ensure Integer Values:** Use parsing functions that guarantee integer outputs.

     ```javascript
     const param = parseInt(value, 10);
     if (isNaN(param)) {
       // Handle the error
     }
     ```

2. **Handle Negative Limits Appropriately:**

   - **Adjust Limit Logic:** If `-1` is meant to represent "no limit," adjust your code to set the limit accordingly without passing `-1` to the SQL query.

     ```javascript
     const limit = requestedLimit === -1 ? null : requestedLimit;
     ```

   - **Modify the Query:**

     ```sql
     LIMIT CASE WHEN $6 IS NULL THEN ALL ELSE $6 END
     ```

3. **Inspect the Parameters Passed to the Query:**

   - **Logging:** Add logs to print out the parameter values before the query executes.

     ```javascript
     console.log('Parameters:', param1, param2, param3, param4, param5, limit);
     ```

   - **Debugging:** Use breakpoints or debuggers to inspect variable states during runtime.

4. **Sanitize User Inputs:**

   - **Input Validation:** Ensure all user-provided inputs are validated and sanitized.

     ```javascript
     function sanitizeInput(input) {
       // Implement validation logic
     }
     ```

5. **Use Prepared Statements and Parameterized Queries:**

   - **Prevent SQL Injection and Type Errors:** Ensure that you're using parameterized queries correctly.

     ```javascript
     const query = 'SELECT ... WHERE id IN ($1, $2, $3, $4, $5) LIMIT $6';
     const params = [id1, id2, id3, id4, id5, limit];
     ```

6. **Update ORM/Database Driver Configuration:**

   - **Check for Known Issues:** Some ORMs have bugs related to handling special numeric values.

   - **Update Packages:** Ensure all your dependencies are up to date.

7. **Review Stack Trace for Additional Clues:**

   - **Parser Errors:**

     ```
     at Parser.handlePacket (/app/code/node_modules/pg-protocol/dist/parser.js:122:29)
     ```

     - Indicates the error occurs during parsing of the database response.

   - **Action:** Verify that the database driver or ORM is correctly handling all data types.

### **Next Steps**

- **Identify the Source of `NaN`:** Trace back in your code where the parameters are set and identify why `NaN` is being assigned.

- **Implement Error Handling:**

  - **Try-Catch Blocks:** Wrap database operations in try-catch blocks to handle exceptions gracefully.

    ```javascript
    try {
      // Execute query
    } catch (error) {
      // Handle error
    }
    ```

- **Test with Known Good Data:**

  - **Controlled Inputs:** Use hardcoded values that are known to be valid to see if the error persists.

- **Consult Documentation:**

  - **Database Docs:** Review PostgreSQL documentation regarding integer inputs.

  - **ORM/Driver Docs:** Check if there are any notes on handling special numeric values like `NaN`.

### **Conclusion**

The error is caused by passing a `NaN` value where an integer is expected in your SQL query parameters. By validating and sanitizing all inputs and parameters before they are used in queries, you can prevent such errors. Additionally, handle special cases like negative limits appropriately in your application logic.

**Comment by hanneskuettner** [comment]
> I seem to be encountering a related issue, in v11.1.1

Looking at the SQL error, this looks unrelated to the original issue, please open a new bug report and add more details, like what does your data model look like, what is the request you're trying to run, do you have the option to run with `LOG_LEVEL=trace` to provide the exact SQL query + parameter bindings Directus is trying to run?
