### ISSUE TITLE
Cannot fetch Marketplace content behind proxy

### ISSUE THREAD

**Issue by Illustratus** [directus/directus#23892]
### Describe the Bug

Heyho,

I really would like to use the marketplace, but unfortunately I'm not able to get it running behind our proxy. I found the following discussion, but nothing works:

- https://github.com/directus/directus/discussions/6386
- https://github.com/directus/directus/discussions/11387

I also tried a nasty dirty way like that:
```sh
docker exec -it --user root directus /bin/sh
chmod 777 /root/

docker exec -it --user node directus /bin/sh
npx pnpm config set store-dir /root/.local/share/pnpm/store/v3 --global && npx pnpm install global-agent

# Add this to cli.js
vi cli.js
```
```js
import { bootstrap } from 'global-agent';
              
bootstrap();                        
console.log('should use proxy: ' + process.env.GLOBAL_AGENT_HTTP_PROXY);
```

But I still get this issue:

```
[08:49:24.616] ERROR: fetch failed

    err: {

      "type": "TypeError",

      "message": "fetch failed: getaddrinfo EAI_AGAIN registry.directus.io",

      "stack":

          TypeError: fetch failed

              at node:internal/deps/undici/undici:12618:11

              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

              at async function_ (file:///directus/node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:18:28)

              at async Ky._retry (file:///directus/node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:185:20)

              at async result.<computed> [as json] (file:///directus/node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:54:39)

              at async getApiVersion (file:///directus/node_modules/.pnpm/@directus+extensions-registry@file+packages+extensions-registry_@unhead+vue@1.9.9_vue@3.4.27__4szr23lbidsl7pxyyois4ajepu/node_modules/@directus/extensions-registry/dist/index.js:27:20)

              at async assertVersionCompatibility (file:///directus/node_modules/.pnpm/@directus+extensions-registry@file+packages+extensions-registry_@unhead+vue@1.9.9_vue@3.4.27__4szr23lbidsl7pxyyois4ajepu/node_modules/@directus/extensions-registry/dist/index.js:36:19)

              at async list (file:///directus/node_modules/.pnpm/@directus+extensions-registry@file+packages+extensions-registry_@unhead+vue@1.9.9_vue@3.4.27__4szr23lbidsl7pxyyois4ajepu/node_modules/@directus/extensions-registry/dist/index.js:239:3)

              at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/controllers/extensions.js:72:21

          caused by: Error: getaddrinfo EAI_AGAIN registry.directus.io

              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)

    }
```

I there any support planned or a solution you can provide?

### To Reproduce

Making sure that the requests called by undici are using any type of proxy.

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis/postgis:15-master

**Comment by Nitwel** [comment]
As we're currently having no plans on supporting proxies in Directus, I'll close this issue. It is only covering a small portion of adding general support for Proxies, so it's redundant to the general goal of Proxy support. Feel free to comment if you ever found a solution/workaround so others can find it as well.
