### ISSUE TITLE
Cockroach DB 24.2.4 migrations failing with new install

### ISSUE THREAD

**Issue by DavidOliver** [directus/directus#23903]
### Describe the Bug

The initial run of migrations is failing on a fresh 11.1.1 install when using CockroachDB (Cloud) with a fresh, empty database (at Koyeb).

```
Instance created. Preparing to start...
Instance is starting... Waiting for health checks to pass.
[14:33:05.111] INFO: Initializing bootstrap...
[14:33:05.134] INFO: Installing Directus system tables...
[14:34:01.862] INFO: Running migrations...
[14:34:01.883] INFO: Applying Remove Collection Foreign Keys...
TCP health check failed on port 8055.
error: alter table "directus_fields" drop constraint "directus_fields_collection_foreign" - constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
    at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
    at TLSSocket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 165,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'errors.go',
  line: '356',
  routine: 'NewUndefinedConstraintError'
}
```

I'm using the `directus/directus:11.1.1` image.

My Koyeb environment variables:

```
ADMIN_EMAIL=***
ADMIN_PASSWORD=***
CACHE_AUTO_PURGE=true
CACHE_ENABLED=true
CACHE_STORE=memory
DB_CLIENT=cockroachdb
DB_CONNECTION_STRING=postgresql://***:***@***.***.cockroachlabs.cloud:26257/***?sslmode=verify-full
KEY=***
PUBLIC_URL=https://{{KOYEB_PUBLIC_DOMAIN}}
SECRET=***
STORAGE_LOCATIONS=s3
STORAGE_S3_BUCKET=***
STORAGE_S3_DRIVER=s3
STORAGE_S3_ENDPOINT=***
STORAGE_S3_KEY=***
STORAGE_S3_REGION=***
STORAGE_S3_SECRET=***
SYNCHRONIZATION_STORE=memory
```

Unlike with #22608, I'm seeing the error on the first migration.

Running in the same way with a Koyeb PostgreSQL database works.

(By the way, I don't know why the first migration is removing unique constraints, but I presume there's a good reason for that and it's intended.)

### To Reproduce

Follow [this Koyeb guide](https://www.koyeb.com/tutorials/how-to-deploy-directus-as-a-backend-as-a-service-baas-on-koyeb).

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

CockroachDB 24.2.4

**Comment by kevincam3** [comment]
I'm seeing the same issue with supabase.
