### ISSUE TITLE
Could not load the "sharp" module using the linuxmusl-arm64 runtime

### ISSUE THREAD

**Issue by Residufermente** [directus/directus#23922]
### Describe the Bug

Hello guys,

In one of my extensions, i have a npm package called [staticmaps](https://github.com/StephanGeorg/staticmaps), this library is based on [Sharp](https://sharp.pixelplumbing.com/).

My problem is that when i start my directus docker composer with this extension which uses staticmaps, i have an error :

```
test-directus-1  | [19:10:50.637] WARN: Couldn't register endpoint "testextension"
test-directus-1  | [19:10:50.641] WARN: Could not load the "sharp" module using the linuxmusl-arm64 runtime
test-directus-1  | undefined: Could not dynamically require "../src/build/Release/sharp-linuxmusl-arm64.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  | undefined: Could not dynamically require "../src/build/Release/sharp-wasm32.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  | undefined: Could not dynamically require "@img/sharp-linuxmusl-arm64/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  | undefined: Could not dynamically require "@img/sharp-wasm32/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  | Possible solutions:
test-directus-1  | - Ensure optional dependencies can be installed:
test-directus-1  |     npm install --include=optional sharp
test-directus-1  |     yarn add sharp --ignore-engines
test-directus-1  | - Ensure your package manager supports multi-platform installation:
test-directus-1  |     See https://sharp.pixelplumbing.com/install#cross-platform
test-directus-1  | - Add platform-specific dependencies:
test-directus-1  |     npm install --os=linux --libc=musl --cpu=arm64 sharp
test-directus-1  | - Consult the installation documentation:
test-directus-1  |     See https://sharp.pixelplumbing.com/install
test-directus-1  |     err: {
test-directus-1  |       "type": "Error",
test-directus-1  |       "message": "Could not load the \"sharp\" module using the linuxmusl-arm64 runtime\nundefined: Could not dynamically require \"../src/build/Release/sharp-linuxmusl-arm64.node\". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.\nundefined: Could not dynamically require \"../src/build/Release/sharp-wasm32.node\". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.\nundefined: Could not dynamically require \"@img/sharp-linuxmusl-arm64/sharp.node\". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.\nundefined: Could not dynamically require \"@img/sharp-wasm32/sharp.node\". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --libc=musl --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
test-directus-1  |       "stack":
test-directus-1  |           Error: Could not load the "sharp" module using the linuxmusl-arm64 runtime
test-directus-1  |           undefined: Could not dynamically require "../src/build/Release/sharp-linuxmusl-arm64.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  |           undefined: Could not dynamically require "../src/build/Release/sharp-wasm32.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  |           undefined: Could not dynamically require "@img/sharp-linuxmusl-arm64/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  |           undefined: Could not dynamically require "@img/sharp-wasm32/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
test-directus-1  |           Possible solutions:
test-directus-1  |           - Ensure optional dependencies can be installed:
test-directus-1  |               npm install --include=optional sharp
test-directus-1  |               yarn add sharp --ignore-engines
test-directus-1  |           - Ensure your package manager supports multi-platform installation:
test-directus-1  |               See https://sharp.pixelplumbing.com/install#cross-platform
test-directus-1  |           - Add platform-specific dependencies:
test-directus-1  |               npm install --os=linux --libc=musl --cpu=arm64 sharp
test-directus-1  |           - Consult the installation documentation:
test-directus-1  |               See https://sharp.pixelplumbing.com/install
test-directus-1  |               at pi (file:///directus/extensions/testextension/dist/index.js?t=1729883450614:1:148353)
test-directus-1  |               at file:///directus/extensions/testextension/dist/index.js?t=1729883450614:1:171677
test-directus-1  |               at ro (file:///directus/extensions/testextension/dist/index.js?t=1729883450614:1:175155)
test-directus-1  |               at file:///directus/extensions/testextension/dist/index.js?t=1729883450614:1:312219
test-directus-1  |               at file:///directus/extensions/testextension/dist/index.js?t=1729883450614:1:331418
test-directus-1  |               at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
test-directus-1  |               at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
test-directus-1  |               at async ExtensionManager.registerEndpointExtension (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/extensions/manager.js:469:42)
test-directus-1  |               at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/extensions/manager.js:426:25
test-directus-1  |               at async Promise.all (index 0)
test-directus-1  |     }


```

I have tried all the suggested fixes in the error message.
@w0kyj also suggested me to check this [issue](https://github.com/directus/directus/issues/20866) but is not related because i'm using node > 18.17

### To Reproduce

1. Create an new directus project
2. Create a new directus extension (mine is an endpoint extension) using create-directus-extension
3. cd into container's extension folder and `npm i staticmaps`
4. in the extension index.ts file paste this : 

```
import StaticMaps from 'staticmaps';

const map = new StaticMaps({
	width: 1000,
	height: 1000,
});

console.log(map);
```
5. Start the container

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite3

## Thank you for your time Directus team :)

**Comment by rijkvanzanten** [comment]
Not the first time native binaries are causing confusion/havoc here 😞
