### ISSUE TITLE
500 error on auth/sso

### ISSUE THREAD

**Issue by criscmaia** [directus/directus#2405]
# Bug Report

## Steps to Reproduce

1, LAMP ([Linux on WSL](https://medium.com/@ssharizal/how-to-install-lamp-stack-server-on-windows-subsystem-linux-wsl-windows-10-133419c22473))
2. sudo apt-get update && sudo apt-get upgrade
3. sudo apt-get install lamp-server^
4. Update etc/apache2/apache2.conf:
```
Servername localhost
AcceptFilter http none
```
5. MySQL removed as I had it on a server already
6. sudo apt-get install php-curl
7. VirtualHost configuration:
```
*:80                   localhost (/etc/apache2/sites-enabled/000-default.conf:1)
*:8080                 example.com (/etc/apache2/sites-enabled/000-default.conf:34)
```
8. git clone https://github.com/directus/directus.git
9. sudo chown www-data -R /var/www/directus
10. sudo chown www-data -R /var/www/directus/public/upload
11. Boilerplate System Database from /src/schema.sql

## Expected Behavior
Load http://localhost:8080/admin to get the configuration page

## Actual Behavior
It goes to the login page instead. Error message on the console:
![image](https://user-images.githubusercontent.com/9072422/61205886-187dd000-a6e9-11e9-996e-0dba39b66932.png)

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/9072422/61205931-2e8b9080-a6e9-11e9-8753-777ec9db2b60.png)

## Technical Details
Window 10 Enterprise 1903
WSL Ubuntu 18.04.02
Apache 2.4.29
PHP 7.2.19
MySQL

**Comment by rom-io** [comment]
same configuration, same issue on 3 separate installations

**Comment by rijkvanzanten** [comment]
Seeing you populated the database manually, "Load http://localhost:8080/admin to get the configuration page" is not expected to happen. 

Are there any PHP errors in either the `/logs` folder of the API or the server logs in general?

**Comment by rom-io** [comment]
> Are there any PHP errors in either the /logs folder of the API or the server logs in general?

I've deleted the instances, maybe @criscmaia still has logs.

My procedure as follows:
- Digital ocean LAMP droplet, Ubuntu 18.04.2 LTS, PHP 7.2.19, MySQL 5.7.26, Apache 2.4.29
- Setup mysql (mysql_secure_installation) new root password, create Directus database, username & pw. Grant privs, flush. Unbind address 127.0.0.1. Restart.
- Install php-curl, php-xml, php-imagick, php-cli, composer. Update.
- Enable rewrite, setup apache access as follow & restart:

```
<Directory /var/www>

    Options Indexes FollowSymLinks MultiViews

    AllowOverride All

    Order allow,deny

    allow from all

 </Directory>
```

- Download Directus via Git to /html, chown www-data -R /var/www/html/directus
- Composer Install Directus
- Setup HTTPS cert
- /public/admin to start set up.

Works fine with 190627A.

**Comment by JbalTero** [comment]
I also have this issue. I just followed `https://docs.directus.io/getting-started/installation.html#setup`

When it says "Navigate your browser to the App at /admin", this is what I got:

![image](https://user-images.githubusercontent.com/3615746/61226835-c6bf5f00-a755-11e9-99bf-0910a3dfc33d.png)

**Comment by rijkvanzanten** [comment]
@JbalTero Are there any PHP errors in either the /logs folder of the API or the server logs in general?

**Comment by JbalTero** [comment]
@rijkvanzanten in apache errors.log, this is what I get,

```
[Mon Jul 15 23:21:11.402192 2019] [php7:notice] [pid 408] [client 127.0.0.1:56905] PHP Notice:  Undefined index: settings in /redacted/absolute/path/to/web/root/src/core/Directus/Application/Application.php on line 145, referer: http://devlocal.redacted/admin/
[Mon Jul 15 23:21:11.509259 2019] [php7:notice] [pid 408] [client 127.0.0.1:56905] PHP Notice:  Undefined index: settings in /redacted/absolute/path/to/web/root/src/core/Directus/Application/Application.php on line 145, referer: http://devlocal.redacted/admin/
[Mon Jul 15 23:21:11.569340 2019] [php7:error] [pid 408] [client 127.0.0.1:56905] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/redacted/absolute/path/to/web/root/logs" could not be opened: failed to open stream: Is a directory in /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, 'Directus\\\\Except...', Array)\n#3 /redacted/absolute/path/to/web/root/src/core/Directus/Appli in /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: http://devlocal.redacted/admin/
```

php:
```
PHP 7.1.30-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:43:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by JbalTero** [comment]
@rijkvanzanten The /logs folder is empty

**Comment by savedario** [comment]
I have the same problem.
The first visit to /admin produces the same exception @criscmaia showed above.
After a manual install, I still cannot login but I get "Unhandled promise rejection 
Object { code: 3, message: "Unauthorized request" }" in the console.
I tried this:
- installing on local machine under localhost/directus
- on local machine under a locally defined domain (There are several other VirtualHost on the same machine)
- on a VPS under https (Which blocks loading of the fonts from http).
By doing some debugging, I've found exceptions raised because 'something' tries to write config/logs/api.log (yes, not under /logs) but with errors that /logs/api.log.
I'll gladly provide more info if needed.

**Comment by rijkvanzanten** [comment]
Here's your answer:

> The stream or file "/redacted/absolute/path/to/web/root/logs" could not be opened: failed to open stream

Try changing the owner of the folder to www-data:

```
chown -R www-data:www-data /redactred/absolute/path/to/web/root/logs
```

**Comment by savedario** [comment]
On my VPS /logs contains several:
[2019-07-15 15:34:15] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in <path_to_vhost_root>/src/helpers/app.php:270
The 'other' app.log has:
[2019-07-15 15:47:26] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException: Reading items from "directus_settings" collection was denied in <path_to_vhost_root>/src/core/Directus/Permissions/Acl.php:988
...
[2019-07-15 15:47:26] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException: Reading items from "directus_collections" collection was denied in <path_to_vhost_root>/src/core/Directus/Permissions/Acl.php:988
BTW: I cannot reproduce now, but one of the first errors I got was about being impossible to write /logs because it's a directory (as if the file name was missing).

**Comment by JbalTero** [comment]
@rijkvanzanten I already followed it before reporting but the same issue happened. I even tried to do `chmod -R 777 logs`

https://docs.directus.io/advanced/requirements.html#permissions

**Comment by JbalTero** [comment]
@savedario probably related to my logs above

**Comment by dapertutto** [comment]
Concerning this error:

> PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/redacted/absolute/path/to/web/root/logs" could not be opened: failed to open stream: Is a directory in /redacted/absolute/path/to/web/root/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0

The error is in 
[src/core/Directus/Application/CoreServicesProvider.php](https://github.com/directus/directus/blob/master/src/core/Directus/Application/CoreServicesProvider.php)
on 133 line:
`$path . '/' . sprintf($filenameFormat, strtolower($name), date('Y-m-d'));`
must be changed to
`$path .= '/' . sprintf($filenameFormat, strtolower($name), date('Y-m-d'));`

But still after clean install and fixin logs issue I got error log entry:
> api[_].ERROR: Directus\Exception\NotInstalledException: This Directus API instance has not been configured. Install via the Directus App (eg: /admin) or read more about configuration at: https://docs.directus.io/     +++getting-started/installation.html#configure in /vagrant/sites/directus/src/core/Directus/Application/ErrorHandlers/NotInstalledNotFoundHandler.php:21

which is nonsense because /admin page shows sign in dialog and no prompts to to complete configuration.

**Comment by dapertutto** [comment]
And here is our culprit for unfinished configuration:
[src/core/Directus/Application/Application.php](https://github.com/directus/directus/blob/master/src/core/Directus/Application/Application.php):145
`'settings' => $appConfig['settings'],`
should be something like:
`'settings' => !empty($appConfig['settings']) ? $appConfig['settings'] : null,`

**Comment by savedario** [comment]
There are a couple of other issues. I can install now, but still cannot login afterwards.
The fix above about $path does not work, it should be:
```
                if ($path !== "php://stdout" && $path !== "php://stderr") {
                    $logPath = $path .'/' . sprintf($filenameFormat, strtolower($name), date('Y-m-d'));
                } else {
                    $logPath = $path;
                }
                $handler = new StreamHandler(
                    $logPath,
                    $level,
                    false
                );
```
and the default configuration schema should have:
```
        if ($isEnv) {
            $loggerPath = "php://stdout";
        } else {
            $loggerPath = __DIR__ . '/../../../../../logs';
        }
```

I will try to gather the fixes in a PR, but perhaps I'll wait after the first login actually works.

**Comment by dapertutto** [comment]
@savedario 
> The fix above about $path does not work, it should be

Well, it works but creates unnecessary directory structure. And considering [commit 190709A](https://github.com/directus/directus/commit/a1620f18dcb55a07d8befa5721d1131ee213692b) changes there should be variable to pass to StreamHandler other then `$path`. Like you proposed.
