### ISSUE TITLE
Directus MariaDB uprade issues

### ISSUE THREAD

**Issue by rybber78** [directus/directus#24054]
### Describe the Bug

Have 11.1.1 running using MariaDB. Works perfectly. But when I upgrade to versions 11.1.2  and 11.2.x using Docker, I get this error. If I delete directus_comments table, it will throw another error.:

```
Error: create table `directus_comments` (`id` char(36) not null, `collection` varchar(64) not null, `item` varchar(255) not null, `comment` text not null, `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) default character set utf8mb4 - Table 'directus_comments' already exists
    at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'directus_comments' already exists",
  sql: 'create table `directus_comments` (`id` char(36) not null, `collection` varchar(64) not null, `item` varchar(255) not null, `comment` text not null, `date_created` timestamp default CURRENT_TIMESTAMP, `date_updated` timestamp default CURRENT_TIMESTAMP, `user_created` char(36), `user_updated` char(36), primary key (`id`)) default character set utf8mb4'
}
```

### To Reproduce

Use 11.1.1, upgrade to 11.1.2  and 11.2.x

### Directus Version

11.2.x

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB docker

**Comment by ComfortablyCoding** [comment]
What is the error you receive if the table does not exist (i.e. the first time the migrations are run)?

**Comment by qparis** [comment]
Same problem. And I cannot rollback to a previous version. The error:

Error: alter table `directus_comments` add constraint `directus_comments_collection_foreign` foreign key (`collection`) references `directus_collections` (`collection`) on delete CASCADE - Can't create table `xxx`.`directus_comments` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlState: 'HY000',
  sqlMessage: 'Can\'t create table `xxx`.`directus_comments` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sql: 'alter table `directus_comments` add constraint `directus_comments_collection_foreign` foreign key (`collection`) references `directus_collections` (`collection`) on delete CASCADE'
}

**Comment by qparis** [comment]
Indeed it is. I also had problems with 10.13.2 where M2A relations would not create. This is why I tried updating in a first place. 
After some investigation, I found out that my databases was using utf8mb3 charsets while directus started to create utf8mb4 tables & fields. 
After wiping and reimporting a backup of my whole database with the right charset, M2A relations seems to work again with 10.13.2. 
I haven't tried to update to 11.2.x yet, but I no longer see any reason it would not work

**Comment by rybber78** [comment]
> What is the error received if the table does not exist (i.e. the first time the migrations are run)?

`[18:38:27.197] INFO: Applying Separate Comments...

Error: alter table `directus_comments` add constraint `directus_comments_collection_foreign` foreign key (`collection`) references `directus_collections` (`collection`) on delete CASCADE - Can't create table `directus`.`directus_comments` (errno: 150 "Foreign key constraint is incorrectly formed")

    at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packets/packet.js:738:17)

    at Query.execute (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/commands/command.js:29:26)

    at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:481:34)

    at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:97:12)

    at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.11.3/node_modules/mysql2/lib/connection.js:104:25)

    at Socket.emit (node:events:517:28)

    at addChunk (node:internal/streams/readable:368:12)

    at readableAddChunk (node:internal/streams/readable:341:9)

    at Readable.push (node:internal/streams/readable:278:10) {

  code: 'ER_CANT_CREATE_TABLE',

  errno: 1005,

  sqlState: 'HY000',

  sqlMessage: 'Can\'t create table `directus`.`directus_comments` (errno: 150 "Foreign key constraint is incorrectly formed")',

  sql: 'alter table `directus_comments` add constraint `directus_comments_collection_foreign` foreign key (`collection`) references `directus_collections` (`collection`) on delete CASCADE'

}`

**Comment by rybber78** [comment]
All tables are:  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci, still same error

**Comment by hanneskuettner** [comment]
What charset is the new `directus_comments` table?

**Comment by rybber78** [comment]
> What charset is the new `directus_comments` table?

Whole DB is UTF8MB4_BIN

**Comment by huhongbo** [comment]
I encounter the problem ,and  I found out that alter the database to utf8mb4general_ci will bypass the problem

**Comment by rybber78** [comment]
> > What charset is the new `directus_comments` table?
> 
> Whole DB is UTF8MB4_BIN

directus_comments is utf8mb4_unicode_ci

**Comment by rybber78** [comment]
> I encounter the problem ,and I found out that alter the database to utf8mb4general_ci will bypass the problem

I can confirm. Did search and replace in SQL file and changed all tables to utf8mb4_general_ci and it worked straight away with directus:latest docker tag, which is 11.2.1 right now.

Is there any downsides of using this charset (non-English language in tables with extra letters)?

**Comment by huhongbo** [comment]
I just alter the database to utf8mb4_general_ci and not all the table, and it worked, I think you can alter the database back to utf8mb4_unicode_ci after the upgrade. The alter action  just effect the new table or field
