### ISSUE TITLE
directus_comments improper types produces Error 500

### ISSUE THREAD

**Issue by Pachat** [directus/directus#24125]
### Describe the Bug

```
/users/me?fields=id,role.id 304 60ms produces

pg_container_db  | 2024-12-02 21:06:04.683 UTC [44] ERROR:  operator does not exist: uuid = text at character 203
pg_container_db  | 2024-12-02 21:06:04.683 UTC [44] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
pg_container_db  | 2024-12-02 21:06:04.683 UTC [44] STATEMENT:  select count("directus_comments"."id") as "count->id" from "directus_comments" where (("directus_comments"."collection" = $1 and "directus_comments"."item" = $2) and ("directus_comments"."user_created" = $2)) limit $3
directus_db      | [21:06:04.690] ERROR: select count("directus_comments"."id") as "count->id" from "directus_comments" where (("directus_comments"."collection" = $1 and "directus_comments"."item" = $2) and ("directus_comments"."user_created" = $2)) limit $3 - operator does not exist: uuid = text
directus_db      |     err: {
directus_db      |       "type": "DatabaseError",
directus_db      |       "message": "select count(\"directus_comments\".\"id\") as \"count->id\" from \"directus_comments\" where ((\"directus_comments\".\"collection\" = $1 and \"directus_comments\".\"item\" = $2) and (\"directus_comments\".\"user_created\" = $2)) limit $3 - operator does not exist: uuid = text",
directus_db      |       "stack":
directus_db      |           error: select count("directus_comments"."id") as "count->id" from "directus_comments" where (("directus_comments"."collection" = $1 and "directus_comments"."item" = $2) and ("directus_comments"."user_created" = $2)) limit $3 - operator does not exist: uuid = text
directus_db      |               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:283:98)
directus_db      |               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:122:29)
directus_db      |               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:35:38)
directus_db      |               at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/index.js:11:42)
directus_db      |               at Socket.emit (node:events:517:28)
directus_db      |               at addChunk (node:internal/streams/readable:368:12)
directus_db      |               at readableAddChunk (node:internal/streams/readable:341:9)
directus_db      |               at Readable.push (node:internal/streams/readable:278:10)
directus_db      |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus_db      |       "length": 197,
directus_db      |       "name": "error",
directus_db      |       "severity": "ERROR",
directus_db      |       "code": "42883",
directus_db      |       "hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
directus_db      |       "position": "203",
directus_db      |       "file": "parse_oper.c",
directus_db      |       "line": "647",
directus_db      |       "routine": "op_error"
directus_db      |     }
```

### To Reproduce

Just click on the avatar at the bottom left

### Directus Version

v11.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by licitdev** [comment]
Reused bindings for different column types caused this issue on PG.

`select count("directus_comments"."id") as "count->id" from "directus_comments" where (("directus_comments"."collection" = $1 and "directus_comments"."item" = $2) and ("directus_comments"."user_created" = $2)) limit $3`

Binding `$2` is the issue here as it's both a `string` comparison for `directus_comments.item` but a `uuid` comparison for `directus_comments.user_created`.

Related PRs: https://github.com/directus/directus/pull/24027, https://github.com/directus/directus/pull/23453

**Comment by Pachat** [comment]
This bug makes the execution of my panel.vue fail.
As I don't use `directus_comments` at all, and as this collection is stated for some reasons as `Required for App access` preventing to set permissions to None, i use the following trick to have the panel.vue working until this bug is fixed:
I changed the `id` type from `uuid` to `integer` in `directus_comments` right in the PostgreSQL DB.

**Comment by Pachat** [comment]
This error prevents to go further than 11.2.0

**Comment by Pachat** [comment]
This error prevents to go further than 11.2.0

**Comment by rijkvanzanten** [comment]
@licitdev Both https://github.com/directus/directus/pull/24027 and  https://github.com/directus/directus/pull/23453 shipped. Is this resolved?

**Comment by ComfortablyCoding** [comment]
> @licitdev Both https://github.com/directus/directus/pull/24027 and  https://github.com/directus/directus/pull/23453 shipped. Is this resolved?

It is not, this is still an issue due to our de-duplication of bindings.

**Comment by jaads** [comment]
I set up a new postgres database, created a collection, added an item and comment on it.
When I make this GET request `/users/me?fields=id,role.id` the following request to the API: 

```json
{
    "data": {
        "id": "1398e06c-b45b-49c3-9959-112caf8d019a",
        "role": {
            "id": "8c2196e6-1272-46a2-9a1b-b2eed789ade8"
        }
    }
}
```
Also when I do this GET request `/permissions/me/directus_users/1398e06c-b45b-49c3-9959-112caf8d019a`. I get
```json
{
    "data": {
        "update": {
            "access": true
        },
        "delete": {
            "access": true
        },
        "share": {
            "access": true
        }
    }
}
```

Am I missing something or is the issue resolved in the meantime? @Pachat

**Comment by ComfortablyCoding** [comment]
> I set up a new postgres database, created a collection, added an item and comment on it. When I make this GET request `/users/me?fields=id,role.id` the following request to the API:
> 
> {
>     "data": {
>         "id": "1398e06c-b45b-49c3-9959-112caf8d019a",
>         "role": {
>             "id": "8c2196e6-1272-46a2-9a1b-b2eed789ade8"
>         }
>     }
> }
> Also when I do this GET request `/permissions/me/directus_users/1398e06c-b45b-49c3-9959-112caf8d019a`. I get
> 
> {
>     "data": {
>         "update": {
>             "access": true
>         },
>         "delete": {
>             "access": true
>         },
>         "share": {
>             "access": true
>         }
>     }
> }
> Am I missing something or is the issue resolved in the meantime? [@Pachat](https://github.com/Pachat)

You must to be logged in as a non-admin user for the query to result in the reported error. Admin accounts to not have the comparison restriction that 

https://github.com/user-attachments/assets/d6487ddb-0eb4-4b40-bba5-63696f7ffde1
