### ISSUE TITLE
MariaDB Install not working, with empty DB. `pnpm --filter api cli bootstrap`

### ISSUE THREAD

**Issue by MCl57** [directus/directus#24139]
### Describe the Bug

An error occurred while executing the command `pnpm --filter api cli bootstrap`. The database was empty. Previously, the following commands were executed:
```bash
git clone <repository-url>
pnpm install
pnpm build
```
**Log:**
```
PS C:\work\Directus\directus> pnpm --filter api cli bootstrap

> @directus/api@23.2.1 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

[22:41:40.009] INFO: Initializing bootstrap...
[22:41:40.020] INFO: Installing Directus system tables...
[22:41:41.794] INFO: Running migrations...
[22:41:41.813] INFO: Applying Remove Collection Foreign Keys...
[22:41:42.043] INFO: Applying Remove System Relations...
[22:41:42.060] INFO: Applying Remove System Collections...
[22:41:42.079] INFO: Applying Remove System Fields...
[22:41:42.095] INFO: Applying Add Cascade System Relations...
[22:41:43.997] INFO: Applying Change Webhook URL Type...
[22:41:44.077] INFO: Applying Add Relations Sort Field...
[22:41:44.149] INFO: Applying Remove Locked Fields...
[22:41:44.222] INFO: Applying Webhooks Collections Text...
[22:41:44.321] INFO: Applying Add Refresh Interval...
[22:41:44.393] INFO: Applying Make Filesize Nullable...
[22:41:44.541] INFO: Applying Add Collections Accountability...
[22:41:44.613] INFO: Applying Remove Files Interface...
[22:41:44.631] INFO: Applying Rename Interfaces...
[22:41:44.693] INFO: Applying Restructure Relations...
[22:41:45.096] INFO: Applying Add Foreign Key Constraints...
[22:41:45.241] INFO: Applying Add System Fk Triggers...
[22:41:46.525] INFO: Applying Add Collections Icon Color...
[22:41:46.560] INFO: Applying Add Insights...
[22:41:46.793] INFO: Applying Add Deep Clone Config...
[22:41:46.834] INFO: Applying Change Filesize Bigint...
[22:41:46.910] INFO: Applying Add Conditions to Fields...
[22:41:46.951] INFO: Applying Add Default Folder...
[22:41:47.073] INFO: Applying Replace Groups...
[22:41:47.090] INFO: Applying Add Required to Fields...
[22:41:47.128] INFO: Applying Update Groups...
[22:41:47.144] INFO: Applying Change Image Metadata Structure...
[22:41:47.161] INFO: Applying Add Geometry Config...
[22:41:47.204] INFO: Applying Remove Limit Column...
[22:41:47.253] INFO: Applying Add Auth Provider...
[22:41:47.488] INFO: Applying Webhooks Collections Not Null...
[22:41:47.550] INFO: Applying Move Module Setup...
[22:41:47.621] INFO: Applying Webhooks URL Not Null...
[22:41:47.681] INFO: Applying Add Collection Organization...
[22:41:47.774] INFO: Applying Replace Fields Group...
[22:41:47.883] INFO: Applying Replace M2M Interface...
[22:41:47.896] INFO: Applying Rename Login Action...
[22:41:47.908] INFO: Applying Update Presets...
[22:41:47.988] INFO: Applying Add Auth Data...
[22:41:48.024] INFO: Applying Add Webhook Headers...
[22:41:48.060] INFO: Applying Set Unique to User Token...
[22:41:48.106] INFO: Applying Update Special Geometry...
[22:41:48.119] INFO: Applying Remove Collections Listing...
[22:41:48.163] INFO: Applying Add Notifications...
[22:41:48.352] INFO: Applying Add Shares...
Error: alter table `directus_sessions` modify  `user` char(36) null  - Got error 42 "No message of desired type" from storage engine InnoDB
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_GET_ERRNO',
  errno: 1030,
  sqlState: 'HY000',
  sqlMessage: 'Got error 42 "No message of desired type" from storage engine InnoDB',
  sql: 'alter table `directus_sessions` modify  `user` char(36) null '
}
```
**again:**
```
C:\work\Directus\directus\api:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/api@23.2.1 cli: `NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"`
Exit status 1
PS C:\work\Directus\directus> pnpm --filter api cli bootstrap

> @directus/api@23.2.1 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

[22:43:15.270] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[22:43:15.285] INFO: Initializing bootstrap...
[22:43:15.292] INFO: Database already initialized, skipping install
[22:43:15.293] INFO: Running migrations...
[22:43:15.307] INFO: Applying Add Shares...
Error: create table `directus_shares` (`id` char(36) not null, `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp null, `date_end` timestamp null, `times_used` int default '0', `max_uses` int, primary key (`id`)) - Table 'directus_shares' already exists
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'directus_shares' already exists",
  sql: "create table `directus_shares` (`id` char(36) not null, `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp null, `date_end` timestamp null, `times_used` int default '0', `max_uses` int, primary key (`id`))"
}
```

**again:**
```
C:\work\Directus\directus\api:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/api@23.2.1 cli: `NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"`
Exit status 1
PS C:\work\Directus\directus> pnpm --filter api cli bootstrap

> @directus/api@23.2.1 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

[22:43:55.935] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[22:43:55.945] INFO: Initializing bootstrap...
[22:43:55.952] INFO: Database already initialized, skipping install
[22:43:55.953] INFO: Running migrations...
[22:43:55.968] INFO: Applying Add Shares...
Error: create table `directus_shares` (`id` char(36) not null, `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp null, `date_end` timestamp null, `times_used` int default '0', `max_uses` int, primary key (`id`)) - Table 'directus_shares' already exists
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'directus_shares' already exists",
  sql: "create table `directus_shares` (`id` char(36) not null, `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp null, `date_end` timestamp null, `times_used` int default '0', `max_uses` int, primary key (`id`))"
}
C:\work\Directus\directus\api:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/api@23.2.1 cli: `NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"`
Exit status 1

```

### To Reproduce

```
####################################################################################################
## General
ADMIN_EMAIL=xxx
ADMIN_PASSWORD=xxx


PORT=8055
PUBLIC_URL="http://localhost:8055"

####################################################################################################
## Database
DB_CLIENT=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=directusdb
DB_USER=directus
DB_PASSWORD=mariadb


####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="xxx"
SECRET="xxx"


ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"
EXTENSIONS_AUTO_RELOAD=true
```

### Directus Version

v11.3.1 origin/main #24128

### Hosting Strategy

Self-Hosted (Custom)

### Database

11.6.2-MariaDB-ubu2404

**Comment by rijkvanzanten** [comment]
Mind trying it against v11.3.2? I believe this might be the same underlying thing as https://github.com/directus/directus/pull/24134

**Comment by licitdev** [comment]
I could not reproduce this issue using your env and `MariaDB-11.6.2` docker image. 🤔 I'm wondering if this issue could be specific to the OS. How are you running your database?

**Comment by MCl57** [comment]
Database is a docker installation 11.6.2 mariadb:latest. 
`CREATE DATABASE `directusdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */;`

**Comment by licitdev** [comment]
What's the OS that's running Directus locally? I've tested on macOS using the mariaDB 11.6.2 docker container and the SQL command above, but could not reproduce this issue.

**Comment by MCl57** [comment]
PowerShell Windows 10
```
PS C:\work\Directus\directus> pnpm --version
9.14.4
PS C:\work\Directus\directus> node --version
v18.20.5
PS C:\work\Directus\directus> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
PS C:\work\Directus\directus> cmd
Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. Alle Rechte vorbehalten.
```

the messages are not the same?
```
 pnpm --filter api cli bootstrap

> @directus/api@23.2.2 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

[08:22:18.998] INFO: Initializing bootstrap...
[08:22:19.008] INFO: Installing Directus system tables...
[08:22:24.893] INFO: Running migrations...
[08:22:24.953] INFO: Applying Remove Collection Foreign Keys...
[08:22:25.638] INFO: Applying Remove System Relations...
[08:22:25.661] INFO: Applying Remove System Collections...
[08:22:25.697] INFO: Applying Remove System Fields...
[08:22:25.878] INFO: Applying Add Cascade System Relations...
[08:22:31.932] INFO: Applying Change Webhook URL Type...
[08:22:32.037] INFO: Applying Add Relations Sort Field...
[08:22:32.131] INFO: Applying Remove Locked Fields...
[08:22:32.217] INFO: Applying Webhooks Collections Text...
[08:22:32.317] INFO: Applying Add Refresh Interval...
[08:22:32.391] INFO: Applying Make Filesize Nullable...
[08:22:32.556] INFO: Applying Add Collections Accountability...
[08:22:32.627] INFO: Applying Remove Files Interface...
[08:22:32.652] INFO: Applying Rename Interfaces...
[08:22:32.731] INFO: Applying Restructure Relations...
[08:22:33.145] INFO: Applying Add Foreign Key Constraints...
[08:22:37.506] INFO: Applying Add System Fk Triggers...
[08:22:40.287] INFO: Applying Add Collections Icon Color...
[08:22:40.372] INFO: Applying Add Insights...
[08:22:40.885] INFO: Applying Add Deep Clone Config...
[08:22:40.965] INFO: Applying Change Filesize Bigint...
[08:22:41.125] INFO: Applying Add Conditions to Fields...
[08:22:41.243] INFO: Applying Add Default Folder...
[08:22:41.477] INFO: Applying Replace Groups...
[08:22:41.500] INFO: Applying Add Required to Fields...
[08:22:41.585] INFO: Applying Update Groups...
[08:22:41.611] INFO: Applying Change Image Metadata Structure...
[08:22:41.636] INFO: Applying Add Geometry Config...
[08:22:41.721] INFO: Applying Remove Limit Column...
[08:22:41.815] INFO: Applying Add Auth Provider...
[08:22:42.388] INFO: Applying Webhooks Collections Not Null...
[08:22:42.501] INFO: Applying Move Module Setup...
[08:22:42.640] INFO: Applying Webhooks URL Not Null...
[08:22:42.743] INFO: Applying Add Collection Organization...
[08:22:42.947] INFO: Applying Replace Fields Group...
[08:22:43.134] INFO: Applying Replace M2M Interface...
[08:22:43.157] INFO: Applying Rename Login Action...
[08:22:43.189] INFO: Applying Update Presets...
[08:22:43.324] INFO: Applying Add Auth Data...
[08:22:43.388] INFO: Applying Add Webhook Headers...
[08:22:43.449] INFO: Applying Set Unique to User Token...
[08:22:43.543] INFO: Applying Update Special Geometry...
[08:22:43.559] INFO: Applying Remove Collections Listing...
[08:22:43.641] INFO: Applying Add Notifications...
[08:22:43.982] INFO: Applying Add Shares...
Error: alter table `directus_sessions` modify  `user` char(36) null  - Got error 42 "No message of desired type" from storage engine InnoDB
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_GET_ERRNO',
  errno: 1030,
  sqlState: 'HY000',
  sqlMessage: 'Got error 42 "No message of desired type" from storage engine InnoDB',
  sql: 'alter table `directus_sessions` modify  `user` char(36) null '
}
```
