### ISSUE TITLE
Upgrade from 10.4.0 to 11.3.2 ( MarketPlace Extension)

### ISSUE THREAD

**Issue by silveryahoo** [directus/directus#24174]
### Describe the Bug

Unable to upgrade to 11.3.2.

I am unable to upgrade from 10.4 to 11.3.2 due to this error.

```
[9/Dec/2024:06:46:37] [06:46:37.479] INFO: Applying Marketplace...
[9/Dec/2024:06:46:37] RequestError: ALTER TABLE [directus_extensions] ADD [id] uniqueidentifier null, [folder] nvarchar(255), [source] nvarchar(255), [bundle] uniqueidentifier - Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once.
[9/Dec/2024:06:46:37] at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/handler.js:286:21)
[9/Dec/2024:06:46:37] at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@18.2.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
[9/Dec/2024:06:46:37] at Readable.emit (node:events:517:28)
[9/Dec/2024:06:46:37] at addChunk (node:internal/streams/readable:368:12)
[9/Dec/2024:06:46:37] at readableAddChunk (node:internal/streams/readable:341:9)
[9/Dec/2024:06:46:37] at Readable.push (node:internal/streams/readable:278:10)
[9/Dec/2024:06:46:37] at next (node:internal/streams/from:98:31)
[9/Dec/2024:06:46:37] at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[9/Dec/2024:06:46:37] code: 'EREQUEST',
[9/Dec/2024:06:46:37] number: 2705,
[9/Dec/2024:06:46:37] state: 4,
[9/Dec/2024:06:46:37] class: 16,
[9/Dec/2024:06:46:37] serverName: 'moandbear-uat-db',
[9/Dec/2024:06:46:37] procName: '',
[9/Dec/2024:06:46:37] lineNumber: 1
[9/Dec/2024:06:46:37] }
```

I have tried multiple steps from previous issues that has been raised here such as dropping the table and recreating it with the query that they have sent which i have successfully updated the system to 10.9.0 but when i try to update to 10.10.0 or higher, i still keep getting this issue. 

As far as i have recall this has been patch based on the PR request done few months ago but issue seems to be still happening

### To Reproduce

Upgrade from 10.4.0 to 11.3.2

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MSSQL

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the information provided. Installed Directus `v10.4.1` fresh on MSSQL Server 2019, updated to `latest` (11.3.2 at time of writing), and ran bootstrap. Upgraded without issue. If possible, mind sharing a database dump of a reproduction where this issue happens? Thanks!

**Comment by silveryahoo** [comment]
@rijkvanzanten ill back up the database and compress it.

Where should i send it?

**Comment by rijkvanzanten** [comment]
Either here in the thread if it's a new minimal reproduction. If there's stuff in there you don't to share publicly you can send it to me directly on rijk@directus.io 🙂
