### ISSUE TITLE
Breaking Change, Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

### ISSUE THREAD

**Issue by robsoncombr** [directus/directus#24198]
### Describe the Bug

Getting @import rules deprecation warnings when running in development mode:

_Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0._

Need to migrate from @import rules to avoid break changes starting with Dart Sass 3.0.0.

Refer to [Breaking Change: `@import` and global built-in functions](https://sass-lang.com/documentation/breaking-changes/import/)

An automatic migration package was created to assist on fixing, that really helps, refer to:
[sass-migrator Reference from breaking-changes](https://sass-lang.com/documentation/breaking-changes/import/#automatic-migration)
[sass-migrator at Github](https://github.com/sass/migrator#readme)
[sass-migrator at npm](https://www.npmjs.com/package/sass-migrator)
[sass-migrator Documentation](https://sass-lang.com/documentation/cli/migrator/)

### To Reproduce

Running Directus in development mode, access the admin and check the container logs, it will output one warning for each @import, as below:

`[20:59:53.021] INFO: Server started at http://0.0.0.0:8055
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import 'base';
  │         ^^^^^^
  ╵
    /directus/app/src/styles/main.scss 1:9  root stylesheet`

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.6 (not applicable)

**Comment by robsoncombr** [comment]
# First Attempt to Fix

I am attempting to resolve the SCSS migration issue. Below are the steps I took to approach the problem.

---

### Step 1: Install `sass-migrator`

```bash
npm install -g sass-migrator
```

**Output:**
```text
added 1 package in 1s
```

---

### Step 2: Locate SCSS Files Containing `@import`

```bash
find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
```

**Output:**
```text
./app/src/styles/lib/_flatpickr.scss
./app/src/styles/_colors.scss
./app/src/styles/_type-styles.scss
./app/src/styles/main.scss
./app/src/styles/_base.scss
```

---

### Step 3: Run `sass-migrator` on Main SCSS File

```bash
sass-migrator module --migrate-deps ./app/src/styles/main.scss
```

---

### Step 4: Check for Remaining `@import` Statements

```bash
find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
```

**Output:**
```text
./app/src/styles/lib/_flatpickr.scss
```

---

### Step 5: Run `sass-migrator` on Specific File

```bash
sass-migrator module --migrate-deps ./app/src/styles/lib/_flatpickr.scss
```

**Output:**
```text
Nothing to migrate!
```

---

### Observations:
It seems I might be facing the issue described in [Gracefully handle members that are already pseudo-private #48](https://github.com/sass/migrator/issues/48). To ensure nothing is left behind, I decided to manually update the file.

---

### Step 6: Manually Replace `@import` with `@use`

```bash
sed -i 's/@import/@use/g' ./app/src/styles/lib/_flatpickr.scss
```

---

### Step 7: Verify All `@import` Statements are Removed

```bash
find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
```

**Output:**
```text
(no output, all imports resolved)
```

---

### Step 8: Uninstall `sass-migrator`

```bash
npm remove -g sass-migrator
```

**Output:**
```text
removed 1 package in 935ms
```

---

## Next Steps

Re-build and test the altered code.

**Comment by robsoncombr** [comment]
Well while building first time seems that I got circular dependency.

```
ubuntu@oci-sampa-n0:~/production/robson-directus$ grep @use app/src/styles/themes -R | grep colors
app/src/styles/themes/_light.scss:@use "../colors";
app/src/styles/themes/_light.scss:@use "mixins/generate-colors";
app/src/styles/themes/mixins/generate-colors.scss:@use "sass:color";
app/src/styles/themes/mixins/generate-colors.scss:@use "sass:math";
app/src/styles/themes/mixins/generate-colors.scss:@use "../../colors";
app/src/styles/themes/_dark.scss:@use "../colors";
app/src/styles/themes/_dark.scss:@use "mixins/generate-colors";
```

Build error:

```
app build$ vite build
│ vite v5.4.10 building for production...
│ transforming...
│ ✓ 751 modules transformed.
│ x Build failed in 2.34s
│ error during build:
│ [vite:css] [sass] Error: Module loop: this module is already being loaded.
│   ┌──> /directus/app/src/styles/themes/mixins/generate-colors.scss
│ 3 │ @use "../../colors";
│   │ ^^^^^^^^^^^^^^^^^^^ new load
│   ╵
│   ┌──> /directus/app/src/styles/main.scss
│ 2 │ @use 'colors';
│   │ ━━━━━━━━━━━━━ original load
│   ╵
│   /directus/app/src/styles/themes/mixins/generate-colors.scss 3:1  @use
│   /directus/app/src/styles/_colors.scss 1:1                        @use
│   /directus/app/src/styles/main.scss 2:1                           root stylesheet
│ file: /directus/app/src/styles/main.scss
│     at handleCompileResponse (/directus/node_modules/.pnpm/sass-embedded@1.80.3/node_modules/sass-embedded/dist/lib/src/compiler/utils.js:158:15)
│     at AsyncCompiler.compileRequestAsync (/directus/node_modules/.pnpm/sass-embedded@1.80.3/node_modules/sass-embedded/dist/lib/src/compiler/async.js:70:54)
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Object.run (file:///directus/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.5_sass-embedded@1.80.3_sass@1.79.4_terser@5.31.6/node_modules/vite/dist/node/chunks…
│     at async process (file:///directus/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.5_sass-embedded@1.80.3_sass@1.79.4_terser@5.31.6/node_modules/vite/dist/node/chunks/de…
│     at async compileCSSPreprocessors (file:///directus/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.5_sass-embedded@1.80.3_sass@1.79.4_terser@5.31.6/node_modules/vite/dis…
│     at async compileCSS (file:///directus/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.5_sass-embedded@1.80.3_sass@1.79.4_terser@5.31.6/node_modules/vite/dist/node/chunks…
│     at async Object.transform (file:///directus/node_modules/.pnpm/vite@5.4.10_@types+node@22.7.5_sass-embedded@1.80.3_sass@1.79.4_terser@5.31.6/node_modules/vite/dist/node/…
│     at async transform (file:///directus/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18830:16)
│     at async ModuleLoader.addModuleSource (file:///directus/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19046:36)
└─ Failed in 3.5s at /directus/app
/directus/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/app@13.3.6 build: `vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by robsoncombr** [comment]
Remove circular uses:

```
ubuntu@oci-sampa-n0:~/production/robson-directus$ grep @use app/src/styles/themes -R | grep colors
app/src/styles/themes/_light.scss:@use "mixins/generate-colors";
app/src/styles/themes/mixins/generate-colors.scss:@use "sass:color";
app/src/styles/themes/mixins/generate-colors.scss:@use "sass:math";
app/src/styles/themes/mixins/generate-colors.scss:@use "../../colors";
app/src/styles/themes/_dark.scss:@use "mixins/generate-colors";
```

```
ubuntu@oci-sampa-n0:~/production/codi-directus$ git merge robson/fix-24198-sass-import-deprecation
Merge made by the 'ort' strategy.
 app/src/styles/themes/_dark.scss                  | 1 -
 app/src/styles/themes/_light.scss                 | 1 -
 app/src/styles/themes/mixins/generate-colors.scss | 2 +-
 3 files changed, 1 insertion(+), 3 deletions(-)
```

**Comment by robsoncombr** [comment]
Still getting problems, sounds like the circular uses was caused by the sass-migrator, will reset back to the first commit 422ddd4a09fd2ecc4ddcc97488d56e976618519e and start from that point.

**Comment by robsoncombr** [comment]
Current list of remaining build error regarding the @use migration.

```
$ pnpm --filter app build | grep "@import '@/"
2 │ @import '@/styles/mixins/no-wrap';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/components/v-checkbox.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/components/v-form/v-form.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/no-wrap';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/components/v-radio.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/export-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/no-wrap';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/render-template.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/layouts/cards/options.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/new-collection.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/flows/components/operation-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/presets/item.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/input-rich-text-md/input-rich-text-md.vue 2:9  root stylesheet

49 │         @import '@/styles/markdown';
   │                 ^^^^^^^^^^^^^^^^^^^
 /directus/app/src/interfaces/input-rich-text-md/input-rich-text-md.vue 49:11  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/map/options.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/list/options.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/translations/translations.vue 2:9  root stylesheet

68 │                 @import '@/styles/markdown';
   │                         ^^^^^^^^^^^^^^^^^^^
 /directus/app/src/views/private/components/notifications-drawer.vue 68:13  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/layout-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/flow-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/content/components/version-menu.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/shares-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/users-invite.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/basic-import-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/refresh-sidebar-detail.vue 2:9  root stylesheet

8 │         @import '@/styles/markdown';
  │                 ^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/marketplace/routes/extension/components/extension-readme.vue 8:11  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/flows/flow-drawer.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/archive-sidebar-detail.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/content/components/version-promote-drawer.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/fields/components/field-select.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-validation.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-field.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-configuration.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2a.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2m.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2o.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-o2m.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/relationship-configuration.vue 2:9  root stylesheet

2 │ @import '@/styles/mixins/form-grid';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-translations.vue 2:9  root stylesheet

3 │ @import '@/styles/mixins/no-wrap';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-translations.vue 3:9  root stylesheet

```

**Comment by robsoncombr** [comment]
Remaining:

`49 │         @import '@/styles/markdown';
   │                 ^^^^^^^^^^^^^^^^^^^
/directus/app/src/interfaces/input-rich-text-md/input-rich-text-md.vue 49:11  root stylesheet

68 │                 @import '@/styles/markdown';
   │                         ^^^^^^^^^^^^^^^^^^^
/directus/app/src/views/private/components/notifications-drawer.vue 68:13  root stylesheet

8 │         @import '@/styles/markdown';
  │                 ^^^^^^^^^^^^^^^^^^^
/directus/app/src/modules/settings/routes/marketplace/routes/extension/components/extension-readme.vue 8:11  root stylesheet`

**Comment by robsoncombr** [comment]
**I was able to build it without any error, I have tested and I was not able to find any problem, the deprecation warning is also gone.
This was really challenging, I'm not sure I did everything correctly and I don't think I can certify the standard from here on my own, etc. I would appreciate if you could help me. Thanks.**

---

` *  Executing task in folder ubuntu: docker exec -it 4fca7d354821b5a1dda9fb2c7a30c084d75d62c8d3ec595ccb204bd68f682d5d bash 

I have no name!@4fca7d354821:/directus$ pnpm --filter app build

> @directus/app@13.3.6 build /directus/app
> vite build

vite v5.4.10 building for production...
✓ 4422 modules transformed.
[plugin:vite:reporter] [plugin vite:reporter] 
(!) /directus/node_modules/.pnpm/date-fns@4.1.0/node_modules/date-fns/locale/en-US.js is dynamically imported by /directus/app/src/utils/get-date-fns-locale.ts but also statically imported by /directus/node_modules/.pnpm/date-fns@4.1.0/node_modules/date-fns/_lib/defaultLocale.js, dynamic import will not move module into another chunk.

[plugin:vite:reporter] [plugin vite:reporter] 
(!) /directus/app/src/lang/translations/en-US.yaml is dynamically imported by /directus/app/src/lang/set-language.ts but also statically imported by /directus/app/src/lang/index.ts, dynamic import will not move module into another chunk.

[plugin:vite:reporter] [plugin vite:reporter] 
(!) /directus/node_modules/.pnpm/codemirror@5.65.18/node_modules/codemirror/mode/markdown/markdown.js is dynamically imported by /directus/app/src/interfaces/input-code/import-codemirror-mode.ts but also statically imported by /directus/node_modules/.pnpm/codemirror@5.65.18/node_modules/codemirror/mode/markdown/markdown.js?commonjs-proxy, /directus/app/src/interfaces/input-rich-text-md/input-rich-text-md.vue?vue&type=script&setup=true&lang.ts, dynamic import will not move module into another chunk.

[plugin:vite:reporter] [plugin vite:reporter] 
(!) /directus/node_modules/.pnpm/codemirror@5.65.18/node_modules/codemirror/mode/javascript/javascript.js is dynamically imported by /directus/app/src/interfaces/input-code/import-codemirror-mode.ts, /directus/app/src/interfaces/input-code/input-code.vue?vue&type=script&setup=true&lang.ts but also statically imported by /directus/node_modules/.pnpm/codemirror@5.65.18/node_modules/codemirror/mode/javascript/javascript.js?commonjs-proxy, /directus/app/src/modules/settings/routes/system-logs/logs.vue?vue&type=script&setup=true&lang.ts, dynamic import will not move module into another chunk.

dist/index.html                                             1.83 kB │ gzip:     0.74 kB
dist/assets/FiraMono-Medium-CE-6Frqh.woff2                 16.15 kB
**_(.removed.)_**
dist/assets/index.yA6csgyz.entry.js                     6,013.85 kB │ gzip: 1,755.80 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 1m 10s `

**Comment by rijkvanzanten** [comment]
Live feed of @robsoncombr this holiday season:

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExemJib21xaDVjcHgwOXFtaXE2NzN5bjA2eXhhZmRidHNwNnkxeGUxZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XIqCQx02E1U9W/giphy.gif)

**Comment by kusaasira** [comment]
> # First Attempt to Fix
> I am attempting to resolve the SCSS migration issue. Below are the steps I took to approach the problem.
> 
> ### Step 1: Install `sass-migrator`
> npm install -g sass-migrator
> **Output:**
> 
> ```
> added 1 package in 1s
> ```
> 
> ### Step 2: Locate SCSS Files Containing `@import`
> find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
> **Output:**
> 
> ```
> ./app/src/styles/lib/_flatpickr.scss
> ./app/src/styles/_colors.scss
> ./app/src/styles/_type-styles.scss
> ./app/src/styles/main.scss
> ./app/src/styles/_base.scss
> ```
> 
> ### Step 3: Run `sass-migrator` on Main SCSS File
> sass-migrator module --migrate-deps ./app/src/styles/main.scss
> ### Step 4: Check for Remaining `@import` Statements
> find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
> **Output:**
> 
> ```
> ./app/src/styles/lib/_flatpickr.scss
> ```
> 
> ### Step 5: Run `sass-migrator` on Specific File
> sass-migrator module --migrate-deps ./app/src/styles/lib/_flatpickr.scss
> **Output:**
> 
> ```
> Nothing to migrate!
> ```
> 
> ### Observations:
> It seems I might be facing the issue described in [Gracefully handle members that are already pseudo-private #48](https://github.com/sass/migrator/issues/48). To ensure nothing is left behind, I decided to manually update the file.
> 
> ### Step 6: Manually Replace `@import` with `@use`
> sed -i 's/@import/@use/g' ./app/src/styles/lib/_flatpickr.scss
> ### Step 7: Verify All `@import` Statements are Removed
> find . -type f -name '*.scss' -exec grep -ql '@import' {} \; -exec echo {} \;
> **Output:**
> 
> ```
> (no output, all imports resolved)
> ```
> 
> ### Step 8: Uninstall `sass-migrator`
> npm remove -g sass-migrator
> **Output:**
> 
> ```
> removed 1 package in 935ms
> ```
> 
> ## Next Steps
> Re-build and test the altered code.

@robsoncombr you are a good person indeed!
