### ISSUE TITLE
Migrate Legacy Comments breaking fresh bootstrap

### ISSUE THREAD

**Issue by camboui** [directus/directus#24249]
### Describe the Bug

Migration "20240924A-migrate-legacy-comments" fails on a clean DB with

Error: alter table `directus_activity` drop `comment` - Can't DROP 'comment'; check that column/key exists
at Packet.asError (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
at Query.execute (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
at Connection.handlePacket (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
at PacketParser.onPacket (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
at PacketParser.executeStart (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
at Socket.<anonymous> (<HIDDEN_USER_DIRECTORY>\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
at Socket.emit (node:events:517:28)
at readableAddChunk (node:internal/streams/readable:341:9)
at Readable.push (node:internal/streams/readable:278:10) {
code: 'ER_CANT_DROP_FIELD_OR_KEY',
errno: 1091,
sqlState: '42000',
sqlMessage: "Can't DROP 'comment'; check that column/key exists",
sql: 'alter table `directus_activity` drop `comment`'
}

### To Reproduce

Run directus boostrap on a clean DB.

Wait for the "Migrate Legacy Comments" to be executed :
...
[13:29:35.222] INFO: Applying Migrate Legacy Comments...
Error: alter table `directus_activity` drop `comment` - Can't DROP 'comment'; check that column/key exists

### Directus Version

11.3.4

### Hosting Strategy

Self-Hosted (Custom)

### Database

mysql

**Comment by licitdev** [comment]
I am unable to reproduce this issue on a fresh MySQL DB.

**Comment by camboui** [comment]
Ok it seems that a custo migration made from  "import { snapshot } from '@directus/api/cli/commands/schema/snapshot';" ran before the migration and broke it.

Maybe i'm using migrations and snapshot the wrong way but it happens often that new directus versions have internal migrations timestamped around my custom ones. It then works perfectely on an already initialised DB but breaks on a fresh install as the migration order is different.

I'm closing the issue.
