### ISSUE TITLE
[INTERNAL_SERVER_ERROR] parentsByForeignKey.get is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by itsminani** [directus/directus#24257]
### Describe the Bug

Having issues with saving anything that references any o2m table or a separate table: I have uploaded screenshots

![image](https://github.com/user-attachments/assets/0063e29d-a788-4026-a928-1ccec041947e)
![image](https://github.com/user-attachments/assets/25a7d542-e87a-416a-9825-f876076c9860)

These used to properly work on the 17th of december

### To Reproduce

Any one to many dashboard seems to generate this issue for us

### Directus Version

v11.3.5

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment]
> These used to properly work on the 17th of december

Can you tell us the version of Directus this was working on? The most recent version at that point (v11.3.4) or some other version?

**Comment by hanneskuettner** [comment]
Looks this is happening in this line of code 

https://github.com/directus/directus/blob/99cd15f3a0e4962602d2476e4f678d7a36fb37a8/api/src/database/run-ast/utils/merge-with-parent-items.ts#L37

Which has been introduced in this PR https://github.com/directus/directus/pull/23907

It seems to be caused by the parent item missing for a foreign key in a nested item.

**Comment by hanneskuettner** [comment]
@itsminani can you identify which queries are causing this issue? You should be able to see them returning a 500 in your browsers network panel. Having these would help greatly at reproducing this issue on our end.

**Comment by semorur** [comment]
i have the same problem.

I have a tables with contacts, companies and a table with addresses
companies->adresses (one 2 many)
contacts->adresses (one 2 many)

in addresses table there are fields company_id and contact_id

the problem appears in ui when I go to addresses and trying to see company/contact name or any other information


in other cases where I have one 2 many everything works. the only difference i see that here addresses table has connections to more than one table (companies and contacts).

**Comment by itsminani** [comment]
@hanneskuettner Sorry for the delay, here are the specific querries:
![image](https://github.com/user-attachments/assets/33dce576-38ab-41d7-8798-3ac1789bd8ac)
![image](https://github.com/user-attachments/assets/71b662ba-1819-441e-92c9-de55d637e2f4)

**Comment by hanneskuettner** [comment]
@itsminani I'm unable to reproduce this issue with trying to recreate an identical query. Since you are a cloud customer, could you please reach out to support@directus.io and let them know I sent you, so we can possibly recreate the issue with your help to get to the bottom of this?

**Comment by Leptopoda** [comment]
Hi there and happy new year. 
We are also facing this issue and I was able to recreate this in a test environment.

I created a table (`test_table`) containing a translated field (`translated`).
We use to query our data by language with a filter on the lagnuage (see the following example graphql query).

#### Query:
```gql
query Test_table {
    test_table {
        id
        translations {
            languages_code(filter: { code: { _eq: "en-US" } }) {
                code
            }
            translated
        }
    }
}
```

#### Result:
```json
{
    "errors": [
        {
            "message": "parentsByForeignKey.get is not a function or its return value is not iterable",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "test_table"
            ]
        }
    ]
}
```

#### Docker logs:
```
directus-1  | [15:18:55.133] ERROR: parentsByForeignKey.get is not a function or its return value is not iterable
directus-1  |     err: {
directus-1  |       "type": "GraphQLError",
directus-1  |       "message": "parentsByForeignKey.get is not a function or its return value is not iterable",
directus-1  |       "stack":
directus-1  |           TypeError: parentsByForeignKey.get is not a function or its return value is not iterable
directus-1  |               at mergeWithParentItems (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/utils/merge-with-parent-items.js:21:58)
directus-1  |               at run (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:106:29)
directus-1  |               at async runAst (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:26:16)
directus-1  |               at async run (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:89:36)
directus-1  |               at async runAst (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:26:16)
directus-1  |               at async ItemsService.readByQuery (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/items.js:373:25)
directus-1  |               at async GraphQLService.read (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/graphql/index.js:1420:15)
directus-1  |               at async GraphQLService.resolveQuery (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/graphql/index.js:1308:24)
directus-1  |               at async resolve (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/graphql/index.js:951:40)
directus-1  |               at async Promise.all (index 0)
directus-1  |       "path": [
directus-1  |         "test_table"
directus-1  |       ],
directus-1  |       "locations": [
directus-1  |         {
directus-1  |           "line": 2,
directus-1  |           "column": 5
directus-1  |         }
directus-1  |       ],
directus-1  |       "extensions": {}
directus-1  |     }
directus-1  | [15:18:55] POST /graphql 200 15ms
```

#### Environment:
```yaml
services:
  directus:
    image: directus/directus:11.3@sha256:6bc79ef2f0daa224d84b4da22ea3831e60697d399589d54067cb3681c2f94514
    ports:
      - 8055:8055
    volumes:
      - .local/database:/directus/database
      - .local/uploads:/directus/uploads
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
```

### DB Dump:
I have no Idea, whether this helps, but here is also the db dump from the test.
[data.db.sql.txt](https://github.com/user-attachments/files/18301182/data.db.sql.txt)

**Comment by AKhateeb** [comment]
I have Directus 11.3.5 running on Docker and I'm facing such an issue:
```
{"severity":"ERROR","level":50,"time":1736173548880,"pid":29,"hostname":"srv604752","err":{"type":"TypeError","message":"parentsByForeignKey.get is not a function or its return value is not iterable","stack":"TypeError: parentsByForeignKey.get is not a function or its return value is not iterable\n    at mergeWithParentItems (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/utils/merge-with-parent-items.js:21:58)\n    at run (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:106:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async runAst (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:26:16)\n    at async ItemsService.readByQuery (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/services/items.js:373:25)\n    at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/controllers/items.js:69:18"},"message":"parentsByForeignKey.get is not a function or its return value is not iterable"}
```
