### ISSUE TITLE
Server Error when logging in after migration, /users/me not found

### ISSUE THREAD

**Issue by aSeriousDeveloper** [directus/directus#2516]
# Bug Report
I migrated over from Directus 7 (following the steps from [this migration guide](https://github.com/directus/directus/releases/tag/v8.0.0)). However, when logging in the app immediately leads to a server error screen.

## Steps to Reproduce
1. Previously existing Directus 7 distro, working
2. truncate migrations table
3. clone Directus 8 repo (originally hadn't cloned for Directus 7)
4. copy & make required changes to config, copy over files, etc
5. Attempt to login

## Expected Behaviour
At this point, I should be able to log back into the system, with directus migrating the database for the new database structure required

## Actual Behaviour
Server error screen, with error reported to console.
`VM1197:1 GET http://localhost/directus_8/public/{{project}}/users/me?fields[0]=id&fields[1]=avatar.*&fields[2]=email&fields[3]=first_name&fields[4]=last_name&fields[5]=locale&fields[6]=role.*&fields[7]=last_page&fields[8]=theme 404 (Not Found)`

I checked the logs and I'm given this error:
`[2019-12-19 14:55:16] api[cpl-group].ERROR: Directus\Database\Exception\ItemNotFoundException: Item not found in C:\xampp\htdocs\directus_8\src\core\Directus\Services\ItemsService.php:138
Stack trace:
#0 C:\xampp\htdocs\directus_8\src\core\Directus\Services\UsersService.php(144): Directus\Services\ItemsService->findByIds
#1 C:\xampp\htdocs\directus_8\src\endpoints\Users.php(92): Directus\Services\UsersService->findByIds
#2 [internal function]: Directus\Api\Routes\Users->read
#3 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func
#4 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#7 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#10 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#12 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#15 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#17 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#20 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#21 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#22 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#25 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#26 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\Route.php(268): Slim\Route->callMiddlewareStack
#27 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\App.php(503): Slim\Route->run
#28 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#29 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#30 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#33 C:\xampp\htdocs\directus_8\vendor\directus\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#34 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#35 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#36 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#39 C:\xampp\htdocs\directus_8\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#40 [internal function]: RKA\Middleware\IpAddress->__invoke
#41 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#44 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(71): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#46 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#49 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#50 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#51 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#52 [internal function]: Slim\DeferredCallable->__invoke
#53 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#54 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#55 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack
#56 C:\xampp\htdocs\directus_8\vendor\slim\slim\Slim\App.php(297): Slim\App->process
#57 C:\xampp\htdocs\directus_8\src\core\Directus\Application\Application.php(161): Slim\App->run
#58 C:\xampp\htdocs\directus_8\public\index.php(5): Directus\Application\Application->run [] []`

From the looks of it, /users/me doesn't exist as a path, but Directus is trying to run this path.
My guess from the stack trace is users/me is being seen as a call for user with id "me" rather than a custom endpoint of the user info for the user currently logged in?

## Other Context & Screenshots
This is the server error screen I receieve:
![image](https://user-images.githubusercontent.com/39706150/71179408-055ac780-2268-11ea-9ed7-ec73c8df7a20.png)

## Technical Details
XAMPP Server:
PHP Version 7.3.6
Apache Version 2.4.39
Database: MySQL 10.3.16-MariaDB
Directus: Latest Version (cloned today)

**Comment by rijkvanzanten** [comment]
`/me` is being matched as ID in that endpoint, and this normally works. I have seen this behavior before where the session cookie doesn't make it to the `/users/me` endpoint, therefore the API is not able to extract who "me" is and fails.
