### ISSUE TITLE
Impossible to edit Translation field

### ISSUE THREAD

**Issue by fribeau** [directus/directus#2680]
# Bug Report
I am unable to edit a Translation field once it has been saved.

## Steps to Reproduce
1. Create junction collection `market_category_translations` (no default fields)
2. Add fields : `market_category_id` (number), `language` (text), `content` (text)
3. Create collection `market_categories` (with status and sort)
4. Add field `name` (translation)
![image](https://user-images.githubusercontent.com/19540101/80242299-728ec700-8665-11ea-81a7-e8130f5106a8.png)
5. Save
6. Open field `name` to edit some parameters (languages, display template, anything)
![image](https://user-images.githubusercontent.com/19540101/80242497-bd104380-8665-11ea-8444-2e83e2c1ddd0.png)

## Expected Behavior
Be able to edit the `name` field.

## Actual Behavior
If I check the logs in `logs/error.2020-04-24.log`, I get this:
```
[2020-04-24 19:56:43] api[courbis].ERROR: Directus\Exception\SQLException: Statement could not be executed (42S22 - 1054 - Unknown column 'name' in 'where clause') in /var/www/directus/src/endpoints/Fields.php:122
Stack trace:
#0 [internal function]: Directus\Api\Routes\Fields->update
#1 /var/www/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#2 /var/www/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#3 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#4 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#5 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#6 [internal function]: Slim\DeferredCallable->__invoke
#7 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#8 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#9 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#10 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
#12 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#13 /var/www/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#14 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#15 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/www/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#19 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#20 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#24 /var/www/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#25 /var/www/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#26 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#27 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#28 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#29 [internal function]: Slim\DeferredCallable->__invoke
#30 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#31 /var/www/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#32 /var/www/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#33 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#34 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#38 [internal function]: RKA\Middleware\IpAddress->__invoke
#39 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#43 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#44 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#47 /var/www/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(63): Slim\App->Slim\{closure}
#48 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#49 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#50 [internal function]: Slim\DeferredCallable->__invoke
#51 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#52 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#53 /var/www/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#54 /var/www/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#55 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#56 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []
```

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/19540101/80243156-f39a8e00-8666-11ea-8232-1566a83e7b31.png)
![image](https://user-images.githubusercontent.com/19540101/80243169-fdbc8c80-8666-11ea-9ca7-48d3b4f95b2d.png)

## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04.4 LTS
- Web Server: Apache/2.4.29 (Ubuntu)
- PHP Version: 7.2.24-0ubuntu0.18.04.4
- Database: mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
- Directus Release Version: 8.6.2
- Install Method: cloned `master` branch

**Comment by benhaynes** [comment]
@directus/team — App or API?

**Comment by fribeau** [comment]
It wired. I have deleted all my collections and recreated them with exactly the same fields except I have prefixed all my fields name with `afs_`. Now I do not have the error and I can edit the translation field except the `required` parameter.

If I try to change the `required` parameter in my translation field, I get the same error than above.

**Comment by rijkvanzanten** [comment]
@fribeau Are you able to accurately reproduce it? Do you still have the old broken one saved somewhere and would you be able to provide a dump? 

Annoying issue for sure, but near impossible to reproduce at this point :(

**Comment by fribeau** [comment]
@rijkvanzanten I cannot reproduce it anymore. I have tried to reproduce it on [https://demo.directus.io](https://demo.directus.io) but I was not able to get the error.
However, I cannot edit the `required` parameter as mentioned in my previous comment. But maybe is it the expected behavior.
