### ISSUE TITLE
MySQL undefined column in field list

### ISSUE THREAD

**Issue by tuxnese** [directus/directus#3130]
I cannot find the previous issue. On rc15 I get the following error:

🚨 select `client_type`.`id`, `client_type`.`name`, `client_type`.`undefined` from `client_type` limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'client_type.undefined' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'client_type.undefined' in 'field list'
    at Query.Sequence._packetToError (/var/www/directus_v9/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/directus_v9/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/directus_v9/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/directus_v9/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/directus_v9/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/directus_v9/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/directus_v9/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/www/directus_v9/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (/var/www/directus_v9/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/directus_v9/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/directus_v9/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/var/www/directus_v9/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/var/www/directus_v9/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/var/www/directus_v9/node_modules/knex/lib/runner.js:151:36)
    at /var/www/directus_v9/node_modules/knex/lib/runner.js:40:23
    at client.acquireConnection.catch.then (/var/www/directus_v9/node_modules/knex/lib/runner.js:277:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by benhaynes** [comment]
Could you provide a bit more context? What DB type/version? Do you have a database dump we can test on? There's nothing special about user tables/content from v8 (it's pure SQL) so this seems to be more related to managing schemas that were created in the database directly.

**Comment by tuxnese** [comment]
Here is the database dump ( without the user table )
[directus_v9_dump_issue.sql.zip](https://github.com/directus/directus/files/5567003/directus_v9_dump_issue.sql.zip)
I am using mysql 8.0.22.
Should I create the collection using the user interface and then copy the records or can I just copy the whole table from one database to the other?

**Comment by benhaynes** [comment]
Creating the schema in Directus and then copying over data should work as a stopgap solution, but what you've described is a bug and should/will be fixed. Directus mirrors the DB, so if you create things outside of Directus they should still work as expected. This is especially important since many people will be upgrading/importing from v8.

**Comment by rijkvanzanten** [comment]
@tuxnese The database export you used for the `client_type` table doesn't include any indices, meaning that there's no primary key in that table. That trips up Directus, as everything is based around primary keys. I've added an extra check that throws an error when trying to read from a corrupted table 👍

**Comment by tuxnese** [comment]
Ok, the primary key attribute got lost when copying the table from one database to the other.
