### ISSUE TITLE
GraphQL Query throws Error 'multiple types named "item".'

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#3232]
When I try to do a graphql query which was working before I now get an error. I stopped working at this project for about 1,5 weeks so I cannot exactly tell you when the error occured for the first time:

```
12:37:31 🚨 Schema must contain uniquely named types but contains multiple types named "item".
Error: Schema must contain uniquely named types but contains multiple types named "item".
    at new GraphQLSchema (/var/www/api/node_modules/graphql/type/schema.js:194:15)
    at GraphQLService.getGraphQLSchema (/var/www/api/node_modules/directus/dist/services/graphql.js:208:16)
    at GraphQLService.<anonymous> (/var/www/api/node_modules/directus/dist/services/graphql.js:68:33)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/api/node_modules/directus/dist/services/graphql.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

```

---

### Project details
Directus Version: 9.0.0-rc.19
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.0.1

**Comment by MichaelNussbaumerGOWEST** [comment]
It is working right now.
