### ISSUE TITLE
Running test fails in sdk-js when module is es2015

### ISSUE THREAD

**Issue by apstanisic** [directus/directus#3475]
Returning value to `"module": "CommonJS"` run tests normally 

Error: 
```
➜ npm run test

> @directus/sdk-js@9.0.0-rc.24 test
> mocha -r ts-node/register/transpile-only -r source-map-support/register --recursive 'tests/**/*.ts'


/home/aleksandar/Projects/oss/directus/packages/sdk-js/tests/handlers/activity.ts:37
import { ActivityHandler } from '../../src/handlers/activity';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module.m._compile (/home/aleksandar/Projects/oss/directus/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/aleksandar/Projects/oss/directus/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/mocha.js:431:19)
    at singleRun (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/aleksandar/Projects/oss/directus/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/aleksandar/Projects/oss/directus/node_modules/mocha/node_modules/yargs/lib/command.js:241:49
```

https://github.com/directus/directus/blob/9f58589a43c6bd66e5248fe536429cc1bf020445/packages/sdk-js/tsconfig.json#L5

**Comment by nickrum** [comment]
My bad! Checking the test command was on my radar, but I somehow forgot about it. Thanks for pointing this out.
