### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: knex: Required configuration option 'client' is missing.

### ISSUE THREAD

**Issue by andrew-medvedev** [directus/directus#3532]
1) See the exception call-stack in my terminal while running `npm run dev`. Expecting not see any exceptions.

```
directus: (node:3224) UnhandledPromiseRejectionWarning: Error: knex: Required configuration option 'client' is missing.
directus:     at new Client (C:\Users\ihatemicrosoft1\Desktop\okay\node_modules\knex\lib\client.js:54:11)
directus:     at Object.Knex [as default] (C:\Users\ihatemicrosoft1\Desktop\okay\node_modules\knex\lib\knex.js:53:28)
directus:     at Object.<anonymous> (C:\Users\ihatemicrosoft1\Desktop\okay\api\src\database\index.ts:36:22)
directus:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
directus:     at Module._compile (C:\Users\ihatemicrosoft1\Desktop\okay\node_modules\source-map-support\source-map-support.js:547:25)
directus:     at Module.m._compile (C:\Users\IHATEM~1\AppData\Local\Temp\ts-node-dev-hook-5239134965307872.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
directus:     at require.extensions.<computed> (C:\Users\IHATEM~1\AppData\Local\Temp\ts-node-dev-hook-5239134965307872.js:59:20)
directus:     at Object.nodeDevHook [as .ts] (C:\Users\ihatemicrosoft1\Desktop\okay\node_modules\ts-node-dev\lib\hook.js:63:13)
directus:     at Module.load (internal/modules/cjs/loader.js:879:32)
```
https://gyazo.com/664924c0bb5d133ab2c6d0cd518cf557

2) Steps from 2 to 6 from here: https://docs.directus.io/getting-started/contributing.html#development-workflow . Nothing more!

3) Directus 9.0.0-rc.26 , Postgresql x64 12 , Node v12.19.0 , Brave v1.18.75

4) I don't think so

**Comment by rijkvanzanten** [comment]
You'll have to provide a `.env` file to run Directus in dev mode 👍
