### ISSUE TITLE
ERROR:  constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist

### ISSUE THREAD

**Issue by andriusign** [directus/directus#3551]
For some reason when starting Directus in Docker I get this error and back-end is not working:

```
directus_1  | 02:47:52 ✨ Initializing bootstrap...
database_1  | 
database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
cache_1     | 1:C 31 Dec 2020 02:47:51.711 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1     | 1:C 31 Dec 2020 02:47:51.711 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1     | 1:C 31 Dec 2020 02:47:51.711 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
database_1  | 
cache_1     | 1:M 31 Dec 2020 02:47:51.713 * Running mode=standalone, port=6379.
cache_1     | 1:M 31 Dec 2020 02:47:51.713 # Server initialized
cache_1     | 1:M 31 Dec 2020 02:47:51.713 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache_1     | 1:M 31 Dec 2020 02:47:51.714 * Loading RDB produced by version 6.0.9
cache_1     | 1:M 31 Dec 2020 02:47:51.714 * RDB age 3 seconds
cache_1     | 1:M 31 Dec 2020 02:47:51.714 * RDB memory usage when created 0.79 Mb
cache_1     | 1:M 31 Dec 2020 02:47:51.714 * DB loaded from disk: 0.000 seconds
cache_1     | 1:M 31 Dec 2020 02:47:51.714 * Ready to accept connections
database_1  | 2020-12-31 02:47:52.769 UTC [1] LOG:  starting PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
database_1  | 2020-12-31 02:47:52.769 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1  | 2020-12-31 02:47:52.769 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1  | 2020-12-31 02:47:52.820 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1  | 2020-12-31 02:47:52.987 UTC [25] LOG:  database system was shut down at 2020-12-31 02:47:49 UTC
database_1  | 2020-12-31 02:47:53.091 UTC [1] LOG:  database system is ready to accept connections
directus_1  | 02:47:53 ✨ Database already initialized, skipping install
directus_1  | 02:47:53 ✨ Running migrations...
database_1  | 2020-12-31 02:47:53.825 UTC [32] ERROR:  constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
database_1  | 2020-12-31 02:47:53.825 UTC [32] STATEMENT:  alter table "directus_fields" drop constraint "directus_fields_collection_foreign"
directus_1  | error: alter table "directus_fields" drop constraint "directus_fields_collection_foreign" - constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
directus_1  |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:278:15)
directus_1  |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus_1  |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus_1  |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
directus_1  |     at Socket.emit (events.js:315:20)
directus_1  |     at addChunk (internal/streams/readable.js:309:12)
directus_1  |     at readableAddChunk (internal/streams/readable.js:284:9)
directus_1  |     at Socket.Readable.push (internal/streams/readable.js:223:10)
directus_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
directus_1  |   length: 162,
directus_1  |   severity: 'ERROR',
directus_1  |   code: '42704',
directus_1  |   detail: undefined,
directus_1  |   hint: undefined,
directus_1  |   position: undefined,
directus_1  |   internalPosition: undefined,
directus_1  |   internalQuery: undefined,
directus_1  |   where: undefined,
directus_1  |   schema: undefined,
directus_1  |   table: undefined,
directus_1  |   column: undefined,
directus_1  |   dataType: undefined,
directus_1  |   constraint: undefined,
directus_1  |   file: 'tablecmds.c',
directus_1  |   line: '10355',
directus_1  |   routine: 'ATExecDropConstraint'
directus_1  | }
database_1  | 2020-12-31 02:47:53.835 UTC [32] LOG:  could not receive data from client: Connection reset by peer

```

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-48-generic
Node: 14.15.2
Running in Docker

**Comment by andriusign** [comment]
It was my fault accidentally deleting some tables from database. Could not figure out how to fix, had to restore database from other Directus installation.
