### ISSUE TITLE
Show nicer error message for missing .env file

### ISSUE THREAD

**Issue by khromov** [directus/directus#3556]
1) The issue and what you expected to happen
 
After following the getting started guide, Directus does not start.

2) Exact steps to reproduce this issue

```bash
npx create-directus-project directus9
# filled out interactive settings, database gets populated successfully
npx directus start

info sharp Using cached /home/k/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br
Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/k/.npm/_npx/3678/lib/node_modules/directus/node_modules/knex/lib/client.js:54:11)
    at Object.Knex [as default] (/home/k/.npm/_npx/3678/lib/node_modules/directus/node_modules/knex/lib/knex.js:14:28)
    at Object.<anonymous> (/home/k/.npm/_npx/3678/lib/node_modules/directus/dist/database/index.js:44:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/k/.npm/_npx/3678/lib/node_modules/directus/dist/server.js:41:36)
```

package.json:
```js
//...
 "dependencies": {
    "directus": "^9.0.0-rc.28",
    "mysql": "^2.18.1"
  }
//...
```

3) Your environment:
* Node 14
* Ubuntu
* MySQL 8 (with `--default-authentication-plugin=mysql_native_password` to enable old-school auth)

4) Any other relevant information we might need to reproduce this issue

Posting my resulting `.env` in case something is missing there:

```
####################################################################################################
## General

PORT=8055
PUBLIC_URL="/"

####################################################################################################
## Database

DB_CLIENT="mysql"
DB_HOST="127.0.0.1"
DB_PORT="33006"
DB_DATABASE="app"
DB_USER="app"
DB_PASSWORD="app"


####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_PUBLIC_URL="/uploads"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="4bf74573-5881-4356-b7c6-7125d52ff427"
SECRET="2lXp3vcc8kNS3ox3W01twX2h4cg5rkRN"


ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

####################################################################################################
## SSO (OAuth) Providers

OAUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"

####################################################################################################
## Email

EMAIL_FROM="no-reply@directus.io"
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"
```

**Comment by khromov** [comment]
A bit embarrassing, but it turns out I was in the wrong folder when trying to run the `npx directus start` command. It would be really helpful if the message was less cryptic (for example: "Could not find `.env` file in current directory")

**Comment by benhaynes** [comment]
@rijkvanzanten , is it possible to make that CLI response clearer?

**Comment by NCorreia100** [comment]
Finally found THIS!

I've been trying to troubleshoot my failed installation of Directus 9 for  >2weeks. In the documentation, there is no reference to the .env file requirement (not on v.9 docs at least) and there is not enough community support for this version yet as I couldn't find (until now) .env examples (for Directus 9 specifically). 
It would be nice if this requirement is added to the docs and/or a default .env file is created in the directory when this error happens, aside form making the error clearer.

**Comment by benhaynes** [comment]
Glad you found your solution... isn't this the Docs you would need to understand the config file options?

https://docs.directus.io/reference/config-files/#env

**Comment by rijkvanzanten** [comment]
Also, a `.env` _file_ isn't required, as long as the environment variables are present. For contexts like Heroku or DigitalOcean App Platform, these environment variables are configured within the GUI of those services respectively
