### ISSUE TITLE
Can't deploy directus v9 on Docker with Amazon Aurora

### ISSUE THREAD

**Issue by cmllr** [directus/directus#3587]
Hello, 

we are currently facing following issue with the docker image of Directus 9.

1) The issue and what you expected to happen

When deploying an directus instance from the image `directus/directus:v9.0.0-rc.28` (or should be another tag as there is no `latest` tag (yet?)) in Docker with `DB_CLIENT=mysql`, the bootstrapping fails:

```
15:10:46 ✨ Initializing bootstrap...
15:10:46 🔍 [3.153ms] select 1 + 1 as result []
Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [table_schema] query: select count(*) as `count` from `information_schema`.`tables` where `table_schema` = ? and `table_name` = ? limit ?
    at QueryCompiler_MySQL.toSQL (/directus/node_modules/knex/lib/query/compiler.js:98:13)
    at Builder.toSQL (/directus/node_modules/knex/lib/query/builder.js:97:44)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Using `mysql2` as the `DB_CLIENT` also fails:

```
15:13:33 ✨ Initializing bootstrap...
15:13:33 🚨 Knex: run
$ npm install mysql2 --save
Cannot find module 'mysql2'
Require stack:
- /directus/node_modules/knex/lib/dialects/mysql2/index.js
- /directus/node_modules/knex/lib/config-resolver.js
- /directus/node_modules/knex/lib/knex.js
- /directus/node_modules/knex/lib/index.js
- /directus/node_modules/knex/knex.js
- /directus/node_modules/directus/dist/cli/utils/create-db-connection.js
- /directus/node_modules/directus/dist/cli/commands/init/index.js
- /directus/node_modules/directus/dist/cli/index.js
- /directus/node_modules/directus/cli.js
Error: Cannot find module 'mysql2'
Require stack:
- /directus/node_modules/knex/lib/dialects/mysql2/index.js
- /directus/node_modules/knex/lib/config-resolver.js
- /directus/node_modules/knex/lib/knex.js
- /directus/node_modules/knex/lib/index.js
- /directus/node_modules/knex/knex.js
- /directus/node_modules/directus/dist/cli/utils/create-db-connection.js
- /directus/node_modules/directus/dist/cli/commands/init/index.js
- /directus/node_modules/directus/dist/cli/index.js
- /directus/node_modules/directus/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_MySQL2._driver (/directus/node_modules/knex/lib/dialects/mysql2/index.js:24:12)
    at Client_MySQL2.initializeDriver (/directus/node_modules/knex/lib/client.js:231:26)
    at Client_MySQL2.Client (/directus/node_modules/knex/lib/client.js:69:10)
    at Client_MySQL2.Client_MySQL (/directus/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at new Client_MySQL2 (/directus/node_modules/knex/lib/dialects/mysql2/index.js:11:16)
    at Object.Knex [as default] (/directus/node_modules/knex/lib/knex.js:14:28)
Error: Knex: run
$ npm install mysql2 --save
Cannot find module 'mysql2'
Require stack:
- /directus/node_modules/knex/lib/dialects/mysql2/index.js
- /directus/node_modules/knex/lib/config-resolver.js
- /directus/node_modules/knex/lib/knex.js
- /directus/node_modules/knex/lib/index.js
- /directus/node_modules/knex/knex.js
- /directus/node_modules/directus/dist/cli/utils/create-db-connection.js
- /directus/node_modules/directus/dist/cli/commands/init/index.js
- /directus/node_modules/directus/dist/cli/index.js
- /directus/node_modules/directus/cli.js
    at Client_MySQL2.initializeDriver (/directus/node_modules/knex/lib/client.js:235:13)
    at Client_MySQL2.Client (/directus/node_modules/knex/lib/client.js:69:10)
    at Client_MySQL2.Client_MySQL (/directus/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at new Client_MySQL2 (/directus/node_modules/knex/lib/dialects/mysql2/index.js:11:16)
    at Object.Knex [as default] (/directus/node_modules/knex/lib/knex.js:14:28)
    at Object.<anonymous> (/directus/node_modules/directus/dist/database/index.js:44:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

2) Exact steps to reproduce this issue

- Running the image `directus/directus:v9.0.0-rc.28` on docker with environment variable `DB_CLIENT` either set to `mysql` or `mysql2` (also fails when using a local mysql-container, for example)

3) Your environment:

- Amazon Aurora DBMS (5.7.mysql_aurora.2.09.0)

4) Any other relevant information we might need to reproduce this issue

- We see the client connecting successfully on the database (to sort out authentification/ network issues)

Thank you!

Greetings,
Christoph

**Comment by rijkvanzanten** [comment]
Seems like Aurora doesn't have the `table_schema` column in information_schema.tables 🤔

**Comment by megamorf** [comment]
Dockerized Directus with AWS Aurora DB works for us. Setup is as follows:

* directus/directus:v9.0-rc.40
* 5.7.mysql_aurora.2.09.1

with:

```yaml
    environment:
      DB_CLIENT: 'mysql'
      DB_HOST: 'foo-cluster-dev.cluster-bar.eu-central-1.rds.amazonaws.com'
      DB_PORT: '3306'
      DB_DATABASE: 'cms_dev'
      DB_USER: 'cms_dev'
      DB_PASSWORD: 'supersecretpassword'
```

**Comment by cmllr** [comment]
Thank you for sharing @megamorf, it's working with that settings. Just verified with rc.43
