### ISSUE TITLE
Error: Invalid undefined schema when POST to /users/invite

### ISSUE THREAD

**Issue by andriusign** [directus/directus#3590]
Post method to endpoint /users/invite returns 500 error.

Post to: http://localhost:8055/users/invite
Body
```
{
    "role": "8df22982-20a3-43b1-8577-01fe7b73341a",
    "email": "user@example.com"
}
```

End-point settings for Public role (Create):
Item permissions: Email, password, status, role
Field validation:
```
{
    "_or": [
        {
            "role": {
                "has": "8df22982-20a3-43b1-8577-01fe7b73341a"
            }
        },
        {
            "role": {
                "has": "45024ca3-6cfd-4166-8d56-d50958234d7f"
            }
        }
    ]
}
```

Error output
```
directus_1  | 19:57:22 🚨 Invalid undefined schema 
directus_1  | Error: Invalid undefined schema
directus_1  |     at new module.exports (/directus/node_modules/@hapi/hoek/lib/error.js:23:19)
directus_1  |     at module.exports (/directus/node_modules/@hapi/hoek/lib/assert.js:20:11)
directus_1  |     at Object.internals.schema (/directus/node_modules/joi/lib/compile.js:33:5)
directus_1  |     at Object.exports.schema (/directus/node_modules/joi/lib/compile.js:17:26)
directus_1  |     at internals.Base.$_compile (/directus/node_modules/joi/lib/base.js:645:24)
directus_1  |     at /directus/node_modules/joi/lib/types/keys.js:256:92
directus_1  |     at Object.exports.tryWithPath (/directus/node_modules/joi/lib/common.js:176:16)
directus_1  |     at internals.Base.method [as keys] (/directus/node_modules/joi/lib/types/keys.js:256:32)
directus_1  |     at Object.args (/directus/node_modules/joi/lib/types/keys.js:49:23)
directus_1  |     at Object.internals.generate (/directus/node_modules/joi/lib/index.js:259:31)
directus_1  | 19:57:22 ✨ request errored POST 500 /users/invite 34ms
directus_1  | 19:57:26 ✨ request completed GET 200 /permissions/45 40ms
directus_1  | 19:57:27 ✨ request completed PATCH 200 /users/me/track/page 32ms
directus_1  | 19:57:29 ✨ request completed PATCH 200 /permissions/45 81ms
directus_1  | 19:57:29 ✨ request completed GET 200 /permissions/45 33ms
directus_1  | 19:57:30 ✨ request completed PATCH 200 /users/me/track/page 96ms
directus_1  | 19:57:31 ✨ request completed DELETE 200 /permissions/45 99ms
directus_1  | 19:57:31 ✨ request completed GET 200 /permissions?filter=%7B%22role%22:%7B%22_null%22:true%7D%7D&limit=-1 46ms
```

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.2
Running in Docker

**Comment by rijkvanzanten** [comment]
I think this is a configuration issue:

```
{
    "_or": [
        {
            "role": {
                "has": "8df22982-20a3-43b1-8577-01fe7b73341a"
            }
        },
        {
            "role": {
                "has": "45024ca3-6cfd-4166-8d56-d50958234d7f"
            }
        }
    ]
}
```

That `"has"` doesn't exist. I think you're looking for:

```
{
    "_or": [
        {
            "role": {
                "_eq": "8df22982-20a3-43b1-8577-01fe7b73341a"
            }
        },
        {
            "role": {
                "_eq": "45024ca3-6cfd-4166-8d56-d50958234d7f"
            }
        }
    ]
}
```

or 

```
{
    "role": {
        "_in": ["8df22982-20a3-43b1-8577-01fe7b73341a", "45024ca3-6cfd-4166-8d56-d50958234d7f"]
    }
}
```

**Comment by andriusign** [comment]
I have checked the docs, and there is "_has" operator according to documentation: https://docs.directus.io/reference/api/query/filter.html
![image](https://user-images.githubusercontent.com/14263959/104494771-8f966c00-55df-11eb-97c5-2076c8996000.png)

I have tried you provided options, but neither did work. Attaching output:

Example 1:
```
{
    "role": {
        "_in": ["8df22982-20a3-43b1-8528-12fe7b73651f", "45024ca3-6cfd-4166-8d56-d50958234d7f"]
    }
}
```

Returned:
```
{
    "errors": [
        {
            "message": "\"role\" must be one of [8, d, f, 2, 9, -, 0, a, 3, 4, b, 1, 5, e, 7, 6]",
            "extensions": {
                "field": "role",
                "type": "in",
                "valid": [
                    "8",
                    "d",
                    "f",
                    "2",
                    "9",
                    "-",
                    "0",
                    "a",
                    "3",
                    "4",
                    "b",
                    "1",
                    "5",
                    "e",
                    "7",
                    "6"
                ],
                "code": "FAILED_VALIDATION"
            }
        }
    ]
}
```

Example 2:
```
{
    "_or": [
        {
            "role": {
                "_eq": "8df22982-20a3-43b1-8528-12fe7b73651f"
            }
        },
        {
            "role": {
                "_eq": "45024ca3-6cfd-4166-8d56-d50958234d7f"
            }
        }
    ]
}
```

Returned:
```
{
    "errors": [
        {
            "message": "\"role\" must be [8]",
            "extensions": {
                "field": "role",
                "type": "eq",
                "valid": "8",
                "code": "FAILED_VALIDATION"
            }
        },
        {
            "message": "\"role\" must be [4]",
            "extensions": {
                "field": "role",
                "type": "eq",
                "valid": "4",
                "code": "FAILED_VALIDATION"
            }
        }
    ]
}
```

My previous example (changed has -> _has):
```
{
    "_or": [
        {
            "role": {
                "_has": "8df22982-20a3-43b1-8528-12fe7b73651f"
            }
        },
        {
            "role": {
                "_has": "45024ca3-6cfd-4166-8d56-d50958234d7f"
            }
        }
    ]
}
```

Returned
```
{
    "errors": [
        {
            "message": "Invalid undefined schema",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

What other options are there to limit users invitation to some groups? If I turn off validation, user gets created with status "Invited"

**Comment by andriusign** [comment]
@rijkvanzanten any comments? Your provided solution did not work.

**Comment by rijkvanzanten** [comment]
Seems like https://github.com/directus/directus/issues/3597 👍🏻
