### ISSUE TITLE
MS SQL install fails if the DB contains special characters 

### ISSUE THREAD

**Issue by infused-kim** [directus/directus#3607]
## 1) The issue and what you expected to happen
I am trying to connect directus to an Azure SQL database (cloud hosted MS SQL).

During the `Installing Directus system tables...` step I get the error in the log below.

The issue is that my database name is `my-db-prod` and directus doesn't escape it correctly. The DB name should be wrapped like this: `[my-db-prod]`.

## 2) Exact steps to reproduce this issue
- Set the `DB_DATABASE` environment variable to contain an illegal SQL character, such as `-`.
- Launch directus

## 3) Your environment:

- DB: Azure SQL (MS SQL in the cloud)
- Deployment: Docker

## Error Log
```
13:45:28 ✨ Initializing bootstrap...
Thu, 07 Jan 2021 13:45:29 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
13:45:30 ✨ Installing Directus system tables...
RequestError:
		SELECT
			c.TABLE_NAME as table_name,
			c.COLUMN_NAME as column_name,
			c.COLUMN_DEFAULT as default_value,
			c.IS_NULLABLE as is_nullable,
			c.DATA_TYPE as data_type,
			pk.PK_SET as column_key
		FROM
			my-db-prod.INFORMATION_SCHEMA.COLUMNS as c
		LEFT JOIN (
			SELECT
				PK_SET = CASE WHEN CONSTRAINT_NAME LIKE '%pk%' THEN 'PRIMARY' ELSE NULL END
			FROM my-db-prod.INFORMATION_SCHEMA.KEY_COLUMN_USAGE
		) as pk
		ON [c].[TABLE_NAME] = [pk].[CONSTRAINT_TABLE_NAME]
		AND [c].[TABLE_CATALOG] = [pk].[CONSTRAINT_CATALOG]
		AND [c].[COLUMN_NAME] = [pk].[CONSTRAINT_COLUMN_NAME]
		 - Incorrect syntax near '-'.
    at handleError (/directus/node_modules/mssql/lib/tedious/request.js:374:15)
    at Connection.emit (events.js:315:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:315:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:315:20)
    at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
  code: 'EREQUEST',
  originalError: Error: Incorrect syntax near '-'.
      at handleError (/directus/node_modules/mssql/lib/tedious/request.js:372:19)
      at Connection.emit (events.js:315:20)
      at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
      at Parser.emit (events.js:315:20)
      at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
      at Parser.emit (events.js:315:20)
      at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
      at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
      at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
      at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
    info: ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 102,
      state: 1,
      class: 15,
      message: "Incorrect syntax near '-'.",
      serverName: 'my-server',
      procName: '',
      lineNumber: 14
    }
  },
  number: 102,
  lineNumber: 14,
  state: 1,
  class: 15,
  serverName: 'my-server',
  procName: '',
  precedingErrors: [
    RequestError: Incorrect syntax near '-'.
        at handleError (/directus/node_modules/mssql/lib/tedious/request.js:374:15)
        at Connection.emit (events.js:315:20)
        at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
        at Parser.emit (events.js:315:20)
        at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
        at Parser.emit (events.js:315:20)
        at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
        at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
        at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
        at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      number: 102,
      lineNumber: 10,
      state: 1,
      class: 15,
      serverName: 'my-server',
      procName: ''
    }
  ]
}
directus_directus_1 exited with code 1
```

**Comment by KimchaC** [comment]
Thanks for processing it so quickly. I totally agree that this is a low priority and that there are bigger fish to fry right now.

But could someone perhaps point me into the right direction of where I could fix this myself and perhaps add a PR?

**Comment by rijkvanzanten** [comment]
@KimchaC Totally! I believe it's this:

https://github.com/directus/directus/blob/9e800dbdf6cf6753fd0876462f737648c19def94/packages/schema/src/dialects/mssql.ts#L58

call to `this.knex.client.database()` that isn't escaped. I _think_ by replacing that by `?` and adding an array to the end of `knex.raw` it should escape it properly 🤔 

From the looks of it in the docs http://knexjs.org/#Raw-Bindings, by using `??` it should treat it as a identifier, so:

```js
knex.raw('SELECT etc FROM ??', [this.knex.client.database()])
```

might work!

**Comment by infused-kim** [comment]
This issue was closed, but the previous fix was incomplete and I still had the same problem when I tested it. The PR https://github.com/directus/directus/pull/3794 fixes it fully.
