### ISSUE TITLE
Make migrations idempotent 

### ISSUE THREAD

**Issue by infused-kim** [directus/directus#3608]
## 1) The issue and what you expected to happen
When I tried to set up directus, I ran into some issues where the initialization failed on the first run. After fixing it, directus didn't detect that the DB wasn't properly initialized (`Database already initialized, skipping install`) and failed, because some tables were missing.

For example, my DB user didn't have `REFERENCES` permissions and the DB initialization failed.

I added the permissions and re-ran directus. Instead of continuing to initialize the DB from where it left off, the log said `Database already initialized, skipping install` and the launch failed.

I had to manually delete all the tables and re-run it.

## 2) Exact steps to reproduce this issue
- Remove the `REFERENCES` permissions on the schema
- Launch directus and let it fail
- Give the `REFERENCES` permissions on the schema
- Launch directus again and see it skipping the initialization

## 3) Your environment:

- DB: Azure SQL (MS SQL in the cloud)
- Deployment: Docker

## Error Log
```
14:02:18 ✨ Initializing bootstrap...
Thu, 07 Jan 2021 14:02:18 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
14:02:20 ✨ Database already initialized, skipping install
14:02:20 ✨ Running migrations...
RequestError: ALTER TABLE [directus_fields] ADD CONSTRAINT [directus_fields_group_foreign] FOREIGN KEY ([group]) REFERENCES [directus_fields] ([id]) ON UPDATE CASCADE ON DELETE SET NULL - Could not create constraint or index. See previous errors.
    at handleError (/directus/node_modules/mssql/lib/tedious/request.js:374:15)
    at Connection.emit (events.js:315:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:315:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:315:20)
    at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
  code: 'EREQUEST',
  originalError: Error: Could not create constraint or index. See previous errors.
      at handleError (/directus/node_modules/mssql/lib/tedious/request.js:372:19)
      at Connection.emit (events.js:315:20)
      at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
      at Parser.emit (events.js:315:20)
      at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
      at Parser.emit (events.js:315:20)
      at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
      at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
      at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
      at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
    info: ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 1750,
      state: 1,
      class: 16,
      message: 'Could not create constraint or index. See previous errors.',
      serverName: 'my-server',
      procName: '',
      lineNumber: 1
    }
  },
  number: 1750,
  lineNumber: 1,
  state: 1,
  class: 16,
  serverName: 'my-server',
  procName: '',
  precedingErrors: [
    RequestError: Introducing FOREIGN KEY constraint 'directus_fields_group_foreign' on table 'directus_fields' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
        at handleError (/directus/node_modules/mssql/lib/tedious/request.js:374:15)
        at Connection.emit (events.js:315:20)
        at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
        at Parser.emit (events.js:315:20)
        at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
        at Parser.emit (events.js:315:20)
        at addChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:298:12)
        at readableAddChunk (/directus/node_modules/readable-stream/lib/_stream_readable.js:280:11)
        at Parser.Readable.push (/directus/node_modules/readable-stream/lib/_stream_readable.js:241:10)
        at Parser.Transform.push (/directus/node_modules/readable-stream/lib/_stream_transform.js:139:32) {
      code: 'EREQUEST',
      originalError: [Error],
      number: 1785,
      lineNumber: 1,
      state: undefined,
      class: 16,
      serverName: 'my-server',
      procName: ''
    }
  ]
}
directus_directus_1 exited with code 1
```

**Comment by 1R053** [comment]
I started a discussion here #3891 on a more generic way to solve this using schema definitions
