### ISSUE TITLE
Publish `latest` tag to dockerhub

### ISSUE THREAD

**Issue by avanwieringen-sensus** [directus/directus#3661]
I am following:
https://docs.directus.io/guides/installation/docker.html#docker-compose

The first command `docker run -p 8055:8055 directus/directus` fails with:
`docker: Error response from daemon: manifest for directus/directus:latest not found: manifest unknown: manifest unknown.
`

Then, a specific version: ` docker run -p 8055:8055 directus/directus:v9.0.0-rc.28  ` fails with
`Error: Sqlite does not support alter column.
    at TableCompiler_SQLite3.addColumns (/directus/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
    at TableCompiler_SQLite3.TableCompiler.alterColumns (/directus/node_modules/knex/lib/schema/tablecompiler.js:184:10)
    at TableCompiler_SQLite3.TableCompiler.alter (/directus/node_modules/knex/lib/schema/tablecompiler.js:77:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/directus/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:44:42)
    at SchemaCompiler_SQLite3.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:79:43)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24`

**Comment by avanwieringen-sensus** [comment]
I notice that this also happens with `npx create-directus-project` and selecting SQLite.

**Comment by rijkvanzanten** [comment]
The Sqlite issue is a known problem: https://github.com/directus/directus/issues/2948

**Comment by WoLfulus** [comment]
BTW: We're not pushing latest tag until we get out of RC.

**Comment by SergioDaroca** [comment]
sudo docker pull directus/directus:v9.0.0-rc.45
works!

**Comment by Jackbennett** [comment]
> BTW: We're not pushing latest tag until we get out of RC. That's why it wont work at this moment.

Might be wise to add that note to https://docs.directus.io/guides/installation/docker/ to look after first-time users. The first and only demo instruction doesn't work.

IMO rc is perfectly acceptable for `latest` nobody in production should be using latest.

**Comment by benhaynes** [comment]
Agree — @WoLfulus can we get `latest` working or at least get the Docs updated?

**Comment by Jackbennett** [comment]
I mean, while I'm here. Doesn't login with 50 & 51;

```
docker run -p 8055:8055 -e ADMIN_EMAIL="admin@example.com" -e ADMIN_PASSWORD="d1r3ctu5" directus/directus:v9.0.0-rc.51
# sign in http://localhost:8055/admin/login with admin@example.com d1r3ctu5 response 400 "Unexpected Error"
{"errors":[{"message":"Invalid foreign key.","extensions":{"code":"INVALID_FOREIGN_KEY"}}]}
