### ISSUE TITLE
Internal server error when serching text with search bar

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#3731]
> error select "test"."id", "test"."foo" from "test" where (("id" = $1) or LOWER("foo") LIKE $2) order by "id" asc limit $3 - invalid syntax for integer type : NaN
    at Parser.parseErrorMessage (C:\Users\*\directus\api\node_modules\pg-protocol\src\parser.ts:357:11)
    at Parser.handlePacket (C:\Users\*\directus\api\node_modules\pg-protocol\src\parser.ts:186:21)
    at Parser.parse (C:\Users\*\directus\api\node_modules\pg-protocol\src\parser.ts:101:30)
    at Socket.<anonymous> (C:\Users\*\directus\api\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

Looks like the text is casted to int to compare it with the `id` ( or any other column with a number type ).
There is no error where typing only numbers in the search bar.
PostgreSQL 13, Windows, latest commit to date (ba0cfd0dcfb9096ed3e4e59e3f565e68ddf13f91)

**Comment by Oreilles** [comment]
A similar error occurs when comparing dates with an advanced filter.
