### ISSUE TITLE
Error when installing on Linux (node-gyp / argon2)

### ISSUE THREAD

**Issue by luminous8** [directus/directus#3810]
Hi, 

First, thank your for this project, it exactly what I was looking for.

It works well in local but when trying to installing in production (on a linode server)
Can you please provide:

1) The issue and what you expected to happen

Whe installing the app via ` sudo npx create-directus-project my-project`

I get errors:
```
npx: installed 53 in 2.804s
⠋ Installing Directus(node:11294) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm install directus --production --no-optional
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.27.1 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/srv/my-project/node_modules/argon2/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/srv/my-project/node_modules/argon2/build'
gyp ERR! System Linux 5.7.6-x86_64-linode136
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/srv/my-project/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/srv/my-project/node_modules/argon2/lib/binding/napi-v3" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /srv/my-project/node_modules/argon2
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/srv/my-project/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/srv/my-project/node_modules/argon2/lib/binding/napi-v3 --napi_version=4 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/srv/my-project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.7.6-x86_64-linode136
node-pre-gyp ERR! command "/usr/local/bin/node" "/srv/my-project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /srv/my-project/node_modules/argon2
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
npm WARN my-project@1.0.0 No description
npm WARN my-project@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.27.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.27.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/my-username/.npm/_logs/2021-01-26T07_10_20_769Z-debug.log

> argon2@0.27.1 install /srv/my-project/node_modules/argon2
> node-pre-gyp install --fallback-to-build

Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/srv/my-project/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/srv/my-project/node_modules/argon2/lib/binding/napi-v3 --napi_version=4 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
    at makeError (/home/my-username/.npm/_npx/11294/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/my-username/.npm/_npx/11294/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

3) Your environment:
Linux ubuntu 16.04
Deployed with npx

4) Any other relevant information we might need to reproduce this issue
/

Thanks for your help

**Comment by WoLfulus** [comment]
This doesn't seem related to Directus. Check the location you're creating the project and your user permissions. Usually you don't want/need to use sudo with npm, and most of the time when you do it, you'll end up with this kind of issue.

Try just `npx create-directus-project my-project` on your home folder instead and check if it works.

**Comment by luminous8** [comment]
Ah thanks for the info!
When doing `npx create-directus-project my-project` without sudo I get Error: EACCES: permission denied error message

Any reco on how to fix this without having to use --unsafe-perm=true --allow-root?

Thanks

**Comment by benhaynes** [comment]
@WoLfulus — is what you mentioned worth adding to the docs?

**Comment by luminous8** [comment]
I succeed to install it by updating the chmod of the folder. I wouldn't have of this without your help, so thanks a lot!

**Comment by WoLfulus** [comment]
> Ah thanks for the info!
> When doing `npx create-directus-project my-project` without sudo I get Error: EACCES: permission denied error message
> 
> Any reco on how to fix this without having to use --unsafe-perm=true --allow-root?
> 
> Thanks

I can't say from your specific environment, but as I mentioned, this is probably caused by a combination one or multiple of:
- Which directory you're trying to create the project (plus it's permissions/ownership)
- The user you're logged into, and the group associated to that user
- How and where you installed node
- How and where you installed npm

What I'd try: 
- Make sure you're on your home directory `cd ~`
- Make sure you (the current user + group) have proper permissions to that folder
- Without `sudo`
  - Create a new directory "test" & `cd test`
  - Now at `~/test` try executing the `npx ...` project creation

If you still get issues after this, I might take a look on how node was installed.

As a rule of thumb (for me at least), I try to avoid putting sudo before any command I run as I find it really easy to mess up pretty badly the permissions, causing all sorts of problems like this one (I'm not a linux user, so I can't say much on why/how)
