### ISSUE TITLE
Type error with JWT handling for thumbnails

### ISSUE THREAD

**Issue by mlbullett** [directus/directus#3944]
# Bug Report
Hi there. Absolutely love your collective work but have discovered a small bug regarding broken thumbnails in the Project Settings panel (and possibly elsewhere).

## Environment
Fresh Directus 1-click App on DigitalOcean
Ubuntu 20.04 LTS
Postgres 12.5
Directus 9.0.0-rc.34
PM2 4.5.1
Caddy 2.3.0
Tested on Brave 88.1.19.90 and Chromium 87.0.4280.141

## Steps to Reproduce

1. Add project logo in Project Settings
2. See broken thumbnail with non-existent path

## Expected Behavior
Thumbnails should be visible

## Actual Behavior
The images are added just fine and can be used but the thumbnail in the Project Settings is broken. Upon further inspection, it would seem that there's an issue with the JWT handling specifically for the thumbnail. The stack trace below indicates that an array is being passed causing a uncaught type error when string.split('.') is called in is-jwt.js. But that's about as far as I got.

## Stack trace

Here's the stack trace of the error. I also logged the type and content of the object being passed to is-jwt.js for reference.
```
object
[
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg?key=system-small-cover',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg'
]
13:21:05 🚨 string.split is not a function
TypeError: string.split is not a function
    at Object.isJWT [as default] (/home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/utils/is-jwt.js:14:26)
    at /home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/middleware/authenticate.js:54:25
    at Generator.next (<anonymous>)
    at /home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/middleware/authenticate.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/middleware/authenticate.js:23:12)
    at /home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/middleware/authenticate.js:43:66
    at scoped (/home/max/work/stegimondo/tech/troubadix/node_modules/directus/dist/utils/async-handler.js:5:60)
    at Layer.handle [as handle_request] (/home/max/work/stegimondo/tech/troubadix/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/max/work/stegimondo/tech/troubadix/node_modules/express/lib/router/index.js:317:13)
13:21:05 ✨ request errored GET 500 /assets/79b630bc-35e7-4b10-bffe-b9b90f3afdc8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg?key=system-small-cover&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg 2ms
```

**Comment by rijkvanzanten** [comment]
Based on your issue, this log:

```
request errored GET 500 /assets/79b630bc-35e7-4b10-bffe-b9b90f3afdc8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg?key=system-small-cover&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5NzVkNWZjLTFkY2MtNDBkMy1hMmVjLTEwYmVlZmFjYjk1ZCIsImlhdCI6MTYxMjUyNzY1MSwiZXhwIjoxNjEyNTI4NTUxfQ.7L3MKpJFQCNhRrtCDA4oMOTHgZzahg1K8BMfFWq35Xg
```

The issue is in here:

https://github.com/directus/directus/blob/4fe04539bb30a5dd379f807a66a13812762a0364/app/src/interfaces/file/file.vue#L164-L175

`imageThumbnail` is using `assetURL`, which already has the token.
