### ISSUE TITLE
fs_1.promises.opendir is not a function

### ISSUE THREAD

**Issue by AntonLugtenburg** [directus/directus#3998]
Running on Node 14.15.5

- Upload a file 
- Delete the File again

In my case, i get the follwing error
```
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file 81837c5d-3345-483a-8a48-1b576fafcd41.
Please open an issue at https://github.com/Slynova-Org/flydrive/issues

Error code: undefined
Original stack:
TypeError: fs_1.promises.opendir is not a function
    at LocalFileSystemStorage._flatDirIterator (/var/www/vhosts/.../node_modules/@slynova/flydrive/build/LocalFileSystemStorage.js:221:45)
    at _flatDirIterator.next (<anonymous>)    at FilesService.<anonymous> (/var/www/vhosts/.../node_modules/directus/dist/services/files.js:165:108)
    at Generator.next (<anonymous>)
   at fulfilled (/var/www/vhosts/.../node_modules/directus/dist/services/files.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

After that, File is no more visible in the Interface, but is still in storage. I use default .env

Expected:

The Database Entry should remain if the file is not deleted successfully

Thank you very much for great work

**Comment by Merionis** [comment]
I have the same issue

**Comment by rijkvanzanten** [comment]
@AntonLugtenburg I know this was brought up already in the flydrive ticket, but ehh... are you sure this is on Node 14.15.5? I just downgraded to that exact version, and I can't reproduce it... 🤔 

The only thing I can think of that would cause this is if you happen to be on a Node version older than 12.12. When I downgrade to 12.5, the error I get is identical to what you shared:

```json
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file d62cff6f-5378-47bc-b521-65f7fb3e885f.\n\nError code: undefined\nOriginal stack:\nTypeError: fs_1.promises.opendir is not a function\n    at LocalFileSystemStorage._flatDirIterator (/Users/rijkvanzanten/Developer/directus/directus/packages/drive/src/LocalFileSystemStorage.ts:217:25)\n    at _flatDirIterator.next (<anonymous>)\n    at FilesService.<anonymous> (/Users/rijkvanzanten/Developer/directus/directus/api/src/services/files.ts:140:55)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rijkvanzanten/Developer/directus/directus/api/src/services/files.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:82:5)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
