### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by inluxc** [directus/directus#4017]
1) The issue and what you expected to happen
    Install directus

2) Exact steps to reproduce this issue
    yarn create directus-project directus or npx create-directus-project directus

3) Your environment:
  Linux Ubuntu 20.04

4) Any other relevant information we might need to reproduce this issue
```
yarn create directus-project directus
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-directus-project@9.0.0-rc.35" with binaries:
      - create-directus-project
/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/client.js:54
    throw new Error(`knex: Required configuration option 'client' is missing.`);
    ^

Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/client.js:54:11)
    at Object.Knex [as default] (/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/knex.js:14:28)
    at Object.<anonymous> (/home/fulvio/Projects/Inluxc/directus/node_modules/directus/dist/database/index.js:44:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code 1
npm ERR! path /home/fulvio/Projects/Inluxc/directus
npm ERR! command failed
npm ERR! command sh -c directus "init"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fulvio/.npm/_logs/2021-02-11T22_05_36_211Z-debug.log
(node:36801) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/home/fulvio/.config/yarn/global/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/fulvio/.config/yarn/global/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:36801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 26.36s.
```

**Comment by MiniDigger** [comment]
Take a look at the env var docs to configure the DB connection:
https://docs.directus.io/reference/environment-variables/

or, you could use `npx directus init` and it will ask you for stuff and create an .env file for you

**Comment by inluxc** [comment]
> Take a look at the env var docs to configure the DB connection:
> https://docs.directus.io/reference/environment-variables/
> 
> or, you could use `npx directus init` and it will ask you for stuff and create an .env file for you



> Take a look at the env var docs to configure the DB connection:
> https://docs.directus.io/reference/environment-variables/
> 
> or, you could use `npx directus init` and it will ask you for stuff and create an .env file for you
```
npx directus init
/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/client.js:54
    throw new Error(`knex: Required configuration option 'client' is missing.`);
    ^

Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/client.js:54:11)
    at Object.Knex [as default] (/home/fulvio/Projects/Inluxc/directus/node_modules/knex/lib/knex.js:14:28)
    at Object.<anonymous> (/home/fulvio/Projects/Inluxc/directus/node_modules/directus/dist/database/index.js:44:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code 1
npm ERR! path /home/fulvio/Projects/Inluxc/directus
npm ERR! command failed
npm ERR! command sh -c directus "init"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fulvio/.npm/_logs/2021-02-11T22_49_46_474Z-debug.log
```
