### ISSUE TITLE
ENOENT  - Failing to install Directus

### ISSUE THREAD

**Issue by carlskii** [directus/directus#4106]
Hi, 

I'm following the quick-start instructions to install Directus and take it for a spin. However I'm hitting this issue: 

```
npx create-directus-project my-project
```

However I'm getting this issue: 

```npx: installed 53 in 3.703s
ENOENT: no such file or directory, open '/Users/jb/development/directus/my-project/.env'
(node:76529) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/Users/jb/.npm/_npx/76529/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/jb/.npm/_npx/76529/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.create (/Users/jb/.npm/_npx/76529/lib/node_modules/create-directus-project/lib/index.js:73:2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
node -v
v14.15.5

Running  on OSX 11.1

````

**Comment by domoran** [comment]
Same issue on Windows 10.
