### ISSUE TITLE
Patch a O2M field will get "schema" must be of type object

### ISSUE THREAD

**Issue by jianliao** [directus/directus#4254]
1) Reproduce
a. Get any item that has a O2M field e.g. http://localhost:8080/fields/menu_item. The schema property is null.
```
        {
            "collection": "menu_item",
            "field": "children",
            "type": "o2m",
            "schema": null,
            "meta": {
                "id": 199,
                "collection": "menu_item",
                "field": "children",
                "special": [
                    "o2m"
                ],
                "interface": "one-to-many",
                "options": null,
                "display": null,
                "display_options": null,
                "locked": false,
                "readonly": false,
                "hidden": false,
                "sort": 11,
                "width": "full",
                "group": null,
                "translations": null,
                "note": "**Menu Group:** The other Menu Items within this group"
            }
        }
```
b. Go to application and try to modify this field - `children` of menu_item. You will get below error:
```
{
  "errors": [
    {
      "message": "\"schema\" must be of type object",
      "extensions": {
        "stack": "Error: \"schema\" must be of type object\n    at /Users/jianliao/Work/scm/github/directus/api/src/controllers/fields.ts:177:10\n    at Generator.next (<anonymous>)\n    at /Users/jianliao/Work/scm/github/directus/api/src/controllers/fields.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/jianliao/Work/scm/github/directus/api/src/controllers/fields.ts:4:12)\n    at /Users/jianliao/Work/scm/github/directus/api/src/controllers/fields.ts:168:40\n    at scoped (/Users/jianliao/Work/scm/github/directus/api/src/utils/async-handler.ts:11:21)\n    at Layer.handle [as handle_request] (/Users/jianliao/Work/scm/github/directus/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/jianliao/Work/scm/github/directus/node_modules/express/lib/router/route.js:137:13)\n    at /Users/jianliao/Work/scm/github/directus/api/src/middleware/collection-exists.ts:36:9",
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
2. Version rc.42

**Comment by jianliao** [comment]
My debug show that schema field was set to null for aliasFields in [service/fields.ts#L107-L117](https://github.com/directus/directus/blob/0eb7f01a3e851c25273ba77bf4e132d4a34e1b4d/api/src/services/fields.ts#L107-L117).

In [controllers/fields](https://github.com/directus/directus/blob/0eb7f01a3e851c25273ba77bf4e132d4a34e1b4d/api/src/controllers/fields.ts#L153-L163) Joi schema is setup schema property is required.

I can't tell what is wrong.
