### ISSUE TITLE
Unable to use multiple schemas in PostgreSQL

### ISSUE THREAD

**Issue by doron-cohen** [directus/directus#4322]
Hi, I am having issues with multiple schemas in Directus.
I am using Directus 9.0.0-rc.44 with PostgreSQL 13.

My end goal is to create a multi tenant application and for that I am going for the project scoping way. Each tenant will have it's own project, DB schema and remote cache namespace.

The issue I am trying to solve is how to share a set of tables with data that should be available to all tenants across all projects. I am trying to do that using a shared schema called `shared` and each tenant will have it's own `tenantX` schema.

When I try to pass multiple schema names in `DB_SEARCH_PATH` (`tenant1,shared`) to the configuration I get this issue: #3228. I believe I solved it with using `array:` prefix but then I get:

```
22:21:23 🚨 Cannot read property 'columns' of undefined 
TypeError: Cannot read property 'columns' of undefined
    at /Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:224:71
    at Generator.next (<anonymous>)
    at /Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:7:12)
    at getFieldsInCollection (/Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:223:20)
    at /Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:154:50
    at Generator.next (<anonymous>)
    at /Users/doroncohen/.cache/npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/utils/get-ast-from-query.js:11:71
    at new Promise (<anonymous>)
22:21:23 ✨ request errored GET 500 /server/info?limit=-1 27ms
```

I have to point out that the `shared` schema is empty. How can I make this work?

**Comment by doron-cohen** [comment]
Well, I think I solved this issue too. The shared schema needs to have Directus meta tables set up. So I ran `DB_SEARCH_PATH=shared npx directus bootstrap` and after that it worked just fine. Worth to document although I am still testing.
