### ISSUE TITLE
API Error with Where Clause

### ISSUE THREAD

**Issue by doodlemania2** [directus/directus#4336]
When performing an anonymous query against our data model, getting the following error in recent updates on RC43 and RC44. Was working in RC42-

```
17:19:45   🚨 select `sku`.`sku_name`, `sku`.`group`, `sku`.`id` from `sku` where   (`sku`.`id` in ('141') and `` = 'published') group by `sku`.`id` limit 1 -   ER_BAD_FIELD_ERROR: Unknown column '' in 'where clause'
--
Error: ER_BAD_FIELD_ERROR: Unknown column '' in 'where clause'
at Query.Sequence._packetToError   (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
at Query.ErrorPacket   (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
at Protocol._parsePacket   (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
at Parser._parsePacket   (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
at Parser.write   (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
at Protocol.write   (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
at Socket.<anonymous>   (/directus/node_modules/mysql/lib/Connection.js:88:28)
at Socket.<anonymous>   (/directus/node_modules/mysql/lib/Connection.js:526:10)
at Socket.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
--------------------
at Protocol._enqueue   (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
at Connection.query   (/directus/node_modules/mysql/lib/Connection.js:198:25)
at   /directus/node_modules/knex/lib/dialects/mysql/index.js:134:18
at new Promise (<anonymous>)
at Client_MySQL._query   (/directus/node_modules/knex/lib/dialects/mysql/index.js:128:12)
at Client_MySQL.query   (/directus/node_modules/knex/lib/client.js:168:17)
at Runner.query   (/directus/node_modules/knex/lib/runner.js:151:36)
at /directus/node_modules/knex/lib/runner.js:40:23
at /directus/node_modules/knex/lib/runner.js:277:24
at runMicrotasks (<anonymous>)
```
I see the error is showing an empty column that should be `Status`
This is from the endpoint, however, located at: https://fqdn/items/sku/141?fields=*.*

The public permissions are configured like this:

```json
{
    "status": {
        "eq": "published"
    }
}
```

At first, we thought it was because "Status" was not in Field Permissions, but we changed it to include Status. Same result.

The only change in our data model recently was moving a field up in the order.

**Comment by doodlemania2** [comment]
Any ideas on how we might run that one down? Same data model as the one I sent you offline if that helps any.

**Comment by rijkvanzanten** [comment]
I'm clearly more awake today than I was 23 hours ago. Try:

```json
{
    "status": {
        "_eq": "published"
    }
}
```

instead of 

```json
{
    "status": {
        "eq": "published"
    }
}
```

**Comment by doodlemania2** [comment]
Oh man, I'm an idiot - yeah, that was it - thought I had found a good bug for us! That fixed it right up 👍
