### ISSUE TITLE
MSSQL install issue

### ISSUE THREAD

**Issue by chriscrossman-ibm** [directus/directus#4427]
I encountered the following installation issue trying to setup directus to work with MSSQL:

```
user$ npx create-directus-project directus-cms
npx: installed 53 in 2.956s
? Choose your database client Microsoft SQL Server (Alpha)
? Database Host: 127.0.0.1
? Port: 1401
? Database Name: directus
? Database User: sa
? Database Password: *******
Error: knex: Unknown configuration option 'client' value tedious. Note that it is case-sensitive, check documentation for supported values.
    at resolveConfig (/directus/directus-cms/node_modules/knex/lib/knex-builder/internal/config-resolver.js:35:13)
    at Function.Knex (/directus/directus-cms/node_modules/knex/lib/knex-builder/Knex.js:10:39)
    at Object.createDBConnection [as default] (/directus/directus-cms/node_modules/directus/dist/cli/utils/create-db-connection.js:50:23)
    at /directus/directus-cms/node_modules/directus/dist/cli/commands/init/index.js:47:58
    at Generator.next (<anonymous>)
    at fulfilled (/directus/directus-cms/node_modules/directus/dist/cli/commands/init/index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29458) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/.npm/_npx/29458/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/.npm/_npx/29458/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems that knex expects this value to be 'mssql' rather than 'client'.  Has anyone seen this issue?  How would I resolve this?

**Comment by rijkvanzanten** [comment]
> It seems that knex expects this value to be 'mssql' rather than 'client'. Has anyone seen this issue? How would I resolve this?

Very close, I think Knex expects the value for client to be `mssql` rather than `tedious` 🙂

**Comment by rijkvanzanten** [comment]
(@nickrum fyi)
