### ISSUE TITLE
Can show related fields, but not able to filter them. 

### ISSUE THREAD

**Issue by irishburlybear** [directus/directus#4459]
I can retrieve these fields just fine. But when I try to filter them, it says there is no column. But there is a column.

I don't know if this has anything to do with the deep query.

I believe my query was working before.

My tables are: Table1 (Many to 1) -> Table 2 (Many to Many) -> Table 3 (Pivot) -> Table 4 (Target Field)

---

```
 select `entry_logs`.`id`, `entry_logs`.`sort`, `entry_logs`.`date_created`, `entry_logs`.`first_name`, `entry_logs`.`last_name`, `entry_logs`.`barcode`, `entry_logs`.`result`, `entry_logs`.`members_id` from `entry_logs` left join `members` as `qlCxI-A8` on `entry_logs`.`members_id` = `qlCxI-A8`.`id` where (`70o0mz9R`.`groups_id` = '49') limit 100 - ER_BAD_FIELD_ERROR: Unknown column '70o0mz9R.groups_id' in 'where clause' 
Error: ER_BAD_FIELD_ERROR: Unknown column '70o0mz9R.groups_id' in 'where clause'
    at Query.Sequence._packetToError (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/administrator/Programs/scac-db/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/administrator/Programs/scac-db/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    --------------------
    at Protocol._enqueue (/home/administrator/Programs/scac-db/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/administrator/Programs/scac-db/node_modules/mysql/lib/Connection.js:198:25)
    at /home/administrator/Programs/scac-db/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/administrator/Programs/scac-db/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/home/administrator/Programs/scac-db/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/home/administrator/Programs/scac-db/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/home/administrator/Programs/scac-db/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/home/administrator/Programs/scac-db/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/home/administrator/Programs/scac-db/node_modules/knex/lib/execution/runner.js:272:20)
10:25:52 ✨ request errored GET 500 /items/entry_logs?fields[]=*&fields[]=members_id.groups.groups_id&filter={%22members_id%22:{%22groups%22:{%22groups_id%22:{%22_eq%22:%2249%22}}}} 19ms
```

Filter:

```json
{
  "members_id": {
    "groups": {
      "groups_id": {
        "_eq": "49"
      }
    }
  }
}
```

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-65-generic
Node: 15.11.0

**Comment by rijkvanzanten** [comment]
This was resolved in https://github.com/directus/directus/pull/5615
