### ISSUE TITLE
Database migrations on rc.46 fail

### ISSUE THREAD

**Issue by lahdekorpi** [directus/directus#4469]
```sql
LOG_LEVEL=trace npx directus database migrate:latest
⠋ Running migrations...09:00:20 🔍 [3.263ms] select * from `directus_migrations` order by `version` asc []
⠙ Running migrations...09:00:20 🔍 [35.760ms] alter table `directus_fields` drop `locked` []
09:00:20 🔍 [2.820ms] insert into `directus_migrations` (`name`, `version`) values (?, ?) [Remove Locked Fields, 20210304A]
Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_activity_collection_foreign'; check that column/key exists
    at Query.Sequence._packetToError (/var/www/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/www/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    --------------------
    at Protocol._enqueue (/var/www/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/backend/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/backend/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/var/www/backend/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/var/www/backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/var/www/backend/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/var/www/backend/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/var/www/backend/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/var/www/backend/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlMessage: "Can't DROP 'directus_activity_collection_foreign'; check that column/key exists",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `directus_activity` drop foreign key `directus_activity_collection_foreign`'
}
```

**Comment by maartenvn** [comment]
I appear to have the same issue (#4470). Looks like we made the same issue at the same time :sweat_smile:

**Comment by lahdekorpi** [comment]
> I appear to have the same issue (#4470). Looks like we made the same issue at the same time 😅

On the same exact minute! 😂 

I'm running on MySQL 8.0.23-0ubuntu0.20.04.1.

**Comment by lahdekorpi** [comment]
Closing this in favor of  #4469
