### ISSUE TITLE
unique constraint - field schema save error 

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#4481]
#4467 

Can't save field schema after mark field as unique. 

```json
{
  "errors": [
    {
      "message": "alter table `faq_categories` add unique `faq_categories_alias_unique`(`alias`) - ER_DUP_KEYNAME: Duplicate key name 'faq_categories_alias_unique'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Directus: v9.0.0-rc.48 - Docker

![docker_unique_issue](https://user-images.githubusercontent.com/17914536/110797067-f8653200-8278-11eb-97e5-ad25b402b7bd.png)

**Comment by asteinarson** [comment]
I can fill in on this, but from the other side - I get an error that the Api cannot drop my constraint (which it shouldn't try to).

What is happening is that I edit a table field, under settings. I change some detail about the interface, and save it. I get this error then. 

I don't get this error in RC 0.44.

![Directus-AlterTable-DropConstraint](https://user-images.githubusercontent.com/8819538/110799443-71658900-827b-11eb-8b8d-e81867da2a14.png)

**Comment by asteinarson** [comment]
Here's a stack trace, on the server side: 
```
14:22:58 ✨ request errored PATCH 500 /fields/account/type 48ms
14:23:49 🚨 error alter table "account" drop constraint "account_type_unique" - constraint "account_type_unique" of relation "account" does not exist
error: alter table "account" drop constraint "account_type_unique" - constraint "account_type_unique" of relation "account" does not exist
    at Parser.parseErrorMessage (/home/arst/proj/ast_dir9/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/arst/proj/ast_dir9/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/arst/proj/ast_dir9/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/arst/proj/ast_dir9/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by nazariydj** [comment]
Here's mine: 

13:39:45 🚨 alter table `faq_categories` add unique `faq_categories_alias_unique`(`alias`) - ER_DUP_KEYNAME: Duplicate key name 'faq_categories_alias_unique' 
Error: ER_DUP_KEYNAME: Duplicate key name 'faq_categories_alias_unique'
    at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/directus/node_modules/mysql/lib/Connection.js:198:25)
    at /directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/directus/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/directus/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/directus/node_modules/knex/lib/execution/runner.js:241:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
13:39:45 ✨ request errored PATCH 500 /fields/faq_categories/alias 25ms

**Comment by doodlemania2** [comment]
+1 on that on my schema - it's a bit quirky

**Comment by rijkvanzanten** [comment]
Yeah, there's an issue in knex+mysql when creating a unique constraint on a field that already has one. We'll be pushing a fix shortly 👍🏻

**Comment by asteinarson** [comment]
To clarify, my database is Postgres (!). 
And I get the bug when just saving meta data changes (i.e. no table modifications requested).
