### ISSUE TITLE
Error connecting to an existing PostgreSQL database

### ISSUE THREAD

**Issue by mmattersdorfer** [directus/directus#4560]
Hi,

I wanted to try out Directus and started a new Directus project with a connection to an existing Postgres database. After starting Directus and the login with the user created while npx created the project, I will get the following error:

![image](https://user-images.githubusercontent.com/9654369/111348569-9f363d80-8680-11eb-99ac-dc993e914ad0.png)

Console output:
```
17:49:03 ­ƒÜ¿ error select "c"."column_name", "c"."table_name", "c"."data_type", "c"."column_default", "c"."character_maximum_length", "c"."is_nullable", "c"."numeric_precision", "c"."numeric_scale", "c"."table_schema", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = quote_ident(c.table_name)::regclass and pg_attribute.attname = c.column_name and pg_index.indisprimary) as "is_primary", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = c.table_name::regclass and pg_attribute.attname = c.column_name and pg_index.indisunique) as "is_unique", (select pg_catalog.col_description(pg_catalog.pg_class.oid, c.ordinal_position:: int) from "pg_catalog"."pg_class" where pg_catalog.pg_class.oid = (select('"' || c.table_name || '"'):: regclass:: oid) and "pg_catalog"."pg_class"."relname" = $1) as "column_comment", pg_get_serial_sequence(quote_ident(c.table_name), c.column_name) as serial, "ffk"."referenced_table_schema", "ffk"."referenced_table_name", "ffk"."referenced_column_name" from information_schema.columns c
        LEFT JOIN (
          SELECT
            k1.table_schema,
            k1.table_name,
            k1.column_name,
            k2.table_schema AS referenced_table_schema,
            k2.table_name AS referenced_table_name,
            k2.column_name AS referenced_column_name
          FROM
            information_schema.key_column_usage k1
            JOIN information_schema.referential_constraints fk using (
              constraint_schema, constraint_name
            )
            JOIN information_schema.key_column_usage k2 ON k2.constraint_schema = fk.unique_constraint_schema
            AND k2.constraint_name = fk.unique_constraint_name
            AND k2.ordinal_position = k1.position_in_unique_constraint
        ) ffk ON ffk.table_name = c.table_name
        AND ffk.column_name = c.column_name
       where "c"."table_schema" in ($2) order by "c"."table_name" asc, "c"."ordinal_position" asc - more than one row returned by a subquery used as an expression
error: select "c"."column_name", "c"."table_name", "c"."data_type", "c"."column_default", "c"."character_maximum_length", "c"."is_nullable", "c"."numeric_precision", "c"."numeric_scale", "c"."table_schema", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = quote_ident(c.table_name)::regclass and pg_attribute.attname = c.column_name and pg_index.indisprimary) as "is_primary", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = c.table_name::regclass and pg_attribute.attname = c.column_name and pg_index.indisunique) as "is_unique", (select pg_catalog.col_description(pg_catalog.pg_class.oid, c.ordinal_position:: int) from "pg_catalog"."pg_class" where pg_catalog.pg_class.oid = (select('"' || c.table_name || '"'):: regclass:: oid) and "pg_catalog"."pg_class"."relname" = $1) as "column_comment", pg_get_serial_sequence(quote_ident(c.table_name), c.column_name) as serial, "ffk"."referenced_table_schema", "ffk"."referenced_table_name", "ffk"."referenced_column_name" from information_schema.columns c
        LEFT JOIN (
          SELECT
            k1.table_schema,
            k1.table_name,
            k1.column_name,
            k2.table_schema AS referenced_table_schema,
            k2.table_name AS referenced_table_name,
            k2.column_name AS referenced_column_name
          FROM
            information_schema.key_column_usage k1
            JOIN information_schema.referential_constraints fk using (
              constraint_schema, constraint_name
            )
            JOIN information_schema.key_column_usage k2 ON k2.constraint_schema = fk.unique_constraint_schema
            AND k2.constraint_name = fk.unique_constraint_name
            AND k2.ordinal_position = k1.position_in_unique_constraint
        ) ffk ON ffk.table_name = c.table_name
        AND ffk.column_name = c.column_name
       where "c"."table_schema" in ($2) order by "c"."table_name" asc, "c"."ordinal_position" asc - more than one row returned by a subquery used as an expression
    at Parser.parseErrorMessage (C:\Dev\liferay-7.3-rest-db\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Dev\liferay-7.3-rest-db\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Dev\liferay-7.3-rest-db\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Dev\liferay-7.3-rest-db\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

    What version of Directus you are using. **9.0.0-rc.50**
    Which DBMS are you using (MySQL 8, Postgres 12, ...). Postgres 12.5 (running in Docker)
    Which deployment are you using (npx, Docker, ...). Posgres running in Docker, Directus directly on my Win10-Machine with npx
    What browser are you using (Chrome 87, Safari 14, ...). Chrome 89.0.4389.82, MS Edge 89.0.774.45

Database Dump (/usr/local/pgsql-13/pg_dumpall --file "/var/lib/pgadmin/storage/pgadmin_usu.com/l73-postgres.dump" --host "l73-postgres" --port "5432" --username "liferay" --no-password --database "liferay" --verbose --role "liferay" --encoding "UTF8") is attached.
[l73-postgres.zip](https://github.com/directus/directus/files/6150931/l73-postgres.zip)

**Comment by patvong** [comment]
I have the same issue with both version rc50 and rc51.

**Comment by rijkvanzanten** [comment]
@mmattersdorfer I just setup your dump on my end, and it seems to run as expected 🤔 

Could you try this again in the latest RC to confirm if it is still a problem?

![CleanShot 2021-04-09 at 19 35 29@2x](https://user-images.githubusercontent.com/9141017/114250172-d1c71380-996a-11eb-9ecf-e3a88da108f3.png)


I think this is fixed in https://github.com/knex/knex-schema-inspector/commit/c38d1b7a3165bfd1fdc88161d96ab4598faeec88

**Comment by mmattersdorfer** [comment]
Yeah it is fixed. Thx.
