### ISSUE TITLE
File Storage Upload and Read not Working from Heroku

### ISSUE THREAD

**Issue by wizzuae** [directus/directus#4614]
Everything working from localhost, but not working from Heroku

It's happen when try to upload a image and also when try to access an image already uploaded via localhost.

Localhost URL ex: http://localhost:8055/assets/8708948a-fb04-428f-8a2a-26e787c ************
Heroku URL ex: http://my-project.herokuapp.com/assets/8708948a-fb04-428f-8a2a-26e787c ************

**ERROR**
````
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file /321b7f09-afb0-4e6d-aa13-ed2d37d233b1.webp.\n\nError code: Forbidden\nOriginal stack:\nForbidden: null\n    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:692:35)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Scaleway Object Storage Integration**
```
## File Storage

STORAGE_LOCATIONS="cloud"
STORAGE_CLOUD_DRIVER="s3"
STORAGE_CLOUD_ROOT="/"
STORAGE_CLOUD_PUBLIC_URL="https://wi****.s3.fr-par.scw.cloud"
STORAGE_CLOUD_KEY="*************************"
STORAGE_CLOUD_SECRET="******************************"
STORAGE_CLOUD_BUCKET="wi****"
STORAGE_CLOUD_REGION="fr-par"
STORAGE_CLOUD_ENDPOINT="https://s3.fr-par.scw.cloud"
````
---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 4.4.0-1086-aws
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
This is most likely a configuration problem in Heroku.. That error `Error code: Forbidden` is returned by the storage provider, so I'm assuming there's a misconfiguration coming from Heroku 🤔
