### ISSUE TITLE
Can't use PostgreSQL and uppercased Table names

### ISSUE THREAD

**Issue by mape** [directus/directus#4708]
I'm poking around with Prisma (https://www.prisma.io/) and Directus (9.0.0-rc.51).
When using Prisma to generate db tables their convention is:

```js
model Test {
    id   Int    @id @default(autoincrement())
    name String @db.VarChar(255)
}
```

which ends up as:

```sql
CREATE DATABASE "testDb"
    WITH 
    OWNER = admin
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

CREATE TABLE "Test" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,

    PRIMARY KEY ("id")
);
```

I install Directus
```> npx create-directus-project directusRepro
npx: installed 54 in 5.031s
? Choose your database client PostgreSQL / Redshift
? Database Host: postgres.domain.tld
? Port: 5432
? Database Name: testDb
? Database User: admin
? Database Password: ********
? Enable SSL: No

Create your first admin user:
? Email admin@domain.tld
? Password ********

Your project has been created at C:\code\directusRepro.

The configuration can be found in C:\code\directusRepro/.env

Start Directus by running:
  cd C:\code\directusRepro
  npx directus start
```
After that is finished I start and login to the admin.
It shows an error page, console outputs:
```
error: select "c"."column_name", "c"."table_name", "c"."data_type", "c"."column_default", "c"."character_maximum_length", "c"."is_nullable", "c"."numeric_precision", "c"."numeric_scale", "c"."table_schema", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = quote_ident(c.table_name)::regclass and pg_attribute.attname = c.column_name and pg_index.indisprimary) as "is_primary", (select 'YES' from "pg_index" 
inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = c.table_name::regclass and pg_attribute.attname = c.column_name and pg_index.indisunique) as "is_unique", (select pg_catalog.col_description(pg_catalog.pg_class.oid, c.ordinal_position:: int) from "pg_catalog"."pg_class" where pg_catalog.pg_class.oid = 
(select('"' || c.table_name || '"'):: regclass:: oid) and "pg_catalog"."pg_class"."relname" = $1) as "column_comment", pg_get_serial_sequence(quote_ident(c.table_name), c.column_name) as serial, "ffk"."referenced_table_schema", "ffk"."referenced_table_name", "ffk"."referenced_column_name" from information_schema.columns c
        LEFT JOIN (
          SELECT
            k1.table_schema,
            k1.table_name,
            k1.column_name,
            k2.table_schema AS referenced_table_schema,
            k2.table_name AS referenced_table_name,
            k2.column_name AS referenced_column_name
          FROM
            information_schema.key_column_usage k1
            JOIN information_schema.referential_constraints fk using (
              constraint_schema, constraint_name
            )
            JOIN information_schema.key_column_usage k2 ON k2.constraint_schema = fk.unique_constraint_schema
            AND k2.constraint_name = fk.unique_constraint_name
            AND k2.ordinal_position = k1.position_in_unique_constraint
        ) ffk ON ffk.table_name = c.table_name
        AND ffk.column_name = c.column_name
       where "c"."table_schema" in ($2) order by "c"."table_name" asc, "c"."ordinal_position" asc - relation "test" does not exist     
    at Parser.parseErrorMessage (C:\code\directusRepro\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\code\directusRepro\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\code\directusRepro\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\code\directusRepro\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

If I rename the table to **test** everything seems to work as intended and I can create an item.

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Windows_NT 10.0.18363 (db is on linux)
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/discussions/4683

**Comment by eliashussary** [comment]
@rijkvanzanten  same issue with camelCase tables - i've narrowed it down to `knex-schema-inspector` - looks like that's your contribution to `knex`? _nice!_ 

gonna revert to a previous build for now.


```
select "c"."column_name", "c"."table_name", "c"."data_type", "c"."column_default", "c"."character_maximum_length", "c"."is_nullable", "c"."numeric_precision", "c"."numeric_scale", "c"."table_schema", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = quote_ident(c.table_name)::regclass and pg_attribute.attname = c.column_name and pg_index.indisprimary) as "is_primary", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = c.table_name::regclass and pg_attribute.attname = c.column_name and pg_index.indisunique) as "is_unique", (select pg_catalog.col_description(pg_catalog.pg_class.oid, c.ordinal_position:: int) from "pg_catalog"."pg_class" where pg_catalog.pg_class.oid = (select('"' || c.table_name || '"'):: regclass:: oid) and "pg_catalog"."pg_class"."relname" = $1) as "column_comment", pg_get_serial_sequence(quote_ident(c.table_name), c.column_name) as serial, "ffk"."referenced_table_schema", "ffk"."referenced_table_name", "ffk"."referenced_column_name" from information_schema.columns c 
        LEFT JOIN (
          SELECT
            k1.table_schema,
            k1.table_name,
            k1.column_name,
            k2.table_schema AS referenced_table_schema,
            k2.table_name AS referenced_table_name,
            k2.column_name AS referenced_column_name
          FROM
            information_schema.key_column_usage k1
            JOIN information_schema.referential_constraints fk using (
              constraint_schema, constraint_name
            )
            JOIN information_schema.key_column_usage k2 ON k2.constraint_schema = fk.unique_constraint_schema
            AND k2.constraint_name = fk.unique_constraint_name
            AND k2.ordinal_position = k1.position_in_unique_constraint
        ) ffk ON ffk.table_name = c.table_name
        AND ffk.column_name = c.column_name
       where "c"."table_schema" in ($2) order by "c"."table_name" asc, "c"."ordinal_position" asc - relation "subscriptionevents" does not exist
```
... **`relation "subscriptionevents" does not exist`**

**Comment by rijkvanzanten** [comment]
> looks like that's your contribution to knex? nice!

Yup! Knex didn't have any schema-reading capabilities, so I started that project to offer an abstracted way to do schema-reading 🙂 

---

IIRC there's a combination of these flags in PG that transforms it to lowercase 🤔 

`... quote_ident(c.table_name)::regclass ...`
`... select('"' || c.table_name || '"'):: regclass:: oid ...`

not sure exactly though

**Comment by eliashussary** [comment]
@rijkvanzanten  yeah i've had some success modifying the query - i'm gonna timebox another 30mins on trying to fix it before rolling back

**Comment by eliashussary** [comment]
@rijkvanzanten  so i can get the queries to run with `quote_ident(c.table_name)::regclass` . 

i have a new issue, which is still relevant as I imagine others will encounter this. - my directus env was installed ontop of an existing database, so this is likely to crop up anyway... see below

one of the subqueries will return multiple rows based on your current conditions

![image](https://user-images.githubusercontent.com/7349258/112870049-cb43bc80-908b-11eb-97ed-3c6270e9a501.png)
![image](https://user-images.githubusercontent.com/7349258/112870365-1fe73780-908c-11eb-9ed3-bab725f9b9b0.png)

without digging further, i'm assuming you just need to return `'YES'` if the column is unique, regardless of how many indexes exist?

if that is the case then the fix is relatively easy, we can just `case when count(1) > 0 then 'YES' else null end`

**Comment by rijkvanzanten** [comment]
> without digging further, i'm assuming you just need to return 'YES' if the column is unique, regardless of how many indexes exist?

Yes!

Another potential solve should be to use a `left join` instead of an `inner join` I think

Mind opening a PR to knex-schema-inspector @eliashussary? 🙂

**Comment by eliashussary** [comment]
@rijkvanzanten 
https://github.com/knex/knex-schema-inspector/pull/37
