### ISSUE TITLE
500 Error assets after creating entry

### ISSUE THREAD

**Issue by tonxxd** [directus/directus#5124]
I just started using Directus v9 and seems amazing! I am encountering a couple of bugs like the one described here 

**1) The issue and what you expected to happen**
   Can't access any assets anymore, I get a generic 500 error

```shell
15:53:50 ✨ request errored GET 500 /assets/a15627b9-84fb-48e4-8a13-5c1e5d716d53?key=system-medium-cover&modified=2021-04-16T14:51:20+02:00&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIxMGZiMjkwLWUxNWEtNGVmMi1iNzQwLWRlMGI1NThiOTE3OSIsImlhdCI6MTYxODY2NzYyMywiZXhwIjoxNjE4NjY4NTIzfQ.NpR1DkuIBQoFzRWGNyCWlwcOF-mwjfy0hFWp4ZMGdmc 647ms
15:53:50 🚨 E_UNKNOWN: An unknown error happened with the file f38dfdcb-cf36-463d-aeb1-ba6e31d55661.png.

Error code: BadRequest
Original stack:
BadRequest: null
    at Request.extractError (/node_modules/aws-sdk/lib/services/s3.js:698:35)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
UnknownException: E_UNKNOWN: An unknown error happened with the file f38dfdcb-cf36-463d-aeb1-ba6e31d55661.png.

Error code: BadRequest
Original stack:
BadRequest: null
    at Request.extractError (/node_modules/aws-sdk/lib/services/s3.js:698:35)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at handleError (/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:19:20)
    at AmazonWebServicesS3Storage.exists (/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:98:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```    

**2) Exact steps to reproduce this issue**
    
I tried to create an asset using the sdk

```javascript
await directus.files.createOne({
   url: url,   // as string 
   ...
})
```
Assets endpoint not working anymore and thus also all the media in the admin panel (including the logo) don't show up

I noticed that an new row is created in the files table in the db but not showing up in the file explorer in the app

**3) Your environment:**
    What version of Directus you are using. v9
    Which DBMS are you using  MySQL 
    Which deployment are you using npx on mac
    What browser are you using (Chrome 87, Safari 14, ...).

**4) Any other relevant information we might need to reproduce this issue**
    
    What third party services you rely on: S3

**Comment by tonxxd** [comment]
**Update:** 
After uploading a new asset from the dashboard all the other assets links seem to be restored. Could be related to some caching? But I restarted the project so I don't see how the cache would persist to a full restart unless it stores something in the remote database

**Comment by rijkvanzanten** [comment]
> After uploading a new asset from the dashboard all the other assets links seem to be restored. Could be related to some caching? 

Could be, hard to tell! In this case, it was S3 that threw the `BadRequest: null` error, so it's a little hard to conclusively say if something went wrong in Directus itself, in S3, or in the connection between the two.. 

I'll close this for now, as it seems to work as expected now. If the issue pops up again, and we have an accurate way to reproduce it we'll reopen and investigate 👍🏻
