### ISSUE TITLE
Unknown column 'accountability' in 'field list' errors on admin routes after upgrading to RC60

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#5208]
Hi team,

We just upgraded from RC59 to RC60. After this accessing the admin app shows these errors in the console. I only pasted 2, just for reference.

```08:11:59 ✨ request completed GET 200 /admin/fonts/Inter-Medium.c709803c.woff2 6ms
08:11:59 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/src/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/src/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/src/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/src/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/src/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (/src/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/src/node_modules/mysql/lib/Connection.js:198:25)
    at /src/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/src/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/src/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/src/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/src/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/src/node_modules/knex/lib/execution/runner.js:272:20)
08:11:59 ✨ request errored POST 500 /auth/refresh 36ms
08:11:59 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/src/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/src/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/src/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/src/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/src/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/src/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (/src/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/src/node_modules/mysql/lib/Connection.js:198:25)
    at /src/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/src/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/src/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/src/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/src/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/src/node_modules/knex/lib/execution/runner.js:272:20)
08:11:59 ✨ request errored GET 500 /server/info?limit=-1 36ms```

**Comment by MadnessCODE** [comment]
@keesvanbemmel  Did you run 'npx directus database migrate:latest' ?

**Comment by keesvanbemmel** [comment]
Wow, that is really annoying. I have the migrate:latest command in this startup script of my docker container which I use for development:

```
#!/usr/bin/env bash
set -e
npx directus database migrate:latest
npx directus start
```

So I assumed I had. However, docker-compose runs a completely different startup script 🤦 

Thanks for identifying a local development setup issue :) I'll close this now.
