### ISSUE TITLE
Fail to build from source (webpack dep problem?)

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#5268]
macOS Big Sur (M1)
Directus 9.0.0-rc.61
PG 12
Node v15.14.0

--

Having a hard time building the code from source (new clean install without any extensions):

`npm run build`

It fails on:

```
> @directus/app@9.0.0-rc.61 build
> vue-cli-service build
```

With error:

```
lerna ERR! npm run build stderr:
-  Building for production...
 ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": [
    null
     ],
  "use": [
      {
      "loader": "/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js",
      "options": {
        "cacheDirectory": "/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/app/node_modules/.cache/babel-loader",
        "cacheIdentifier": "6b93e66c"
      },
      "ident": "clonedRuleSet-38[0].rules[0].use[0]"
     },
      {
      "loader": "/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-plugin-babel/node_modules/thread-loader/dist/cjs.js",
      "options": "undefined",
      "ident": "undefined"
     },
      {
      "loader": "/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/babel-loader/lib/index.js",
      "options": "undefined",
      "ident": "undefined"
      }
      ]
      }
```

Trace:

```
    at checkResourceSource (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:198:4)
    at /Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:636:31)
    at Compiler.newCompilationParams (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:653:30)
    at Compiler.compile (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:661:23)
    at /Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at run (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:248:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/danielwestman/Projekt/Grannskap/custom-directus/directus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
```

The problem seems to have to do with webpack (v.5.x). When downgrading to a older version:

```
npm uninstall webpack
npm install webpack@^4.0.0 --save-dev
```

It all works!

Any thoughts?

**Comment by paescuj** [comment]
It does work for me with a fresh clone of 9.0.0-rc.61 on macOS.
Also in my case webpack got installed in v4 (which is actually required by vue). Can you check which version of webpack is installed when you do "npm install" on a fresh clone?
