### ISSUE TITLE
npm update from RC 59 -> RC 61 accountability column missing...

### ISSUE THREAD

**Issue by irishburlybear** [directus/directus#5323]
ran npm update in directus directory. 
Version RC 59 to RC 61:
Got this:

administrator@customer-portal:~/Programs/directus-api$ npx directus start
12:05:12 ✨ Server started at port 8055
12:05:15 ✨ request completed GET 304 /admin 4ms
12:05:15 ✨ request completed GET 304 /admin/css/app.a3183a91.css 4ms
12:05:15 ✨ request completed GET 304 /admin/css/chunk-vendors.2b987c5b.css 3ms
12:05:15 ✨ request completed GET 304 /admin/js/app.e47e9984.js 3ms
12:05:15 ✨ request completed GET 304 /admin/js/chunk-vendors.ec007636.js 3ms
12:05:15 ✨ request completed GET 304 /admin/js/interface-wysiwyg.148204f3.js 2ms
12:05:15 ✨ request completed GET 304 /admin/js/markdown.acb1f1ae.js 3ms
12:05:15 ✨ request completed GET 200 /admin/img/icons/android-chrome-192x192.png 3ms
12:05:15 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/administrator/Programs/blankrome/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/administrator/Programs/blankrome/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    --------------------
    at Protocol._enqueue (/home/administrator/Programs/blankrome/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/administrator/Programs/blankrome/node_modules/mysql/lib/Connection.js:198:25)
    at /home/administrator/Programs/blankrome/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/administrator/Programs/blankrome/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/home/administrator/Programs/blankrome/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/home/administrator/Programs/blankrome/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/home/administrator/Programs/blankrome/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/home/administrator/Programs/blankrome/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/home/administrator/Programs/blankrome/node_modules/knex/lib/execution/runner.js:272:20)

I solved it by adding the accountability field manually but I don't know what kind of field it is so I defaulted and used a VARCHAR 255 type.

**Comment by benhaynes** [comment]
Did you run the database migration command?

**Comment by irishburlybear** [comment]
No. I never came across any documentation about running a migration command. I've always just updated npm and went on.
Can you point me to that and maybe highlight that for others?

**Comment by YannickMol** [comment]
Here you go! https://docs.directus.io/guides/projects/#upgrading-a-project

**Comment by irishburlybear** [comment]
Thank you. I now know another step I need to do between upgrades.
