### ISSUE TITLE
SQL query error

### ISSUE THREAD

**Issue by Meldiron** [directus/directus#5370]
Using Directus RC61 I keep getting this error when trying to update an item in a collection:

```
{
  "message": "SELECT * FROM collections_products WHERE id =  LIMIT 1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 1' at line 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

![image](https://user-images.githubusercontent.com/19310830/116564959-b74adf00-a905-11eb-8c21-4076113e2715.png)

The problem seems to be with MTM relation. I have also seen error in sql query with `WHERE id = 1, 2`, not sure if that error is related to this one.

**Comment by rijkvanzanten** [comment]
Could you share some more information on the schema setup / MariaDB version? Seems like the top level item save doesn't extract the primary key correctly, which means that the nested updates can't be performed as the primary key isn't known

**Comment by Meldiron** [comment]
I am using `image: mariadb:10` for SQL server (docker).

Collection contains multiple products (M2M)
![image](https://user-images.githubusercontent.com/19310830/116569239-7d7bd780-a909-11eb-980a-5570ec14adf2.png)


My field setup is:

![image](https://user-images.githubusercontent.com/19310830/116569256-82408b80-a909-11eb-806c-600c08854b40.png)

![image](https://user-images.githubusercontent.com/19310830/116569264-84a2e580-a909-11eb-96a0-8c58bbb2ca24.png)

![image](https://user-images.githubusercontent.com/19310830/116569275-879dd600-a909-11eb-9cf1-ba5b8eed4aff.png)

![image](https://user-images.githubusercontent.com/19310830/116569286-8a003000-a909-11eb-9189-ec9c253d6d73.png)

![image](https://user-images.githubusercontent.com/19310830/116569294-8b315d00-a909-11eb-9763-8dc92d74c48e.png)


Collection table schema:
![image](https://user-images.githubusercontent.com/19310830/116569410-a56b3b00-a909-11eb-8d1b-57a5ceb75e09.png)

Products table schema:
![image](https://user-images.githubusercontent.com/19310830/116569504-bf0c8280-a909-11eb-844f-ab0ad72fa045.png)

**Comment by Meldiron** [comment]
Sorry, I forgot about table to join these two, here is the schema:
![image](https://user-images.githubusercontent.com/19310830/116569714-f11de480-a909-11eb-83d9-81daa80b01d9.png)

**Comment by Meldiron** [comment]
Hello, today I found out the problem was inside a hook that was running in `.update.before`. When I removed all hooks from the extensions folder, the problem was gone.

I am sorry if I wasted your time. The only idea to think about might be: Can we somehow separate Directus and hook errors? This was the full error I got:
```
objednajsidomov_admin_1  | 08:03:26 🚨 SELECT * FROM collections_products WHERE id =  LIMIT 1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 1' at line 1 
objednajsidomov_admin_1  | Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 1' at line 1
objednajsidomov_admin_1  |     at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
objednajsidomov_admin_1  |     at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
objednajsidomov_admin_1  |     at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
objednajsidomov_admin_1  |     at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
objednajsidomov_admin_1  |     at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
objednajsidomov_admin_1  |     at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
objednajsidomov_admin_1  |     at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)
objednajsidomov_admin_1  |     at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)
objednajsidomov_admin_1  |     at Socket.emit (events.js:315:20)
objednajsidomov_admin_1  |     at addChunk (internal/streams/readable.js:309:12)
objednajsidomov_admin_1  |     --------------------
objednajsidomov_admin_1  |     at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
objednajsidomov_admin_1  |     at Connection.query (/directus/node_modules/mysql/lib/Connection.js:198:25)
objednajsidomov_admin_1  |     at /directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
objednajsidomov_admin_1  |     at new Promise (<anonymous>)
objednajsidomov_admin_1  |     at Client_MySQL._query (/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
objednajsidomov_admin_1  |     at executeQuery (/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
objednajsidomov_admin_1  |     at Client_MySQL.query (/directus/node_modules/knex/lib/client.js:134:12)
objednajsidomov_admin_1  |     at /directus/node_modules/knex/lib/execution/transaction.js:363:24
objednajsidomov_admin_1  |     at new Promise (<anonymous>)
objednajsidomov_admin_1  |     at Client_MySQL.trxClient.query (/directus/node_modules/knex/lib/execution/transaction.js:358:12)
objednajsidomov_admin_1  | 08:03:26 ✨ request errored PATCH 500 /items/collections/1 58ms
```

Log like `running product-hook` or `Error thrown in product-hook` might be a great addition to prevent issues just like mine.
