### ISSUE TITLE
Google Cloud Storage driver error

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#5431]
When trying to upload a file to GCS, it doesn't work.

Full message:
```
Error code: undefined
Original stack:
TypeError: key must be a string, a buffer or an object
    at typeError (/Users/nitoref/github/directus/node_modules/google-auth-library/node_modules/jwa/index.js:115:10)
    at checkIsPrivateKey (/Users/nitoref/github/directus/node_modules/google-auth-library/node_modules/jwa/index.js:61:9)
    at Object.sign (/Users/nitoref/github/directus/node_modules/google-auth-library/node_modules/jwa/index.js:147:5)
    at Object.jwsSign [as sign] (/Users/nitoref/github/directus/node_modules/google-auth-library/node_modules/jws/lib/sign-stream.js:32:24)
    at JWTAccess.getRequestHeaders (/Users/nitoref/github/directus/node_modules/google-auth-library/build/src/auth/jwtaccess.js:87:31)
    at JWT.getRequestMetadataAsync (/Users/nitoref/github/directus/node_modules/google-auth-library/build/src/auth/jwtclient.js:76:51)
    at JWT.getRequestHeaders (/Users/nitoref/github/directus/node_modules/google-auth-library/build/src/auth/oauth2client.js:236:37)
    at GoogleAuth.authorizeRequest (/Users/nitoref/github/directus/node_modules/google-auth-library/build/src/auth/googleauth.js:593:38)
```

I defined the appropriate environment variables (DRIVER, PUBLIC_URL, KEY_FILENAME, BUCKET).
I tried setting an incorrect filename and it's handled appropriately. I tried setting different buckets url (`my_bucket`, `browser/my_bucket`, `storage/browser/my_bucket`) and get the same result each time.

Directus v9.0.0-rc.59, Postgres 13.

**Comment by rijkvanzanten** [comment]
So to confirm, when using

```
STORAGE_<DRIVER>_KEY_FILENAME
```

with an invalid value, it throws a correct error?

Makes me think think Directus itself is passing the value correctly, and it being `@google-cloud/storage` that's having a little brainfart 🤔

**Comment by rijkvanzanten** [comment]
I just tried this locally, with a "freshly" downloaded json keyfile from GCS, and everything is working as expected 🤔 

I don't think this is an issue in how Directus passes the key file to @google-cloud/storage, as omitting the file throws a different error altogether: 

```
directus: Error code: undefined
directus: Original stack:
directus: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
directus:     at GoogleAuth.getApplicationDefaultAsync (/Users/rijkvanzanten/Developer/directus/directus/node_modules/google-auth-library/build/src/auth/googleauth.js:173:19)
directus:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
directus:     at GoogleAuth.getClient (/Users/rijkvanzanten/Developer/directus/directus/node_modules/google-auth-library/build/src/auth/googleauth.js:551:17)
directus:     at GoogleAuth.authorizeRequest (/Users/rijkvanzanten/Developer/directus/directus/node_modules/google-auth-library/build/src/auth/googleauth.js:592:24)
```

However, I _am_ able to reproduce your issue by going into the key.json file that Google provides and removing the `private_key` field from the JSON object. That results in:

```
directus: Error code: undefined
directus: Original stack:
directus: TypeError: key must be a string, a buffer or an object
```

which is the issue you shared. Which only leaves me to conclude that the key.json file you're using is wrong / corrupt :o
