### ISSUE TITLE
Default ACL to undefined instead of empty string

### ISSUE THREAD

**Issue by pichot** [directus/directus#5435]
When trying to upload a file to an S3-compatible service (which has previously worked), the upload throws an error.

May have the same root cause as https://github.com/directus/directus/issues/5431. 

On upload, logs show:
```
2021-05-03T16:32:08.345299709Z app[web.1]: 16:32:08 ⚠️  Couldn't save file a09bd474-446d-4337-81fa-19385f6e5c83.jpeg
2021-05-03T16:32:08.348641662Z app[web.1]: 16:32:08 ⚠️  E_UNKNOWN: An unknown error happened with the file a09bd474-446d-4337-81fa-19385f6e5c83.jpeg.
2021-05-03T16:32:08.348820539Z app[web.1]:
2021-05-03T16:32:08.348835347Z app[web.1]: Error code: InvalidArgument
2021-05-03T16:32:08.348845395Z app[web.1]: Original stack:
2021-05-03T16:32:08.348856355Z app[web.1]: InvalidArgument: Invalid Argument.
2021-05-03T16:32:08.348865172Z app[web.1]:     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:718:35)
2021-05-03T16:32:08.348874109Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2021-05-03T16:32:08.348883677Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2021-05-03T16:32:08.348893064Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
2021-05-03T16:32:08.348902863Z app[web.1]:     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
2021-05-03T16:32:08.348912761Z app[web.1]:     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
2021-05-03T16:32:08.348923393Z app[web.1]:     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
2021-05-03T16:32:08.348976673Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
2021-05-03T16:32:08.348998954Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
2021-05-03T16:32:08.349008682Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2021-05-03T16:32:08.494866379Z app[web.1]: 16:32:08 🚨 E_UNKNOWN: An unknown error happened with the file a09bd474-446d-4337-81fa-19385f6e5c83.jpeg.
2021-05-03T16:32:08.494932594Z app[web.1]:
2021-05-03T16:32:08.494945298Z app[web.1]: Error code: NotFound
2021-05-03T16:32:08.494956528Z app[web.1]: Original stack:
2021-05-03T16:32:08.494966228Z app[web.1]: NotFound: null
2021-05-03T16:32:08.494977018Z app[web.1]:     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:698:35)
2021-05-03T16:32:08.494987528Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2021-05-03T16:32:08.494998579Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2021-05-03T16:32:08.495007225Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
2021-05-03T16:32:08.495015400Z app[web.1]:     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
2021-05-03T16:32:08.495024247Z app[web.1]:     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
2021-05-03T16:32:08.495034346Z app[web.1]:     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
2021-05-03T16:32:08.495042922Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
2021-05-03T16:32:08.495056657Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
2021-05-03T16:32:08.495071465Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2021-05-03T16:32:08.495080873Z app[web.1]: UnknownException: E_UNKNOWN: An unknown error happened with the file a09bd474-446d-4337-81fa-19385f6e5c83.jpeg.
2021-05-03T16:32:08.495088347Z app[web.1]:
2021-05-03T16:32:08.495095681Z app[web.1]: Error code: NotFound
2021-05-03T16:32:08.495104367Z app[web.1]: Original stack:
2021-05-03T16:32:08.495113243Z app[web.1]: NotFound: null
2021-05-03T16:32:08.495122721Z app[web.1]:     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:698:35)
2021-05-03T16:32:08.495133372Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2021-05-03T16:32:08.495142699Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2021-05-03T16:32:08.495156375Z app[web.1]:     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
2021-05-03T16:32:08.495167726Z app[web.1]:     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
2021-05-03T16:32:08.495177054Z app[web.1]:     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
2021-05-03T16:32:08.495185659Z app[web.1]:     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
2021-05-03T16:32:08.495268907Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
2021-05-03T16:32:08.495285819Z app[web.1]:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
2021-05-03T16:32:08.495295887Z app[web.1]:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2021-05-03T16:32:08.495304413Z app[web.1]:     at handleError (/app/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:19:20)
2021-05-03T16:32:08.495317828Z app[web.1]:     at AmazonWebServicesS3Storage.getStat (/app/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:163:19)
2021-05-03T16:32:08.495326936Z app[web.1]:     at runMicrotasks (<anonymous>)
2021-05-03T16:32:08.495336874Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-03T16:32:08.495584720Z app[web.1]: 16:32:08 ✨ request errored POST 500 /files 458ms
```

I have these environment variables set:
```
STORAGE_LOCATIONS:          scaleway
STORAGE_SCALEWAY_BUCKET:    *****
STORAGE_SCALEWAY_DRIVER:    s3
STORAGE_SCALEWAY_ENDPOINT:  s3.fr-par.scw.cloud
STORAGE_SCALEWAY_KEY:       *****
STORAGE_SCALEWAY_REGION:    fr-par
STORAGE_SCALEWAY_SECRET:    *****
```

Running : 
```
Directus 9.0.0-rc.61
Postgres 12.5
```

**Comment by Oreilles** [comment]
Probably not related to #5431, I only faced the issue with GCS. I've just set up a Amazon S3 bucket instead and it worked flawlessly. The region and endpoint seem redundant to me. Have you tried removing the region ? Or setting only the endpoint as <bucket>.s3.<region>.<provider>.<tld> ?

**Comment by meezaan** [comment]
I can confirm that I am facing the same issue with v9.0.0-rc.68.

@Oreilles I have tried removing the the region to use just the endpoint with the FQDN of the actual bucket, but the error is still the same.

**Comment by wc-matteo** [comment]
same issue here with scaleway

**Comment by meezaan** [comment]
It is Linode in my case so I don't think the problem is provider specific.

**Comment by aidenfoxx** [comment]
It could be that you don't have permissions to write to the root? If you've been allocated a directory you can set it with `STORAGE_SCALEWAY_ROOT="mydir"`?

**Comment by meezaan** [comment]
> It could be that you don't have permissions to write to the root? If you've been allocated a directory you can set it with `STORAGE_SCALEWAY_ROOT="mydir"`?

That is at least not the case for me.

**Comment by aidenfoxx** [comment]
@meezaan Maybe it's an issue with the endpoint? I know the URL is partially generated by the `aws-sdk` module. I'd try:

```
// Replace `fr-par` with your region
STORAGE_SCALEWAY_ENDPOINT:  scw.cloud
OR
STORAGE_SCALEWAY_ENDPOINT:  fr-par.scw.cloud
```

Either way, this issue isn't necessarily with Directus since it's basically acting as a pass-through for `aws-sdk` which is causing throwing the error.

**Comment by wc-matteo** [comment]
I found the fix for my case.

**Comment by wc-matteo** [comment]
I found the fix for my case:

the api doesn't like that [empty string](https://github.com/directus/directus/blob/main/packages/drive-s3/src/AmazonWebServicesS3Storage.ts#L52) for the acl. The fast fix is to fill `STORAGE_<LOCATION>_ACL` with one of [these](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl), the real fix would be to change `''` to `undefined`

**Comment by meezaan** [comment]
Great stuff @wc-matteo! That did the trick!

**Comment by rijkvanzanten** [comment]
Ref:

https://github.com/directus/directus/blob/bb14309b9c16aa29eac9422f105d310ce5a6cf03/packages/drive-s3/src/AmazonWebServicesS3Storage.ts#L52
