### ISSUE TITLE
Applying migrations error, duplicate column name

### ISSUE THREAD

**Issue by avatarbabe** [directus/directus#5672]
I'm trying to upgrade from RC57 to RC64. But when I try to apply the latest migrations with 'npx directus database migrate:latest'. I get an sql-error 'Duplicate column name 'sort_field''. And if I don't run the migrations I get this error in the application:

"Select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'"

This is the stacktrace for the duplicate column error:
`` $ npx directus database migrate:latest
✨ Running migrations...
✨ Applying Add Relations Sort Field...
Error: ER_DUP_FIELDNAME: Duplicate column name 'sort_field'
    at Query.Sequence._packetToError (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\marsod\Downloads\248\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\marsod\Downloads\248\node_modules\knex\lib\dialects\mysql\index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\marsod\Downloads\248\node_modules\knex\lib\dialects\mysql\index.js:120:12)
    at executeQuery (C:\Users\marsod\Downloads\248\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_MySQL.query (C:\Users\marsod\Downloads\248\node_modules\knex\lib\client.js:134:12)
    at Runner.query (C:\Users\marsod\Downloads\248\node_modules\knex\lib\execution\runner.js:130:36)
    at Runner.queryArray (C:\Users\marsod\Downloads\248\node_modules\knex\lib\execution\runner.js:224:21)
    at ensureConnectionCallback (C:\Users\marsod\Downloads\248\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:11:19) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlMessage: "Duplicate column name 'sort_field'",
  sqlState: '42S21',
  index: 0,
  sql: 'alter table `directus_relations` add `sort_field` varchar(255)'
}
``

Maybe I'm doing something wrong? This is what my 'directus_migrations' table looks like, I might have missed some migrations. But how do I get it up-to date?
![image](https://user-images.githubusercontent.com/28014919/118261474-e0e23980-b4b3-11eb-8e4c-ea9187021222.png)

---

### Project details
Directus Version: 9.0.0-rc.57
Environment: production
OS: Linux 5.4.0-1031-azure
Node: 14.15.1

**Comment by avatarbabe** [comment]
I solved it by just adding the next migration to the database, ran the migrations again and now it all works.
