### ISSUE TITLE
docker image directus/directus:v9-rc.65 fails to start

### ISSUE THREAD

**Issue by bywo** [directus/directus#5689]
When i run `docker run directus/directus:v9-rc.65` or `docker run directus/directus:latest`

I get the following
```
internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, open '/root/.npm/_npx/29/lib/node_modules/directus/node_modules/argon2/package.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Run.parseOpts [as parseArgv] (/directus/node_modules/node-pre-gyp/lib/node-pre-gyp.js:136:36)
    at Object.<anonymous> (/directus/node_modules/node-pre-gyp/bin/node-pre-gyp:24:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.npm/_npx/29/lib/node_modules/directus/node_modules/argon2/package.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.27.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.27.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-14T22_43_48_298Z-debug.log
Install for [ 'directus@latest' ] failed with code 1
```

`docker run directus/directus:v9-rc.64` works.

**Comment by rijkvanzanten** [comment]
@bywo I redeployed a release to docker (rc.65) which seems to run as expected. Must've been a weird deployment bug somewhere in the packages 🤷🏻
