### ISSUE TITLE
Issue with npx bootstrap on MySQL database

### ISSUE THREAD

**Issue by nsteinfeld** [directus/directus#5792]
I've get the following error after `npx directus bootstrap` using MySQL(5.7.26) as my database.

```
✨ Initializing bootstrap...
✨ Database already initialized, skipping install
✨ Running migrations...
✨ Applying Remove Collection Foreign Keys...

Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_fields_collection_foreign'; check that column/key exists
    at Query.Sequence._packetToError (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/Users/xxx/.npm/_npx/47645/lib/node_modules/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {

  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlMessage: "Can't DROP 'directus_fields_collection_foreign'; check that column/key exists",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `directus_fields` drop foreign key `directus_fields_collection_foreign`'
```

Could be that this is related to [Issue Seeding with npx install on a MSSQL database #3158](https://github.com/directus/directus/issues/3158)

**Comment by rijkvanzanten** [comment]
On what database are you running bootstrap? It says that the database was already initialized, but then it starts running the very first migration 🤔 Did you truncate the `directus_migrations` table at some point?

**Comment by nsteinfeld** [comment]
This a directus database dump file was passed on to me by another developer. I imported it on my local server then ran the bootstrap command and got this error.

**Comment by rijkvanzanten** [comment]
What rows does `directus_migrations` contain? Do you happen to know on what version of Directus this dump was created?

**Comment by nsteinfeld** [comment]
There are 79 rows in `directus_migrations`. Do you need to see specifics?

**Comment by rijkvanzanten** [comment]
Yes please, that definitely sounds wrong.. There have only been 15 or so up until the latest release

**Comment by rijkvanzanten** [comment]
I'll close this for now, as it's most likely that you're working with a broken/corrupted dump..

**Comment by nsteinfeld** [comment]
-------------------------------
migration_name
-------------------------------
CreateFieldsTable
CreateActivityTable
CreateCollectionsPresetsTable
CreateCollectionsTable
CreateFilesTable
CreateFoldersTable
CreateRolesTable
CreatePermissionsTable
CreateRelationsTable
CreateRevisionsTable
CreateSettingsTable
CreateUsersTable
Upgrade070003
TimezoneChoices
Upgrade070006
LocaleInterface
RemoveScope
AddTrustedProxiesSettingField
AddProjectUrlSettingField
IncreaseUsersLastPageLength
AddUsersEmailValidation
AddAppUrlSettingField
AddMissingSettingsField
AddRolesUsersField
AddFilesChecksumField
AddNavOverride
SetPasswordTypeToHash
UseFileInterface
SetO2mOptionsRoles
SetWidth
SettingsFields
CollectionNotes
MiscRequiredFields
UseJson
SetNullableValueFieldSettingsT
UseTimeline
AddUsers2faSecretField
AddEnforce2faRoleField
AddFileNamingInSetting
AddLoginAttemptsAllowedSetting
UpdateIstanbulTimezone
AddFileExtensionSetting
PasswordValidationSettingField
UpdateNoteForDefaultLimit
UpdateDirectusFieldsField
CreateUserSessions
CreateWebHooks
UpdateDirectusFilesField
UseNewWysiwyg
AddUserSessions
AddWebhooks
RemoveActivitySeen
ConvertUserRoles
UpdateDirectusUsers
UpdateDirectusSettings
UpdateDirectusFiles
UpdateDirectusRoles
ResetDirectusRelations
ResetDirectusFields
AddHashFiledownloadIfEmpty
UseCorrectWysiwyg
UpdateDirectusThumbnailSizes
AddProjectPublicNote
SetOptionsCollectionListing
AllowNullInSettings
HideExternalid
NewTranslationsStructure
AddUserLastPasswordUpdate
RemoveFileMaxSize
UpdateUserCreatedToOwner
UpdateSlugType
AddAssetUrlNamingSetting
UpdateTypeOfCollectionListing
RenameToggle
UpdateUserCreatedInterface
UpdateValidationSizeForDirectu
UpdateLoginAttemptValue
UpdateSlugOptionForAssetWhiteL
AddAuthTtlField
-------------------------------

**Comment by rijkvanzanten** [comment]
Ohhhh you're trying to use a v8 database dump in v9. That's not going to work.. You can migrate a running v8 instance to v9 using https://github.com/directus-community/migration-tool
