### ISSUE TITLE
Directus doesn't load the admin page anymore

### ISSUE THREAD

**Issue by Mbengparis** [directus/directus#5919]
Have been working on a project using directus. Today when i start directus it starts but when i open on localhost i get the following error from the console:

npx directus start
22:22:40 ✨ Server started at port 8055
22:22:41 ✨ Email connection established
22:22:43 ✨ request completed GET 304 /admin 5ms
22:22:43 ✨ request completed GET 304 /admin/css/app.bd9e8a4b.css 3ms
22:22:43 ✨ request completed GET 304 /admin/js/chunk-vendors.2bd9296a.js 3ms
22:22:43 ✨ request completed GET 304 /admin/css/chunk-vendors.2ac9cbb8.css 2ms
22:22:43 ✨ request completed GET 304 /admin/js/app.e81a952f.js 2ms
22:22:43 ✨ request completed GET 200 /admin/js/interface-input-rich-text-html.9c2f0779.js 9ms
22:22:43 ✨ request completed GET 200 /admin/js/markdown.5e1aa397.js 9ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored GET 500 /extensions/displays/ 50ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored GET 500 /extensions/layouts/ 50ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored GET 500 /extensions/interfaces/ 56ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored GET 500 /extensions/modules/ 52ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored POST 500 /auth/refresh 14ms
22:22:43 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
    at Query.Sequence._packetToError (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/mbeng/My Documents/Arbeit Manx/arx_africa/node_modules/knex/lib/execution/runner.js:272:20)
22:22:43 ✨ request errored GET 500 /server/info?limit=-1 14m

<img width="1440" alt="Screenshot 2021-05-27 at 22 25 09" src="https://user-images.githubusercontent.com/49481570/119892510-84166280-bf3a-11eb-8538-deeefaf0b610.png">

**Comment by rijkvanzanten** [comment]
Have you run the database migrations? https://docs.directus.io/guides/projects/#upgrading-a-project

**Comment by Mbengparis** [comment]
No I haven't 


Gesendet von Yahoo Mail für iPhone


Am Donnerstag, Mai 27, 2021, 10:34 PM schrieb Rijk van Zanten ***@***.***>:




Have you run the database migrations? https://docs.directus.io/guides/projects/#upgrading-a-project

**Comment by razuro** [comment]
I think this is related https://github.com/directus/directus/discussions/5787
