### ISSUE TITLE
Failed to create new project

### ISSUE THREAD

**Issue by ukasyah99** [directus/directus#5980]
1) The issue and what you expected to happen
    I got **"DB_CLIENT" Environment Variable is missing** when trying to create a new directus project with the latest version (v9.0.0-rc.70).

2) Exact steps to reproduce this issue
    Run `npx create-directus-project my-project`

3) Your environment:
    Directus v9.0.0-rc.70

4) Any other relevant information we might need to reproduce this issue
    ```
    $ npx create-directus-project my-project
    npx: installed 50 in 6.608s
    03:54:50 🚨 "DB_CLIENT" Environment Variable is missing.
    (node:318560) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: 
    npx directus init
    ```

**Comment by paescuj** [comment]
Probably caused by new version of execa (https://github.com/directus/directus/commit/a11d97ded6befa17153e90ab2c20f4277a847a8f)?

It seems like it doesn't accept any input on `npx directus init` and thus the questions won't appear.

With Directus v9.0.0-rc.70:
```
❯ npx directus init
09:00:06 🚨 "DB_CLIENT" Environment Variable is missing.
```

With Directus v9.0.0-rc.69:
```
❯ npx directus@9.0.0-rc.69 init

[...]

? Choose your database client
❯ PostgreSQL / Redshift
  MySQL / MariaDB / Aurora
  SQLite
  Microsoft SQL Server
  Oracle Database (Alpha)
```

**Comment by KristofferBroberg** [comment]
Here's my error output (RC 70 and Node 16.2.0)

```
npx create-directus-project orfreg
15:09:11 🚨 "DB_CLIENT" Environment Variable is missing.
/Users/u0065422/.npm/_npx/e739e1666a2b218e/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: npx directus init
    at makeError (/Users/u0065422/.npm/_npx/e739e1666a2b218e/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/u0065422/.npm/_npx/e739e1666a2b218e/node_modules/execa/index.js:116:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.create (/Users/u0065422/.npm/_npx/e739e1666a2b218e/node_modules/create-directus-project/lib/index.js:69:2) {
  shortMessage: 'Command failed with exit code 1: npx directus init',
  command: 'npx directus init',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
