### ISSUE TITLE
Cannot delete User account

### ISSUE THREAD

**Issue by andriusign** [directus/directus#6095]
DELETE /users/id not working.

49:38 🚨 error delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions" 
error: delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions"
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
16:49:38 ✨ request errored DELETE 500 /users/ddc0ea9f-19cb-48da-a5e8-309415043e26 35ms

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 5.4.0-72-generic
Node: 14.16.1

**Comment by rijkvanzanten** [comment]
Make sure you're on the latest version of directus 👍🏻
