### ISSUE TITLE
Directus migration fails to insert new fields for Users model

### ISSUE THREAD

**Issue by andriusign** [directus/directus#6432]
Trying to add another field to my model results in failing migration.

First migration was successfull:
```
module.exports = {
  async up(knex) {
    await knex('directus_fields').insert([
      {
        collection: 'directus_users',
        field: 'background',
        special: null,
        interface: 'file-image',
        options: null,
        display: 'image',
        display_options: null,
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
      {
        collection: 'directus_users',
        field: 'username',
        special: null,
        interface: 'input',
        options: null,
        display: 'raw',
        display_options: { icon: false, defaultColor: '#B0BEC5' },
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
      {
        collection: 'directus_users',
        field: 'someField',
        special: 'boolean',
        interface: 'boolean',
        options: null,
        display: 'boolean',
        display_options: null,
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
      {
        collection: 'directus_users',
        field: 'otherField',
        special: 'boolean',
        interface: 'boolean',
        options: null,
        display: 'boolean',
        display_options: null,
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
      {
        collection: 'directus_users',
        field: 'donate',
        special: null,
        interface: 'input-rich-text-html',
        options: null,
        display: 'formatted-value',
        display_options: null,
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
    ]);
  },

  async down(knex) {
    await knex('directus_fields').where({ collection: 'directus_users' }).del();
  },
};

```

Second migration:
```
module.exports = {
  async up(knex) {
    await knex('directus_fields').insert([
      {
        collection: 'directus_users',
        field: 'nickname',
        special: null,
        interface: 'input',
        options: null,
        display: 'raw',
        display_options: { icon: false, defaultColor: '#B0BEC5' },
        readonly: false,
        hidden: false,
        sort: null,
        width: 'full',
        group: null,
        translations: null,
        note: null,
      },
    ]);
  },

  async down(knex) {
    await knex('directus_fields').where({ collection: 'directus_users', field: 'nickname' }).del();
  },
};

```

After running second migration the following error occurs:
```
app-api | ✨ Applying Users Fields...
app-db | 2021-06-22 15:31:49.998 UTC [35] ERROR:  duplicate key value violates unique constraint "directus_migrations_pkey"
app-db | 2021-06-22 15:31:49.998 UTC [35] DETAIL:  Key (version)=(20210622B) already exists.
app-db | 2021-06-22 15:31:49.998 UTC [35] STATEMENT:  insert into "directus_migrations" ("name", "version") values ($1, $2)
app-api | error: insert into "directus_migrations" ("name", "version") values ($1, $2) - duplicate key value violates unique constraint "directus_migrations_pkey"
app-api |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
app-api |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
app-api |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
app-api |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
app-api |     at Socket.emit (events.js:376:20)
app-api |     at addChunk (internal/streams/readable.js:309:12)
app-api |     at readableAddChunk (internal/streams/readable.js:284:9)
app-api |     at Socket.Readable.push (internal/streams/readable.js:223:10)
app-api |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
app-api |   length: 235,
app-api |   severity: 'ERROR',
app-api |   code: '23505',
app-api |   detail: 'Key (version)=(20210622B) already exists.',
app-api |   hint: undefined,
app-api |   position: undefined,
app-api |   internalPosition: undefined,
app-api |   internalQuery: undefined,
app-api |   where: undefined,
app-api |   schema: 'public',
app-api |   table: 'directus_migrations',
app-api |   column: undefined,
app-api |   dataType: undefined,
app-api |   constraint: 'directus_migrations_pkey',
app-api |   file: 'nbtinsert.c',
app-api |   line: '570',
app-api |   routine: '_bt_check_unique'
app-api | }
```

Directus v9 rc70

**Comment by andriusign** [comment]
Apparently there was a naming collision:
20210622B-users-permissions.js
20210622B-users-fields.js

This naming is incorrect, strangely Directus did not care about second part of file name after "-" so I had to rename to:
20210622B-users-permissions.js
20210622C-users-fields.js

**Comment by rijkvanzanten** [comment]
The problem isn't the hyphens in the name, the problem is the fact that you used the same identifier for both `20210622B` 👍🏻

**Comment by andriusign** [comment]
But the identifier is the full file name or not? That is strange indeed.

**Comment by rijkvanzanten** [comment]
As per [the docs](https://docs.directus.io/guides/migrations/#file-name), it's `[identifier]-[name].js`, so `20210622B` is the identifier, everything afterwards it the human readable name.
