### ISSUE TITLE
Field "multiple files" causes complete crash of admin

### ISSUE THREAD

**Issue by gabrielstuff** [directus/directus#6673]
### Describe the Bug

After creating a multiple files field on a collection, the whole server crash. User can login, but admin is not accessible. The API is still working.

In the log the error is as follow :  

```
🚨 select `directus_files`.`charset`, `directus_files`.`description`, `directus_files`.`duration`, `directus_files`.`embed`, `directus_files`.`filename_disk`, `directus_files`.`filename_download`, `directus_files`.`filesize`, `directus_files`.`folder`, `directus_files`.`height`, `directus_files`.`id`, `directus_files`.`location`, `directus_files`.`metadata`, `directus_files`.`modified_by`, `directus_files`.`modified_on`, `directus_files`.`storage`, `directus_files`.`tags`, `directus_files`.`title`, `directus_files`.`type`, `directus_files`.`uploaded_by`, `directus_files`.`uploaded_on`, `directus_files`.`width`, `directus_files`.`buckets` from `directus_files` - ER_BAD_FIELD_ERROR: Unknown column 'directus_files.buckets' in 'field list'
Error: ER_BAD_FIELD_ERROR: Unknown column 'directus_files.buckets' in 'field list'
    at Query.Sequence._packetToError (playground/directus-test/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (playground/directus-test/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (playground/directus-test/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (playground/directus-test/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (playground/directus-test/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (playground/directus-test/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (playground/directus-test/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (playground/directus-test/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (playground/directus-test/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (playground/directus-test/node_modules/mysql/lib/Connection.js:198:25)
    at playground/directus-test/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (playground/directus-test/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (playground/directus-test/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (playground/directus-test/node_modules/knex/lib/client.js:134:12)
    at Runner.query (playground/directus-test/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (playground/directus-test/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (playground/directus-test/node_modules/knex/lib/execution/runner.js:272:20)
```

### To Reproduce

1. Create a new collection
2. Add a media field
3. Select the option "multiple files"
4. Then select many to many

it shows the following warnings : 

<img width="612" alt="Screenshot 2021-07-06 at 18 29 49" src="https://user-images.githubusercontent.com/285033/124636273-a62fc880-de88-11eb-9a87-98ea9de487d9.png">

And then it crashes.

I've tried to reproduce with *^9.0.0-rc.83* but it worked. Nonetheless, I'm currently stuck with my project and I would apreciate a little help to debug this out.

Thanks

### What version of Directus are you using?

9.0.0-rc.69

### What version of Node.js are you using?

v14.17.0

### What database are you using?

Mysql

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by paescuj** [comment]
What stops you from upgrading to 9.0.0-rc.83?

**Comment by rijkvanzanten** [comment]
Closing this as it's apparently already fixed in a later version 👍🏻 

FWIW it sounds like there was a custom field `buckets` on `directus_files` at one point that's now causing issues 🤔

**Comment by gabrielstuff** [comment]
Hello, 
Nothing stopped me from upgrading. I didn't think I would need to upgrade.
I will keep you posted.

To improve the comment : 

When I first created this new fields, I first receive an error.

Then after clicking again, the error change to tell me the field already existed. I guess the process didn't go through and I was in an unstable state. Then after refreshing, the 404 error came in.

For references and in such a case, what should be the procedure to manually clean the collection model, and remove the problematic fields ?
