### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by msoler75** [directus/directus#6674]
I just tried to install in local and it fails. 

I show the console error:

```
PS D:\projects> npx create-directus-project directus-sample
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module '@directus/shared/utils'
Require stack:
- D:\projects\directus-sample\node_modules\directus\dist\extensions.js
- D:\projects\directus-sample\node_modules\directus\dist\services\graphql.js
- D:\projects\directus-sample\node_modules\directus\dist\services\index.js
- D:\projects\directus-sample\node_modules\directus\dist\utils\get-schema.js
- D:\projects\directus-sample\node_modules\directus\dist\cli\commands\bootstrap\index.js
- D:\projects\directus-sample\node_modules\directus\dist\cli\index.js
- D:\projects\directus-sample\node_modules\directus\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\projects\directus-sample\node_modules\directus\dist\extensions.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\extensions.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\services\\graphql.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\services\\index.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\utils\\get-schema.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\cli\\commands\\bootstrap\\index.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\dist\\cli\\index.js',
    'D:\\projects\\directus-sample\\node_modules\\directus\\cli.js'
  ]
}
(node:5472) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (C:\Users\msole\AppData\Local\npm-cache\_npx\e739e1666a2b218e\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\msole\AppData\Local\npm-cache\_npx\e739e1666a2b218e\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.create (C:\Users\msole\AppData\Local\npm-cache\_npx\e739e1666a2b218e\node_modules\create-directus-project\lib\index.js:71:2)
(node:5472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\projects>

```

### To Reproduce

npx create-directus-project directus-sample

### What version of Directus are you using?

9+

### What version of Node.js are you using?

12.16.0

### What database are you using?

10.1.37-MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Directus requires Node 12.20 and up to run 👍🏻
