### ISSUE TITLE
expose knex mssql trustServerCertificate option

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#7002]
### Describe the Bug

knex recently added [it](https://github.com/knex/knex/pull/4500). And directus has [that](https://github.com/directus/directus/pull/6958) version

### To Reproduce

try to connect to mssql using a self signed certificate. You get:
```js
ConnectionError: Failed to connect to foo.bar - self signed certificate
    at ConnectionError (/directus/node_modules/tedious/lib/errors.js:13:12)
    at Connection.socketError (/directus/node_modules/tedious/lib/connection.js:1663:56)
    at Socket.<anonymous> (/directus/node_modules/tedious/lib/connection.js:1427:14)
    at Socket.emit (node:events:406:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

it was working fine in `v9.0.0-rc.85`

### What version of Directus are you using?

v9.0.0-rc.86

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by rijkvanzanten** [comment]
Directus converts the DB env vars to a camelCased object which is passed on to `knex`. You should be able to use this option already by setting `DB_OPTIONS__TRUST_SERVER_CERTIFICATE=true`. Let me know if that works for you 👍🏻

**Comment by wc-matteo** [comment]
ohhh nice! It does indeed! :)
