### ISSUE TITLE
Creating relation with non-existent collection crashes Directus

### ISSUE THREAD

**Issue by paescuj** [directus/directus#7302]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm using the SDK to create a relation between `directus_users` and a custom collection:
```js
await directus.relations.createOne({
  collection: 'directus_users',
  field: 'example',
  related_collection: 'examples',
  meta: {
    one_field: 'user',
  },
  schema: {
    on_delete: 'CASCADE',
  },
});
```

This used to work with v9.0.0-rc.88 but is now crashing Directus with the following error message:
```
directus_1  | /directus/node_modules/directus/dist/services/relations.js:375
directus_1  |         const relatedFieldDBType = this.schema.collections[relation.related_collection].fields[this.schema.collections[relation.related_collection].primary].dbType;
directus_1  |                                                                                         ^
directus_1  |
directus_1  | TypeError: Cannot read property 'fields' of undefined
directus_1  |     at RelationsService.alterType (/directus/node_modules/directus/dist/services/relations.js:375:89)
directus_1  |     at TableBuilder._fn (/directus/node_modules/directus/dist/services/relations.js:151:26)
directus_1  |     at TableBuilder.toSQL (/directus/node_modules/directus/node_modules/knex/lib/schema/tablebuilder.js:44:14)
directus_1  |     at SchemaCompiler_PG.alterTable (/directus/node_modules/directus/node_modules/knex/lib/schema/compiler.js:101:25)
directus_1  |     at SchemaCompiler_PG.toSQL (/directus/node_modules/directus/node_modules/knex/lib/schema/compiler.js:63:26)
directus_1  |     at SchemaBuilder.toSQL (/directus/node_modules/directus/node_modules/knex/lib/schema/builder.js:35:45)
directus_1  |     at ensureConnectionCallback (/directus/node_modules/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
directus_1  |     at Runner.ensureConnection (/directus/node_modules/directus/node_modules/knex/lib/execution/runner.js:272:20)
directus_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
directus_1  |     at async Runner.run (/directus/node_modules/directus/node_modules/knex/lib/execution/runner.js:30:19)
```

### To Reproduce

```js
// Create collection "examples"
await directus.collections.createMany([
  {
    collection: 'examples',
    fields: [
      {
        field: 'id',
        type: 'integer',
        meta: {
          interface: 'input',
          readonly: true,
          hidden: true,
        },
        schema: {
          is_primary_key: true,
          has_auto_increment: true,
        },
      },
      {
        field: 'user',
        type: 'o2m',
        meta: {
          display: 'related-values',
          display_options: {
            template: '{{email}}',
          },
          interface: 'list-o2m',
          options: {
            template: '{{email}}',
          },
          special: 'o2m',
        },
      },
    ],
  },
  // other collections
]);

// Create field "example" in "directus_users"
await directus.items('directus_fields/directus_users').createOne({
  field: 'example',
  type: 'integer',
});

// Create relation from "user" in "directus_users" to "user" in "examples"
await directus.relations.createOne({
    collection: 'directus_users',
    field: 'example',
    related_collection: 'examples',
    meta: {
      one_field: 'user',
    },
    // Delete "directus_users" entries when related "examples" entry is deleted
    schema: {
      on_delete: 'CASCADE',
    },
  });
```

### What version of Directus are you using?

v9.0.0-rc.89

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment]
Okay, so turns out the collection "examples" hasn't been created due to #7304.
After fixing this, I'm able to create the relation successfully.

But I still think that we need to catch this and Directus shouldn't crash when a relation is created with an non-existing collection.
