### ISSUE TITLE
Error: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON  can't have a default value

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#7377]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Got mysql error with query

```
🚨 create table `mailing_list` (`created_by` char(36) null, `created_on` timestamp null, `email` varchar(200) null, `first_name` varchar(200) null, `frequency` json null default '{   \"default\": [\"daily\", \"weekly\", \"monthly\"] }', `id` int unsigned not null auto_increment primary key, `last_name` varchar(200) null, `status` varchar(20) null default 'active') - ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'frequency' can't have a default value 
Error: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'frequency' can't have a default value
    at Query.Sequence._packetToError (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    --------------------
    at Protocol._enqueue (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/e01/Workspace/directus-demo/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/e01/Workspace/directus-demo/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/e01/Workspace/directus-demo/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/e01/Workspace/directus-demo/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/e01/Workspace/directus-demo/node_modules/knex/lib/client.js:134:12)
    at /Users/e01/Workspace/directus-demo/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/e01/Workspace/directus-demo/node_modules/knex/lib/execution/transaction.js:358:12)
```

### To Reproduce

Start fresh instance from v9.0.0-rc90

Start directus v8 instance (initialized with the demo data) and tried to use migration-tool, error appears on v9 instance

### What version of Directus are you using?

v9.0.0-rc90

### What version of Node.js are you using?

16

### What database are you using?

MySQL 8.0.26

### What browser are you using?

chrome

### What operating system are you using?

macos

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
v8 didn't rely on JSON types for storing JSON values. MySQL doesn't accept strings as a default value for JSON objects, so this is something we should address in the migration-tool 👍🏻
