### ISSUE TITLE
Geometry helper not implemented on postgres. 

### ISSUE THREAD

**Issue by botzill** [directus/directus#7559]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I get this error when upgrading  to the latest version:

```05:46:30 🚨 Geometry helper not implemented on postgres. 
Error: Geometry helper not implemented on postgres.
    at Object.getGeometryHelper (/directus/node_modules/directus/dist/database/helpers/geometry.js:24:19)
    at getColumnPreprocessor (/directus/node_modules/directus/dist/database/run-ast.js:94:31)
    at getDBQuery (/directus/node_modules/directus/dist/database/run-ast.js:104:24)
    at run (/directus/node_modules/directus/dist/database/run-ast.js:33:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.runAST [as default] (/directus/node_modules/directus/dist/database/run-ast.js:27:16)
    at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:216:25)
    at async RelationsService.readAll (/directus/node_modules/directus/dist/services/relations.js:66:17)
    at async getDatabaseSchema (/directus/node_modules/directus/dist/utils/get-schema.js:155:24)
    at async Object.getSchema (/directus/node_modules/directus/dist/utils/get-schema.js:39:22)```

### To Reproduce

Upgrade to the latest version, `v9.0.0-rc.91`

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

K8S

**Comment by Oreilles** [comment]
https://github.com/directus/directus/blob/ba390ee8d614175fb3efb23da7a41467eb504c0f/api/src/database/helpers/geometry.ts#L17

This line should fix it. It's weird that your client is named `postgres` when mine has always been named `pg` though..
As a side note, the PostGIS extensions will be required if you want to use native geometric types.
