### ISSUE TITLE
Batch updating M2O field: 'Invalid one-to-many update structure: "value" must be of type object'

### ISSUE THREAD

**Issue by jrvidotti** [directus/directus#7955]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When batch updating a M2O field, got following error:
![image](https://user-images.githubusercontent.com/5623041/132748324-976b67cd-aae9-4ee8-baaf-76e50260c82a.png)

```
{
  "message": "Invalid one-to-many update structure: \"value\" must be of type object",
  "extensions": {
    "code": "INVALID_PAYLOAD",
    "stack": "Error: Invalid one-to-many update structure: \"value\" must be of type object\n    at PayloadService.processO2M (/home/junior/dev/directus/directus/api/src/services/payload.ts:607:22)\n    at /home/junior/dev/directus/directus/api/src/services/items.ts:453:48\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  }
}
```

Payload:
```
{
  "keys": [
    1,
    2,
    23
  ],
  "data": {
    "equipe": 5
  }
}
```

### To Reproduce

Try to batch update a M2O field.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v16.8.0

### What database are you using?

Postgres 13.2

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu WSL2

### How are you deploying Directus?

local

**Comment by jrvidotti** [comment]
I don't know what's going on, but dropping and recreating column solved the problem. This database was restored and some other data was manually imported directly via SQL, maybe it affected stability...
