### ISSUE TITLE
Postgres query error upon applying schema through CLI

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#8311]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When trying to apply my schema I'm getting this error:

```
09:42:02 🚨 error 

        SELECT c.table_name

          , c.column_name

          , c.column_default as default_value

          , c.data_type

  , c.character_maximum_length as max_length

          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity

          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable

        FROM

          information_schema.columns c

        LEFT JOIN information_schema.tables t

          ON c.table_name = t.table_name

        WHERE

          t.table_type = 'BASE TABLE'

          AND c.table_schema IN ($1);

       - current transaction is aborted, commands ignored until end of transaction block 

error: 

        SELECT c.table_name

          , c.column_name

          , c.column_default as default_value

          , c.data_type

  , c.character_maximum_length as max_length

warning "directus > @directus/extensions-sdk > rollup-plugin-typescript2@0.30.0" has unmet peer dependency "typescript@>=2.4.0".

          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity

          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable

        FROM

          information_schema.columns c

        LEFT JOIN information_schema.tables t

          ON c.table_name = t.table_name

        WHERE

          t.table_type = 'BASE TABLE'

          AND c.table_schema IN ($1);

       - current transaction is aborted, commands ignored until end of transaction block

    at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)

    at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)

    at Socket.emit (events.js:400:28)

    at addChunk (internal/streams/readable.js:290:12)

    at readableAddChunk (internal/streams/readable.js:265:9)

    at Socket.Readable.push (internal/streams/readable.js:204:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

As always, happy to discuss. Can't share my schema.yaml file here, will send it privately.

### To Reproduce

snapshot gemaakt van lokale postgres omgeving, lokale db weg gehaald, snapshot applied op lege postgres database, krijg ik deze error:

1. Create a snapshot from my local postgres database
2. Delete local postgres database
3. Recreate empty local postgres database
4. Apply the schema.yaml created at step 1.

### What version of Directus are you using?

rc94

### What version of Node.js are you using?

14 lts

### What database are you using?

Postgres 12

### What browser are you using?

na

### What operating system are you using?

na

### How are you deploying Directus?

Docker

**Comment by keesvanbemmel** [comment]
This might be connected/similar to #8176
