### ISSUE TITLE
MariaDB database migration error on rc95

### ISSUE THREAD

**Issue by micheleferraro** [directus/directus#8370]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I got this error during migration from rc.94:
```
alter table `directus_fields` drop `group` - ER_DROP_INDEX_FK: Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint 
Error: ER_DROP_INDEX_FK: Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint
    at Query.Sequence._packetToError (/home/directus/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/directus/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/directus/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/directus/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/directus/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/directus/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/directus/directus/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/directus/directus/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Protocol._enqueue (/home/directus/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/directus/directus/node_modules/mysql/lib/Connection.js:198:25)
    at /home/directus/directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/directus/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/home/directus/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/home/directus/directus/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/home/directus/directus/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/home/directus/directus/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/home/directus/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
```

### To Reproduce

1. run `npm update directus`
2. run `npx directus database migrate:latest`

### What version of Directus are you using?

9.0.0-rc.94

### What version of Node.js are you using?

14.17.2

### What database are you using?

MariaDB 10.5.11

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Running locally

**Comment by micheleferraro** [comment]
Looks like #8369 refers to the same issue, I'm closing this one.
