### ISSUE TITLE
Error: select "ip_access" from "directus_roles" where "id" is null limit $1

### ISSUE THREAD

**Issue by RSamaium** [directus/directus#8634]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Request on any endpoint: 

`{"errors":[{"message":"An unexpected error occurred.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

Server log

```
Error: select "ip_access" from "directus_roles" where "id" is null limit $1 - Connection terminated unexpectedly

    at Connection.<anonymous> (/directus/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:509:28)

    at Connection.emit (node:events:390:28)

    at Socket.<anonymous> (/directus/node_modules/pg/lib/connection.js:57:12)

    at Socket.emit (node:events:390:28)

    at TCP.<anonymous> (node:net:672:12)
```

### To Reproduce

The problem occurs if Directus has been in "rest" for a little while. As soon as we make a request afterwards, I get the error. On the second request, I don't have the problem anymore

### What version of Directus are you using?

9.0.0-rc.95 and below

### What version of Node.js are you using?

16.10.0

### What database are you using?

Postgress 12

### What browser are you using?

Brave

### What operating system are you using?

Linux Ubuntu

### How are you deploying Directus?

Docker

**Comment by RSamaium** [comment]
Thanks. I've set the environment variable. I'll let you know if the problem persists
