### ISSUE TITLE
Schema apply broken on foreign constraint after upgrade to RC98

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#8874]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After upgrading to RC98 (no other changes) the schema snapshot application results in an error. This was not the case with RC97, same schema.

```
10:11:18 🚨 error alter table "external_supplier_infos" drop constraint "external_supplier_infos_orderline_foreign" - relation "external_supplier_infos" does not exist 
error: alter table "external_supplier_infos" drop constraint "external_supplier_infos_orderline_foreign" - relation "external_supplier_infos" does not exist
at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)
at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)
at Socket.emit (events.js:400:28)
at addChunk (internal/streams/readable.js:290:12)
at readableAddChunk (internal/streams/readable.js:265:9)
at Socket.Readable.push (internal/streams/readable.js:204:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### To Reproduce

1. Clean installation of RC97 on Postgres
2. Apply schema (attached)
3. Upgrade to RC98
4. Apply same schema.

Expected output is: No changes to apply.
Output is: 
```
10:11:18 🚨 error alter table "external_supplier_infos" drop constraint "external_supplier_infos_orderline_foreign" - relation "external_supplier_infos" does not exist 
error: alter table "external_supplier_infos" drop constraint "external_supplier_infos_orderline_foreign" - relation "external_supplier_infos" does not exist
at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)
at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)
at Socket.emit (events.js:400:28)
at addChunk (internal/streams/readable.js:290:12)
at readableAddChunk (internal/streams/readable.js:265:9)
at Socket.Readable.push (internal/streams/readable.js:204:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### What version of Directus are you using?

RC98

### What version of Node.js are you using?

14 LTS

### What database are you using?

Postgres 13

### What browser are you using?

Chrome but not applicable

### What operating system are you using?

MacOS
[shema.yaml.txt](https://github.com/directus/directus/files/7359624/shema.yaml.txt)

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Note to others looking into this: I haven't personally tried the reproduction, but I believe this is most probably related to this: https://github.com/directus/directus/issues/8854#issuecomment-945401322

**Comment by rijkvanzanten** [comment]
I was able to apply the provided snapshot without issues in the latest version (9.1.2). Closing this as I believe it was resolved 👍🏻
