### ISSUE TITLE
getting timeout error, while trying to select an item (a one to many relationship)

### ISSUE THREAD

**Issue by vahidreza** [directus/directus#8943]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

when tried to test the app i changed the type of the field's interface to many to one and then on the edit page of the item, I presented a list of items after clicking on the specified field, then I tried to search for other items and after some time I get an error.

if there is somewhere where I can define the timeout, things most probably are going to work.

### To Reproduce

i have my database of almost 20 thousand records and it has to search and return some records.
i did a direct SQL query and it was fine but it took a while to do it, probably passing the timeout setting.

### Errors Shown

```
15:47:18 🚨 select count(*) as [count] from [Patients] where (LOWER([Patients].[StringID]) LIKE @p0 or LOWER([Patients].[TreatmentFileCode]) LIKE @p1 or LOWER([Patients].[TreatmentCenter]) LIKE @p2 or LOWER([Patients].[Name]) LIKE @p3 or LOWER([Patients].[LastName]) LIKE @p4 or LOWER([Patients].[FatherName]) LIKE @p5 or LOWER([Patients].[NationalCode]) LIKE @p6 or LOWER([Patients].[Sex]) LIKE @p7 or LOWER([Patients].[MarriageStatus]) LIKE @p8 or LOWER([Patients].[Job]) LIKE @p9 or LOWER([Patients].[HomeOwnershipStatus]) LIKE @p10 or LOWER([Patients].[FamilyHeadStatus]) LIKE @p11 or LOWER([Patients].[FamilyHeadJob]) LIKE @p12 or LOWER([Patients].[Education]) LIKE @p13 or LOWER([Patients].[FinalOpinion]) LIKE @p14 or LOWER([Patients].[SocailHelperScoreOpinion]) LIKE @p15 or LOWER([Patients].[SystemScoreReason]) LIKE @p16 or LOWER([Patients].[isForeigner_passportNumber]) LIKE @p17 or LOWER([Patients].[isForeigner_preparationCard_ID]) LIKE @p18 or LOWER([Patients].[isForeigner_preparationCard_familyNumber]) LIKE @p19 or LOWER([Patients].[CreatedBy]) LIKE @p20 or LOWER([Patients].[ModifiedBy]) LIKE @p21 or LOWER([Patients].[allPhonesAllAddresses]) LIKE @p22 or LOWER([Patients].[patientOwnStatus]) LIKE @p23 or LOWER([Patients].[deletedBy]) LIKE @p24 or LOWER([Patients].[RowVersion]) LIKE @p25) - Timeout: Request failed to complete in 15000ms 
RequestError: select count(*) as [count] from [Patients] where (LOWER([Patients].[StringID]) LIKE @p0 or LOWER([Patients].[TreatmentFileCode]) LIKE @p1 or LOWER([Patients].[TreatmentCenter]) LIKE @p2 or LOWER([Patients].[Name]) LIKE @p3 or LOWER([Patients].[LastName]) LIKE @p4 or LOWER([Patients].[FatherName]) LIKE @p5 or LOWER([Patients].[NationalCode]) LIKE @p6 or LOWER([Patients].[Sex]) LIKE @p7 or LOWER([Patients].[MarriageStatus]) LIKE @p8 or LOWER([Patients].[Job]) LIKE @p9 or LOWER([Patients].[HomeOwnershipStatus]) LIKE @p10 or LOWER([Patients].[FamilyHeadStatus]) LIKE @p11 or LOWER([Patients].[FamilyHeadJob]) LIKE @p12 or LOWER([Patients].[Education]) LIKE @p13 or LOWER([Patients].[FinalOpinion]) LIKE @p14 or LOWER([Patients].[SocailHelperScoreOpinion]) LIKE @p15 or LOWER([Patients].[SystemScoreReason]) LIKE @p16 or LOWER([Patients].[isForeigner_passportNumber]) LIKE @p17 or LOWER([Patients].[isForeigner_preparationCard_ID]) LIKE @p18 or LOWER([Patients].[isForeigner_preparationCard_familyNumber]) LIKE @p19 or LOWER([Patients].[CreatedBy]) LIKE @p20 or LOWER([Patients].[ModifiedBy]) LIKE @p21 or LOWER([Patients].[allPhonesAllAddresses]) LIKE @p22 or LOWER([Patients].[patientOwnStatus]) LIKE @p23 or LOWER([Patients].[deletedBy]) LIKE @p24 or LOWER([Patients].[RowVersion]) LIKE @p25) - **Timeout: Request failed to complete in 15000ms
    at Connection.requestTimeout (/Users/vahidreza/behnam/node_modules/tedious/lib/connection.js:1261:21)
    at Timeout._onTimeout (/Users/vahidreza/behnam/node_modules/tedious/lib/connection.js:1213:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)**
15:47:18 ✨ request errored GET 500 /items/Patients?limit=25&fields[]=Id&fields[]=RegistrationCode&fields[]=RegistrationDate&fields[]=StringID&sort[]=Id&page=1&search=%D8%B9%D9%84%DB%8C+&meta[]=filter_count&meta[]=total_count 15.6s
```

### What version of Directus are you using?

https://github.com/directus/directus/releases/tag/v9.0.0-rc.98

### What version of Node.js are you using?

v12.18.3

### What database are you using?

docker image -> mcr.microsoft.com/mssql/server:2017-latest

### What browser are you using?

chrome Version 94.0.4606.81 (Official Build) (x86_64)

### What operating system are you using?

MacOS BigSur 11.5.2 (20G95)

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
You should be able to use `DB_REQUEST_TIMEOUT` to control that value 👍🏻
