### ISSUE TITLE
Microsoft SSO auth OpenID results in JsonWebTokenError

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#9149]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After upgrading to RC99 I needed to reconfigure the Microsoft AUTH provider and I wanted to used openID.

I think I did everything correctly, but it seems that the token is not passed to open id auth driver.

These are the ENV variables to set up SSO (redacted of course):

```
AUTH_PROVIDERS="microsoft"
AUTH_MICROSOFT_DRIVER="openid"
AUTH_MICROSOFT_CLIENT_ID="00000000-0000-0000-0000-000000000000"
AUTH_MICROSOFT_CLIENT_SECRET="0000000000000000000000"
AUTH_MICROSOFT_SCOPE="openid profile email"
AUTH_MICROSOFT_ISSUER_URL="https://login.microsoftonline.com/<REDACTED-TENANT-ID>/v2.0/.well-known/openid-configuration"
```

### To Reproduce

Added env variables like above, expected it to work like that. So either it's a bug or, more likely, I'm missing a config key?

### Errors Shown

```
07:31:50 ✨ request completed GET 302 /auth/login/microsoft?redirect=?continuehttp://localhost:8055/admin/login 13ms

07:31:51 ⚠️  Invalid user credentials.

07:31:51 ✨ request completed GET 302 /auth/login/microsoft/callback?code=0.AXMAh<REDACTED>&session_state=<REDACTED> 529ms

07:31:51 🚨 JsonWebTokenError jwt must be provided 

JsonWebTokenError: jwt must be provided

    at Object.module.exports [as verify] (/src/node_modules/jsonwebtoken/verify.js:53:17)

    at /src/node_modules/directus/dist/auth/drivers/openid.js:185:63

    at scoped (/src/node_modules/directus/dist/utils/async-handler.js:5:60)

    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)

    at next (/src/node_modules/express/lib/router/route.js:137:13)

    at Route.dispatch (/src/node_modules/express/lib/router/route.js:112:3)

    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)

    at /src/node_modules/express/lib/router/index.js:281:22

    at Function.process_params (/src/node_modules/express/lib/router/index.js:335:12)

    at next (/src/node_modules/express/lib/router/index.js:275:10)

    at Function.handle (/src/node_modules/express/lib/router/index.js:174:3)

    at router (/src/node_modules/express/lib/router/index.js:47:12)

    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)

    at trim_prefix (/src/node_modules/express/lib/router/index.js:317:13)

    at /src/node_modules/express/lib/router/index.js:284:7

    at Function.process_params (/src/node_modules/express/lib/router/index.js:335:12)

07:31:51 ✨ request errored GET 500 /auth/login/microsoft/callback?reason=INVALID_USER 10ms
```

### What version of Directus are you using?

rc99

### What version of Node.js are you using?

14lts

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### What operating system are you using?

macos

### How are you deploying Directus?

docker

**Comment by infomiho** [comment]
@aidenfoxx For when is the fixed planned?

**Comment by aidenfoxx** [comment]
@infomiho It was released in rc100 I believe.

**Comment by rijkvanzanten** [comment]
@aidenfoxx is correct, this was fixed https://github.com/directus/directus/pull/9054
