### ISSUE TITLE
Unable to migrate from rc.93 to rc.94 or higher

### ISSUE THREAD

**Issue by skeletorXVI** [directus/directus#9215]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When attempting to upgrade from rc.93 to rc.94 or higher, the migration fails due to an invalid query.

We originally ran rc.59, then upgraded to rc.85 and intended to upgrade to rc.99. Unfortunately we were only able to upgrade to rc.93 and were blocked from further upgrades by the migration failing.

The same error occurs when only running the migrate command or starting rc.94 or newer.

### To Reproduce

I was unable to create a minimal example, on short notice, without including confidential data. _I will try to break down our database so that I can provide an reproducible example during the next week._

In the mean time I hope that someone might have an idea how to resolve this issue.

### Errors Shown

```
cms-backend-directus-1  | 08:29:12 ✨ Initializing bootstrap...
cms-backend-directus-1  | 08:29:12 ✨ Database already initialized, skipping install
cms-backend-directus-1  | 08:29:12 ✨ Running migrations...
cms-backend-directus-1  | 08:29:12 ✨ Applying Add Insights...
cms-backend-directus-1  | Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'directus_dashboards_user_created_foreign' are incompatible.
cms-backend-directus-1  |     at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
cms-backend-directus-1  |     at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
cms-backend-directus-1  |     at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
cms-backend-directus-1  |     at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
cms-backend-directus-1  |     at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
cms-backend-directus-1  |     at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
cms-backend-directus-1  |     at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)
cms-backend-directus-1  |     at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)
cms-backend-directus-1  |     at Socket.emit (node:events:394:28)
cms-backend-directus-1  |     at addChunk (node:internal/streams/readable:315:12)
cms-backend-directus-1  |     --------------------
cms-backend-directus-1  |     at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
cms-backend-directus-1  |     at Connection.query (/directus/node_modules/mysql/lib/Connection.js:198:25)
cms-backend-directus-1  |     at /directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
cms-backend-directus-1  |     at new Promise (<anonymous>)
cms-backend-directus-1  |     at Client_MySQL._query (/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
cms-backend-directus-1  |     at executeQuery (/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
cms-backend-directus-1  |     at Client_MySQL.query (/directus/node_modules/knex/lib/client.js:134:12)
cms-backend-directus-1  |     at Runner.query (/directus/node_modules/knex/lib/execution/runner.js:130:36)
cms-backend-directus-1  |     at Runner.queryArray (/directus/node_modules/knex/lib/execution/runner.js:224:21)
cms-backend-directus-1  |     at Runner.queryArray (/directus/node_modules/knex/lib/execution/runner.js:241:31) {
cms-backend-directus-1  |   code: 'UNKNOWN_CODE_PLEASE_REPORT',
cms-backend-directus-1  |   errno: 3780,
cms-backend-directus-1  |   sqlMessage: "Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'directus_dashboards_user_created_foreign' are incompatible.",
cms-backend-directus-1  |   sqlState: 'HY000',
cms-backend-directus-1  |   index: 0,
cms-backend-directus-1  |   sql: 'alter table `directus_dashboards` add constraint `directus_dashboards_user_created_foreign` foreign key (`user_created`) references `directus_users` (`id`) on delete SET NULL'
cms-backend-directus-1  | }
```

### What version of Directus are you using?

directus/directus:9.0.0-rc.93

### What version of Node.js are you using?

v16.9.1

### What database are you using?

MySQL 8.0.12 & Azure MySQL 8.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by skeletorXVI** [comment]
> Can you try setting the `DB_CHARSET` environment variable to either `latin1` or `utf8mb4`, restart your server and see which work ?

Just tested it, in our case setting it to latin1 resolved the issue. It appears somewhere down the line I mixed up the character sets in my scripts, resulting in my test database being generated with a different set than the original database.
