### ISSUE TITLE
Directus Postgres with Postgis Init/bootstrap

### ISSUE THREAD

**Issue by RegisHubelia** [directus/directus#9462]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When you bootstrap directus to create the initial tables following a fresh creation of a database+postgis, the following error occurs:

```
TypeError: Cannot set properties of undefined (setting 'primary')
    at Postgres.<anonymous> (***/node_modules/@directus/schema/dist/dialects/postgres.js:124:58)
    at step (***/node_modules/@directus/schema/dist/dialects/postgres.js:67:23)
    at Object.next (***/node_modules/@directus/schema/dist/dialects/postgres.js:48:53)
    at fulfilled (***/node_modules/@directus/schema/dist/dialects/postgres.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

It is related to the table "us_gaz, us_lex, us_rules" that are created as part of the postgis setup.  the "overview[table_name]" doesn't exists, therefore is undefined.  I guess this would also lead to issues if you have any other tables that are not part of directus...

I worked around it by modifying the postgres.ts file and added the following:

```js
if(!overview[table_name]) continue; at line 128
```

Everything seems to be working fine after this, but it's probably not an ideal solution...

### To Reproduce

1) Start a fresh project
2) Create a fresh Database, and install postgis like so:

```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION postgis_sfcgal;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION address_standardizer;
CREATE EXTENSION address_standardizer_data_us;
CREATE EXTENSION postgis_tiger_geocoder;
```

3) Run npx directus bootstrap and the error will appears

### Errors Shown

```
TypeError: Cannot set properties of undefined (setting 'primary')
    at Postgres.<anonymous> (***/node_modules/@directus/schema/dist/dialects/postgres.js:124:58)
    at step (***/node_modules/@directus/schema/dist/dialects/postgres.js:67:23)
    at Object.next (***/node_modules/@directus/schema/dist/dialects/postgres.js:48:53)
    at fulfilled (***/node_modules/@directus/schema/dist/dialects/postgres.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

### What version of Directus are you using?

9.0.0-rc.101

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chromium

### What operating system are you using?

Linux

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
@RegisHubelia Does the database user you're using with Directus have any special privileges or reduces permissions to certain tables?

**Comment by RegisHubelia** [comment]
Hey @rijkvanzanten, you are right on..!

Even if the account used in directus was owner on the database, I used a different account to install postgis.  That account was the owner of the postgis-related tables within this database.  Upon changing the owner for the postgis tables for the same account used by directus, it went trough just fine...  Duh...  I should of check this before raising this issue.  The spatial_ref_sys table wasn't producing the error, so I was confused as of why the other 3 tables had the issue...

So non-issue after all, sorry about this. 

Thanks for your help!

**Comment by rijkvanzanten** [comment]
Gotcha! Thanks for confirming that 🙂

**Comment by RegisHubelia** [comment]
One thing tough, the tables now are showing up in the directus interface:
![image](https://user-images.githubusercontent.com/25985730/140408876-b85826d3-7ea3-4d14-b55e-daed4f1c4fb7.png)

**Comment by rijkvanzanten** [comment]
@RegisHubelia You can use the DB_EXCLUDE_TABLES env var to ignore those system-wide 👍🏻 

https://docs.directus.io/configuration/config-options/#database

**Comment by RegisHubelia** [comment]
@rijkvanzanten, awesome, thank you!

**Comment by sevetseh28** [comment]
Im having the same issue with an existing database.. is PostGiIs required? I don't need it. 
```
11:07:00 ✨ Initializing bootstrap...
2022-08-04T11:07:00.911485000Z 11:07:00 ✨ Database already initialized, skipping install
2022-08-04T11:07:00.911590000Z 11:07:00 ✨ Running migrations...
2022-08-04T11:07:00.943779000Z 11:07:00 ✨ Done
2022-08-04T11:07:06.434202800Z 11:07:06 ⚠️  PostGIS isn't installed. Geometry type support will be limited.
2022-08-04T11:07:06.833822500Z TypeError: Cannot set properties of undefined (setting 'primary')
2022-08-04T11:07:06.833981900Z     at Postgres.<anonymous> (/directus/node_modules/@directus/schema/dist/dialects/postgres.js:127:58)
2022-08-04T11:07:06.834014000Z     at step (/directus/node_modules/@directus/schema/dist/dialects/postgres.js:67:23)
2022-08-04T11:07:06.834048500Z     at Object.next (/directus/node_modules/@directus/schema/dist/dialects/postgres.js:48:53)
2022-08-04T11:07:06.834109800Z     at fulfilled (/directus/node_modules/@directus/schema/dist/dialects/postgres.js:39:58)
2022-08-04T11:07:06.834144600Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by RegisHubelia** [comment]
Hey, make sure that the users has rights on every existing tables in the schema.

**Comment by sevetseh28** [comment]
Thanks for answering! What permissions exactly do we need? I couldn't find that documented anywhere. Im trying with this in Postgres:
```
create user directus_user with encrypted password 'example';
grant all on database testdatabase to directus_user;
```

**Comment by RegisHubelia** [comment]
Yhea you'll need a bit more than that as this won't set permissions on existing tables.  Try something like this (assuming you are using the public schema):
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO directus_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO directus_user;

**Comment by rijkvanzanten** [comment]
Directus introspects the schema, so it needs to have the correct privileges to do so 👍🏻

**Comment by sevetseh28** [comment]
Thanks! it worked 🙏
