### ISSUE TITLE
Schema migration of relations does not work on mysql

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#9531]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When importing the demo via `npx directus schema apply ./demo.yaml` it fails while trying to create the relations.

### To Reproduce

1. clean install directus db via `npm run cli init`.
2. run `npx directus schema apply ./demo.yaml`

### Errors Shown

relation.collection seems to be `undefined`

```
E:\Programmieren\Directus\directus\api\dist\services\relations.js:371
        const m2oFieldDBType = this.schema.collections[relation.collection].fields[relation.field].dbType;
                                                                            ^

TypeError: Cannot read properties of undefined (reading 'fields')
    at RelationsService.alterType (E:\Programmieren\Directus\directus\api\dist\services\relations.js:371:77)
    at TableBuilder._fn (E:\Programmieren\Directus\directus\api\dist\services\relations.js:205:26)
    at TableBuilder.toSQL (E:\Programmieren\Directus\directus\node_modules\knex\lib\schema\tablebuilder.js:47:16)
    at SchemaCompiler_MySQL.build (E:\Programmieren\Directus\directus\node_modules\knex\lib\schema\compiler.js:143:23)
    at SchemaCompiler_MySQL.alterTable (E:\Programmieren\Directus\directus\node_modules\knex\lib\schema\compiler.js:164:13)
    at SchemaCompiler_MySQL.toSQL (E:\Programmieren\Directus\directus\node_modules\knex\lib\schema\compiler.js:97:26)
    at SchemaBuilder.toSQL (E:\Programmieren\Directus\directus\node_modules\knex\lib\schema\builder.js:35:45)
    at ensureConnectionCallback (E:\Programmieren\Directus\directus\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (E:\Programmieren\Directus\directus\node_modules\knex\lib\execution\runner.js:272:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS E:\Programmieren\Directus\directus>
```

### What version of Directus are you using?

Latest

### What version of Node.js are you using?

Latest

### What database are you using?

MariaDB

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by leonardobrito** [comment]
I have the same problem using `PostgreSQL`, I had removed one collection, and when I run `schema apply`, I've got this same error.

**Comment by azrikahar** [comment]
Just noticed that this is likely a duplicate of #8443.

**Comment by Nitwel** [comment]
Yep, looks like it. Closing this in favor of #8443
